package pe.royalsystems.springerp.erpspringsalud.model;
// Generated Aug 6, 2015 12:12:22 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import pe.royalsystems.springerp.erpspringsalud.util.JsonViewCustom;

/**
 * SsGeEspecialidad generated by hbm2java
 */
@JsonIgnoreProperties( value = { 
		/**Campos a ignorar*/	
		"uri"
		,"paginable"
	})
@JsonViewCustom(JsonViewInterfaces.ViewGeneral.class)
public class SsGeEspecialidadJson extends EntidadJson {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEspecialidad;
	private String codigo;
	private String nombre;
	private String descripcion;
	private BigDecimal tiempoPromedioAtencion;
	private Integer formularioInicial;
	private Integer formularioFinal;
	private Integer formularioInforme;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Integer cantidadCitasAdicional;
	private Integer atencionPeriodoCronico;
	private Integer indicadorValidarFlujo;
	private Integer reporteCita;
	private String foto;
	private String descripcionDet;
	private Integer indicadorWeb;
	private String accion;

	public SsGeEspecialidadJson() {
	}

	public SsGeEspecialidadJson(Integer idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	public SsGeEspecialidadJson(Integer idEspecialidad, String codigo, String nombre, String descripcion,
			BigDecimal tiempoPromedioAtencion, Integer formularioInicial, Integer formularioFinal,
			Integer formularioInforme, Integer estado, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion, Integer cantidadCitasAdicional,
			Integer atencionPeriodoCronico, Integer indicadorValidarFlujo, Integer reporteCita, String foto,
			String descripcionDet, Integer indicadorWeb, String accion) {
		this.idEspecialidad = idEspecialidad;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tiempoPromedioAtencion = tiempoPromedioAtencion;
		this.formularioInicial = formularioInicial;
		this.formularioFinal = formularioFinal;
		this.formularioInforme = formularioInforme;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.cantidadCitasAdicional = cantidadCitasAdicional;
		this.atencionPeriodoCronico = atencionPeriodoCronico;
		this.indicadorValidarFlujo = indicadorValidarFlujo;
		this.reporteCita = reporteCita;
		this.foto = foto;
		this.descripcionDet = descripcionDet;
		this.indicadorWeb = indicadorWeb;
		this.accion = accion;
	}

	public Integer getIdEspecialidad() {
		return idEspecialidad;
	}

	public void setIdEspecialidad(Integer idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getTiempoPromedioAtencion() {
		return tiempoPromedioAtencion;
	}

	public void setTiempoPromedioAtencion(BigDecimal tiempoPromedioAtencion) {
		this.tiempoPromedioAtencion = tiempoPromedioAtencion;
	}

	public Integer getFormularioInicial() {
		return formularioInicial;
	}

	public void setFormularioInicial(Integer formularioInicial) {
		this.formularioInicial = formularioInicial;
	}

	public Integer getFormularioFinal() {
		return formularioFinal;
	}

	public void setFormularioFinal(Integer formularioFinal) {
		this.formularioFinal = formularioFinal;
	}

	public Integer getFormularioInforme() {
		return formularioInforme;
	}

	public void setFormularioInforme(Integer formularioInforme) {
		this.formularioInforme = formularioInforme;
	}

	public Integer getEstado() {
		return estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public String getUsuarioCreacion() {
		return usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getCantidadCitasAdicional() {
		return cantidadCitasAdicional;
	}

	public void setCantidadCitasAdicional(Integer cantidadCitasAdicional) {
		this.cantidadCitasAdicional = cantidadCitasAdicional;
	}

	public Integer getAtencionPeriodoCronico() {
		return atencionPeriodoCronico;
	}

	public void setAtencionPeriodoCronico(Integer atencionPeriodoCronico) {
		this.atencionPeriodoCronico = atencionPeriodoCronico;
	}

	public Integer getIndicadorValidarFlujo() {
		return indicadorValidarFlujo;
	}

	public void setIndicadorValidarFlujo(Integer indicadorValidarFlujo) {
		this.indicadorValidarFlujo = indicadorValidarFlujo;
	}

	public Integer getReporteCita() {
		return reporteCita;
	}

	public void setReporteCita(Integer reporteCita) {
		this.reporteCita = reporteCita;
	}

	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public String getDescripcionDet() {
		return descripcionDet;
	}

	public void setDescripcionDet(String descripcionDet) {
		this.descripcionDet = descripcionDet;
	}

	public Integer getIndicadorWeb() {
		return indicadorWeb;
	}

	public void setIndicadorWeb(Integer indicadorWeb) {
		this.indicadorWeb = indicadorWeb;
	}

	public String getAccion() {
		return accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}
	
	
	
}
