package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 10, 2015 12:19:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Companyowner generated by hbm2java
 */
@Entity
@Table(name = "companyowner")
public class Companyowner extends Entidad implements java.io.Serializable {

	private String companyowner;
	private String description;
	private String englishdescription;
	private Float percentage;
	private String company;
	private String owner;
	private Float changeRate;
	private String lastuser;
	private Date lastdate;
	private String accion;

	public Companyowner() {
	}

	public Companyowner(String companyowner, String description) {
		this.companyowner = companyowner;
		this.description = description;
	}

	public Companyowner(String companyowner, String description, String englishdescription, Float percentage,
			String company, String owner, Float changeRate, String lastuser, Date lastdate, String accion) {
		this.companyowner = companyowner;
		this.description = description;
		this.englishdescription = englishdescription;
		this.percentage = percentage;
		this.company = company;
		this.owner = owner;
		this.changeRate = changeRate;
		this.lastuser = lastuser;
		this.lastdate = lastdate;
		this.accion = accion;
	}

	@Id

	@Column(name = "companyowner", unique = true, nullable = false, length = 8)
	public String getCompanyowner() {
		return this.companyowner;
	}

	public void setCompanyowner(String companyowner) {
		this.companyowner = companyowner;
	}

	@Column(name = "description", nullable = false, length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "englishdescription", length = 40)
	public String getEnglishdescription() {
		return this.englishdescription;
	}

	public void setEnglishdescription(String englishdescription) {
		this.englishdescription = englishdescription;
	}

	@Column(name = "percentage", precision = 24, scale = 0)
	public Float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Float percentage) {
		this.percentage = percentage;
	}

	@Column(name = "company", length = 15)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "owner", length = 2)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "ChangeRate", precision = 24, scale = 0)
	public Float getChangeRate() {
		return this.changeRate;
	}

	public void setChangeRate(Float changeRate) {
		this.changeRate = changeRate;
	}

	@Column(name = "lastuser", length = 10)
	public String getLastuser() {
		return this.lastuser;
	}

	public void setLastuser(String lastuser) {
		this.lastuser = lastuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastdate", length = 23)
	public Date getLastdate() {
		return this.lastdate;
	}

	public void setLastdate(Date lastdate) {
		this.lastdate = lastdate;
	}

	@Column(name = "ACCION", length = 30)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
