package pe.royalsystems.springerp.model.domain;
// Generated Sep 2, 2015 10:08:57 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleadomast generated by hbm2java
 */
@Entity
@Table(name = "EMPLEADOMAST")
public class Empleadomast extends Entidad  implements java.io.Serializable {

	private EmpleadomastId id;
	private String tipoPago;
	private String tipoTrabajador;
	private String raza;
	private String religion;
	private String tipoVisa;
	private Date visaFechaInicio;
	private Date visaFechaExpiracion;
	private Date servicioMilitarDesde;
	private Date servicioMilitarHasta;
	private String numeroArchivo;
	private String unidadNegocioAsignada;
	private String locacionAsignada;
	private String locaciondePago;
	private String responsableEmpleado;
	private String responsableJefe;
	private String responsableSueldo;
	private String codigoUsuario;
	private String tipoAsistenciaSocial;
	private String centroAsistenciaSocial;
	private String tipoCarnetAsistenciaSocial;
	private String carnetAsistenciaSocial;
	private String tipoPension;
	private Date fechaInicioPension;
	private Date fechaTerminoPension;
	private String codigoAfp;
	private String numeroAfp;
	private String bancoCts;
	private String tipoCuentaCts;
	private String tipoMonedaCts;
	private String numeroCuentaCts;
	private Character estadoEmpleado;
	private String tipoPlanilla;
	private Date fechaIngreso;
	private Date fechaUltimaPlanilla;
	private String tipoContrato;
	private Date fechaInicioContrato;
	private Date fechaFinContrato;
	private Date fechaCese;
	private String razonCese;
	private Integer contratista;
	private String centroCostos;
	private String afe;
	private String deptoOrganizacion;
	private Integer tipoHorario;
	private String gradoSalario;
	private String cargo;
	private String posicion;
	private String nivelAcceso;
	private Character flagIpssvida;
	private Character flagAccTrabajo;
	private Character flagSindicato;
	private Character flagCooperativa;
	private Character flagRetencionJudicial;
	private Character flagReingresos;
	private Character flagComision;
	private Character flagImpuestoRenta;
	private String correoInterno;
	private BigDecimal sueldoActualLocal;
	private BigDecimal sueldoActualDolar;
	private BigDecimal sueldoAnteriorLocal;
	private BigDecimal sueldoAnteriorDolar;
	private String monedaPago;
	private Integer empleadoRelacionado;
	private String foto;
	private String tarjetadeCredito;
	private Integer motivoCese;
	private String departamentoOrganizacional;
	private String departamentoOperacional;
	private Integer perfil;
	private String nivelSalario;
	private Date fechaLiquidacion;
	private Date fechaReingreso;
	private String unidadReplicacion;
	private Integer codigoCargo;
	private Date ultimaFechaPagoVacacion;
	private Integer gerencia;
	private Integer subGerencia;
	private Double redondeoAcuenta;
	private String ruccentroAsistenciaSocial;
	private Integer plantillaConcepto;
	private String sucursal;
	private String actividad;
	private String estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private String estadoNivelacion;
	private Integer aprobadorNivelacion;
	private Integer solicitadorNivelacion;
	private Character flagSmf;
	private Date fechaVacaciones;
	private String formato2;
	private Long grupoOcupacional;
	private Integer posicionOrganigrama;
	private Character flagAccTrabajoP;
	private String sucursalbanconacion;
	private Integer cliente;
	private Integer clienteUnidad;
	private Integer tareoNivel;
	private Integer empleadoNivel;
	private Long tipoPuesto;
	private String telefonoextranjero;
	private String celularextranjero;
	private String celularemergencia;
	private String telefonoemergencia;
	private String firmaDigitalizada;
	private Character flagJefeDepartamento;
	private Character flagPorcentaje;
	private String planta;
	private String provincia;
	private String clasificadorMovimiento;
	private String conceptoGasto;
	private String unidadOrganizacional;
	private String centroCostoAbu;
	private Integer idEjecutivo;
	private Integer jefeResponsable;
	private Integer supervisor;
	private String almacen;
	private String cmp;
	private Integer idTipoAtencion;
	private Integer idGrupoAtencion;
	private Integer idServicio;
	private Integer idEspecialidad;
	private Character flagTrabajadorPensionista;
	private Character flagSctrsalud;
	private Character flagSctrpension;
	private Character flagDiscapacidad;
	private Character flagSujetoControl;
	private Character flagSindicalizado;
	private Character flagDomiciliado;
	private String nivelEducativoRtps;
	private Character flagregimenalternativo;
	private Character flagjornadamaxima;
	private Character flaghorarionocturno;
	private Character flagotrosquinta;
	private Character flagquintaexonerada;
	private Character situacionespecial;
	private Character flagmadreresponsabilidad;
	private Character flagcentroformacion;
	private String tipomodalidadformativa;
	private String prestadorServicio;
	private Integer indicadorImpRenta;
	private Integer indicadorTarjetaCredito;
	private Integer tipoMedico;
	private Integer pool;
	private String claveFirmaDigital;
	private String firmaDigital;
	private Character flagAseguraPension;
	private String categoriaOcupacional;
	private Character flagConvenioDobleTrib;
	private Character flagDeConfianza;
	private String establecimientoRtps;
	private Date fechaBajaEps;
	private Integer empleadoRepresentante;
	private String tipoActividad;
	private Integer codigoUnidad;
	private String areaTmp;
	private String cargoTmp;
	private String tipoTrabajadorSalud;
	private Integer indSupervisorLiquidacion;
	private String division;
	private Integer indicadorImpPdf;
	private String rutaImpPdf;
	private String rutaCurriculum;
	private Character tipoComisionAfp;
	private String accion;

	public Empleadomast() {
	}

	public Empleadomast(EmpleadomastId id) {
		this.id = id;
	}

	public Empleadomast(EmpleadomastId id, String tipoPago, String tipoTrabajador, String raza, String religion,
			String tipoVisa, Date visaFechaInicio, Date visaFechaExpiracion, Date servicioMilitarDesde,
			Date servicioMilitarHasta, String numeroArchivo, String unidadNegocioAsignada, String locacionAsignada,
			String locaciondePago, String responsableEmpleado, String responsableJefe, String responsableSueldo,
			String codigoUsuario, String tipoAsistenciaSocial, String centroAsistenciaSocial,
			String tipoCarnetAsistenciaSocial, String carnetAsistenciaSocial, String tipoPension,
			Date fechaInicioPension, Date fechaTerminoPension, String codigoAfp, String numeroAfp, String bancoCts,
			String tipoCuentaCts, String tipoMonedaCts, String numeroCuentaCts, Character estadoEmpleado,
			String tipoPlanilla, Date fechaIngreso, Date fechaUltimaPlanilla, String tipoContrato,
			Date fechaInicioContrato, Date fechaFinContrato, Date fechaCese, String razonCese, Integer contratista,
			String centroCostos, String afe, String deptoOrganizacion, Integer tipoHorario, String gradoSalario,
			String cargo, String posicion, String nivelAcceso, Character flagIpssvida, Character flagAccTrabajo,
			Character flagSindicato, Character flagCooperativa, Character flagRetencionJudicial,
			Character flagReingresos, Character flagComision, Character flagImpuestoRenta, String correoInterno,
			BigDecimal sueldoActualLocal, BigDecimal sueldoActualDolar, BigDecimal sueldoAnteriorLocal,
			BigDecimal sueldoAnteriorDolar, String monedaPago, Integer empleadoRelacionado, String foto,
			String tarjetadeCredito, Integer motivoCese, String departamentoOrganizacional,
			String departamentoOperacional, Integer perfil, String nivelSalario, Date fechaLiquidacion,
			Date fechaReingreso, String unidadReplicacion, Integer codigoCargo, Date ultimaFechaPagoVacacion,
			Integer gerencia, Integer subGerencia, Double redondeoAcuenta, String ruccentroAsistenciaSocial,
			Integer plantillaConcepto, String sucursal, String actividad, String estado, String ultimoUsuario,
			Date ultimaFechaModif, String estadoNivelacion, Integer aprobadorNivelacion, Integer solicitadorNivelacion,
			Character flagSmf, Date fechaVacaciones, String formato2, Long grupoOcupacional,
			Integer posicionOrganigrama, Character flagAccTrabajoP, String sucursalbanconacion, Integer cliente,
			Integer clienteUnidad, Integer tareoNivel, Integer empleadoNivel, Long tipoPuesto,
			String telefonoextranjero, String celularextranjero, String celularemergencia, String telefonoemergencia,
			String firmaDigitalizada, Character flagJefeDepartamento, Character flagPorcentaje, String planta,
			String provincia, String clasificadorMovimiento, String conceptoGasto, String unidadOrganizacional,
			String centroCostoAbu, Integer idEjecutivo, Integer jefeResponsable, Integer supervisor, String almacen,
			String cmp, Integer idTipoAtencion, Integer idGrupoAtencion, Integer idServicio, Integer idEspecialidad,
			Character flagTrabajadorPensionista, Character flagSctrsalud, Character flagSctrpension,
			Character flagDiscapacidad, Character flagSujetoControl, Character flagSindicalizado,
			Character flagDomiciliado, String nivelEducativoRtps, Character flagregimenalternativo,
			Character flagjornadamaxima, Character flaghorarionocturno, Character flagotrosquinta,
			Character flagquintaexonerada, Character situacionespecial, Character flagmadreresponsabilidad,
			Character flagcentroformacion, String tipomodalidadformativa, String prestadorServicio,
			Integer indicadorImpRenta, Integer indicadorTarjetaCredito, Integer tipoMedico, Integer pool,
			String claveFirmaDigital, String firmaDigital, Character flagAseguraPension, String categoriaOcupacional,
			Character flagConvenioDobleTrib, Character flagDeConfianza, String establecimientoRtps, Date fechaBajaEps,
			Integer empleadoRepresentante, String tipoActividad, Integer codigoUnidad, String areaTmp, String cargoTmp,
			String tipoTrabajadorSalud, Integer indSupervisorLiquidacion, String division, Integer indicadorImpPdf,
			String rutaImpPdf, String rutaCurriculum, Character tipoComisionAfp, String accion) {
		this.id = id;
		this.tipoPago = tipoPago;
		this.tipoTrabajador = tipoTrabajador;
		this.raza = raza;
		this.religion = religion;
		this.tipoVisa = tipoVisa;
		this.visaFechaInicio = visaFechaInicio;
		this.visaFechaExpiracion = visaFechaExpiracion;
		this.servicioMilitarDesde = servicioMilitarDesde;
		this.servicioMilitarHasta = servicioMilitarHasta;
		this.numeroArchivo = numeroArchivo;
		this.unidadNegocioAsignada = unidadNegocioAsignada;
		this.locacionAsignada = locacionAsignada;
		this.locaciondePago = locaciondePago;
		this.responsableEmpleado = responsableEmpleado;
		this.responsableJefe = responsableJefe;
		this.responsableSueldo = responsableSueldo;
		this.codigoUsuario = codigoUsuario;
		this.tipoAsistenciaSocial = tipoAsistenciaSocial;
		this.centroAsistenciaSocial = centroAsistenciaSocial;
		this.tipoCarnetAsistenciaSocial = tipoCarnetAsistenciaSocial;
		this.carnetAsistenciaSocial = carnetAsistenciaSocial;
		this.tipoPension = tipoPension;
		this.fechaInicioPension = fechaInicioPension;
		this.fechaTerminoPension = fechaTerminoPension;
		this.codigoAfp = codigoAfp;
		this.numeroAfp = numeroAfp;
		this.bancoCts = bancoCts;
		this.tipoCuentaCts = tipoCuentaCts;
		this.tipoMonedaCts = tipoMonedaCts;
		this.numeroCuentaCts = numeroCuentaCts;
		this.estadoEmpleado = estadoEmpleado;
		this.tipoPlanilla = tipoPlanilla;
		this.fechaIngreso = fechaIngreso;
		this.fechaUltimaPlanilla = fechaUltimaPlanilla;
		this.tipoContrato = tipoContrato;
		this.fechaInicioContrato = fechaInicioContrato;
		this.fechaFinContrato = fechaFinContrato;
		this.fechaCese = fechaCese;
		this.razonCese = razonCese;
		this.contratista = contratista;
		this.centroCostos = centroCostos;
		this.afe = afe;
		this.deptoOrganizacion = deptoOrganizacion;
		this.tipoHorario = tipoHorario;
		this.gradoSalario = gradoSalario;
		this.cargo = cargo;
		this.posicion = posicion;
		this.nivelAcceso = nivelAcceso;
		this.flagIpssvida = flagIpssvida;
		this.flagAccTrabajo = flagAccTrabajo;
		this.flagSindicato = flagSindicato;
		this.flagCooperativa = flagCooperativa;
		this.flagRetencionJudicial = flagRetencionJudicial;
		this.flagReingresos = flagReingresos;
		this.flagComision = flagComision;
		this.flagImpuestoRenta = flagImpuestoRenta;
		this.correoInterno = correoInterno;
		this.sueldoActualLocal = sueldoActualLocal;
		this.sueldoActualDolar = sueldoActualDolar;
		this.sueldoAnteriorLocal = sueldoAnteriorLocal;
		this.sueldoAnteriorDolar = sueldoAnteriorDolar;
		this.monedaPago = monedaPago;
		this.empleadoRelacionado = empleadoRelacionado;
		this.foto = foto;
		this.tarjetadeCredito = tarjetadeCredito;
		this.motivoCese = motivoCese;
		this.departamentoOrganizacional = departamentoOrganizacional;
		this.departamentoOperacional = departamentoOperacional;
		this.perfil = perfil;
		this.nivelSalario = nivelSalario;
		this.fechaLiquidacion = fechaLiquidacion;
		this.fechaReingreso = fechaReingreso;
		this.unidadReplicacion = unidadReplicacion;
		this.codigoCargo = codigoCargo;
		this.ultimaFechaPagoVacacion = ultimaFechaPagoVacacion;
		this.gerencia = gerencia;
		this.subGerencia = subGerencia;
		this.redondeoAcuenta = redondeoAcuenta;
		this.ruccentroAsistenciaSocial = ruccentroAsistenciaSocial;
		this.plantillaConcepto = plantillaConcepto;
		this.sucursal = sucursal;
		this.actividad = actividad;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.estadoNivelacion = estadoNivelacion;
		this.aprobadorNivelacion = aprobadorNivelacion;
		this.solicitadorNivelacion = solicitadorNivelacion;
		this.flagSmf = flagSmf;
		this.fechaVacaciones = fechaVacaciones;
		this.formato2 = formato2;
		this.grupoOcupacional = grupoOcupacional;
		this.posicionOrganigrama = posicionOrganigrama;
		this.flagAccTrabajoP = flagAccTrabajoP;
		this.sucursalbanconacion = sucursalbanconacion;
		this.cliente = cliente;
		this.clienteUnidad = clienteUnidad;
		this.tareoNivel = tareoNivel;
		this.empleadoNivel = empleadoNivel;
		this.tipoPuesto = tipoPuesto;
		this.telefonoextranjero = telefonoextranjero;
		this.celularextranjero = celularextranjero;
		this.celularemergencia = celularemergencia;
		this.telefonoemergencia = telefonoemergencia;
		this.firmaDigitalizada = firmaDigitalizada;
		this.flagJefeDepartamento = flagJefeDepartamento;
		this.flagPorcentaje = flagPorcentaje;
		this.planta = planta;
		this.provincia = provincia;
		this.clasificadorMovimiento = clasificadorMovimiento;
		this.conceptoGasto = conceptoGasto;
		this.unidadOrganizacional = unidadOrganizacional;
		this.centroCostoAbu = centroCostoAbu;
		this.idEjecutivo = idEjecutivo;
		this.jefeResponsable = jefeResponsable;
		this.supervisor = supervisor;
		this.almacen = almacen;
		this.cmp = cmp;
		this.idTipoAtencion = idTipoAtencion;
		this.idGrupoAtencion = idGrupoAtencion;
		this.idServicio = idServicio;
		this.idEspecialidad = idEspecialidad;
		this.flagTrabajadorPensionista = flagTrabajadorPensionista;
		this.flagSctrsalud = flagSctrsalud;
		this.flagSctrpension = flagSctrpension;
		this.flagDiscapacidad = flagDiscapacidad;
		this.flagSujetoControl = flagSujetoControl;
		this.flagSindicalizado = flagSindicalizado;
		this.flagDomiciliado = flagDomiciliado;
		this.nivelEducativoRtps = nivelEducativoRtps;
		this.flagregimenalternativo = flagregimenalternativo;
		this.flagjornadamaxima = flagjornadamaxima;
		this.flaghorarionocturno = flaghorarionocturno;
		this.flagotrosquinta = flagotrosquinta;
		this.flagquintaexonerada = flagquintaexonerada;
		this.situacionespecial = situacionespecial;
		this.flagmadreresponsabilidad = flagmadreresponsabilidad;
		this.flagcentroformacion = flagcentroformacion;
		this.tipomodalidadformativa = tipomodalidadformativa;
		this.prestadorServicio = prestadorServicio;
		this.indicadorImpRenta = indicadorImpRenta;
		this.indicadorTarjetaCredito = indicadorTarjetaCredito;
		this.tipoMedico = tipoMedico;
		this.pool = pool;
		this.claveFirmaDigital = claveFirmaDigital;
		this.firmaDigital = firmaDigital;
		this.flagAseguraPension = flagAseguraPension;
		this.categoriaOcupacional = categoriaOcupacional;
		this.flagConvenioDobleTrib = flagConvenioDobleTrib;
		this.flagDeConfianza = flagDeConfianza;
		this.establecimientoRtps = establecimientoRtps;
		this.fechaBajaEps = fechaBajaEps;
		this.empleadoRepresentante = empleadoRepresentante;
		this.tipoActividad = tipoActividad;
		this.codigoUnidad = codigoUnidad;
		this.areaTmp = areaTmp;
		this.cargoTmp = cargoTmp;
		this.tipoTrabajadorSalud = tipoTrabajadorSalud;
		this.indSupervisorLiquidacion = indSupervisorLiquidacion;
		this.division = division;
		this.indicadorImpPdf = indicadorImpPdf;
		this.rutaImpPdf = rutaImpPdf;
		this.rutaCurriculum = rutaCurriculum;
		this.tipoComisionAfp = tipoComisionAfp;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "empleado", column = @Column(name = "Empleado", nullable = false) ),
			@AttributeOverride(name = "companiaSocio", column = @Column(name = "CompaniaSocio", nullable = false, length = 8) ) })
	public EmpleadomastId getId() {
		return this.id;
	}

	public void setId(EmpleadomastId id) {
		this.id = id;
	}

	@Column(name = "TipoPago", length = 2)
	public String getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(String tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Column(name = "TipoTrabajador", length = 2)
	public String getTipoTrabajador() {
		return this.tipoTrabajador;
	}

	public void setTipoTrabajador(String tipoTrabajador) {
		this.tipoTrabajador = tipoTrabajador;
	}

	@Column(name = "Raza", length = 3)
	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	@Column(name = "Religion", length = 3)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "TipoVisa", length = 3)
	public String getTipoVisa() {
		return this.tipoVisa;
	}

	public void setTipoVisa(String tipoVisa) {
		this.tipoVisa = tipoVisa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VisaFechaInicio", length = 23)
	public Date getVisaFechaInicio() {
		return this.visaFechaInicio;
	}

	public void setVisaFechaInicio(Date visaFechaInicio) {
		this.visaFechaInicio = visaFechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VisaFechaExpiracion", length = 23)
	public Date getVisaFechaExpiracion() {
		return this.visaFechaExpiracion;
	}

	public void setVisaFechaExpiracion(Date visaFechaExpiracion) {
		this.visaFechaExpiracion = visaFechaExpiracion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ServicioMilitarDesde", length = 23)
	public Date getServicioMilitarDesde() {
		return this.servicioMilitarDesde;
	}

	public void setServicioMilitarDesde(Date servicioMilitarDesde) {
		this.servicioMilitarDesde = servicioMilitarDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ServicioMilitarHasta", length = 23)
	public Date getServicioMilitarHasta() {
		return this.servicioMilitarHasta;
	}

	public void setServicioMilitarHasta(Date servicioMilitarHasta) {
		this.servicioMilitarHasta = servicioMilitarHasta;
	}

	@Column(name = "NumeroArchivo", length = 10)
	public String getNumeroArchivo() {
		return this.numeroArchivo;
	}

	public void setNumeroArchivo(String numeroArchivo) {
		this.numeroArchivo = numeroArchivo;
	}

	@Column(name = "UnidadNegocioAsignada", length = 4)
	public String getUnidadNegocioAsignada() {
		return this.unidadNegocioAsignada;
	}

	public void setUnidadNegocioAsignada(String unidadNegocioAsignada) {
		this.unidadNegocioAsignada = unidadNegocioAsignada;
	}

	@Column(name = "LocacionAsignada", length = 4)
	public String getLocacionAsignada() {
		return this.locacionAsignada;
	}

	public void setLocacionAsignada(String locacionAsignada) {
		this.locacionAsignada = locacionAsignada;
	}

	@Column(name = "LocaciondePago", length = 4)
	public String getLocaciondePago() {
		return this.locaciondePago;
	}

	public void setLocaciondePago(String locaciondePago) {
		this.locaciondePago = locaciondePago;
	}

	@Column(name = "ResponsableEmpleado", length = 4)
	public String getResponsableEmpleado() {
		return this.responsableEmpleado;
	}

	public void setResponsableEmpleado(String responsableEmpleado) {
		this.responsableEmpleado = responsableEmpleado;
	}

	@Column(name = "ResponsableJefe", length = 4)
	public String getResponsableJefe() {
		return this.responsableJefe;
	}

	public void setResponsableJefe(String responsableJefe) {
		this.responsableJefe = responsableJefe;
	}

	@Column(name = "ResponsableSueldo", length = 4)
	public String getResponsableSueldo() {
		return this.responsableSueldo;
	}

	public void setResponsableSueldo(String responsableSueldo) {
		this.responsableSueldo = responsableSueldo;
	}

	@Column(name = "CodigoUsuario", length = 25)
	public String getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(String codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "TipoAsistenciaSocial", length = 3)
	public String getTipoAsistenciaSocial() {
		return this.tipoAsistenciaSocial;
	}

	public void setTipoAsistenciaSocial(String tipoAsistenciaSocial) {
		this.tipoAsistenciaSocial = tipoAsistenciaSocial;
	}

	@Column(name = "CentroAsistenciaSocial", length = 20)
	public String getCentroAsistenciaSocial() {
		return this.centroAsistenciaSocial;
	}

	public void setCentroAsistenciaSocial(String centroAsistenciaSocial) {
		this.centroAsistenciaSocial = centroAsistenciaSocial;
	}

	@Column(name = "TipoCarnetAsistenciaSocial", length = 2)
	public String getTipoCarnetAsistenciaSocial() {
		return this.tipoCarnetAsistenciaSocial;
	}

	public void setTipoCarnetAsistenciaSocial(String tipoCarnetAsistenciaSocial) {
		this.tipoCarnetAsistenciaSocial = tipoCarnetAsistenciaSocial;
	}

	@Column(name = "CarnetAsistenciaSocial", length = 20)
	public String getCarnetAsistenciaSocial() {
		return this.carnetAsistenciaSocial;
	}

	public void setCarnetAsistenciaSocial(String carnetAsistenciaSocial) {
		this.carnetAsistenciaSocial = carnetAsistenciaSocial;
	}

	@Column(name = "TipoPension", length = 3)
	public String getTipoPension() {
		return this.tipoPension;
	}

	public void setTipoPension(String tipoPension) {
		this.tipoPension = tipoPension;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaInicioPension", length = 23)
	public Date getFechaInicioPension() {
		return this.fechaInicioPension;
	}

	public void setFechaInicioPension(Date fechaInicioPension) {
		this.fechaInicioPension = fechaInicioPension;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaTerminoPension", length = 23)
	public Date getFechaTerminoPension() {
		return this.fechaTerminoPension;
	}

	public void setFechaTerminoPension(Date fechaTerminoPension) {
		this.fechaTerminoPension = fechaTerminoPension;
	}

	@Column(name = "CodigoAFP", length = 3)
	public String getCodigoAfp() {
		return this.codigoAfp;
	}

	public void setCodigoAfp(String codigoAfp) {
		this.codigoAfp = codigoAfp;
	}

	@Column(name = "NumeroAFP", length = 20)
	public String getNumeroAfp() {
		return this.numeroAfp;
	}

	public void setNumeroAfp(String numeroAfp) {
		this.numeroAfp = numeroAfp;
	}

	@Column(name = "BancoCTS", length = 3)
	public String getBancoCts() {
		return this.bancoCts;
	}

	public void setBancoCts(String bancoCts) {
		this.bancoCts = bancoCts;
	}

	@Column(name = "TipoCuentaCTS", length = 3)
	public String getTipoCuentaCts() {
		return this.tipoCuentaCts;
	}

	public void setTipoCuentaCts(String tipoCuentaCts) {
		this.tipoCuentaCts = tipoCuentaCts;
	}

	@Column(name = "TipoMonedaCTS", length = 2)
	public String getTipoMonedaCts() {
		return this.tipoMonedaCts;
	}

	public void setTipoMonedaCts(String tipoMonedaCts) {
		this.tipoMonedaCts = tipoMonedaCts;
	}

	@Column(name = "NumeroCuentaCTS", length = 20)
	public String getNumeroCuentaCts() {
		return this.numeroCuentaCts;
	}

	public void setNumeroCuentaCts(String numeroCuentaCts) {
		this.numeroCuentaCts = numeroCuentaCts;
	}

	@Column(name = "EstadoEmpleado", length = 1)
	public Character getEstadoEmpleado() {
		return this.estadoEmpleado;
	}

	public void setEstadoEmpleado(Character estadoEmpleado) {
		this.estadoEmpleado = estadoEmpleado;
	}

	@Column(name = "TipoPlanilla", length = 2)
	public String getTipoPlanilla() {
		return this.tipoPlanilla;
	}

	public void setTipoPlanilla(String tipoPlanilla) {
		this.tipoPlanilla = tipoPlanilla;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaIngreso", length = 23)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaUltimaPlanilla", length = 23)
	public Date getFechaUltimaPlanilla() {
		return this.fechaUltimaPlanilla;
	}

	public void setFechaUltimaPlanilla(Date fechaUltimaPlanilla) {
		this.fechaUltimaPlanilla = fechaUltimaPlanilla;
	}

	@Column(name = "TipoContrato", length = 2)
	public String getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaInicioContrato", length = 23)
	public Date getFechaInicioContrato() {
		return this.fechaInicioContrato;
	}

	public void setFechaInicioContrato(Date fechaInicioContrato) {
		this.fechaInicioContrato = fechaInicioContrato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaFinContrato", length = 23)
	public Date getFechaFinContrato() {
		return this.fechaFinContrato;
	}

	public void setFechaFinContrato(Date fechaFinContrato) {
		this.fechaFinContrato = fechaFinContrato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCese", length = 23)
	public Date getFechaCese() {
		return this.fechaCese;
	}

	public void setFechaCese(Date fechaCese) {
		this.fechaCese = fechaCese;
	}

	@Column(name = "RazonCese", length = 30)
	public String getRazonCese() {
		return this.razonCese;
	}

	public void setRazonCese(String razonCese) {
		this.razonCese = razonCese;
	}

	@Column(name = "Contratista")
	public Integer getContratista() {
		return this.contratista;
	}

	public void setContratista(Integer contratista) {
		this.contratista = contratista;
	}

	@Column(name = "CentroCostos", length = 10)
	public String getCentroCostos() {
		return this.centroCostos;
	}

	public void setCentroCostos(String centroCostos) {
		this.centroCostos = centroCostos;
	}

	@Column(name = "AFE", length = 15)
	public String getAfe() {
		return this.afe;
	}

	public void setAfe(String afe) {
		this.afe = afe;
	}

	@Column(name = "DeptoOrganizacion", length = 3)
	public String getDeptoOrganizacion() {
		return this.deptoOrganizacion;
	}

	public void setDeptoOrganizacion(String deptoOrganizacion) {
		this.deptoOrganizacion = deptoOrganizacion;
	}

	@Column(name = "TipoHorario")
	public Integer getTipoHorario() {
		return this.tipoHorario;
	}

	public void setTipoHorario(Integer tipoHorario) {
		this.tipoHorario = tipoHorario;
	}

	@Column(name = "GradoSalario", length = 3)
	public String getGradoSalario() {
		return this.gradoSalario;
	}

	public void setGradoSalario(String gradoSalario) {
		this.gradoSalario = gradoSalario;
	}

	@Column(name = "Cargo", length = 3)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "Posicion", length = 6)
	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	@Column(name = "NivelAcceso", length = 3)
	public String getNivelAcceso() {
		return this.nivelAcceso;
	}

	public void setNivelAcceso(String nivelAcceso) {
		this.nivelAcceso = nivelAcceso;
	}

	@Column(name = "FlagIPSSVIDA", length = 1)
	public Character getFlagIpssvida() {
		return this.flagIpssvida;
	}

	public void setFlagIpssvida(Character flagIpssvida) {
		this.flagIpssvida = flagIpssvida;
	}

	@Column(name = "FlagAccTrabajo", length = 1)
	public Character getFlagAccTrabajo() {
		return this.flagAccTrabajo;
	}

	public void setFlagAccTrabajo(Character flagAccTrabajo) {
		this.flagAccTrabajo = flagAccTrabajo;
	}

	@Column(name = "FlagSindicato", length = 1)
	public Character getFlagSindicato() {
		return this.flagSindicato;
	}

	public void setFlagSindicato(Character flagSindicato) {
		this.flagSindicato = flagSindicato;
	}

	@Column(name = "FlagCooperativa", length = 1)
	public Character getFlagCooperativa() {
		return this.flagCooperativa;
	}

	public void setFlagCooperativa(Character flagCooperativa) {
		this.flagCooperativa = flagCooperativa;
	}

	@Column(name = "FlagRetencionJudicial", length = 1)
	public Character getFlagRetencionJudicial() {
		return this.flagRetencionJudicial;
	}

	public void setFlagRetencionJudicial(Character flagRetencionJudicial) {
		this.flagRetencionJudicial = flagRetencionJudicial;
	}

	@Column(name = "FlagReingresos", length = 1)
	public Character getFlagReingresos() {
		return this.flagReingresos;
	}

	public void setFlagReingresos(Character flagReingresos) {
		this.flagReingresos = flagReingresos;
	}

	@Column(name = "FlagComision", length = 1)
	public Character getFlagComision() {
		return this.flagComision;
	}

	public void setFlagComision(Character flagComision) {
		this.flagComision = flagComision;
	}

	@Column(name = "FlagImpuestoRenta", length = 1)
	public Character getFlagImpuestoRenta() {
		return this.flagImpuestoRenta;
	}

	public void setFlagImpuestoRenta(Character flagImpuestoRenta) {
		this.flagImpuestoRenta = flagImpuestoRenta;
	}

	@Column(name = "CorreoInterno", length = 50)
	public String getCorreoInterno() {
		return this.correoInterno;
	}

	public void setCorreoInterno(String correoInterno) {
		this.correoInterno = correoInterno;
	}

	@Column(name = "SueldoActualLocal", scale = 4)
	public BigDecimal getSueldoActualLocal() {
		return this.sueldoActualLocal;
	}

	public void setSueldoActualLocal(BigDecimal sueldoActualLocal) {
		this.sueldoActualLocal = sueldoActualLocal;
	}

	@Column(name = "SueldoActualDolar", scale = 4)
	public BigDecimal getSueldoActualDolar() {
		return this.sueldoActualDolar;
	}

	public void setSueldoActualDolar(BigDecimal sueldoActualDolar) {
		this.sueldoActualDolar = sueldoActualDolar;
	}

	@Column(name = "SueldoAnteriorLocal", scale = 4)
	public BigDecimal getSueldoAnteriorLocal() {
		return this.sueldoAnteriorLocal;
	}

	public void setSueldoAnteriorLocal(BigDecimal sueldoAnteriorLocal) {
		this.sueldoAnteriorLocal = sueldoAnteriorLocal;
	}

	@Column(name = "SueldoAnteriorDolar", scale = 4)
	public BigDecimal getSueldoAnteriorDolar() {
		return this.sueldoAnteriorDolar;
	}

	public void setSueldoAnteriorDolar(BigDecimal sueldoAnteriorDolar) {
		this.sueldoAnteriorDolar = sueldoAnteriorDolar;
	}

	@Column(name = "MonedaPago", length = 2)
	public String getMonedaPago() {
		return this.monedaPago;
	}

	public void setMonedaPago(String monedaPago) {
		this.monedaPago = monedaPago;
	}

	@Column(name = "EmpleadoRelacionado")
	public Integer getEmpleadoRelacionado() {
		return this.empleadoRelacionado;
	}

	public void setEmpleadoRelacionado(Integer empleadoRelacionado) {
		this.empleadoRelacionado = empleadoRelacionado;
	}

	@Column(name = "Foto", length = 150)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "TarjetadeCredito", length = 20)
	public String getTarjetadeCredito() {
		return this.tarjetadeCredito;
	}

	public void setTarjetadeCredito(String tarjetadeCredito) {
		this.tarjetadeCredito = tarjetadeCredito;
	}

	@Column(name = "MotivoCese")
	public Integer getMotivoCese() {
		return this.motivoCese;
	}

	public void setMotivoCese(Integer motivoCese) {
		this.motivoCese = motivoCese;
	}

	@Column(name = "DepartamentoOrganizacional", length = 5)
	public String getDepartamentoOrganizacional() {
		return this.departamentoOrganizacional;
	}

	public void setDepartamentoOrganizacional(String departamentoOrganizacional) {
		this.departamentoOrganizacional = departamentoOrganizacional;
	}

	@Column(name = "DepartamentoOperacional", length = 10)
	public String getDepartamentoOperacional() {
		return this.departamentoOperacional;
	}

	public void setDepartamentoOperacional(String departamentoOperacional) {
		this.departamentoOperacional = departamentoOperacional;
	}

	@Column(name = "Perfil")
	public Integer getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Integer perfil) {
		this.perfil = perfil;
	}

	@Column(name = "NivelSalario", length = 3)
	public String getNivelSalario() {
		return this.nivelSalario;
	}

	public void setNivelSalario(String nivelSalario) {
		this.nivelSalario = nivelSalario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaLiquidacion", length = 23)
	public Date getFechaLiquidacion() {
		return this.fechaLiquidacion;
	}

	public void setFechaLiquidacion(Date fechaLiquidacion) {
		this.fechaLiquidacion = fechaLiquidacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaReingreso", length = 23)
	public Date getFechaReingreso() {
		return this.fechaReingreso;
	}

	public void setFechaReingreso(Date fechaReingreso) {
		this.fechaReingreso = fechaReingreso;
	}

	@Column(name = "UnidadReplicacion", length = 10)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "CodigoCargo")
	public Integer getCodigoCargo() {
		return this.codigoCargo;
	}

	public void setCodigoCargo(Integer codigoCargo) {
		this.codigoCargo = codigoCargo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaPagoVacacion", length = 23)
	public Date getUltimaFechaPagoVacacion() {
		return this.ultimaFechaPagoVacacion;
	}

	public void setUltimaFechaPagoVacacion(Date ultimaFechaPagoVacacion) {
		this.ultimaFechaPagoVacacion = ultimaFechaPagoVacacion;
	}

	@Column(name = "Gerencia")
	public Integer getGerencia() {
		return this.gerencia;
	}

	public void setGerencia(Integer gerencia) {
		this.gerencia = gerencia;
	}

	@Column(name = "SubGerencia")
	public Integer getSubGerencia() {
		return this.subGerencia;
	}

	public void setSubGerencia(Integer subGerencia) {
		this.subGerencia = subGerencia;
	}

	@Column(name = "RedondeoACuenta", precision = 53, scale = 0)
	public Double getRedondeoAcuenta() {
		return this.redondeoAcuenta;
	}

	public void setRedondeoAcuenta(Double redondeoAcuenta) {
		this.redondeoAcuenta = redondeoAcuenta;
	}

	@Column(name = "RUCCentroAsistenciaSocial", length = 20)
	public String getRuccentroAsistenciaSocial() {
		return this.ruccentroAsistenciaSocial;
	}

	public void setRuccentroAsistenciaSocial(String ruccentroAsistenciaSocial) {
		this.ruccentroAsistenciaSocial = ruccentroAsistenciaSocial;
	}

	@Column(name = "PlantillaConcepto")
	public Integer getPlantillaConcepto() {
		return this.plantillaConcepto;
	}

	public void setPlantillaConcepto(Integer plantillaConcepto) {
		this.plantillaConcepto = plantillaConcepto;
	}

	@Column(name = "Sucursal", length = 4)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "Actividad", length = 8)
	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

	@Column(name = "Estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "EstadoNivelacion", length = 2)
	public String getEstadoNivelacion() {
		return this.estadoNivelacion;
	}

	public void setEstadoNivelacion(String estadoNivelacion) {
		this.estadoNivelacion = estadoNivelacion;
	}

	@Column(name = "AprobadorNivelacion")
	public Integer getAprobadorNivelacion() {
		return this.aprobadorNivelacion;
	}

	public void setAprobadorNivelacion(Integer aprobadorNivelacion) {
		this.aprobadorNivelacion = aprobadorNivelacion;
	}

	@Column(name = "SolicitadorNivelacion")
	public Integer getSolicitadorNivelacion() {
		return this.solicitadorNivelacion;
	}

	public void setSolicitadorNivelacion(Integer solicitadorNivelacion) {
		this.solicitadorNivelacion = solicitadorNivelacion;
	}

	@Column(name = "FlagSMF", length = 1)
	public Character getFlagSmf() {
		return this.flagSmf;
	}

	public void setFlagSmf(Character flagSmf) {
		this.flagSmf = flagSmf;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaVacaciones", length = 23)
	public Date getFechaVacaciones() {
		return this.fechaVacaciones;
	}

	public void setFechaVacaciones(Date fechaVacaciones) {
		this.fechaVacaciones = fechaVacaciones;
	}

	@Column(name = "Formato_2", length = 3)
	public String getFormato2() {
		return this.formato2;
	}

	public void setFormato2(String formato2) {
		this.formato2 = formato2;
	}

	@Column(name = "GrupoOcupacional", precision = 10, scale = 0)
	public Long getGrupoOcupacional() {
		return this.grupoOcupacional;
	}

	public void setGrupoOcupacional(Long grupoOcupacional) {
		this.grupoOcupacional = grupoOcupacional;
	}

	@Column(name = "PosicionOrganigrama")
	public Integer getPosicionOrganigrama() {
		return this.posicionOrganigrama;
	}

	public void setPosicionOrganigrama(Integer posicionOrganigrama) {
		this.posicionOrganigrama = posicionOrganigrama;
	}

	@Column(name = "FlagAccTrabajoP", length = 1)
	public Character getFlagAccTrabajoP() {
		return this.flagAccTrabajoP;
	}

	public void setFlagAccTrabajoP(Character flagAccTrabajoP) {
		this.flagAccTrabajoP = flagAccTrabajoP;
	}

	@Column(name = "sucursalbanconacion", length = 4)
	public String getSucursalbanconacion() {
		return this.sucursalbanconacion;
	}

	public void setSucursalbanconacion(String sucursalbanconacion) {
		this.sucursalbanconacion = sucursalbanconacion;
	}

	@Column(name = "Cliente")
	public Integer getCliente() {
		return this.cliente;
	}

	public void setCliente(Integer cliente) {
		this.cliente = cliente;
	}

	@Column(name = "ClienteUnidad")
	public Integer getClienteUnidad() {
		return this.clienteUnidad;
	}

	public void setClienteUnidad(Integer clienteUnidad) {
		this.clienteUnidad = clienteUnidad;
	}

	@Column(name = "TareoNivel")
	public Integer getTareoNivel() {
		return this.tareoNivel;
	}

	public void setTareoNivel(Integer tareoNivel) {
		this.tareoNivel = tareoNivel;
	}

	@Column(name = "EmpleadoNivel")
	public Integer getEmpleadoNivel() {
		return this.empleadoNivel;
	}

	public void setEmpleadoNivel(Integer empleadoNivel) {
		this.empleadoNivel = empleadoNivel;
	}

	@Column(name = "TipoPuesto", precision = 10, scale = 0)
	public Long getTipoPuesto() {
		return this.tipoPuesto;
	}

	public void setTipoPuesto(Long tipoPuesto) {
		this.tipoPuesto = tipoPuesto;
	}

	@Column(name = "telefonoextranjero", length = 15)
	public String getTelefonoextranjero() {
		return this.telefonoextranjero;
	}

	public void setTelefonoextranjero(String telefonoextranjero) {
		this.telefonoextranjero = telefonoextranjero;
	}

	@Column(name = "celularextranjero", length = 15)
	public String getCelularextranjero() {
		return this.celularextranjero;
	}

	public void setCelularextranjero(String celularextranjero) {
		this.celularextranjero = celularextranjero;
	}

	@Column(name = "celularemergencia", length = 15)
	public String getCelularemergencia() {
		return this.celularemergencia;
	}

	public void setCelularemergencia(String celularemergencia) {
		this.celularemergencia = celularemergencia;
	}

	@Column(name = "telefonoemergencia", length = 15)
	public String getTelefonoemergencia() {
		return this.telefonoemergencia;
	}

	public void setTelefonoemergencia(String telefonoemergencia) {
		this.telefonoemergencia = telefonoemergencia;
	}

	@Column(name = "FirmaDigitalizada", length = 100)
	public String getFirmaDigitalizada() {
		return this.firmaDigitalizada;
	}

	public void setFirmaDigitalizada(String firmaDigitalizada) {
		this.firmaDigitalizada = firmaDigitalizada;
	}

	@Column(name = "FlagJefeDepartamento", length = 1)
	public Character getFlagJefeDepartamento() {
		return this.flagJefeDepartamento;
	}

	public void setFlagJefeDepartamento(Character flagJefeDepartamento) {
		this.flagJefeDepartamento = flagJefeDepartamento;
	}

	@Column(name = "FlagPorcentaje", length = 1)
	public Character getFlagPorcentaje() {
		return this.flagPorcentaje;
	}

	public void setFlagPorcentaje(Character flagPorcentaje) {
		this.flagPorcentaje = flagPorcentaje;
	}

	@Column(name = "Planta", length = 6)
	public String getPlanta() {
		return this.planta;
	}

	public void setPlanta(String planta) {
		this.planta = planta;
	}

	@Column(name = "provincia", length = 2)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "ClasificadorMovimiento", length = 15)
	public String getClasificadorMovimiento() {
		return this.clasificadorMovimiento;
	}

	public void setClasificadorMovimiento(String clasificadorMovimiento) {
		this.clasificadorMovimiento = clasificadorMovimiento;
	}

	@Column(name = "ConceptoGasto", length = 15)
	public String getConceptoGasto() {
		return this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}

	@Column(name = "UnidadOrganizacional", length = 15)
	public String getUnidadOrganizacional() {
		return this.unidadOrganizacional;
	}

	public void setUnidadOrganizacional(String unidadOrganizacional) {
		this.unidadOrganizacional = unidadOrganizacional;
	}

	@Column(name = "CentroCosto_ABU", length = 15)
	public String getCentroCostoAbu() {
		return this.centroCostoAbu;
	}

	public void setCentroCostoAbu(String centroCostoAbu) {
		this.centroCostoAbu = centroCostoAbu;
	}

	@Column(name = "IdEjecutivo")
	public Integer getIdEjecutivo() {
		return this.idEjecutivo;
	}

	public void setIdEjecutivo(Integer idEjecutivo) {
		this.idEjecutivo = idEjecutivo;
	}

	@Column(name = "JefeResponsable")
	public Integer getJefeResponsable() {
		return this.jefeResponsable;
	}

	public void setJefeResponsable(Integer jefeResponsable) {
		this.jefeResponsable = jefeResponsable;
	}

	@Column(name = "Supervisor")
	public Integer getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(Integer supervisor) {
		this.supervisor = supervisor;
	}

	@Column(name = "Almacen", length = 15)
	public String getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(String almacen) {
		this.almacen = almacen;
	}

	@Column(name = "CMP", length = 25)
	public String getCmp() {
		return this.cmp;
	}

	public void setCmp(String cmp) {
		this.cmp = cmp;
	}

	@Column(name = "idTipoAtencion")
	public Integer getIdTipoAtencion() {
		return this.idTipoAtencion;
	}

	public void setIdTipoAtencion(Integer idTipoAtencion) {
		this.idTipoAtencion = idTipoAtencion;
	}

	@Column(name = "idGrupoAtencion")
	public Integer getIdGrupoAtencion() {
		return this.idGrupoAtencion;
	}

	public void setIdGrupoAtencion(Integer idGrupoAtencion) {
		this.idGrupoAtencion = idGrupoAtencion;
	}

	@Column(name = "idServicio")
	public Integer getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Integer idServicio) {
		this.idServicio = idServicio;
	}

	@Column(name = "idEspecialidad")
	public Integer getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(Integer idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	@Column(name = "FlagTrabajadorPensionista", length = 1)
	public Character getFlagTrabajadorPensionista() {
		return this.flagTrabajadorPensionista;
	}

	public void setFlagTrabajadorPensionista(Character flagTrabajadorPensionista) {
		this.flagTrabajadorPensionista = flagTrabajadorPensionista;
	}

	@Column(name = "FlagSCTRSalud", length = 1)
	public Character getFlagSctrsalud() {
		return this.flagSctrsalud;
	}

	public void setFlagSctrsalud(Character flagSctrsalud) {
		this.flagSctrsalud = flagSctrsalud;
	}

	@Column(name = "FlagSCTRPension", length = 1)
	public Character getFlagSctrpension() {
		return this.flagSctrpension;
	}

	public void setFlagSctrpension(Character flagSctrpension) {
		this.flagSctrpension = flagSctrpension;
	}

	@Column(name = "FlagDiscapacidad", length = 1)
	public Character getFlagDiscapacidad() {
		return this.flagDiscapacidad;
	}

	public void setFlagDiscapacidad(Character flagDiscapacidad) {
		this.flagDiscapacidad = flagDiscapacidad;
	}

	@Column(name = "FlagSujetoControl", length = 1)
	public Character getFlagSujetoControl() {
		return this.flagSujetoControl;
	}

	public void setFlagSujetoControl(Character flagSujetoControl) {
		this.flagSujetoControl = flagSujetoControl;
	}

	@Column(name = "FlagSindicalizado", length = 1)
	public Character getFlagSindicalizado() {
		return this.flagSindicalizado;
	}

	public void setFlagSindicalizado(Character flagSindicalizado) {
		this.flagSindicalizado = flagSindicalizado;
	}

	@Column(name = "FlagDomiciliado", length = 1)
	public Character getFlagDomiciliado() {
		return this.flagDomiciliado;
	}

	public void setFlagDomiciliado(Character flagDomiciliado) {
		this.flagDomiciliado = flagDomiciliado;
	}

	@Column(name = "NivelEducativoRTPS", length = 2)
	public String getNivelEducativoRtps() {
		return this.nivelEducativoRtps;
	}

	public void setNivelEducativoRtps(String nivelEducativoRtps) {
		this.nivelEducativoRtps = nivelEducativoRtps;
	}

	@Column(name = "flagregimenalternativo", length = 1)
	public Character getFlagregimenalternativo() {
		return this.flagregimenalternativo;
	}

	public void setFlagregimenalternativo(Character flagregimenalternativo) {
		this.flagregimenalternativo = flagregimenalternativo;
	}

	@Column(name = "flagjornadamaxima", length = 1)
	public Character getFlagjornadamaxima() {
		return this.flagjornadamaxima;
	}

	public void setFlagjornadamaxima(Character flagjornadamaxima) {
		this.flagjornadamaxima = flagjornadamaxima;
	}

	@Column(name = "flaghorarionocturno", length = 1)
	public Character getFlaghorarionocturno() {
		return this.flaghorarionocturno;
	}

	public void setFlaghorarionocturno(Character flaghorarionocturno) {
		this.flaghorarionocturno = flaghorarionocturno;
	}

	@Column(name = "flagotrosquinta", length = 1)
	public Character getFlagotrosquinta() {
		return this.flagotrosquinta;
	}

	public void setFlagotrosquinta(Character flagotrosquinta) {
		this.flagotrosquinta = flagotrosquinta;
	}

	@Column(name = "flagquintaexonerada", length = 1)
	public Character getFlagquintaexonerada() {
		return this.flagquintaexonerada;
	}

	public void setFlagquintaexonerada(Character flagquintaexonerada) {
		this.flagquintaexonerada = flagquintaexonerada;
	}

	@Column(name = "situacionespecial", length = 1)
	public Character getSituacionespecial() {
		return this.situacionespecial;
	}

	public void setSituacionespecial(Character situacionespecial) {
		this.situacionespecial = situacionespecial;
	}

	@Column(name = "flagmadreresponsabilidad", length = 1)
	public Character getFlagmadreresponsabilidad() {
		return this.flagmadreresponsabilidad;
	}

	public void setFlagmadreresponsabilidad(Character flagmadreresponsabilidad) {
		this.flagmadreresponsabilidad = flagmadreresponsabilidad;
	}

	@Column(name = "flagcentroformacion", length = 1)
	public Character getFlagcentroformacion() {
		return this.flagcentroformacion;
	}

	public void setFlagcentroformacion(Character flagcentroformacion) {
		this.flagcentroformacion = flagcentroformacion;
	}

	@Column(name = "tipomodalidadformativa", length = 2)
	public String getTipomodalidadformativa() {
		return this.tipomodalidadformativa;
	}

	public void setTipomodalidadformativa(String tipomodalidadformativa) {
		this.tipomodalidadformativa = tipomodalidadformativa;
	}

	@Column(name = "PrestadorServicio", length = 11)
	public String getPrestadorServicio() {
		return this.prestadorServicio;
	}

	public void setPrestadorServicio(String prestadorServicio) {
		this.prestadorServicio = prestadorServicio;
	}

	@Column(name = "IndicadorImpRenta")
	public Integer getIndicadorImpRenta() {
		return this.indicadorImpRenta;
	}

	public void setIndicadorImpRenta(Integer indicadorImpRenta) {
		this.indicadorImpRenta = indicadorImpRenta;
	}

	@Column(name = "IndicadorTarjetaCredito")
	public Integer getIndicadorTarjetaCredito() {
		return this.indicadorTarjetaCredito;
	}

	public void setIndicadorTarjetaCredito(Integer indicadorTarjetaCredito) {
		this.indicadorTarjetaCredito = indicadorTarjetaCredito;
	}

	@Column(name = "TipoMedico")
	public Integer getTipoMedico() {
		return this.tipoMedico;
	}

	public void setTipoMedico(Integer tipoMedico) {
		this.tipoMedico = tipoMedico;
	}

	@Column(name = "Pool")
	public Integer getPool() {
		return this.pool;
	}

	public void setPool(Integer pool) {
		this.pool = pool;
	}

	@Column(name = "ClaveFirmaDigital", length = 15)
	public String getClaveFirmaDigital() {
		return this.claveFirmaDigital;
	}

	public void setClaveFirmaDigital(String claveFirmaDigital) {
		this.claveFirmaDigital = claveFirmaDigital;
	}

	@Column(name = "FirmaDigital", length = 150)
	public String getFirmaDigital() {
		return this.firmaDigital;
	}

	public void setFirmaDigital(String firmaDigital) {
		this.firmaDigital = firmaDigital;
	}

	@Column(name = "FlagAseguraPension", length = 1)
	public Character getFlagAseguraPension() {
		return this.flagAseguraPension;
	}

	public void setFlagAseguraPension(Character flagAseguraPension) {
		this.flagAseguraPension = flagAseguraPension;
	}

	@Column(name = "CategoriaOcupacional", length = 2)
	public String getCategoriaOcupacional() {
		return this.categoriaOcupacional;
	}

	public void setCategoriaOcupacional(String categoriaOcupacional) {
		this.categoriaOcupacional = categoriaOcupacional;
	}

	@Column(name = "FlagConvenioDobleTrib", length = 1)
	public Character getFlagConvenioDobleTrib() {
		return this.flagConvenioDobleTrib;
	}

	public void setFlagConvenioDobleTrib(Character flagConvenioDobleTrib) {
		this.flagConvenioDobleTrib = flagConvenioDobleTrib;
	}

	@Column(name = "FlagDeConfianza", length = 1)
	public Character getFlagDeConfianza() {
		return this.flagDeConfianza;
	}

	public void setFlagDeConfianza(Character flagDeConfianza) {
		this.flagDeConfianza = flagDeConfianza;
	}

	@Column(name = "EstablecimientoRTPS", length = 4)
	public String getEstablecimientoRtps() {
		return this.establecimientoRtps;
	}

	public void setEstablecimientoRtps(String establecimientoRtps) {
		this.establecimientoRtps = establecimientoRtps;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaBajaEPS", length = 23)
	public Date getFechaBajaEps() {
		return this.fechaBajaEps;
	}

	public void setFechaBajaEps(Date fechaBajaEps) {
		this.fechaBajaEps = fechaBajaEps;
	}

	@Column(name = "EmpleadoRepresentante")
	public Integer getEmpleadoRepresentante() {
		return this.empleadoRepresentante;
	}

	public void setEmpleadoRepresentante(Integer empleadoRepresentante) {
		this.empleadoRepresentante = empleadoRepresentante;
	}

	@Column(name = "TipoActividad", length = 3)
	public String getTipoActividad() {
		return this.tipoActividad;
	}

	public void setTipoActividad(String tipoActividad) {
		this.tipoActividad = tipoActividad;
	}

	@Column(name = "CodigoUnidad")
	public Integer getCodigoUnidad() {
		return this.codigoUnidad;
	}

	public void setCodigoUnidad(Integer codigoUnidad) {
		this.codigoUnidad = codigoUnidad;
	}

	@Column(name = "area_tmp", length = 500)
	public String getAreaTmp() {
		return this.areaTmp;
	}

	public void setAreaTmp(String areaTmp) {
		this.areaTmp = areaTmp;
	}

	@Column(name = "cargo_tmp", length = 500)
	public String getCargoTmp() {
		return this.cargoTmp;
	}

	public void setCargoTmp(String cargoTmp) {
		this.cargoTmp = cargoTmp;
	}

	@Column(name = "TipoTrabajadorSalud", length = 2)
	public String getTipoTrabajadorSalud() {
		return this.tipoTrabajadorSalud;
	}

	public void setTipoTrabajadorSalud(String tipoTrabajadorSalud) {
		this.tipoTrabajadorSalud = tipoTrabajadorSalud;
	}

	@Column(name = "IndSupervisorLiquidacion")
	public Integer getIndSupervisorLiquidacion() {
		return this.indSupervisorLiquidacion;
	}

	public void setIndSupervisorLiquidacion(Integer indSupervisorLiquidacion) {
		this.indSupervisorLiquidacion = indSupervisorLiquidacion;
	}

	@Column(name = "Division", length = 4)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "IndicadorImpPDF")
	public Integer getIndicadorImpPdf() {
		return this.indicadorImpPdf;
	}

	public void setIndicadorImpPdf(Integer indicadorImpPdf) {
		this.indicadorImpPdf = indicadorImpPdf;
	}

	@Column(name = "RutaImpPDF", length = 35)
	public String getRutaImpPdf() {
		return this.rutaImpPdf;
	}

	public void setRutaImpPdf(String rutaImpPdf) {
		this.rutaImpPdf = rutaImpPdf;
	}

	@Column(name = "RutaCurriculum", length = 250)
	public String getRutaCurriculum() {
		return this.rutaCurriculum;
	}

	public void setRutaCurriculum(String rutaCurriculum) {
		this.rutaCurriculum = rutaCurriculum;
	}

	@Column(name = "TipoComisionAFP", length = 1)
	public Character getTipoComisionAfp() {
		return this.tipoComisionAfp;
	}

	public void setTipoComisionAfp(Character tipoComisionAfp) {
		this.tipoComisionAfp = tipoComisionAfp;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
