package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 18, 2015 3:43:21 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GeUnidadMedida generated by hbm2java
 */
@Entity
@Table(name = "GE_UnidadMedida")
public class GeUnidadMedida extends Entidad implements java.io.Serializable {

	private int idUnidadMedida;
	private Character tipoMedida;
	private Integer indicadorMedidaBase;
	private BigDecimal factorConversion;
	private String codigoUnidadMedida;
	private String descripcion;
	private String descripcionExtranjera;
	private Integer numeroDecimales;
	private int estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Integer indAfectocalculocantidad;

	public GeUnidadMedida() {
	}

	public GeUnidadMedida(int idUnidadMedida, String codigoUnidadMedida, String descripcion, int estado) {
		this.idUnidadMedida = idUnidadMedida;
		this.codigoUnidadMedida = codigoUnidadMedida;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	public GeUnidadMedida(int idUnidadMedida, Character tipoMedida, Integer indicadorMedidaBase,
			BigDecimal factorConversion, String codigoUnidadMedida, String descripcion, String descripcionExtranjera,
			Integer numeroDecimales, int estado, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion,
			Date fechaModificacion, Integer indAfectocalculocantidad) {
		this.idUnidadMedida = idUnidadMedida;
		this.tipoMedida = tipoMedida;
		this.indicadorMedidaBase = indicadorMedidaBase;
		this.factorConversion = factorConversion;
		this.codigoUnidadMedida = codigoUnidadMedida;
		this.descripcion = descripcion;
		this.descripcionExtranjera = descripcionExtranjera;
		this.numeroDecimales = numeroDecimales;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.indAfectocalculocantidad = indAfectocalculocantidad;
	}

	@Id
	@Column(name = "IdUnidadMedida", nullable = false)
	public int getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(int idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	@Column(name = "TipoMedida", length = 1)
	public Character getTipoMedida() {
		return this.tipoMedida;
	}

	public void setTipoMedida(Character tipoMedida) {
		this.tipoMedida = tipoMedida;
	}

	@Column(name = "IndicadorMedidaBase")
	public Integer getIndicadorMedidaBase() {
		return this.indicadorMedidaBase;
	}

	public void setIndicadorMedidaBase(Integer indicadorMedidaBase) {
		this.indicadorMedidaBase = indicadorMedidaBase;
	}

	@Column(name = "FactorConversion", precision = 16, scale = 6)
	public BigDecimal getFactorConversion() {
		return this.factorConversion;
	}

	public void setFactorConversion(BigDecimal factorConversion) {
		this.factorConversion = factorConversion;
	}

	@Column(name = "CodigoUnidadMedida", nullable = false, length = 3)
	public String getCodigoUnidadMedida() {
		return this.codigoUnidadMedida;
	}

	public void setCodigoUnidadMedida(String codigoUnidadMedida) {
		this.codigoUnidadMedida = codigoUnidadMedida;
	}

	@Column(name = "Descripcion", nullable = false, length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DescripcionExtranjera", length = 40)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "NumeroDecimales")
	public Integer getNumeroDecimales() {
		return this.numeroDecimales;
	}

	public void setNumeroDecimales(Integer numeroDecimales) {
		this.numeroDecimales = numeroDecimales;
	}

	@Column(name = "Estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "indAfectocalculocantidad")
	public Integer getIndAfectocalculocantidad() {
		return this.indAfectocalculocantidad;
	}

	public void setIndAfectocalculocantidad(Integer indAfectocalculocantidad) {
		this.indAfectocalculocantidad = indAfectocalculocantidad;
	}

	

}
