package pe.royalsystems.springerp.model.domain;
// Generated Aug 7, 2015 3:08:50 PM by Hibernate Tools 4.3.1

import java.util.Arrays;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MaMiscelaneosDetalle generated by hbm2java
 */
@Entity
@Table(name = "MA_MiscelaneosDetalle")
public class MaMiscelaneosDetalle extends Entidad implements java.io.Serializable {
	


	private String aplicacionCodigo;
	private String codigoTabla;
	private String compania;
	private String codigoElemento;
	private String descripcionLocal;
	private String descripcionExtranjera;
	private Double valorNumerico;
	private String valorCodigo1;
	private String valorCodigo2;
	private String valorCodigo3;
	private String valorCodigo4;
	private String valorCodigo5;
	private Date valorFecha;
	private String estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private byte[] timestamp;
	private String accion;
	private Integer rowId;
	private Integer valorEntero1;
	private Integer valorEntero2;
	private Integer valorEntero3;
	private Integer valorEntero4;
	private Integer valorEntero5;
	private String valorCodigo6;
	private String valorCodigo7;
	private Integer valorEntero6;
	private Integer valorEntero7;

	private String dataTexto;
	
	public MaMiscelaneosDetalle() {
		
	}

	public MaMiscelaneosDetalle(String aplicacionCodigo, String codigoTabla, String compania, String codigoElemento) {
		this.aplicacionCodigo = aplicacionCodigo;
		this.codigoTabla = codigoTabla;
		this.compania = compania;
		this.codigoElemento = codigoElemento;
	}

	public MaMiscelaneosDetalle(String aplicacionCodigo, String codigoTabla, String compania, String codigoElemento,
			String descripcionLocal, String descripcionExtranjera, Double valorNumerico, String valorCodigo1,
			String valorCodigo2, String valorCodigo3, String valorCodigo4, String valorCodigo5, Date valorFecha,
			String estado, String ultimoUsuario, Date ultimaFechaModif, byte[] timestamp, String accion,
			Integer rowId, Integer valorEntero1, Integer valorEntero2, Integer valorEntero3, Integer valorEntero4,
			Integer valorEntero5, String valorCodigo6, String valorCodigo7, Integer valorEntero6,
			Integer valorEntero7) {
		this.aplicacionCodigo = aplicacionCodigo;
		this.codigoTabla = codigoTabla;
		this.compania = compania;
		this.codigoElemento = codigoElemento;
		this.descripcionLocal = descripcionLocal;
		this.descripcionExtranjera = descripcionExtranjera;
		this.valorNumerico = valorNumerico;
		this.valorCodigo1 = valorCodigo1;
		this.valorCodigo2 = valorCodigo2;
		this.valorCodigo3 = valorCodigo3;
		this.valorCodigo4 = valorCodigo4;
		this.valorCodigo5 = valorCodigo5;
		this.valorFecha = valorFecha;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.timestamp = timestamp;
		this.accion = accion;
		this.rowId = rowId;
		this.valorEntero1 = valorEntero1;
		this.valorEntero2 = valorEntero2;
		this.valorEntero3 = valorEntero3;
		this.valorEntero4 = valorEntero4;
		this.valorEntero5 = valorEntero5;
		this.valorCodigo6 = valorCodigo6;
		this.valorCodigo7 = valorCodigo7;
		this.valorEntero6 = valorEntero6;
		this.valorEntero7 = valorEntero7;
	}

	@Column(name = "AplicacionCodigo", nullable = false, length = 2)
	public String getAplicacionCodigo() {
		return this.aplicacionCodigo;
	}

	public void setAplicacionCodigo(String aplicacionCodigo) {
		this.aplicacionCodigo = aplicacionCodigo;
	}

	@Column(name = "CodigoTabla", nullable = false, length = 10)
	public String getCodigoTabla() {
		return this.codigoTabla;
	}

	public void setCodigoTabla(String codigoTabla) {
		this.codigoTabla = codigoTabla;
	}

	@Column(name = "Compania", nullable = false, length = 6)
	public String getCompania() {
		return this.compania;
	}

	public void setCompania(String compania) {
		this.compania = compania;
	}

	@Id
	@Column(name = "CodigoElemento", nullable = false, length = 10)
	public String getCodigoElemento() {
		return this.codigoElemento;
	}

	public void setCodigoElemento(String codigoElemento) {
		this.codigoElemento = codigoElemento;
	}

	@Column(name = "DescripcionLocal", length = 80)
	public String getDescripcionLocal() {
		return this.descripcionLocal;
	}

	public void setDescripcionLocal(String descripcionLocal) {
		this.descripcionLocal = descripcionLocal;
	}

	@Column(name = "DescripcionExtranjera", length = 80)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "ValorNumerico", precision = 53, scale = 0)
	public Double getValorNumerico() {
		return this.valorNumerico;
	}

	public void setValorNumerico(Double valorNumerico) {
		this.valorNumerico = valorNumerico;
	}

	@Column(name = "ValorCodigo1", length = 300)
	public String getValorCodigo1() {
		return this.valorCodigo1;
	}

	public void setValorCodigo1(String valorCodigo1) {
		this.valorCodigo1 = valorCodigo1;
	}

	@Column(name = "ValorCodigo2", length = 300)
	public String getValorCodigo2() {
		return this.valorCodigo2;
	}

	public void setValorCodigo2(String valorCodigo2) {
		this.valorCodigo2 = valorCodigo2;
	}

	@Column(name = "ValorCodigo3", length = 300)
	public String getValorCodigo3() {
		return this.valorCodigo3;
	}

	public void setValorCodigo3(String valorCodigo3) {
		this.valorCodigo3 = valorCodigo3;
	}

	@Column(name = "ValorCodigo4", length = 300)
	public String getValorCodigo4() {
		return this.valorCodigo4;
	}

	public void setValorCodigo4(String valorCodigo4) {
		this.valorCodigo4 = valorCodigo4;
	}

	@Column(name = "ValorCodigo5", length = 300)
	public String getValorCodigo5() {
		return this.valorCodigo5;
	}

	public void setValorCodigo5(String valorCodigo5) {
		this.valorCodigo5 = valorCodigo5;
	}

	@Column(name = "ValorFecha", length = 23)
	public Date getValorFecha() {
		return this.valorFecha;
	}

	public void setValorFecha(Date valorFecha) {
		this.valorFecha = valorFecha;
	}

	@Column(name = "Estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "Timestamp")
	public byte[] getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(byte[] timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "RowID")
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "ValorEntero1")
	public Integer getValorEntero1() {
		return this.valorEntero1;
	}

	public void setValorEntero1(Integer valorEntero1) {
		this.valorEntero1 = valorEntero1;
	}

	@Column(name = "ValorEntero2")
	public Integer getValorEntero2() {
		return this.valorEntero2;
	}

	public void setValorEntero2(Integer valorEntero2) {
		this.valorEntero2 = valorEntero2;
	}

	@Column(name = "ValorEntero3")
	public Integer getValorEntero3() {
		return this.valorEntero3;
	}

	public void setValorEntero3(Integer valorEntero3) {
		this.valorEntero3 = valorEntero3;
	}

	@Column(name = "ValorEntero4")
	public Integer getValorEntero4() {
		return this.valorEntero4;
	}

	public void setValorEntero4(Integer valorEntero4) {
		this.valorEntero4 = valorEntero4;
	}

	@Column(name = "ValorEntero5")
	public Integer getValorEntero5() {
		return this.valorEntero5;
	}

	public void setValorEntero5(Integer valorEntero5) {
		this.valorEntero5 = valorEntero5;
	}

	@Column(name = "ValorCodigo6", length = 25)
	public String getValorCodigo6() {
		return this.valorCodigo6;
	}

	public void setValorCodigo6(String valorCodigo6) {
		this.valorCodigo6 = valorCodigo6;
	}

	@Column(name = "ValorCodigo7", length = 25)
	public String getValorCodigo7() {
		return this.valorCodigo7;
	}

	public void setValorCodigo7(String valorCodigo7) {
		this.valorCodigo7 = valorCodigo7;
	}

	@Column(name = "ValorEntero6")
	public Integer getValorEntero6() {
		return this.valorEntero6;
	}

	public void setValorEntero6(Integer valorEntero6) {
		this.valorEntero6 = valorEntero6;
	}

	@Column(name = "ValorEntero7")
	public Integer getValorEntero7() {
		return this.valorEntero7;
	}

	public void setValorEntero7(Integer valorEntero7) {
		this.valorEntero7 = valorEntero7;
	}

	@Column(name="DataTexto")
	public String getDataTexto() {
		return dataTexto;
	}

	public void setDataTexto(String dataTexto) {
		this.dataTexto = dataTexto;
	}

}
