package pe.royalsystems.springerp.model.domain;

import java.security.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

//default package
//Generated Sep 10, 2015 2:27:44 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
* MaMiscelaneosHeader generated by hbm2java
*/
@Entity
@Table(name = "MA_MiscelaneosHeader")
public class MaMiscelaneosHeader implements java.io.Serializable {

	private MaMiscelaneosHeaderId id;
	private byte[] timestamp;
	private String descripcionLocal;
	private String descripcionExtranjera;
	private Character estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private String accion;

	public MaMiscelaneosHeader() {
	}

	public MaMiscelaneosHeader(MaMiscelaneosHeaderId id) {
		this.id = id;
	}

	public MaMiscelaneosHeader(MaMiscelaneosHeaderId id, String descripcionLocal, String descripcionExtranjera,
			Character estado, String ultimoUsuario, Date ultimaFechaModif, String accion) {
		this.id = id;
		this.descripcionLocal = descripcionLocal;
		this.descripcionExtranjera = descripcionExtranjera;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "aplicacionCodigo", column = @Column(name = "AplicacionCodigo", nullable = false, length = 2) ),
			@AttributeOverride(name = "codigoTabla", column = @Column(name = "CodigoTabla", nullable = false, length = 10) ),
			@AttributeOverride(name = "compania", column = @Column(name = "Compania", nullable = false, length = 6) ) })
	public MaMiscelaneosHeaderId getId() {
		return this.id;
	}

	public void setId(MaMiscelaneosHeaderId id) {
		this.id = id;
	}

	@Column(name = "Timestamp")
	public byte[] getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(byte[] timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "DescripcionLocal", length = 100)
	public String getDescripcionLocal() {
		return this.descripcionLocal;
	}

	public void setDescripcionLocal(String descripcionLocal) {
		this.descripcionLocal = descripcionLocal;
	}

	@Column(name = "DescripcionExtranjera", length = 80)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
