package pe.royalsystems.springerp.model.domain;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParametrosMast generated by hbm2java
 */
@Entity
@Table(name = "ParametrosMast")
public class ParametrosMast extends Entidad {

	private ParametrosMastId id;
	private String descripcionParametro;
	private String explicacion;
	private String tipodeDatoFlag;
	private String texto;
	private BigDecimal numero;
	private Date fecha;
	private String financeComunFlag;
	private String estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private String explicacionAdicional;
	private String texto1;
	private String texto2;
	private String unidadReplicacion;
	private String accion;
	private String usuarioCreacion;
	private Date fechaCreacion;

	public ParametrosMast() {
	}

	public ParametrosMast(ParametrosMastId id) {
		this.id = id;
	}

	public ParametrosMast(ParametrosMastId id, String descripcionParametro, String explicacion,
			String tipodeDatoFlag, String texto, BigDecimal numero, Date fecha, String financeComunFlag,
			String estado, String ultimoUsuario, Date ultimaFechaModif, String explicacionAdicional, String texto1,
			String texto2, String unidadReplicacion, String accion, String usuarioCreacion, Date fechaCreacion) {
		this.id = id;
		this.descripcionParametro = descripcionParametro;
		this.explicacion = explicacion;
		this.tipodeDatoFlag = tipodeDatoFlag;
		this.texto = texto;
		this.numero = numero;
		this.fecha = fecha;
		this.financeComunFlag = financeComunFlag;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.explicacionAdicional = explicacionAdicional;
		this.texto1 = texto1;
		this.texto2 = texto2;
		this.unidadReplicacion = unidadReplicacion;
		this.accion = accion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companiaCodigo", column = @Column(name = "CompaniaCodigo", nullable = false, length = 10) ),
			@AttributeOverride(name = "aplicacionCodigo", column = @Column(name = "AplicacionCodigo", nullable = false, length = 2) ),
			@AttributeOverride(name = "parametroClave", column = @Column(name = "ParametroClave", nullable = false, length = 10) ) })
	public ParametrosMastId getId() {
		return this.id;
	}

	public void setId(ParametrosMastId id) {
		this.id = id;
	}

	@Column(name = "DescripcionParametro", length = 300)
	public String getDescripcionParametro() {
		return this.descripcionParametro;
	}

	public void setDescripcionParametro(String descripcionParametro) {
		this.descripcionParametro = descripcionParametro;
	}

	@Column(name = "Explicacion", length = 300)
	public String getExplicacion() {
		return this.explicacion;
	}

	public void setExplicacion(String explicacion) {
		this.explicacion = explicacion;
	}

	@Column(name = "TipodeDatoFlag", length = 1)
	public String getTipodeDatoFlag() {
		return this.tipodeDatoFlag;
	}

	public void setTipodeDatoFlag(String tipodeDatoFlag) {
		this.tipodeDatoFlag = tipodeDatoFlag;
	}

	@Column(name = "Texto", length = 20)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "Numero", scale = 4)
	public BigDecimal getNumero() {
		return this.numero;
	}

	public void setNumero(BigDecimal numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha", length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "FinanceComunFlag", length = 1)
	public String getFinanceComunFlag() {
		return this.financeComunFlag;
	}

	public void setFinanceComunFlag(String financeComunFlag) {
		this.financeComunFlag = financeComunFlag;
	}

	@Column(name = "Estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "ExplicacionAdicional", length = 250)
	public String getExplicacionAdicional() {
		return this.explicacionAdicional;
	}

	public void setExplicacionAdicional(String explicacionAdicional) {
		this.explicacionAdicional = explicacionAdicional;
	}

	@Column(name = "Texto1", length = 10)
	public String getTexto1() {
		return this.texto1;
	}

	public void setTexto1(String texto1) {
		this.texto1 = texto1;
	}

	@Column(name = "Texto2", length = 10)
	public String getTexto2() {
		return this.texto2;
	}

	public void setTexto2(String texto2) {
		this.texto2 = texto2;
	}

	@Column(name = "UnidadReplicacion", length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

}
