package pe.royalsystems.springerp.model.domain;

//default package
//Generated Sep 10, 2015 3:27:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
* ParametrosMastId generated by hbm2java
*/
@Embeddable
public class ParametrosMastId implements java.io.Serializable {

	private String companiaCodigo;
	private String aplicacionCodigo;
	private String parametroClave;

	public ParametrosMastId() {
	}

	public ParametrosMastId(String companiaCodigo, String aplicacionCodigo, String parametroClave) {
		this.companiaCodigo = companiaCodigo;
		this.aplicacionCodigo = aplicacionCodigo;
		this.parametroClave = parametroClave;
	}

	@Column(name = "CompaniaCodigo", nullable = false, length = 10)
	public String getCompaniaCodigo() {
		return this.companiaCodigo;
	}

	public void setCompaniaCodigo(String companiaCodigo) {
		this.companiaCodigo = companiaCodigo;
	}

	@Column(name = "AplicacionCodigo", nullable = false, length = 2)
	public String getAplicacionCodigo() {
		return this.aplicacionCodigo;
	}

	public void setAplicacionCodigo(String aplicacionCodigo) {
		this.aplicacionCodigo = aplicacionCodigo;
	}

	@Column(name = "ParametroClave", nullable = false, length = 10)
	public String getParametroClave() {
		return this.parametroClave;
	}

	public void setParametroClave(String parametroClave) {
		this.parametroClave = parametroClave;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametrosMastId))
			return false;
		ParametrosMastId castOther = (ParametrosMastId) other;

		return ((this.getCompaniaCodigo() == castOther.getCompaniaCodigo())
				|| (this.getCompaniaCodigo() != null && castOther.getCompaniaCodigo() != null
						&& this.getCompaniaCodigo().equals(castOther.getCompaniaCodigo())))
				&& ((this.getAplicacionCodigo() == castOther.getAplicacionCodigo())
						|| (this.getAplicacionCodigo() != null && castOther.getAplicacionCodigo() != null
								&& this.getAplicacionCodigo().equals(castOther.getAplicacionCodigo())))
				&& ((this.getParametroClave() == castOther.getParametroClave())
						|| (this.getParametroClave() != null && castOther.getParametroClave() != null
								&& this.getParametroClave().equals(castOther.getParametroClave())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompaniaCodigo() == null ? 0 : this.getCompaniaCodigo().hashCode());
		result = 37 * result + (getAplicacionCodigo() == null ? 0 : this.getAplicacionCodigo().hashCode());
		result = 37 * result + (getParametroClave() == null ? 0 : this.getParametroClave().hashCode());
		return result;
	}

}

