package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 28, 2015 2:18:16 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personamast generated by hbm2java
 */
@Entity
@Table(name = "PERSONAMAST")
public class Personamast extends Entidad implements java.io.Serializable {

	private Integer persona;
	private String origen;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombres;
	private String nombreCompleto;
	private String busqueda;
	private String grupoEmpresarial;
	private String tipoDocumento;
	private String documento;
	private String codigoBarras;
	private String esCliente;
	private String esProveedor;
	private String esEmpleado;
	private String esOtro;
	private String tipoPersona;
	private Date fechaNacimiento;
	private String ciudadNacimiento;
	private String sexo;
	private String nacionalidad;
	private String estadoCivil;
	private String nivelInstruccion;
	private String direccion;
	private String codigoPostal;
	private String provincia;
	private String departamento;
	private String telefono;
	private String fax;
	private String documentoFiscal;
	private String documentoIdentidad;
	private String carnetExtranjeria;
	private String documentoMilitarFa;
	private String tipoBrevete;
	private String brevete;
	private String pasaporte;
	private String nombreEmergencia;
	private String direccionEmergencia;
	private String telefonoEmergencia;
	private String bancoMonedaLocal;
	private String tipoCuentaLocal;
	private String cuentaMonedaLocal;
	private String bancoMonedaExtranjera;
	private String tipoCuentaExtranjera;
	private String cuentaMonedaExtranjera;
	private String personaAnt;
	private String correoElectronico;
	private String clasePersonaCodigo;
	private String personaClasificacion;
	private String enfermedadGraveFlag;
	private Date ingresoFechaRegistro;
	private String ingresoAplicacionCodigo;
	private String ingresoUsuario;
	private String pymeflag;
	private String estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private String tipoPersonaUsuario;
	private String direccionReferencia;
	private String celular;
	private String parentescoEmergencia;
	private String celularEmergencia;
	private String lugarNacimiento;
	private String suspensionFonaviFlag;
	private String flagRepetido;
	private String codDiscamec;
	private Date fecIniDiscamec;
	private Date fecFinDiscamec;
	private String codLicArma;
	private String marcaArma;
	private String serieArma;
	private Date inicioArma;
	private Date vencimientoArma;
	private String seguroDiscamec;
	private String correlativoSctr;
	private String cuentaMonedaExtranjeraTmp;
	private String cuentaMonedaLocalTmp;
	private String flagActualizacion;
	private String tarjetadeCredito;
	private String pais;
	private String esPaciente;
	private String esEmpresa;
	private Integer personaOld;
	private Integer personanew;
	private String cmp;
	private String sunatnacionalidad;
	private String sunatvia;
	private String sunatzona;
	private String sunatubigeo;
	private String sunatdomiciliado;
	private Integer indicadorAutogenerado;
	private String rutaFirma;
	private String tipoDocumentoIdentidad;
	private Integer idPersonaUnificado;
	private Integer idpersonaOk;
	private Integer edad;
	private String rangoEtario;
	private Integer tipoMedico;
	private Integer correcion;
	private Integer idEmpresaAnteriorUnificacion;
	private Date breveteFecvcto;
	private Date carnetextranjeriaFecvcto;
	private String estadoBk;
	private String estadoBks;
	private Integer indicadorVinculada;
	private String paisEmisor;
	private String codigoLdn;
	private String sunatConvenio;
	private Integer indicadorRegistroManual;
	private Integer indicadorFallecido;
	private Integer indicadorSinCorreo;
	private String accion;

	public Personamast() {
	}

	public Personamast(Integer persona, String origen, String tipoDocumento, String documento) {
		this.persona = persona;
		this.origen = origen;
		this.tipoDocumento = tipoDocumento;
		this.documento = documento;
	}

	public Personamast(Integer persona, String origen, String apellidoPaterno, String apellidoMaterno, String nombres,
			String nombreCompleto, String busqueda, String grupoEmpresarial, String tipoDocumento, String documento,
			String codigoBarras, String esCliente, String esProveedor, String esEmpleado, String esOtro,
			String tipoPersona, Date fechaNacimiento, String ciudadNacimiento, String sexo, String nacionalidad,
			String estadoCivil, String nivelInstruccion, String direccion, String codigoPostal, String provincia,
			String departamento, String telefono, String fax, String documentoFiscal, String documentoIdentidad,
			String carnetExtranjeria, String documentoMilitarFa, String tipoBrevete, String brevete,
			String pasaporte, String nombreEmergencia, String direccionEmergencia, String telefonoEmergencia,
			String bancoMonedaLocal, String tipoCuentaLocal, String cuentaMonedaLocal, String bancoMonedaExtranjera,
			String tipoCuentaExtranjera, String cuentaMonedaExtranjera, String personaAnt, String correoElectronico,
			String clasePersonaCodigo, String personaClasificacion, String enfermedadGraveFlag,
			Date ingresoFechaRegistro, String ingresoAplicacionCodigo, String ingresoUsuario, String pymeflag,
			String estado, String ultimoUsuario, Date ultimaFechaModif, String tipoPersonaUsuario,
			String direccionReferencia, String celular, String parentescoEmergencia, String celularEmergencia,
			String lugarNacimiento, String suspensionFonaviFlag, String flagRepetido, String codDiscamec,
			Date fecIniDiscamec, Date fecFinDiscamec, String codLicArma, String marcaArma, String serieArma,
			Date inicioArma, Date vencimientoArma, String seguroDiscamec, String correlativoSctr,
			String cuentaMonedaExtranjeraTmp, String cuentaMonedaLocalTmp, String flagActualizacion,
			String tarjetadeCredito, String pais, String esPaciente, String esEmpresa, Integer personaOld,
			Integer personanew, String cmp, String sunatnacionalidad, String sunatvia, String sunatzona,
			String sunatubigeo, String sunatdomiciliado, Integer indicadorAutogenerado, String rutaFirma,
			String tipoDocumentoIdentidad, Integer idPersonaUnificado, Integer idpersonaOk, Integer edad,
			String rangoEtario, Integer tipoMedico, Integer correcion, Integer idEmpresaAnteriorUnificacion,
			Date breveteFecvcto, Date carnetextranjeriaFecvcto, String estadoBk, String estadoBks,
			Integer indicadorVinculada, String paisEmisor, String codigoLdn, String sunatConvenio,
			Integer indicadorRegistroManual, Integer indicadorFallecido, Integer indicadorSinCorreo, String accion) {
		this.persona = persona;
		this.origen = origen;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombres = nombres;
		this.nombreCompleto = nombreCompleto;
		this.busqueda = busqueda;
		this.grupoEmpresarial = grupoEmpresarial;
		this.tipoDocumento = tipoDocumento;
		this.documento = documento;
		this.codigoBarras = codigoBarras;
		this.esCliente = esCliente;
		this.esProveedor = esProveedor;
		this.esEmpleado = esEmpleado;
		this.esOtro = esOtro;
		this.tipoPersona = tipoPersona;
		this.fechaNacimiento = fechaNacimiento;
		this.ciudadNacimiento = ciudadNacimiento;
		this.sexo = sexo;
		this.nacionalidad = nacionalidad;
		this.estadoCivil = estadoCivil;
		this.nivelInstruccion = nivelInstruccion;
		this.direccion = direccion;
		this.codigoPostal = codigoPostal;
		this.provincia = provincia;
		this.departamento = departamento;
		this.telefono = telefono;
		this.fax = fax;
		this.documentoFiscal = documentoFiscal;
		this.documentoIdentidad = documentoIdentidad;
		this.carnetExtranjeria = carnetExtranjeria;
		this.documentoMilitarFa = documentoMilitarFa;
		this.tipoBrevete = tipoBrevete;
		this.brevete = brevete;
		this.pasaporte = pasaporte;
		this.nombreEmergencia = nombreEmergencia;
		this.direccionEmergencia = direccionEmergencia;
		this.telefonoEmergencia = telefonoEmergencia;
		this.bancoMonedaLocal = bancoMonedaLocal;
		this.tipoCuentaLocal = tipoCuentaLocal;
		this.cuentaMonedaLocal = cuentaMonedaLocal;
		this.bancoMonedaExtranjera = bancoMonedaExtranjera;
		this.tipoCuentaExtranjera = tipoCuentaExtranjera;
		this.cuentaMonedaExtranjera = cuentaMonedaExtranjera;
		this.personaAnt = personaAnt;
		this.correoElectronico = correoElectronico;
		this.clasePersonaCodigo = clasePersonaCodigo;
		this.personaClasificacion = personaClasificacion;
		this.enfermedadGraveFlag = enfermedadGraveFlag;
		this.ingresoFechaRegistro = ingresoFechaRegistro;
		this.ingresoAplicacionCodigo = ingresoAplicacionCodigo;
		this.ingresoUsuario = ingresoUsuario;
		this.pymeflag = pymeflag;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.tipoPersonaUsuario = tipoPersonaUsuario;
		this.direccionReferencia = direccionReferencia;
		this.celular = celular;
		this.parentescoEmergencia = parentescoEmergencia;
		this.celularEmergencia = celularEmergencia;
		this.lugarNacimiento = lugarNacimiento;
		this.suspensionFonaviFlag = suspensionFonaviFlag;
		this.flagRepetido = flagRepetido;
		this.codDiscamec = codDiscamec;
		this.fecIniDiscamec = fecIniDiscamec;
		this.fecFinDiscamec = fecFinDiscamec;
		this.codLicArma = codLicArma;
		this.marcaArma = marcaArma;
		this.serieArma = serieArma;
		this.inicioArma = inicioArma;
		this.vencimientoArma = vencimientoArma;
		this.seguroDiscamec = seguroDiscamec;
		this.correlativoSctr = correlativoSctr;
		this.cuentaMonedaExtranjeraTmp = cuentaMonedaExtranjeraTmp;
		this.cuentaMonedaLocalTmp = cuentaMonedaLocalTmp;
		this.flagActualizacion = flagActualizacion;
		this.tarjetadeCredito = tarjetadeCredito;
		this.pais = pais;
		this.esPaciente = esPaciente;
		this.esEmpresa = esEmpresa;
		this.personaOld = personaOld;
		this.personanew = personanew;
		this.cmp = cmp;
		this.sunatnacionalidad = sunatnacionalidad;
		this.sunatvia = sunatvia;
		this.sunatzona = sunatzona;
		this.sunatubigeo = sunatubigeo;
		this.sunatdomiciliado = sunatdomiciliado;
		this.indicadorAutogenerado = indicadorAutogenerado;
		this.rutaFirma = rutaFirma;
		this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
		this.idPersonaUnificado = idPersonaUnificado;
		this.idpersonaOk = idpersonaOk;
		this.edad = edad;
		this.rangoEtario = rangoEtario;
		this.tipoMedico = tipoMedico;
		this.correcion = correcion;
		this.idEmpresaAnteriorUnificacion = idEmpresaAnteriorUnificacion;
		this.breveteFecvcto = breveteFecvcto;
		this.carnetextranjeriaFecvcto = carnetextranjeriaFecvcto;
		this.estadoBk = estadoBk;
		this.estadoBks = estadoBks;
		this.indicadorVinculada = indicadorVinculada;
		this.paisEmisor = paisEmisor;
		this.codigoLdn = codigoLdn;
		this.sunatConvenio = sunatConvenio;
		this.indicadorRegistroManual = indicadorRegistroManual;
		this.indicadorFallecido = indicadorFallecido;
		this.indicadorSinCorreo = indicadorSinCorreo;
		this.accion = accion;
	}

	@Id

	@Column(name = "Persona", unique = true, nullable = false)
	public Integer getPersona() {
		return this.persona;
	}

	public void setPersona(Integer persona) {
		this.persona = persona;
	}

	@Column(name = "Origen", nullable = false, length = 4)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "ApellidoPaterno", length = 40)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "ApellidoMaterno", length = 40)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "Nombres", length = 40)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "NombreCompleto", length = 100)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@Column(name = "Busqueda", length = 100)
	public String getBusqueda() {
		return this.busqueda;
	}

	public void setBusqueda(String busqueda) {
		this.busqueda = busqueda;
	}

	@Column(name = "GrupoEmpresarial", length = 4)
	public String getGrupoEmpresarial() {
		return this.grupoEmpresarial;
	}

	public void setGrupoEmpresarial(String grupoEmpresarial) {
		this.grupoEmpresarial = grupoEmpresarial;
	}

	@Column(name = "TipoDocumento", nullable = false, length = 1)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "Documento", nullable = false, length = 20)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "CodigoBarras", length = 18)
	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	@Column(name = "EsCliente", length = 1)
	public String getEsCliente() {
		return this.esCliente;
	}

	public void setEsCliente(String esCliente) {
		this.esCliente = esCliente;
	}

	@Column(name = "EsProveedor", length = 1)
	public String getEsProveedor() {
		return this.esProveedor;
	}

	public void setEsProveedor(String esProveedor) {
		this.esProveedor = esProveedor;
	}

	@Column(name = "EsEmpleado", length = 1)
	public String getEsEmpleado() {
		return this.esEmpleado;
	}

	public void setEsEmpleado(String esEmpleado) {
		this.esEmpleado = esEmpleado;
	}

	@Column(name = "EsOtro", length = 1)
	public String getEsOtro() {
		return this.esOtro;
	}

	public void setEsOtro(String esOtro) {
		this.esOtro = esOtro;
	}

	@Column(name = "TipoPersona", length = 1)
	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaNacimiento", length = 23)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "CiudadNacimiento", length = 20)
	public String getCiudadNacimiento() {
		return this.ciudadNacimiento;
	}

	public void setCiudadNacimiento(String ciudadNacimiento) {
		this.ciudadNacimiento = ciudadNacimiento;
	}

	@Column(name = "Sexo", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "Nacionalidad", length = 20)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "EstadoCivil", length = 1)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "NivelInstruccion", length = 3)
	public String getNivelInstruccion() {
		return this.nivelInstruccion;
	}

	public void setNivelInstruccion(String nivelInstruccion) {
		this.nivelInstruccion = nivelInstruccion;
	}

	@Column(name = "Direccion", length = 190)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "CodigoPostal", length = 3)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "Provincia", length = 3)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "Departamento", length = 3)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "Telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "Fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "DocumentoFiscal", length = 20)
	public String getDocumentoFiscal() {
		return this.documentoFiscal;
	}

	public void setDocumentoFiscal(String documentoFiscal) {
		this.documentoFiscal = documentoFiscal;
	}

	@Column(name = "DocumentoIdentidad", length = 20)
	public String getDocumentoIdentidad() {
		return this.documentoIdentidad;
	}

	public void setDocumentoIdentidad(String documentoIdentidad) {
		this.documentoIdentidad = documentoIdentidad;
	}

	@Column(name = "CarnetExtranjeria", length = 10)
	public String getCarnetExtranjeria() {
		return this.carnetExtranjeria;
	}

	public void setCarnetExtranjeria(String carnetExtranjeria) {
		this.carnetExtranjeria = carnetExtranjeria;
	}

	@Column(name = "DocumentoMilitarFA", length = 10)
	public String getDocumentoMilitarFa() {
		return this.documentoMilitarFa;
	}

	public void setDocumentoMilitarFa(String documentoMilitarFa) {
		this.documentoMilitarFa = documentoMilitarFa;
	}

	@Column(name = "TipoBrevete", length = 1)
	public String getTipoBrevete() {
		return this.tipoBrevete;
	}

	public void setTipoBrevete(String tipoBrevete) {
		this.tipoBrevete = tipoBrevete;
	}

	@Column(name = "Brevete", length = 18)
	public String getBrevete() {
		return this.brevete;
	}

	public void setBrevete(String brevete) {
		this.brevete = brevete;
	}

	@Column(name = "Pasaporte", length = 18)
	public String getPasaporte() {
		return this.pasaporte;
	}

	public void setPasaporte(String pasaporte) {
		this.pasaporte = pasaporte;
	}

	@Column(name = "NombreEmergencia", length = 50)
	public String getNombreEmergencia() {
		return this.nombreEmergencia;
	}

	public void setNombreEmergencia(String nombreEmergencia) {
		this.nombreEmergencia = nombreEmergencia;
	}

	@Column(name = "DireccionEmergencia", length = 60)
	public String getDireccionEmergencia() {
		return this.direccionEmergencia;
	}

	public void setDireccionEmergencia(String direccionEmergencia) {
		this.direccionEmergencia = direccionEmergencia;
	}

	@Column(name = "TelefonoEmergencia", length = 15)
	public String getTelefonoEmergencia() {
		return this.telefonoEmergencia;
	}

	public void setTelefonoEmergencia(String telefonoEmergencia) {
		this.telefonoEmergencia = telefonoEmergencia;
	}

	@Column(name = "BancoMonedaLocal", length = 3)
	public String getBancoMonedaLocal() {
		return this.bancoMonedaLocal;
	}

	public void setBancoMonedaLocal(String bancoMonedaLocal) {
		this.bancoMonedaLocal = bancoMonedaLocal;
	}

	@Column(name = "TipoCuentaLocal", length = 3)
	public String getTipoCuentaLocal() {
		return this.tipoCuentaLocal;
	}

	public void setTipoCuentaLocal(String tipoCuentaLocal) {
		this.tipoCuentaLocal = tipoCuentaLocal;
	}

	@Column(name = "CuentaMonedaLocal", length = 20)
	public String getCuentaMonedaLocal() {
		return this.cuentaMonedaLocal;
	}

	public void setCuentaMonedaLocal(String cuentaMonedaLocal) {
		this.cuentaMonedaLocal = cuentaMonedaLocal;
	}

	@Column(name = "BancoMonedaExtranjera", length = 3)
	public String getBancoMonedaExtranjera() {
		return this.bancoMonedaExtranjera;
	}

	public void setBancoMonedaExtranjera(String bancoMonedaExtranjera) {
		this.bancoMonedaExtranjera = bancoMonedaExtranjera;
	}

	@Column(name = "TipoCuentaExtranjera", length = 3)
	public String getTipoCuentaExtranjera() {
		return this.tipoCuentaExtranjera;
	}

	public void setTipoCuentaExtranjera(String tipoCuentaExtranjera) {
		this.tipoCuentaExtranjera = tipoCuentaExtranjera;
	}

	@Column(name = "CuentaMonedaExtranjera", length = 20)
	public String getCuentaMonedaExtranjera() {
		return this.cuentaMonedaExtranjera;
	}

	public void setCuentaMonedaExtranjera(String cuentaMonedaExtranjera) {
		this.cuentaMonedaExtranjera = cuentaMonedaExtranjera;
	}

	@Column(name = "PersonaAnt", length = 15)
	public String getPersonaAnt() {
		return this.personaAnt;
	}

	public void setPersonaAnt(String personaAnt) {
		this.personaAnt = personaAnt;
	}

	@Column(name = "CorreoElectronico", length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "ClasePersonaCodigo", length = 3)
	public String getClasePersonaCodigo() {
		return this.clasePersonaCodigo;
	}

	public void setClasePersonaCodigo(String clasePersonaCodigo) {
		this.clasePersonaCodigo = clasePersonaCodigo;
	}

	@Column(name = "PersonaClasificacion", length = 8)
	public String getPersonaClasificacion() {
		return this.personaClasificacion;
	}

	public void setPersonaClasificacion(String personaClasificacion) {
		this.personaClasificacion = personaClasificacion;
	}

	@Column(name = "EnfermedadGraveFlag", length = 1)
	public String getEnfermedadGraveFlag() {
		return this.enfermedadGraveFlag;
	}

	public void setEnfermedadGraveFlag(String enfermedadGraveFlag) {
		this.enfermedadGraveFlag = enfermedadGraveFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IngresoFechaRegistro", length = 23)
	public Date getIngresoFechaRegistro() {
		return this.ingresoFechaRegistro;
	}

	public void setIngresoFechaRegistro(Date ingresoFechaRegistro) {
		this.ingresoFechaRegistro = ingresoFechaRegistro;
	}

	@Column(name = "IngresoAplicacionCodigo", length = 2)
	public String getIngresoAplicacionCodigo() {
		return this.ingresoAplicacionCodigo;
	}

	public void setIngresoAplicacionCodigo(String ingresoAplicacionCodigo) {
		this.ingresoAplicacionCodigo = ingresoAplicacionCodigo;
	}

	@Column(name = "IngresoUsuario", length = 25)
	public String getIngresoUsuario() {
		return this.ingresoUsuario;
	}

	public void setIngresoUsuario(String ingresoUsuario) {
		this.ingresoUsuario = ingresoUsuario;
	}

	@Column(name = "PYMEFlag", length = 1)
	public String getPymeflag() {
		return this.pymeflag;
	}

	public void setPymeflag(String pymeflag) {
		this.pymeflag = pymeflag;
	}

	@Column(name = "Estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "TipoPersonaUsuario", length = 3)
	public String getTipoPersonaUsuario() {
		return this.tipoPersonaUsuario;
	}

	public void setTipoPersonaUsuario(String tipoPersonaUsuario) {
		this.tipoPersonaUsuario = tipoPersonaUsuario;
	}

	@Column(name = "DireccionReferencia")
	public String getDireccionReferencia() {
		return this.direccionReferencia;
	}

	public void setDireccionReferencia(String direccionReferencia) {
		this.direccionReferencia = direccionReferencia;
	}

	@Column(name = "Celular", length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "ParentescoEmergencia", length = 15)
	public String getParentescoEmergencia() {
		return this.parentescoEmergencia;
	}

	public void setParentescoEmergencia(String parentescoEmergencia) {
		this.parentescoEmergencia = parentescoEmergencia;
	}

	@Column(name = "CelularEmergencia", length = 15)
	public String getCelularEmergencia() {
		return this.celularEmergencia;
	}

	public void setCelularEmergencia(String celularEmergencia) {
		this.celularEmergencia = celularEmergencia;
	}

	@Column(name = "LugarNacimiento")
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "SuspensionFonaviFlag", length = 10)
	public String getSuspensionFonaviFlag() {
		return this.suspensionFonaviFlag;
	}

	public void setSuspensionFonaviFlag(String suspensionFonaviFlag) {
		this.suspensionFonaviFlag = suspensionFonaviFlag;
	}

	@Column(name = "FlagRepetido", length = 1)
	public String getFlagRepetido() {
		return this.flagRepetido;
	}

	public void setFlagRepetido(String flagRepetido) {
		this.flagRepetido = flagRepetido;
	}

	@Column(name = "CodDiscamec", length = 15)
	public String getCodDiscamec() {
		return this.codDiscamec;
	}

	public void setCodDiscamec(String codDiscamec) {
		this.codDiscamec = codDiscamec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FecIniDiscamec", length = 23)
	public Date getFecIniDiscamec() {
		return this.fecIniDiscamec;
	}

	public void setFecIniDiscamec(Date fecIniDiscamec) {
		this.fecIniDiscamec = fecIniDiscamec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FecFinDiscamec", length = 23)
	public Date getFecFinDiscamec() {
		return this.fecFinDiscamec;
	}

	public void setFecFinDiscamec(Date fecFinDiscamec) {
		this.fecFinDiscamec = fecFinDiscamec;
	}

	@Column(name = "CodLicArma", length = 15)
	public String getCodLicArma() {
		return this.codLicArma;
	}

	public void setCodLicArma(String codLicArma) {
		this.codLicArma = codLicArma;
	}

	@Column(name = "MarcaArma", length = 10)
	public String getMarcaArma() {
		return this.marcaArma;
	}

	public void setMarcaArma(String marcaArma) {
		this.marcaArma = marcaArma;
	}

	@Column(name = "SerieArma", length = 10)
	public String getSerieArma() {
		return this.serieArma;
	}

	public void setSerieArma(String serieArma) {
		this.serieArma = serieArma;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "InicioArma", length = 23)
	public Date getInicioArma() {
		return this.inicioArma;
	}

	public void setInicioArma(Date inicioArma) {
		this.inicioArma = inicioArma;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VencimientoArma", length = 23)
	public Date getVencimientoArma() {
		return this.vencimientoArma;
	}

	public void setVencimientoArma(Date vencimientoArma) {
		this.vencimientoArma = vencimientoArma;
	}

	@Column(name = "SeguroDiscamec", length = 1)
	public String getSeguroDiscamec() {
		return this.seguroDiscamec;
	}

	public void setSeguroDiscamec(String seguroDiscamec) {
		this.seguroDiscamec = seguroDiscamec;
	}

	@Column(name = "CorrelativoSCTR", length = 3)
	public String getCorrelativoSctr() {
		return this.correlativoSctr;
	}

	public void setCorrelativoSctr(String correlativoSctr) {
		this.correlativoSctr = correlativoSctr;
	}

	@Column(name = "CuentaMonedaExtranjera_tmp", length = 15)
	public String getCuentaMonedaExtranjeraTmp() {
		return this.cuentaMonedaExtranjeraTmp;
	}

	public void setCuentaMonedaExtranjeraTmp(String cuentaMonedaExtranjeraTmp) {
		this.cuentaMonedaExtranjeraTmp = cuentaMonedaExtranjeraTmp;
	}

	@Column(name = "CuentaMonedaLocal_tmp", length = 15)
	public String getCuentaMonedaLocalTmp() {
		return this.cuentaMonedaLocalTmp;
	}

	public void setCuentaMonedaLocalTmp(String cuentaMonedaLocalTmp) {
		this.cuentaMonedaLocalTmp = cuentaMonedaLocalTmp;
	}

	@Column(name = "FlagActualizacion", length = 1)
	public String getFlagActualizacion() {
		return this.flagActualizacion;
	}

	public void setFlagActualizacion(String flagActualizacion) {
		this.flagActualizacion = flagActualizacion;
	}

	@Column(name = "TarjetadeCredito", length = 20)
	public String getTarjetadeCredito() {
		return this.tarjetadeCredito;
	}

	public void setTarjetadeCredito(String tarjetadeCredito) {
		this.tarjetadeCredito = tarjetadeCredito;
	}

	@Column(name = "Pais", length = 4)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "EsPaciente", length = 1)
	public String getEsPaciente() {
		return this.esPaciente;
	}

	public void setEsPaciente(String esPaciente) {
		this.esPaciente = esPaciente;
	}

	@Column(name = "EsEmpresa", length = 1)
	public String getEsEmpresa() {
		return this.esEmpresa;
	}

	public void setEsEmpresa(String esEmpresa) {
		this.esEmpresa = esEmpresa;
	}

	@Column(name = "Persona_Old")
	public Integer getPersonaOld() {
		return this.personaOld;
	}

	public void setPersonaOld(Integer personaOld) {
		this.personaOld = personaOld;
	}

	@Column(name = "personanew")
	public Integer getPersonanew() {
		return this.personanew;
	}

	public void setPersonanew(Integer personanew) {
		this.personanew = personanew;
	}

	@Column(name = "cmp", length = 15)
	public String getCmp() {
		return this.cmp;
	}

	public void setCmp(String cmp) {
		this.cmp = cmp;
	}

	@Column(name = "SUNATNacionalidad", length = 6)
	public String getSunatnacionalidad() {
		return this.sunatnacionalidad;
	}

	public void setSunatnacionalidad(String sunatnacionalidad) {
		this.sunatnacionalidad = sunatnacionalidad;
	}

	@Column(name = "SUNATVia", length = 2)
	public String getSunatvia() {
		return this.sunatvia;
	}

	public void setSunatvia(String sunatvia) {
		this.sunatvia = sunatvia;
	}

	@Column(name = "SUNATZona", length = 2)
	public String getSunatzona() {
		return this.sunatzona;
	}

	public void setSunatzona(String sunatzona) {
		this.sunatzona = sunatzona;
	}

	@Column(name = "SUNATUbigeo", length = 10)
	public String getSunatubigeo() {
		return this.sunatubigeo;
	}

	public void setSunatubigeo(String sunatubigeo) {
		this.sunatubigeo = sunatubigeo;
	}

	@Column(name = "SUNATDomiciliado", length = 1)
	public String getSunatdomiciliado() {
		return this.sunatdomiciliado;
	}

	public void setSunatdomiciliado(String sunatdomiciliado) {
		this.sunatdomiciliado = sunatdomiciliado;
	}

	@Column(name = "IndicadorAutogenerado")
	public Integer getIndicadorAutogenerado() {
		return this.indicadorAutogenerado;
	}

	public void setIndicadorAutogenerado(Integer indicadorAutogenerado) {
		this.indicadorAutogenerado = indicadorAutogenerado;
	}

	@Column(name = "RutaFirma", length = 250)
	public String getRutaFirma() {
		return this.rutaFirma;
	}

	public void setRutaFirma(String rutaFirma) {
		this.rutaFirma = rutaFirma;
	}

	@Column(name = "TipoDocumentoIdentidad", length = 1)
	public String getTipoDocumentoIdentidad() {
		return this.tipoDocumentoIdentidad;
	}

	public void setTipoDocumentoIdentidad(String tipoDocumentoIdentidad) {
		this.tipoDocumentoIdentidad = tipoDocumentoIdentidad;
	}

	@Column(name = "IdPersonaUnificado")
	public Integer getIdPersonaUnificado() {
		return this.idPersonaUnificado;
	}

	public void setIdPersonaUnificado(Integer idPersonaUnificado) {
		this.idPersonaUnificado = idPersonaUnificado;
	}

	@Column(name = "idpersona_ok")
	public Integer getIdpersonaOk() {
		return this.idpersonaOk;
	}

	public void setIdpersonaOk(Integer idpersonaOk) {
		this.idpersonaOk = idpersonaOk;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "rangoEtario", length = 10)
	public String getRangoEtario() {
		return this.rangoEtario;
	}

	public void setRangoEtario(String rangoEtario) {
		this.rangoEtario = rangoEtario;
	}

	@Column(name = "TipoMedico")
	public Integer getTipoMedico() {
		return this.tipoMedico;
	}

	public void setTipoMedico(Integer tipoMedico) {
		this.tipoMedico = tipoMedico;
	}

	@Column(name = "Correcion")
	public Integer getCorrecion() {
		return this.correcion;
	}

	public void setCorrecion(Integer correcion) {
		this.correcion = correcion;
	}

	@Column(name = "IdEmpresaAnteriorUnificacion")
	public Integer getIdEmpresaAnteriorUnificacion() {
		return this.idEmpresaAnteriorUnificacion;
	}

	public void setIdEmpresaAnteriorUnificacion(Integer idEmpresaAnteriorUnificacion) {
		this.idEmpresaAnteriorUnificacion = idEmpresaAnteriorUnificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "brevete_fecvcto", length = 23)
	public Date getBreveteFecvcto() {
		return this.breveteFecvcto;
	}

	public void setBreveteFecvcto(Date breveteFecvcto) {
		this.breveteFecvcto = breveteFecvcto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "carnetextranjeria_fecvcto", length = 23)
	public Date getCarnetextranjeriaFecvcto() {
		return this.carnetextranjeriaFecvcto;
	}

	public void setCarnetextranjeriaFecvcto(Date carnetextranjeriaFecvcto) {
		this.carnetextranjeriaFecvcto = carnetextranjeriaFecvcto;
	}

	@Column(name = "Estado_BK", length = 1)
	public String getEstadoBk() {
		return this.estadoBk;
	}

	public void setEstadoBk(String estadoBk) {
		this.estadoBk = estadoBk;
	}

	@Column(name = "Estado_Bks", length = 1)
	public String getEstadoBks() {
		return this.estadoBks;
	}

	public void setEstadoBks(String estadoBks) {
		this.estadoBks = estadoBks;
	}

	@Column(name = "IndicadorVinculada")
	public Integer getIndicadorVinculada() {
		return this.indicadorVinculada;
	}

	public void setIndicadorVinculada(Integer indicadorVinculada) {
		this.indicadorVinculada = indicadorVinculada;
	}

	@Column(name = "PaisEmisor", length = 3)
	public String getPaisEmisor() {
		return this.paisEmisor;
	}

	public void setPaisEmisor(String paisEmisor) {
		this.paisEmisor = paisEmisor;
	}

	@Column(name = "CodigoLDN", length = 3)
	public String getCodigoLdn() {
		return this.codigoLdn;
	}

	public void setCodigoLdn(String codigoLdn) {
		this.codigoLdn = codigoLdn;
	}

	@Column(name = "SunatConvenio", length = 1)
	public String getSunatConvenio() {
		return this.sunatConvenio;
	}

	public void setSunatConvenio(String sunatConvenio) {
		this.sunatConvenio = sunatConvenio;
	}

	@Column(name = "IndicadorRegistroManual")
	public Integer getIndicadorRegistroManual() {
		return this.indicadorRegistroManual;
	}

	public void setIndicadorRegistroManual(Integer indicadorRegistroManual) {
		this.indicadorRegistroManual = indicadorRegistroManual;
	}

	@Column(name = "IndicadorFallecido")
	public Integer getIndicadorFallecido() {
		return this.indicadorFallecido;
	}

	public void setIndicadorFallecido(Integer indicadorFallecido) {
		this.indicadorFallecido = indicadorFallecido;
	}

	@Column(name = "IndicadorSinCorreo")
	public Integer getIndicadorSinCorreo() {
		return this.indicadorSinCorreo;
	}

	public void setIndicadorSinCorreo(Integer indicadorSinCorreo) {
		this.indicadorSinCorreo = indicadorSinCorreo;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
