package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 13, 2015 1:11:12 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RmProyectoUsuarioSupervisorId generated by hbm2java
 */
@Embeddable
public class RmProyectoUsuarioSupervisorId implements java.io.Serializable {

	private String proyecto;
	private String centroCosto;
	private String usuarioSupervisor;

	public RmProyectoUsuarioSupervisorId() {
	}

	public RmProyectoUsuarioSupervisorId(String proyecto, String centroCosto, String usuarioSupervisor) {
		this.proyecto = proyecto;
		this.centroCosto = centroCosto;
		this.usuarioSupervisor = usuarioSupervisor;
	}

	@Column(name = "Proyecto", nullable = false, length = 15)
	public String getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(String proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "CentroCosto", nullable = false, length = 10)
	public String getCentroCosto() {
		return this.centroCosto;
	}

	public void setCentroCosto(String centroCosto) {
		this.centroCosto = centroCosto;
	}

	@Column(name = "UsuarioSupervisor", nullable = false, length = 20)
	public String getUsuarioSupervisor() {
		return this.usuarioSupervisor;
	}

	public void setUsuarioSupervisor(String usuarioSupervisor) {
		this.usuarioSupervisor = usuarioSupervisor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RmProyectoUsuarioSupervisorId))
			return false;
		RmProyectoUsuarioSupervisorId castOther = (RmProyectoUsuarioSupervisorId) other;

		return ((this.getProyecto() == castOther.getProyecto()) || (this.getProyecto() != null
				&& castOther.getProyecto() != null && this.getProyecto().equals(castOther.getProyecto())))
				&& ((this.getCentroCosto() == castOther.getCentroCosto())
						|| (this.getCentroCosto() != null && castOther.getCentroCosto() != null
								&& this.getCentroCosto().equals(castOther.getCentroCosto())))
				&& ((this.getUsuarioSupervisor() == castOther.getUsuarioSupervisor())
						|| (this.getUsuarioSupervisor() != null && castOther.getUsuarioSupervisor() != null
								&& this.getUsuarioSupervisor().equals(castOther.getUsuarioSupervisor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProyecto() == null ? 0 : this.getProyecto().hashCode());
		result = 37 * result + (getCentroCosto() == null ? 0 : this.getCentroCosto().hashCode());
		result = 37 * result + (getUsuarioSupervisor() == null ? 0 : this.getUsuarioSupervisor().hashCode());
		return result;
	}

}
