package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 13, 2015 1:11:12 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RmProyectoUsuarioSupervisor generated by hbm2java
 */
@Entity
@Table(name = "RM_ProyectoUsuarioSupervisor", schema = "dbo", catalog = "WebCoreManager")
public class RmProyectoUsuarioSupervisor extends Entidad implements java.io.Serializable {

	private RmProyectoUsuarioSupervisorId id;

	public RmProyectoUsuarioSupervisor() {
	}

	public RmProyectoUsuarioSupervisor(RmProyectoUsuarioSupervisorId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "proyecto", column = @Column(name = "Proyecto", nullable = false, length = 15) ),
			@AttributeOverride(name = "centroCosto", column = @Column(name = "CentroCosto", nullable = false, length = 10) ),
			@AttributeOverride(name = "usuarioSupervisor", column = @Column(name = "UsuarioSupervisor", nullable = false, length = 20) ) })
	public RmProyectoUsuarioSupervisorId getId() {
		return this.id;
	}

	public void setId(RmProyectoUsuarioSupervisorId id) {
		this.id = id;
	}

}
