package pe.royalsystems.springerp.model.domain;

import java.util.Date;

// default package
// Generated Sep 10, 2015 12:39:11 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SeguridadAutorizacionCompania generated by hbm2java
 */
@Entity
@Table(name = "SeguridadAutorizacionCompania")
public class SeguridadAutorizacionCompania extends Entidad implements java.io.Serializable {

	private SeguridadAutorizacionCompaniaId id;
	private String estado;
	private Date ultimaFechaModif;
	private String ultimoUsuario;
	private String campoData;

	public SeguridadAutorizacionCompania() {
	}

	public SeguridadAutorizacionCompania(SeguridadAutorizacionCompaniaId id, String estado, Date ultimaFechaModif,
			String ultimoUsuario, String campoData) {
		this.id = id;
		this.estado = estado;
		this.ultimaFechaModif = ultimaFechaModif;
		this.ultimoUsuario = ultimoUsuario;
		this.campoData = campoData;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companyowner", column = @Column(name = "Companyowner", nullable = false, length = 8) ),
			@AttributeOverride(name = "usuario", column = @Column(name = "Usuario", length = 25) ),
		 })
	public SeguridadAutorizacionCompaniaId getId() {
		return this.id;
	}

	public void setId(SeguridadAutorizacionCompaniaId id) {
		this.id = id;
	}
	
	@Column(name = "Estado", length = 2)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "CampoData", length = 50)
	public String getCampoData() {
		return this.campoData;
	}

	public void setCampoData(String campoData) {
		this.campoData = campoData;
	}

}
