package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 7, 2015 4:48:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SgGrupo generated by hbm2java
 */
@Entity
@Table(name = "SG_Grupo")
public class SgGrupo extends Entidad implements java.io.Serializable {

	private int idGrupo;
	private SgGrupo sgGrupo;
	private String codigoGrupo;
	private String cadenaRecursividad;
	private Integer nivelGrupo;
	private String nombre;
	private String descripcion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;
	private Set<SgGrupo> sgGrupos = new HashSet<SgGrupo>(0);

	public SgGrupo() {
	}

	public SgGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	public SgGrupo(int idGrupo, SgGrupo sgGrupo, String codigoGrupo, String cadenaRecursividad, Integer nivelGrupo,
			String nombre, String descripcion, Integer estado, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion, String accion, Set<SgGrupo> sgGrupos) {
		this.idGrupo = idGrupo;
		this.sgGrupo = sgGrupo;
		this.codigoGrupo = codigoGrupo;
		this.cadenaRecursividad = cadenaRecursividad;
		this.nivelGrupo = nivelGrupo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
		this.sgGrupos = sgGrupos;
	}

	@Id

	@Column(name = "IdGrupo", unique = true, nullable = false)
	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdGrupoPadre")
	public SgGrupo getSgGrupo() {
		return this.sgGrupo;
	}

	public void setSgGrupo(SgGrupo sgGrupo) {
		this.sgGrupo = sgGrupo;
	}

	@Column(name = "CodigoGrupo", length = 15)
	public String getCodigoGrupo() {
		return this.codigoGrupo;
	}

	public void setCodigoGrupo(String codigoGrupo) {
		this.codigoGrupo = codigoGrupo;
	}

	@Column(name = "CadenaRecursividad", length = 150)
	public String getCadenaRecursividad() {
		return this.cadenaRecursividad;
	}

	public void setCadenaRecursividad(String cadenaRecursividad) {
		this.cadenaRecursividad = cadenaRecursividad;
	}

	@Column(name = "NivelGrupo")
	public Integer getNivelGrupo() {
		return this.nivelGrupo;
	}

	public void setNivelGrupo(Integer nivelGrupo) {
		this.nivelGrupo = nivelGrupo;
	}

	@Column(name = "Nombre", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgGrupo")
	public Set<SgGrupo> getSgGrupos() {
		return this.sgGrupos;
	}

	public void setSgGrupos(Set<SgGrupo> sgGrupos) {
		this.sgGrupos = sgGrupos;
	}

}
