package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 7, 2015 3:46:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SgPerfilUsuario generated by hbm2java
 */
@Entity
@Table(name = "SG_PerfilUsuario")
public class SgPerfilUsuario extends Entidad implements java.io.Serializable {

	private SgPerfilUsuarioId id;
	private String version;
	private SgAgente sgAgente;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;

	public SgPerfilUsuario() {
		id = new SgPerfilUsuarioId();
	}

	public SgPerfilUsuario(SgPerfilUsuarioId id, SgAgente sgAgente) {
		this.id = id;
		this.sgAgente = sgAgente;
	}

	public SgPerfilUsuario(SgPerfilUsuarioId id, SgAgente sgAgente, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, String accion) {
		this.id = id;
		this.sgAgente = sgAgente;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPerfil", column = @Column(name = "IdPerfil", nullable = false) ),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "IdUsuario", nullable = false) ) })
	public SgPerfilUsuarioId getId() {
		return this.id;
	}

	public void setId(SgPerfilUsuarioId id) {
		this.id = id;
	}


	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdUsuario", nullable = false, insertable = false, updatable = false)
	public SgAgente getSgAgente() {
		return this.sgAgente;
	}

	public void setSgAgente(SgAgente sgAgente) {
		this.sgAgente = sgAgente;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
