package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 7, 2015 3:46:46 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SgPerfilUsuarioId generated by hbm2java
 */
@Embeddable
public class SgPerfilUsuarioId implements java.io.Serializable {

	private Integer idPerfil;
	private Integer idUsuario;

	public SgPerfilUsuarioId() {
	}

	public SgPerfilUsuarioId(Integer idPerfil, Integer idUsuario) {
		this.idPerfil = idPerfil;
		this.idUsuario = idUsuario;
	}

	@Column(name = "IdPerfil", nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "IdUsuario", nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SgPerfilUsuarioId))
			return false;
		SgPerfilUsuarioId castOther = (SgPerfilUsuarioId) other;

		return (this.getIdPerfil() == castOther.getIdPerfil()) && (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
