package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 14, 2015 10:34:01 AM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.util.Date;

/**
 * SsAdOrdenAtencionPreexistencia generated by hbm2java
 */
@Entity
@Table(name = "SS_AD_OrdenAtencionPreexistencia")
public class SsAdOrdenAtencionPreexistencia extends Entidad  implements java.io.Serializable {

	private SsAdOrdenAtencionPreexistenciaId id;
	private SsAdOrdenAtencion ssAdOrdenAtencion;
	private Integer idDiagnostico;
	private String codigoDiagnostico;
	private String nombreDiagnostico;
	private String observacion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;

	public SsAdOrdenAtencionPreexistencia() {
	}

	public SsAdOrdenAtencionPreexistencia(SsAdOrdenAtencionPreexistenciaId id, SsAdOrdenAtencion ssAdOrdenAtencion) {
		this.id = id;
		this.ssAdOrdenAtencion = ssAdOrdenAtencion;
	}

	public SsAdOrdenAtencionPreexistencia(SsAdOrdenAtencionPreexistenciaId id, SsAdOrdenAtencion ssAdOrdenAtencion,
			Integer idDiagnostico, String codigoDiagnostico, String nombreDiagnostico, String observacion,
			Integer estado, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion,
			Date fechaModificacion, String accion) {
		this.id = id;
		this.ssAdOrdenAtencion = ssAdOrdenAtencion;
		this.idDiagnostico = idDiagnostico;
		this.codigoDiagnostico = codigoDiagnostico;
		this.nombreDiagnostico = nombreDiagnostico;
		this.observacion = observacion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrdenAtencion", column = @Column(name = "IdOrdenAtencion", nullable = false) ),
			@AttributeOverride(name = "secuencial", column = @Column(name = "Secuencial", nullable = false) ) })
	public SsAdOrdenAtencionPreexistenciaId getId() {
		return this.id;
	}

	public void setId(SsAdOrdenAtencionPreexistenciaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdOrdenAtencion", nullable = false, insertable = false, updatable = false)
	public SsAdOrdenAtencion getSsAdOrdenAtencion() {
		return this.ssAdOrdenAtencion;
	}

	public void setSsAdOrdenAtencion(SsAdOrdenAtencion ssAdOrdenAtencion) {
		this.ssAdOrdenAtencion = ssAdOrdenAtencion;
	}

	@Column(name = "IdDiagnostico")
	public Integer getIdDiagnostico() {
		return this.idDiagnostico;
	}

	public void setIdDiagnostico(Integer idDiagnostico) {
		this.idDiagnostico = idDiagnostico;
	}

	@Column(name = "CodigoDiagnostico", length = 15)
	public String getCodigoDiagnostico() {
		return this.codigoDiagnostico;
	}

	public void setCodigoDiagnostico(String codigoDiagnostico) {
		this.codigoDiagnostico = codigoDiagnostico;
	}

	@Column(name = "NombreDiagnostico", length = 250)
	public String getNombreDiagnostico() {
		return this.nombreDiagnostico;
	}

	public void setNombreDiagnostico(String nombreDiagnostico) {
		this.nombreDiagnostico = nombreDiagnostico;
	}

	@Column(name = "Observacion", length = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "accion", length = 20)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
