package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 14, 2015 10:34:01 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SsAdOrdenAtencion generated by hbm2java
 */
@Entity
@Table(name = "SS_AD_OrdenAtencion")
public class SsAdOrdenAtencion extends Entidad {

	private Integer idOrdenAtencion;
	private Integer idPolizaPlan;
	private Integer secuencialPolizaPlan;
	private Integer tipoOrdenAtencion;
	private String codigoOa;
	private Integer especialidad;
	private Date fechaPreparacion;
	private Date fechaInicio;
	private Date fechaFinal;
	private Integer idOrdenRelacionada;
	private Integer tipoAtencion;
	private Integer tipoPaciente;
	private Integer tipoParentesco;
	private Integer modalidad;
	private Integer idServicio;
	private Integer idTurno;
	private Integer idPaciente;
	private Integer idEmpresaAseguradora;
	private String compania;
	private String sucursal;
	private Integer idEstablecimiento;
	private Integer idCaja;
	private String centroCosto;
	private String clasificadorMovimiento;
	private String unidadOrganizacional;
	private String proyecto;
	private String conceptoGasto;
	private Integer idOpc;
	private String tipoOpc;
	private String serieOpc;
	private Integer numeroOpc;
	private Integer idTransaccion;
	private Integer tipoAlta;
	private Date fechaAlta;
	private Integer idMedicoAutoriza;
	private String observacionAlta;
	private Integer estadoDocumento;
	private Integer estadoDocumentoAnterior;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Integer indicadorTmh;
	private Integer idEmpleado;
	private Integer idAlumno;
	private Date fechaEmision;
	private Integer secuencialTmh;
	private Integer idEmpresaEmpleadora;
	private Integer idLineaOrdenRelacionada;
	private Integer idContrato;
	private Integer idPoliza;
	private Integer idPlan;
	private Integer idCobertura;
	private BigDecimal copagoFijo;
	private BigDecimal copagoVariable;
	private Integer idPersonaAntUnificacion;
	private Date fechaAnterior;
	private String copagoMoneda;
	private String codigoSiteds;
	private String titularNombre;
	private Integer coberturaMedico;
	private Integer situacionControlOa;
	private Integer idEmpresaAnteriorUnificacion;
	private String descripcionempresaSeguros;
	private Integer tipoAltaMedica;
	private Integer idConsultaExternaPrincipal;
	private Integer idTopico;
	private Integer indicadorOcultarOa;
	private Integer indicadorAltaMedica;
	private Integer coberturaMedicoOriginal;
	private Integer tipoAltaMedicaOriginal;
	private String observacionAltaOriginal;
	private Integer indicadorAltaMedicaOriginal;
	private Integer idConsultaExternaPrincipalOriginal;
	private Integer indHospitalizado;
	private Integer indicadorEmergenciaRm;
	private Integer bkestadodocumento20110517;
	private Integer bkestadodocumentoanterior20110517;
	private String listaExamenComplementario;
	private String listaProcedimiento;
	private String usuarioAmpliacionOa;
	private String usuarioAnteriorAmpliacionOa;
	private Integer indicadorAuditoria;
	private Integer indicadorAtencionWeb;
	private Integer indicadorRecalculoModalidad;
	private Integer tipoPacienteInicial;
	private Integer idPacienteInicial;
	private String unidadReplicacion;
	private Integer prioridad;
	private String contratoNum;
	private Set<SsAdOrdenAtencionPreexistencia> ssAdOrdenAtencionPreexistencias = new HashSet<SsAdOrdenAtencionPreexistencia>(
			0);

	public SsAdOrdenAtencion() {
	}

	public SsAdOrdenAtencion(Integer idOrdenAtencion) {
		this.idOrdenAtencion = idOrdenAtencion;
	}

	public SsAdOrdenAtencion(Integer idOrdenAtencion, Integer idPolizaPlan, Integer secuencialPolizaPlan,
			Integer tipoOrdenAtencion, String codigoOa, Integer especialidad, Date fechaPreparacion, Date fechaInicio,
			Date fechaFinal, Integer idOrdenRelacionada, Integer tipoAtencion, Integer tipoPaciente,
			Integer tipoParentesco, Integer modalidad, Integer idServicio, Integer idTurno, Integer idPaciente,
			Integer idEmpresaAseguradora, String compania, String sucursal, Integer idEstablecimiento, Integer idCaja,
			String centroCosto, String clasificadorMovimiento, String unidadOrganizacional, String proyecto,
			String conceptoGasto, Integer idOpc, String tipoOpc, String serieOpc, Integer numeroOpc,
			Integer idTransaccion, Integer tipoAlta, Date fechaAlta, Integer idMedicoAutoriza, String observacionAlta,
			Integer estadoDocumento, Integer estadoDocumentoAnterior, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, Integer indicadorTmh,
			Integer idEmpleado, Integer idAlumno, Date fechaEmision, Integer secuencialTmh, Integer idEmpresaEmpleadora,
			Integer idLineaOrdenRelacionada, Integer idContrato, Integer idPoliza, Integer idPlan, Integer idCobertura,
			BigDecimal copagoFijo, BigDecimal copagoVariable, Integer idPersonaAntUnificacion, Date fechaAnterior,
			String copagoMoneda, String codigoSiteds, String titularNombre, Integer coberturaMedico,
			Integer situacionControlOa, Integer idEmpresaAnteriorUnificacion, String descripcionempresaSeguros,
			Integer tipoAltaMedica, Integer idConsultaExternaPrincipal, Integer idTopico, Integer indicadorOcultarOa,
			Integer indicadorAltaMedica, Integer coberturaMedicoOriginal, Integer tipoAltaMedicaOriginal,
			String observacionAltaOriginal, Integer indicadorAltaMedicaOriginal,
			Integer idConsultaExternaPrincipalOriginal, Integer indHospitalizado, Integer indicadorEmergenciaRm,
			Integer bkestadodocumento20110517, Integer bkestadodocumentoanterior20110517,
			String listaExamenComplementario, String listaProcedimiento, String usuarioAmpliacionOa,
			String usuarioAnteriorAmpliacionOa, Integer indicadorAuditoria, Integer indicadorAtencionWeb,
			Integer indicadorRecalculoModalidad, Integer tipoPacienteInicial, Integer idPacienteInicial,
			String unidadReplicacion, Integer prioridad, String contratoNum,
			Set<SsAdOrdenAtencionPreexistencia> ssAdOrdenAtencionPreexistencias) {
		this.idOrdenAtencion = idOrdenAtencion;
		this.idPolizaPlan = idPolizaPlan;
		this.secuencialPolizaPlan = secuencialPolizaPlan;
		this.tipoOrdenAtencion = tipoOrdenAtencion;
		this.codigoOa = codigoOa;
		this.especialidad = especialidad;
		this.fechaPreparacion = fechaPreparacion;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.idOrdenRelacionada = idOrdenRelacionada;
		this.tipoAtencion = tipoAtencion;
		this.tipoPaciente = tipoPaciente;
		this.tipoParentesco = tipoParentesco;
		this.modalidad = modalidad;
		this.idServicio = idServicio;
		this.idTurno = idTurno;
		this.idPaciente = idPaciente;
		this.idEmpresaAseguradora = idEmpresaAseguradora;
		this.compania = compania;
		this.sucursal = sucursal;
		this.idEstablecimiento = idEstablecimiento;
		this.idCaja = idCaja;
		this.centroCosto = centroCosto;
		this.clasificadorMovimiento = clasificadorMovimiento;
		this.unidadOrganizacional = unidadOrganizacional;
		this.proyecto = proyecto;
		this.conceptoGasto = conceptoGasto;
		this.idOpc = idOpc;
		this.tipoOpc = tipoOpc;
		this.serieOpc = serieOpc;
		this.numeroOpc = numeroOpc;
		this.idTransaccion = idTransaccion;
		this.tipoAlta = tipoAlta;
		this.fechaAlta = fechaAlta;
		this.idMedicoAutoriza = idMedicoAutoriza;
		this.observacionAlta = observacionAlta;
		this.estadoDocumento = estadoDocumento;
		this.estadoDocumentoAnterior = estadoDocumentoAnterior;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.indicadorTmh = indicadorTmh;
		this.idEmpleado = idEmpleado;
		this.idAlumno = idAlumno;
		this.fechaEmision = fechaEmision;
		this.secuencialTmh = secuencialTmh;
		this.idEmpresaEmpleadora = idEmpresaEmpleadora;
		this.idLineaOrdenRelacionada = idLineaOrdenRelacionada;
		this.idContrato = idContrato;
		this.idPoliza = idPoliza;
		this.idPlan = idPlan;
		this.idCobertura = idCobertura;
		this.copagoFijo = copagoFijo;
		this.copagoVariable = copagoVariable;
		this.idPersonaAntUnificacion = idPersonaAntUnificacion;
		this.fechaAnterior = fechaAnterior;
		this.copagoMoneda = copagoMoneda;
		this.codigoSiteds = codigoSiteds;
		this.titularNombre = titularNombre;
		this.coberturaMedico = coberturaMedico;
		this.situacionControlOa = situacionControlOa;
		this.idEmpresaAnteriorUnificacion = idEmpresaAnteriorUnificacion;
		this.descripcionempresaSeguros = descripcionempresaSeguros;
		this.tipoAltaMedica = tipoAltaMedica;
		this.idConsultaExternaPrincipal = idConsultaExternaPrincipal;
		this.idTopico = idTopico;
		this.indicadorOcultarOa = indicadorOcultarOa;
		this.indicadorAltaMedica = indicadorAltaMedica;
		this.coberturaMedicoOriginal = coberturaMedicoOriginal;
		this.tipoAltaMedicaOriginal = tipoAltaMedicaOriginal;
		this.observacionAltaOriginal = observacionAltaOriginal;
		this.indicadorAltaMedicaOriginal = indicadorAltaMedicaOriginal;
		this.idConsultaExternaPrincipalOriginal = idConsultaExternaPrincipalOriginal;
		this.indHospitalizado = indHospitalizado;
		this.indicadorEmergenciaRm = indicadorEmergenciaRm;
		this.bkestadodocumento20110517 = bkestadodocumento20110517;
		this.bkestadodocumentoanterior20110517 = bkestadodocumentoanterior20110517;
		this.listaExamenComplementario = listaExamenComplementario;
		this.listaProcedimiento = listaProcedimiento;
		this.usuarioAmpliacionOa = usuarioAmpliacionOa;
		this.usuarioAnteriorAmpliacionOa = usuarioAnteriorAmpliacionOa;
		this.indicadorAuditoria = indicadorAuditoria;
		this.indicadorAtencionWeb = indicadorAtencionWeb;
		this.indicadorRecalculoModalidad = indicadorRecalculoModalidad;
		this.tipoPacienteInicial = tipoPacienteInicial;
		this.idPacienteInicial = idPacienteInicial;
		this.unidadReplicacion = unidadReplicacion;
		this.prioridad = prioridad;
		this.contratoNum = contratoNum;
		this.ssAdOrdenAtencionPreexistencias = ssAdOrdenAtencionPreexistencias;
	}

	@Id

	@Column(name = "IdOrdenAtencion", unique = true, nullable = false)
	public Integer getIdOrdenAtencion() {
		return this.idOrdenAtencion;
	}

	public void setIdOrdenAtencion(Integer idOrdenAtencion) {
		this.idOrdenAtencion = idOrdenAtencion;
	}

	@Column(name = "IdPolizaPlan")
	public Integer getIdPolizaPlan() {
		return this.idPolizaPlan;
	}

	public void setIdPolizaPlan(Integer idPolizaPlan) {
		this.idPolizaPlan = idPolizaPlan;
	}

	@Column(name = "SecuencialPolizaPlan")
	public Integer getSecuencialPolizaPlan() {
		return this.secuencialPolizaPlan;
	}

	public void setSecuencialPolizaPlan(Integer secuencialPolizaPlan) {
		this.secuencialPolizaPlan = secuencialPolizaPlan;
	}

	@Column(name = "TipoOrdenAtencion")
	public Integer getTipoOrdenAtencion() {
		return this.tipoOrdenAtencion;
	}

	public void setTipoOrdenAtencion(Integer tipoOrdenAtencion) {
		this.tipoOrdenAtencion = tipoOrdenAtencion;
	}

	@Column(name = "CodigoOA", length = 15)
	public String getCodigoOa() {
		return this.codigoOa;
	}

	public void setCodigoOa(String codigoOa) {
		this.codigoOa = codigoOa;
	}

	@Column(name = "Especialidad")
	public Integer getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(Integer especialidad) {
		this.especialidad = especialidad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaPreparacion", length = 23)
	public Date getFechaPreparacion() {
		return this.fechaPreparacion;
	}

	public void setFechaPreparacion(Date fechaPreparacion) {
		this.fechaPreparacion = fechaPreparacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaInicio", length = 23)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaFinal", length = 23)
	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	@Column(name = "IdOrdenRelacionada")
	public Integer getIdOrdenRelacionada() {
		return this.idOrdenRelacionada;
	}

	public void setIdOrdenRelacionada(Integer idOrdenRelacionada) {
		this.idOrdenRelacionada = idOrdenRelacionada;
	}

	@Column(name = "TipoAtencion")
	public Integer getTipoAtencion() {
		return this.tipoAtencion;
	}

	public void setTipoAtencion(Integer tipoAtencion) {
		this.tipoAtencion = tipoAtencion;
	}

	@Column(name = "TipoPaciente")
	public Integer getTipoPaciente() {
		return this.tipoPaciente;
	}

	public void setTipoPaciente(Integer tipoPaciente) {
		this.tipoPaciente = tipoPaciente;
	}

	@Column(name = "TipoParentesco")
	public Integer getTipoParentesco() {
		return this.tipoParentesco;
	}

	public void setTipoParentesco(Integer tipoParentesco) {
		this.tipoParentesco = tipoParentesco;
	}

	@Column(name = "Modalidad")
	public Integer getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(Integer modalidad) {
		this.modalidad = modalidad;
	}

	@Column(name = "IdServicio")
	public Integer getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Integer idServicio) {
		this.idServicio = idServicio;
	}

	@Column(name = "IdTurno")
	public Integer getIdTurno() {
		return this.idTurno;
	}

	public void setIdTurno(Integer idTurno) {
		this.idTurno = idTurno;
	}

	@Column(name = "IdPaciente")
	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "IdEmpresaAseguradora")
	public Integer getIdEmpresaAseguradora() {
		return this.idEmpresaAseguradora;
	}

	public void setIdEmpresaAseguradora(Integer idEmpresaAseguradora) {
		this.idEmpresaAseguradora = idEmpresaAseguradora;
	}

	@Column(name = "Compania", length = 15)
	public String getCompania() {
		return this.compania;
	}

	public void setCompania(String compania) {
		this.compania = compania;
	}

	@Column(name = "Sucursal", length = 15)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "IdEstablecimiento")
	public Integer getIdEstablecimiento() {
		return this.idEstablecimiento;
	}

	public void setIdEstablecimiento(Integer idEstablecimiento) {
		this.idEstablecimiento = idEstablecimiento;
	}

	@Column(name = "IdCaja")
	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	@Column(name = "CentroCosto", length = 15)
	public String getCentroCosto() {
		return this.centroCosto;
	}

	public void setCentroCosto(String centroCosto) {
		this.centroCosto = centroCosto;
	}

	@Column(name = "ClasificadorMovimiento", length = 15)
	public String getClasificadorMovimiento() {
		return this.clasificadorMovimiento;
	}

	public void setClasificadorMovimiento(String clasificadorMovimiento) {
		this.clasificadorMovimiento = clasificadorMovimiento;
	}

	@Column(name = "UnidadOrganizacional", length = 15)
	public String getUnidadOrganizacional() {
		return this.unidadOrganizacional;
	}

	public void setUnidadOrganizacional(String unidadOrganizacional) {
		this.unidadOrganizacional = unidadOrganizacional;
	}

	@Column(name = "Proyecto", length = 15)
	public String getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(String proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "ConceptoGasto", length = 15)
	public String getConceptoGasto() {
		return this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}

	@Column(name = "IdOPC")
	public Integer getIdOpc() {
		return this.idOpc;
	}

	public void setIdOpc(Integer idOpc) {
		this.idOpc = idOpc;
	}

	@Column(name = "TipoOPC", length = 2)
	public String getTipoOpc() {
		return this.tipoOpc;
	}

	public void setTipoOpc(String tipoOpc) {
		this.tipoOpc = tipoOpc;
	}

	@Column(name = "SerieOPC", length = 3)
	public String getSerieOpc() {
		return this.serieOpc;
	}

	public void setSerieOpc(String serieOpc) {
		this.serieOpc = serieOpc;
	}

	@Column(name = "NumeroOPC")
	public Integer getNumeroOpc() {
		return this.numeroOpc;
	}

	public void setNumeroOpc(Integer numeroOpc) {
		this.numeroOpc = numeroOpc;
	}

	@Column(name = "IdTransaccion")
	public Integer getIdTransaccion() {
		return this.idTransaccion;
	}

	public void setIdTransaccion(Integer idTransaccion) {
		this.idTransaccion = idTransaccion;
	}

	@Column(name = "TipoAlta")
	public Integer getTipoAlta() {
		return this.tipoAlta;
	}

	public void setTipoAlta(Integer tipoAlta) {
		this.tipoAlta = tipoAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaAlta", length = 23)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "IdMedicoAutoriza")
	public Integer getIdMedicoAutoriza() {
		return this.idMedicoAutoriza;
	}

	public void setIdMedicoAutoriza(Integer idMedicoAutoriza) {
		this.idMedicoAutoriza = idMedicoAutoriza;
	}

	@Column(name = "ObservacionAlta", length = 250)
	public String getObservacionAlta() {
		return this.observacionAlta;
	}

	public void setObservacionAlta(String observacionAlta) {
		this.observacionAlta = observacionAlta;
	}

	@Column(name = "EstadoDocumento")
	public Integer getEstadoDocumento() {
		return this.estadoDocumento;
	}

	public void setEstadoDocumento(Integer estadoDocumento) {
		this.estadoDocumento = estadoDocumento;
	}

	@Column(name = "EstadoDocumentoAnterior")
	public Integer getEstadoDocumentoAnterior() {
		return this.estadoDocumentoAnterior;
	}

	public void setEstadoDocumentoAnterior(Integer estadoDocumentoAnterior) {
		this.estadoDocumentoAnterior = estadoDocumentoAnterior;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "IndicadorTMH")
	public Integer getIndicadorTmh() {
		return this.indicadorTmh;
	}

	public void setIndicadorTmh(Integer indicadorTmh) {
		this.indicadorTmh = indicadorTmh;
	}

	@Column(name = "IdEmpleado")
	public Integer getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(Integer idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "IdAlumno")
	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaEmision", length = 23)
	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@Column(name = "SecuencialTMH")
	public Integer getSecuencialTmh() {
		return this.secuencialTmh;
	}

	public void setSecuencialTmh(Integer secuencialTmh) {
		this.secuencialTmh = secuencialTmh;
	}

	@Column(name = "IdEmpresaEmpleadora")
	public Integer getIdEmpresaEmpleadora() {
		return this.idEmpresaEmpleadora;
	}

	public void setIdEmpresaEmpleadora(Integer idEmpresaEmpleadora) {
		this.idEmpresaEmpleadora = idEmpresaEmpleadora;
	}

	@Column(name = "IdLineaOrdenRelacionada")
	public Integer getIdLineaOrdenRelacionada() {
		return this.idLineaOrdenRelacionada;
	}

	public void setIdLineaOrdenRelacionada(Integer idLineaOrdenRelacionada) {
		this.idLineaOrdenRelacionada = idLineaOrdenRelacionada;
	}

	@Column(name = "IdContrato")
	public Integer getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(Integer idContrato) {
		this.idContrato = idContrato;
	}

	@Column(name = "IdPoliza")
	public Integer getIdPoliza() {
		return this.idPoliza;
	}

	public void setIdPoliza(Integer idPoliza) {
		this.idPoliza = idPoliza;
	}

	@Column(name = "IdPlan")
	public Integer getIdPlan() {
		return this.idPlan;
	}

	public void setIdPlan(Integer idPlan) {
		this.idPlan = idPlan;
	}

	@Column(name = "IdCobertura")
	public Integer getIdCobertura() {
		return this.idCobertura;
	}

	public void setIdCobertura(Integer idCobertura) {
		this.idCobertura = idCobertura;
	}

	@Column(name = "CopagoFijo", precision = 20, scale = 6)
	public BigDecimal getCopagoFijo() {
		return this.copagoFijo;
	}

	public void setCopagoFijo(BigDecimal copagoFijo) {
		this.copagoFijo = copagoFijo;
	}

	@Column(name = "CopagoVariable", precision = 20, scale = 6)
	public BigDecimal getCopagoVariable() {
		return this.copagoVariable;
	}

	public void setCopagoVariable(BigDecimal copagoVariable) {
		this.copagoVariable = copagoVariable;
	}

	@Column(name = "IdPersonaAntUnificacion")
	public Integer getIdPersonaAntUnificacion() {
		return this.idPersonaAntUnificacion;
	}

	public void setIdPersonaAntUnificacion(Integer idPersonaAntUnificacion) {
		this.idPersonaAntUnificacion = idPersonaAntUnificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaAnterior", length = 23)
	public Date getFechaAnterior() {
		return this.fechaAnterior;
	}

	public void setFechaAnterior(Date fechaAnterior) {
		this.fechaAnterior = fechaAnterior;
	}

	@Column(name = "CopagoMoneda", length = 2)
	public String getCopagoMoneda() {
		return this.copagoMoneda;
	}

	public void setCopagoMoneda(String copagoMoneda) {
		this.copagoMoneda = copagoMoneda;
	}

	@Column(name = "CodigoSiteds", length = 15)
	public String getCodigoSiteds() {
		return this.codigoSiteds;
	}

	public void setCodigoSiteds(String codigoSiteds) {
		this.codigoSiteds = codigoSiteds;
	}

	@Column(name = "TitularNombre", length = 150)
	public String getTitularNombre() {
		return this.titularNombre;
	}

	public void setTitularNombre(String titularNombre) {
		this.titularNombre = titularNombre;
	}

	@Column(name = "CoberturaMedico")
	public Integer getCoberturaMedico() {
		return this.coberturaMedico;
	}

	public void setCoberturaMedico(Integer coberturaMedico) {
		this.coberturaMedico = coberturaMedico;
	}

	@Column(name = "SituacionControlOA")
	public Integer getSituacionControlOa() {
		return this.situacionControlOa;
	}

	public void setSituacionControlOa(Integer situacionControlOa) {
		this.situacionControlOa = situacionControlOa;
	}

	@Column(name = "IdEmpresaAnteriorUnificacion")
	public Integer getIdEmpresaAnteriorUnificacion() {
		return this.idEmpresaAnteriorUnificacion;
	}

	public void setIdEmpresaAnteriorUnificacion(Integer idEmpresaAnteriorUnificacion) {
		this.idEmpresaAnteriorUnificacion = idEmpresaAnteriorUnificacion;
	}

	@Column(name = "descripcionempresa_seguros", length = 100)
	public String getDescripcionempresaSeguros() {
		return this.descripcionempresaSeguros;
	}

	public void setDescripcionempresaSeguros(String descripcionempresaSeguros) {
		this.descripcionempresaSeguros = descripcionempresaSeguros;
	}

	@Column(name = "TipoAltaMedica")
	public Integer getTipoAltaMedica() {
		return this.tipoAltaMedica;
	}

	public void setTipoAltaMedica(Integer tipoAltaMedica) {
		this.tipoAltaMedica = tipoAltaMedica;
	}

	@Column(name = "IdConsultaExternaPrincipal")
	public Integer getIdConsultaExternaPrincipal() {
		return this.idConsultaExternaPrincipal;
	}

	public void setIdConsultaExternaPrincipal(Integer idConsultaExternaPrincipal) {
		this.idConsultaExternaPrincipal = idConsultaExternaPrincipal;
	}

	@Column(name = "IdTopico")
	public Integer getIdTopico() {
		return this.idTopico;
	}

	public void setIdTopico(Integer idTopico) {
		this.idTopico = idTopico;
	}

	@Column(name = "IndicadorOcultarOA")
	public Integer getIndicadorOcultarOa() {
		return this.indicadorOcultarOa;
	}

	public void setIndicadorOcultarOa(Integer indicadorOcultarOa) {
		this.indicadorOcultarOa = indicadorOcultarOa;
	}

	@Column(name = "IndicadorAltaMedica")
	public Integer getIndicadorAltaMedica() {
		return this.indicadorAltaMedica;
	}

	public void setIndicadorAltaMedica(Integer indicadorAltaMedica) {
		this.indicadorAltaMedica = indicadorAltaMedica;
	}

	@Column(name = "CoberturaMedicoOriginal")
	public Integer getCoberturaMedicoOriginal() {
		return this.coberturaMedicoOriginal;
	}

	public void setCoberturaMedicoOriginal(Integer coberturaMedicoOriginal) {
		this.coberturaMedicoOriginal = coberturaMedicoOriginal;
	}

	@Column(name = "TipoAltaMedicaOriginal")
	public Integer getTipoAltaMedicaOriginal() {
		return this.tipoAltaMedicaOriginal;
	}

	public void setTipoAltaMedicaOriginal(Integer tipoAltaMedicaOriginal) {
		this.tipoAltaMedicaOriginal = tipoAltaMedicaOriginal;
	}

	@Column(name = "ObservacionAltaOriginal", length = 250)
	public String getObservacionAltaOriginal() {
		return this.observacionAltaOriginal;
	}

	public void setObservacionAltaOriginal(String observacionAltaOriginal) {
		this.observacionAltaOriginal = observacionAltaOriginal;
	}

	@Column(name = "IndicadorAltaMedicaOriginal")
	public Integer getIndicadorAltaMedicaOriginal() {
		return this.indicadorAltaMedicaOriginal;
	}

	public void setIndicadorAltaMedicaOriginal(Integer indicadorAltaMedicaOriginal) {
		this.indicadorAltaMedicaOriginal = indicadorAltaMedicaOriginal;
	}

	@Column(name = "IdConsultaExternaPrincipalOriginal")
	public Integer getIdConsultaExternaPrincipalOriginal() {
		return this.idConsultaExternaPrincipalOriginal;
	}

	public void setIdConsultaExternaPrincipalOriginal(Integer idConsultaExternaPrincipalOriginal) {
		this.idConsultaExternaPrincipalOriginal = idConsultaExternaPrincipalOriginal;
	}

	@Column(name = "IndHospitalizado")
	public Integer getIndHospitalizado() {
		return this.indHospitalizado;
	}

	public void setIndHospitalizado(Integer indHospitalizado) {
		this.indHospitalizado = indHospitalizado;
	}

	@Column(name = "IndicadorEmergenciaRM")
	public Integer getIndicadorEmergenciaRm() {
		return this.indicadorEmergenciaRm;
	}

	public void setIndicadorEmergenciaRm(Integer indicadorEmergenciaRm) {
		this.indicadorEmergenciaRm = indicadorEmergenciaRm;
	}

	@Column(name = "bkestadodocumento_2011_05_17")
	public Integer getBkestadodocumento20110517() {
		return this.bkestadodocumento20110517;
	}

	public void setBkestadodocumento20110517(Integer bkestadodocumento20110517) {
		this.bkestadodocumento20110517 = bkestadodocumento20110517;
	}

	@Column(name = "bkestadodocumentoanterior_2011_05_17")
	public Integer getBkestadodocumentoanterior20110517() {
		return this.bkestadodocumentoanterior20110517;
	}

	public void setBkestadodocumentoanterior20110517(Integer bkestadodocumentoanterior20110517) {
		this.bkestadodocumentoanterior20110517 = bkestadodocumentoanterior20110517;
	}

	@Column(name = "ListaExamenComplementario", length = 250)
	public String getListaExamenComplementario() {
		return this.listaExamenComplementario;
	}

	public void setListaExamenComplementario(String listaExamenComplementario) {
		this.listaExamenComplementario = listaExamenComplementario;
	}

	@Column(name = "ListaProcedimiento", length = 250)
	public String getListaProcedimiento() {
		return this.listaProcedimiento;
	}

	public void setListaProcedimiento(String listaProcedimiento) {
		this.listaProcedimiento = listaProcedimiento;
	}

	@Column(name = "UsuarioAmpliacionOA", length = 25)
	public String getUsuarioAmpliacionOa() {
		return this.usuarioAmpliacionOa;
	}

	public void setUsuarioAmpliacionOa(String usuarioAmpliacionOa) {
		this.usuarioAmpliacionOa = usuarioAmpliacionOa;
	}

	@Column(name = "UsuarioAnteriorAmpliacionOA", length = 25)
	public String getUsuarioAnteriorAmpliacionOa() {
		return this.usuarioAnteriorAmpliacionOa;
	}

	public void setUsuarioAnteriorAmpliacionOa(String usuarioAnteriorAmpliacionOa) {
		this.usuarioAnteriorAmpliacionOa = usuarioAnteriorAmpliacionOa;
	}

	@Column(name = "IndicadorAuditoria")
	public Integer getIndicadorAuditoria() {
		return this.indicadorAuditoria;
	}

	public void setIndicadorAuditoria(Integer indicadorAuditoria) {
		this.indicadorAuditoria = indicadorAuditoria;
	}

	@Column(name = "IndicadorAtencionWeb")
	public Integer getIndicadorAtencionWeb() {
		return this.indicadorAtencionWeb;
	}

	public void setIndicadorAtencionWeb(Integer indicadorAtencionWeb) {
		this.indicadorAtencionWeb = indicadorAtencionWeb;
	}

	@Column(name = "IndicadorRecalculoModalidad")
	public Integer getIndicadorRecalculoModalidad() {
		return this.indicadorRecalculoModalidad;
	}

	public void setIndicadorRecalculoModalidad(Integer indicadorRecalculoModalidad) {
		this.indicadorRecalculoModalidad = indicadorRecalculoModalidad;
	}

	@Column(name = "TipoPacienteInicial")
	public Integer getTipoPacienteInicial() {
		return this.tipoPacienteInicial;
	}

	public void setTipoPacienteInicial(Integer tipoPacienteInicial) {
		this.tipoPacienteInicial = tipoPacienteInicial;
	}

	@Column(name = "idPacienteInicial")
	public Integer getIdPacienteInicial() {
		return this.idPacienteInicial;
	}

	public void setIdPacienteInicial(Integer idPacienteInicial) {
		this.idPacienteInicial = idPacienteInicial;
	}

	@Column(name = "UnidadReplicacion", length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "Prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "ContratoNum", length = 15)
	public String getContratoNum() {
		return this.contratoNum;
	}

	public void setContratoNum(String contratoNum) {
		this.contratoNum = contratoNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ssAdOrdenAtencion")
	public Set<SsAdOrdenAtencionPreexistencia> getSsAdOrdenAtencionPreexistencias() {
		return this.ssAdOrdenAtencionPreexistencias;
	}

	public void setSsAdOrdenAtencionPreexistencias(
			Set<SsAdOrdenAtencionPreexistencia> ssAdOrdenAtencionPreexistencias) {
		this.ssAdOrdenAtencionPreexistencias = ssAdOrdenAtencionPreexistencias;
	}

}
