package pe.royalsystems.springerp.model.domain;
// Generated Aug 27, 2015 10:28:46 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SsGeProcedimientoMedicoDos generated by hbm2java
 */
@Entity
@Table(name = "SS_GE_ProcedimientoMedicoDos")
public class SsGeProcedimientoMedicoDos extends Entidad implements java.io.Serializable {

	private int idProcedimientoDos;
	private String codigoProcedimientoDos;
	private String codigoPadre;
	private String nombre;
	private String descripcion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Integer idProcedimientoDosPadre;
	private Integer orden;
	private String cadenaRecursividad;
	private Integer nivel;
	private String diagnosticoSiteds;
	private Integer indicadorPermitido;
	private Integer tipofolder;
	private String nombreTabla;
	private String accion;

	public SsGeProcedimientoMedicoDos() {
	}

	public SsGeProcedimientoMedicoDos(int idProcedimientoDos) {
		this.idProcedimientoDos = idProcedimientoDos;
	}

	public SsGeProcedimientoMedicoDos(int idProcedimientoDos, String codigoProcedimientoDos, String codigoPadre,
			String nombre, String descripcion, Integer estado, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion, Integer idProcedimientoDosPadre, Integer orden,
			String cadenaRecursividad, Integer nivel, String diagnosticoSiteds, Integer indicadorPermitido,
			Integer tipofolder, String nombreTabla, String accion) {
		this.idProcedimientoDos = idProcedimientoDos;
		this.codigoProcedimientoDos = codigoProcedimientoDos;
		this.codigoPadre = codigoPadre;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.idProcedimientoDosPadre = idProcedimientoDosPadre;
		this.orden = orden;
		this.cadenaRecursividad = cadenaRecursividad;
		this.nivel = nivel;
		this.diagnosticoSiteds = diagnosticoSiteds;
		this.indicadorPermitido = indicadorPermitido;
		this.tipofolder = tipofolder;
		this.nombreTabla = nombreTabla;
		this.accion = accion;
	}

	@Id

	@Column(name = "IdProcedimientoDos", unique = true, nullable = false)
	public int getIdProcedimientoDos() {
		return this.idProcedimientoDos;
	}

	public void setIdProcedimientoDos(int idProcedimientoDos) {
		this.idProcedimientoDos = idProcedimientoDos;
	}

	@Column(name = "CodigoProcedimientoDos", length = 15)
	public String getCodigoProcedimientoDos() {
		return this.codigoProcedimientoDos;
	}

	public void setCodigoProcedimientoDos(String codigoProcedimientoDos) {
		this.codigoProcedimientoDos = codigoProcedimientoDos;
	}

	@Column(name = "CodigoPadre", length = 15)
	public String getCodigoPadre() {
		return this.codigoPadre;
	}

	public void setCodigoPadre(String codigoPadre) {
		this.codigoPadre = codigoPadre;
	}

	@Column(name = "Nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "IdProcedimientoDosPadre")
	public Integer getIdProcedimientoDosPadre() {
		return this.idProcedimientoDosPadre;
	}

	public void setIdProcedimientoDosPadre(Integer idProcedimientoDosPadre) {
		this.idProcedimientoDosPadre = idProcedimientoDosPadre;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "CadenaRecursividad", length = 150)
	public String getCadenaRecursividad() {
		return this.cadenaRecursividad;
	}

	public void setCadenaRecursividad(String cadenaRecursividad) {
		this.cadenaRecursividad = cadenaRecursividad;
	}

	@Column(name = "Nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "DiagnosticoSiteds", length = 15)
	public String getDiagnosticoSiteds() {
		return this.diagnosticoSiteds;
	}

	public void setDiagnosticoSiteds(String diagnosticoSiteds) {
		this.diagnosticoSiteds = diagnosticoSiteds;
	}

	@Column(name = "IndicadorPermitido")
	public Integer getIndicadorPermitido() {
		return this.indicadorPermitido;
	}

	public void setIndicadorPermitido(Integer indicadorPermitido) {
		this.indicadorPermitido = indicadorPermitido;
	}

	@Column(name = "tipofolder")
	public Integer getTipofolder() {
		return this.tipofolder;
	}

	public void setTipofolder(Integer tipofolder) {
		this.tipofolder = tipofolder;
	}

	@Column(name = "NombreTabla", length = 15)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
