package pe.royalsystems.springerp.model.domain;
// Generated Aug 27, 2015 10:27:59 AM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.util.Date;

/**
 * SsGeProcedimientoMedico generated by hbm2java
 */
@Entity
@Table(name = "SS_GE_ProcedimientoMedico")
public class SsGeProcedimientoMedico extends Entidad implements java.io.Serializable {

	private Integer idProcedimiento;
	private String codigoProcedimiento;
	private String codigoPadre;
	private String nombre;
	private String descripcion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Integer idProcedimientoPadre;
	private Integer orden;
	private String cadenaRecursividad;
	private Integer nivel;
	private String diagnosticoSiteds;
	private Integer indicadorPermitido;
	private Integer tipofolder;
	private String nombreTabla;
	private String accion;

	public SsGeProcedimientoMedico() {
	}

	public SsGeProcedimientoMedico(Integer idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}

	public SsGeProcedimientoMedico(Integer idProcedimiento, String codigoProcedimiento, String codigoPadre, String nombre,
			String descripcion, Integer estado, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion,
			Date fechaModificacion, Integer idProcedimientoPadre, Integer orden, String cadenaRecursividad,
			Integer nivel, String diagnosticoSiteds, Integer indicadorPermitido, Integer tipofolder, String nombreTabla,
			String accion) {
		this.idProcedimiento = idProcedimiento;
		this.codigoProcedimiento = codigoProcedimiento;
		this.codigoPadre = codigoPadre;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.idProcedimientoPadre = idProcedimientoPadre;
		this.orden = orden;
		this.cadenaRecursividad = cadenaRecursividad;
		this.nivel = nivel;
		this.diagnosticoSiteds = diagnosticoSiteds;
		this.indicadorPermitido = indicadorPermitido;
		this.tipofolder = tipofolder;
		this.nombreTabla = nombreTabla;
		this.accion = accion;
	}

	@Id

	@Column(name = "IdProcedimiento", unique = true )
	public Integer getIdProcedimiento() {
		return this.idProcedimiento;
	}

	public void setIdProcedimiento(int idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}

	@Column(name = "CodigoProcedimiento", length = 15)
	public String getCodigoProcedimiento() {
		return this.codigoProcedimiento;
	}

	public void setCodigoProcedimiento(String codigoProcedimiento) {
		this.codigoProcedimiento = codigoProcedimiento;
	}

	@Column(name = "CodigoPadre", length = 15)
	public String getCodigoPadre() {
		return this.codigoPadre;
	}

	public void setCodigoPadre(String codigoPadre) {
		this.codigoPadre = codigoPadre;
	}

	@Column(name = "Nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "IdProcedimientoPadre")
	public Integer getIdProcedimientoPadre() {
		return this.idProcedimientoPadre;
	}

	public void setIdProcedimientoPadre(Integer idProcedimientoPadre) {
		this.idProcedimientoPadre = idProcedimientoPadre;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "CadenaRecursividad", length = 150)
	public String getCadenaRecursividad() {
		return this.cadenaRecursividad;
	}

	public void setCadenaRecursividad(String cadenaRecursividad) {
		this.cadenaRecursividad = cadenaRecursividad;
	}

	@Column(name = "Nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "DiagnosticoSiteds", length = 15)
	public String getDiagnosticoSiteds() {
		return this.diagnosticoSiteds;
	}

	public void setDiagnosticoSiteds(String diagnosticoSiteds) {
		this.diagnosticoSiteds = diagnosticoSiteds;
	}

	@Column(name = "IndicadorPermitido")
	public Integer getIndicadorPermitido() {
		return this.indicadorPermitido;
	}

	public void setIndicadorPermitido(Integer indicadorPermitido) {
		this.indicadorPermitido = indicadorPermitido;
	}

	@Column(name = "tipofolder")
	public Integer getTipofolder() {
		return this.tipofolder;
	}

	public void setTipofolder(Integer tipofolder) {
		this.tipofolder = tipofolder;
	}

	@Column(name = "NombreTabla", length = 15)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
