package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 5, 2015 11:10:50 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SsHcAnamnesisAf generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_Anamnesis_AF")
public class SsHcAnamnesisAf extends Entidad implements java.io.Serializable {

	private SsHcAnamnesisAfId id;
	private String version;
	private Integer idTipoParentesco;
	private Integer edad;
	private Integer idVivo;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;

	public SsHcAnamnesisAf() {
	}

	public SsHcAnamnesisAf(SsHcAnamnesisAfId id) {
		this.id = id;
	}

	public SsHcAnamnesisAf(SsHcAnamnesisAfId id, Integer idTipoParentesco, Integer edad, Integer idVivo, Integer estado,
			String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion,
			String accion) {
		this.id = id;
		this.idTipoParentesco = idTipoParentesco;
		this.edad = edad;
		this.idVivo = idVivo;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unidadReplicacion", column = @Column(name = "UnidadReplicacion", nullable = false, length = 4) ),
			@AttributeOverride(name = "idEpisodioAtencion", column = @Column(name = "IdEpisodioAtencion", nullable = false) ),
			@AttributeOverride(name = "idPaciente", column = @Column(name = "IdPaciente", nullable = false) ),
			@AttributeOverride(name = "episodioClinico", column = @Column(name = "EpisodioClinico", nullable = false) ) })
	public SsHcAnamnesisAfId getId() {
		return this.id;
	}

	public void setId(SsHcAnamnesisAfId id) {
		this.id = id;
	}

	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "IdTipoParentesco")
	public Integer getIdTipoParentesco() {
		return this.idTipoParentesco;
	}

	public void setIdTipoParentesco(Integer idTipoParentesco) {
		this.idTipoParentesco = idTipoParentesco;
	}

	@Column(name = "Edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "IdVivo")
	public Integer getIdVivo() {
		return this.idVivo;
	}

	public void setIdVivo(Integer idVivo) {
		this.idVivo = idVivo;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
