package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 23, 2015 5:19:40 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SsHcMedicamentoId generated by hbm2java
 */
@Embeddable
public class SsHcMedicamentoId implements java.io.Serializable {

	private String unidadReplicacion;
	private Long idEpisodioAtencion;
	private Integer idPaciente;
	private Integer episodioClinico;
	private Integer secuencia;

	public SsHcMedicamentoId() {
	}

	public SsHcMedicamentoId(String unidadReplicacion, Long idEpisodioAtencion, Integer idPaciente, Integer episodioClinico,
			Integer secuencia) {
		this.unidadReplicacion = unidadReplicacion;
		this.idEpisodioAtencion = idEpisodioAtencion;
		this.idPaciente = idPaciente;
		this.episodioClinico = episodioClinico;
		this.secuencia = secuencia;
	}

	@Column(name = "UnidadReplicacion", nullable = false, length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "IdEpisodioAtencion", nullable = false)
	public Long getIdEpisodioAtencion() {
		return this.idEpisodioAtencion;
	}

	public void setIdEpisodioAtencion(Long idEpisodioAtencion) {
		this.idEpisodioAtencion = idEpisodioAtencion;
	}

	@Column(name = "IdPaciente", nullable = false)
	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "EpisodioClinico", nullable = false)
	public Integer getEpisodioClinico() {
		return this.episodioClinico;
	}

	public void setEpisodioClinico(Integer episodioClinico) {
		this.episodioClinico = episodioClinico;
	}

	@Column(name = "Secuencia", nullable = false)
	public Integer getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(Integer secuencia) {
		this.secuencia = secuencia;
	}

}
