package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 23, 2015 5:19:40 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SsHcMedicamento generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_Medicamento")
public class SsHcMedicamento extends Entidad implements java.io.Serializable {

	private SsHcMedicamentoId id;
	private String version;
	private Integer tipoMedicamento;
	private Integer idUnidadMedida;
	private String linea;
	private String familia;
	private String subFamilia;
	private Character tipoComponente;
	private String codigoComponente;
	private Integer idVia;
	private BigDecimal dosis;
	private BigDecimal diasTratamiento;
	private BigDecimal frecuencia;
	private BigDecimal cantidad;
	private Integer indicadorEps;
	private Integer tipoReceta;
	private Integer forma;
	private String comentario;
	private Integer indicadorAuditoria;
	private String usuarioAuditoria;
	private Integer tipoComida;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;
	private List<SsHcIndicaciones> ssHcIndicacioneses = new ArrayList<SsHcIndicaciones>();

	public SsHcMedicamento() {
		id = new SsHcMedicamentoId();
	}

	public SsHcMedicamento(SsHcMedicamentoId id) {
		this.id = id;
	}

	public SsHcMedicamento(SsHcMedicamentoId id, Integer tipoMedicamento, Integer idUnidadMedida, String linea,
			String familia, String subFamilia, Character tipoComponente, String codigoComponente, Integer idVia,
			BigDecimal dosis, BigDecimal diasTratamiento, BigDecimal frecuencia, BigDecimal cantidad,
			Integer indicadorEps, Integer tipoReceta, Integer forma, String comentario, Integer indicadorAuditoria,
			String usuarioAuditoria, Integer tipoComida, Integer estado, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion, String accion,
			List<SsHcIndicaciones> ssHcIndicacioneses) {
		this.id = id;
		this.tipoMedicamento = tipoMedicamento;
		this.idUnidadMedida = idUnidadMedida;
		this.linea = linea;
		this.familia = familia;
		this.subFamilia = subFamilia;
		this.tipoComponente = tipoComponente;
		this.codigoComponente = codigoComponente;
		this.idVia = idVia;
		this.dosis = dosis;
		this.diasTratamiento = diasTratamiento;
		this.frecuencia = frecuencia;
		this.cantidad = cantidad;
		this.indicadorEps = indicadorEps;
		this.tipoReceta = tipoReceta;
		this.forma = forma;
		this.comentario = comentario;
		this.indicadorAuditoria = indicadorAuditoria;
		this.usuarioAuditoria = usuarioAuditoria;
		this.tipoComida = tipoComida;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
		this.ssHcIndicacioneses = ssHcIndicacioneses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unidadReplicacion", column = @Column(name = "UnidadReplicacion", nullable = false, length = 4) ),
			@AttributeOverride(name = "idEpisodioAtencion", column = @Column(name = "IdEpisodioAtencion", nullable = false) ),
			@AttributeOverride(name = "idPaciente", column = @Column(name = "IdPaciente", nullable = false) ),
			@AttributeOverride(name = "episodioClinico", column = @Column(name = "EpisodioClinico", nullable = false) ),
			@AttributeOverride(name = "secuencia", column = @Column(name = "Secuencia", nullable = false) ) })
	public SsHcMedicamentoId getId() {
		return this.id;
	}

	public void setId(SsHcMedicamentoId id) {
		this.id = id;
	}

	
	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "TipoMedicamento")
	public Integer getTipoMedicamento() {
		return this.tipoMedicamento;
	}

	public void setTipoMedicamento(Integer tipoMedicamento) {
		this.tipoMedicamento = tipoMedicamento;
	}

	@Column(name = "IdUnidadMedida")
	public Integer getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(Integer idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	@Column(name = "Linea", length = 6)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "Familia", length = 6)
	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	@Column(name = "SubFamilia", length = 6)
	public String getSubFamilia() {
		return this.subFamilia;
	}

	public void setSubFamilia(String subFamilia) {
		this.subFamilia = subFamilia;
	}

	@Column(name = "TipoComponente", length = 1)
	public Character getTipoComponente() {
		return this.tipoComponente;
	}

	public void setTipoComponente(Character tipoComponente) {
		this.tipoComponente = tipoComponente;
	}

	@Column(name = "CodigoComponente", length = 25)
	public String getCodigoComponente() {
		return this.codigoComponente;
	}

	public void setCodigoComponente(String codigoComponente) {
		this.codigoComponente = codigoComponente;
	}

	@Column(name = "IdVia")
	public Integer getIdVia() {
		return this.idVia;
	}

	public void setIdVia(Integer idVia) {
		this.idVia = idVia;
	}

	@Column(name = "Dosis", precision = 9)
	public BigDecimal getDosis() {
		return this.dosis;
	}

	public void setDosis(BigDecimal dosis) {
		this.dosis = dosis;
	}

	@Column(name = "DiasTratamiento", precision = 9)
	public BigDecimal getDiasTratamiento() {
		return this.diasTratamiento;
	}

	public void setDiasTratamiento(BigDecimal diasTratamiento) {
		this.diasTratamiento = diasTratamiento;
	}

	@Column(name = "Frecuencia", precision = 9)
	public BigDecimal getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(BigDecimal frecuencia) {
		this.frecuencia = frecuencia;
	}

	@Column(name = "Cantidad", precision = 20, scale = 6)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "IndicadorEPS")
	public Integer getIndicadorEps() {
		return this.indicadorEps;
	}

	public void setIndicadorEps(Integer indicadorEps) {
		this.indicadorEps = indicadorEps;
	}

	@Column(name = "TipoReceta")
	public Integer getTipoReceta() {
		return this.tipoReceta;
	}

	public void setTipoReceta(Integer tipoReceta) {
		this.tipoReceta = tipoReceta;
	}

	@Column(name = "Forma")
	public Integer getForma() {
		return this.forma;
	}

	public void setForma(Integer forma) {
		this.forma = forma;
	}

	@Column(name = "Comentario", length = 250)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Column(name = "IndicadorAuditoria")
	public Integer getIndicadorAuditoria() {
		return this.indicadorAuditoria;
	}

	public void setIndicadorAuditoria(Integer indicadorAuditoria) {
		this.indicadorAuditoria = indicadorAuditoria;
	}

	@Column(name = "UsuarioAuditoria", length = 25)
	public String getUsuarioAuditoria() {
		return this.usuarioAuditoria;
	}

	public void setUsuarioAuditoria(String usuarioAuditoria) {
		this.usuarioAuditoria = usuarioAuditoria;
	}

	@Column(name = "TipoComida")
	public Integer getTipoComida() {
		return this.tipoComida;
	}

	public void setTipoComida(Integer tipoComida) {
		this.tipoComida = tipoComida;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ssHcMedicamento")
	public List<SsHcIndicaciones> getSsHcIndicacioneses() {
		return this.ssHcIndicacioneses;
	}

	public void setSsHcIndicacioneses(List<SsHcIndicaciones> ssHcIndicacioneses) {
		this.ssHcIndicacioneses = ssHcIndicacioneses;
	}

}
