package pe.royalsystems.springerp.model.domain;

//default package
//Generated Sep 10, 2015 3:55:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
* SsHcProcedimiento generated by hbm2java
*/
@Entity
@Table(name = "SS_HC_Procedimiento")
public class SsHcProcedimiento extends Entidad implements java.io.Serializable {

	private int idProcedimiento;
	private String version;
	private Integer idProcedimientoPadre;
	private String descripcion;
	private String descripcionExtranjera;
	private Integer nivel;
	private Character ultimoNivelFlag;
	private String cadenaRecursiva;
	private Integer orden;
	private String icono;
	private String nombreInterfaz;
	private String codigoProcedimiento;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private Integer estado;

	public SsHcProcedimiento() {
	}

	public SsHcProcedimiento(int idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}

	public SsHcProcedimiento(int idProcedimiento, Integer idProcedimientoPadre, String descripcion,
			String descripcionExtranjera, Integer nivel, Character ultimoNivelFlag, String cadenaRecursiva,
			Integer orden, String icono, String nombreInterfaz, String codigoProcedimiento, String usuarioModificacion,
			Date fechaModificacion, String accion, String usuarioCreacion, Date fechaCreacion, Integer estado) {
		this.idProcedimiento = idProcedimiento;
		this.idProcedimientoPadre = idProcedimientoPadre;
		this.descripcion = descripcion;
		this.descripcionExtranjera = descripcionExtranjera;
		this.nivel = nivel;
		this.ultimoNivelFlag = ultimoNivelFlag;
		this.cadenaRecursiva = cadenaRecursiva;
		this.orden = orden;
		this.icono = icono;
		this.nombreInterfaz = nombreInterfaz;
		this.codigoProcedimiento = codigoProcedimiento;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
	}

	@Id

	@Column(name = "IdProcedimiento", unique = true, nullable = false)
	public int getIdProcedimiento() {
		return this.idProcedimiento;
	}

	public void setIdProcedimiento(int idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}


	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "IdProcedimientoPadre")
	public Integer getIdProcedimientoPadre() {
		return this.idProcedimientoPadre;
	}

	public void setIdProcedimientoPadre(Integer idProcedimientoPadre) {
		this.idProcedimientoPadre = idProcedimientoPadre;
	}

	@Column(name = "Descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DescripcionExtranjera", length = 200)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "Nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "UltimoNivelFlag", length = 1)
	public Character getUltimoNivelFlag() {
		return this.ultimoNivelFlag;
	}

	public void setUltimoNivelFlag(Character ultimoNivelFlag) {
		this.ultimoNivelFlag = ultimoNivelFlag;
	}

	@Column(name = "CadenaRecursiva", length = 150)
	public String getCadenaRecursiva() {
		return this.cadenaRecursiva;
	}

	public void setCadenaRecursiva(String cadenaRecursiva) {
		this.cadenaRecursiva = cadenaRecursiva;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "Icono", length = 100)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@Column(name = "NombreInterfaz", length = 100)
	public String getNombreInterfaz() {
		return this.nombreInterfaz;
	}

	public void setNombreInterfaz(String nombreInterfaz) {
		this.nombreInterfaz = nombreInterfaz;
	}

	@Column(name = "CodigoProcedimiento", length = 15)
	public String getCodigoProcedimiento() {
		return this.codigoProcedimiento;
	}

	public void setCodigoProcedimiento(String codigoProcedimiento) {
		this.codigoProcedimiento = codigoProcedimiento;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

}
