package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 11, 2015 6:03:59 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SsHcAnamnesisAp generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_Anamnesis_AP")
public class SsHcAnamnesisAp extends Entidad implements java.io.Serializable {

	private SsHcAnamnesisApId id;
	private Short idTipoEmbarazo;
	private String patologiaGestacion;
	private Short idControlPrenatal;
	private Short cpnumeroControles;
	private Short cpnumeroEmbarazos;
	private String lugarControl;
	private Short idTipoParto;
	private String complicacionesParto;
	private Short idLugarParto;
	private Short idPartoAtendidoPor;
	private String antecentesPatologicos;
	private Short semanasGestacionNacer;
	private Integer pesoAlNacerGr;
	private BigDecimal tallaAlNacerCm;
	private BigDecimal perimetroCefalicoCm;
	private String patologiasPernatales;
	private Short diasHospitalizacion;
	private Short idTipoLecheHasta6meses;
	private String antecLactancia;
	private Short edadInicioAblactanciaMeses;
	private String desarrolloSicomotriz;
	private Date fechaUltimaRegla;
	private Date fechaUltimoPeriodo;
	private String metodosAnticonceptivos;
	private String menarquia;
	private String menopausia;
	private String caracteristicasMenstruaciones;
	private String informacionEmbarazos;
	private String transfusiones;
	private Date deinmunizFechaAproximada;
	private Integer deinmunizEdadAproximada;
	private String alcohol;
	private String tabaco;
	private String drogas;
	private String actividadFisica;
	private String consumoVerduras;
	private String consumoFrutas;
	private String medicamentos;
	private String alimentos;
	private String sustanciasEnElAmbiente;
	private String sustanciasContactoConPiel;
	private String contactoPersonaEnferma;
	private String crianzaAnimalesDomesticos;
	private String aguaPotable;
	private String disposicionExcretas;
	private String reaccionAdversaMedicamentos;
	private String saludBucal;
	private String vigilanciaDeCrecimiento;
	private String vigilanciaDelDesarrollo;
	private Short idValoracionFuncional1;
	private Short idValoracionFuncional2;
	private Short idValoracionFuncional3;
	private Short idValoracionFuncional4;
	private Short idValoracionFuncional5;
	private Short idValoracionFuncional6;
	private Short diagnosticoFuncional;
	private Short idEstadoCognitivo1;
	private Short idEstadoCognitivo2;
	private Short idEstadoCognitivo3;
	private Short idEstadoCognitivo4;
	private Short idEstadoCognitivo5;
	private Short idEstadoCognitivo6;
	private Short idEstadoCognitivo7;
	private Short idEstadoCognitivo8;
	private Short idEstadoCognitivo9;
	private Short idEstadoCognitivo10;
	private Short valoracionCognitiva;
	private Short idEstadoAfectivo1;
	private Short idEstadoAfectivo2;
	private Short idEstadoAfectivo3;
	private Short idEstadoAfectivo4;
	private Short conManifestacionesDepresivas;
	private Short valoracionSocioFamiliar1;
	private Short valoracionSocioFamiliar2;
	private Short valoracionSocioFamiliar3;
	private Short valoracionSocioFamiliar4;
	private Short valoracionSocioFamiliar5;
	private Short valoracionSocioFamiliar;
	private Short idCategoriaAdutoMayor;
	private Short estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;

	public SsHcAnamnesisAp() {
	}

	public SsHcAnamnesisAp(SsHcAnamnesisApId id) {
		this.id = id;
	}

	public SsHcAnamnesisAp(SsHcAnamnesisApId id, Short idTipoEmbarazo, String patologiaGestacion,
			Short idControlPrenatal, Short cpnumeroControles, Short cpnumeroEmbarazos, String lugarControl,
			Short idTipoParto, String complicacionesParto, Short idLugarParto, Short idPartoAtendidoPor,
			String antecentesPatologicos, Short semanasGestacionNacer, Integer pesoAlNacerGr, BigDecimal tallaAlNacerCm,
			BigDecimal perimetroCefalicoCm, String patologiasPernatales, Short diasHospitalizacion,
			Short idTipoLecheHasta6meses, String antecLactancia, Short edadInicioAblactanciaMeses,
			String desarrolloSicomotriz, Date fechaUltimaRegla, Date fechaUltimoPeriodo, String metodosAnticonceptivos,
			String menarquia, String menopausia, String caracteristicasMenstruaciones, String informacionEmbarazos,
			String transfusiones, Date deinmunizFechaAproximada, Integer deinmunizEdadAproximada, String alcohol,
			String tabaco, String drogas, String actividadFisica, String consumoVerduras, String consumoFrutas,
			String medicamentos, String alimentos, String sustanciasEnElAmbiente, String sustanciasContactoConPiel,
			String contactoPersonaEnferma, String crianzaAnimalesDomesticos, String aguaPotable,
			String disposicionExcretas, String reaccionAdversaMedicamentos, String saludBucal,
			String vigilanciaDeCrecimiento, String vigilanciaDelDesarrollo, Short idValoracionFuncional1,
			Short idValoracionFuncional2, Short idValoracionFuncional3, Short idValoracionFuncional4,
			Short idValoracionFuncional5, Short idValoracionFuncional6, Short diagnosticoFuncional,
			Short idEstadoCognitivo1, Short idEstadoCognitivo2, Short idEstadoCognitivo3, Short idEstadoCognitivo4,
			Short idEstadoCognitivo5, Short idEstadoCognitivo6, Short idEstadoCognitivo7, Short idEstadoCognitivo8,
			Short idEstadoCognitivo9, Short idEstadoCognitivo10, Short valoracionCognitiva, Short idEstadoAfectivo1,
			Short idEstadoAfectivo2, Short idEstadoAfectivo3, Short idEstadoAfectivo4,
			Short conManifestacionesDepresivas, Short valoracionSocioFamiliar1, Short valoracionSocioFamiliar2,
			Short valoracionSocioFamiliar3, Short valoracionSocioFamiliar4, Short valoracionSocioFamiliar5,
			Short valoracionSocioFamiliar, Short idCategoriaAdutoMayor, Short estado, String usuarioCreacion,
			Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, String accion) {
		this.id = id;
		this.idTipoEmbarazo = idTipoEmbarazo;
		this.patologiaGestacion = patologiaGestacion;
		this.idControlPrenatal = idControlPrenatal;
		this.cpnumeroControles = cpnumeroControles;
		this.cpnumeroEmbarazos = cpnumeroEmbarazos;
		this.lugarControl = lugarControl;
		this.idTipoParto = idTipoParto;
		this.complicacionesParto = complicacionesParto;
		this.idLugarParto = idLugarParto;
		this.idPartoAtendidoPor = idPartoAtendidoPor;
		this.antecentesPatologicos = antecentesPatologicos;
		this.semanasGestacionNacer = semanasGestacionNacer;
		this.pesoAlNacerGr = pesoAlNacerGr;
		this.tallaAlNacerCm = tallaAlNacerCm;
		this.perimetroCefalicoCm = perimetroCefalicoCm;
		this.patologiasPernatales = patologiasPernatales;
		this.diasHospitalizacion = diasHospitalizacion;
		this.idTipoLecheHasta6meses = idTipoLecheHasta6meses;
		this.antecLactancia = antecLactancia;
		this.edadInicioAblactanciaMeses = edadInicioAblactanciaMeses;
		this.desarrolloSicomotriz = desarrolloSicomotriz;
		this.fechaUltimaRegla = fechaUltimaRegla;
		this.fechaUltimoPeriodo = fechaUltimoPeriodo;
		this.metodosAnticonceptivos = metodosAnticonceptivos;
		this.menarquia = menarquia;
		this.menopausia = menopausia;
		this.caracteristicasMenstruaciones = caracteristicasMenstruaciones;
		this.informacionEmbarazos = informacionEmbarazos;
		this.transfusiones = transfusiones;
		this.deinmunizFechaAproximada = deinmunizFechaAproximada;
		this.deinmunizEdadAproximada = deinmunizEdadAproximada;
		this.alcohol = alcohol;
		this.tabaco = tabaco;
		this.drogas = drogas;
		this.actividadFisica = actividadFisica;
		this.consumoVerduras = consumoVerduras;
		this.consumoFrutas = consumoFrutas;
		this.medicamentos = medicamentos;
		this.alimentos = alimentos;
		this.sustanciasEnElAmbiente = sustanciasEnElAmbiente;
		this.sustanciasContactoConPiel = sustanciasContactoConPiel;
		this.contactoPersonaEnferma = contactoPersonaEnferma;
		this.crianzaAnimalesDomesticos = crianzaAnimalesDomesticos;
		this.aguaPotable = aguaPotable;
		this.disposicionExcretas = disposicionExcretas;
		this.reaccionAdversaMedicamentos = reaccionAdversaMedicamentos;
		this.saludBucal = saludBucal;
		this.vigilanciaDeCrecimiento = vigilanciaDeCrecimiento;
		this.vigilanciaDelDesarrollo = vigilanciaDelDesarrollo;
		this.idValoracionFuncional1 = idValoracionFuncional1;
		this.idValoracionFuncional2 = idValoracionFuncional2;
		this.idValoracionFuncional3 = idValoracionFuncional3;
		this.idValoracionFuncional4 = idValoracionFuncional4;
		this.idValoracionFuncional5 = idValoracionFuncional5;
		this.idValoracionFuncional6 = idValoracionFuncional6;
		this.diagnosticoFuncional = diagnosticoFuncional;
		this.idEstadoCognitivo1 = idEstadoCognitivo1;
		this.idEstadoCognitivo2 = idEstadoCognitivo2;
		this.idEstadoCognitivo3 = idEstadoCognitivo3;
		this.idEstadoCognitivo4 = idEstadoCognitivo4;
		this.idEstadoCognitivo5 = idEstadoCognitivo5;
		this.idEstadoCognitivo6 = idEstadoCognitivo6;
		this.idEstadoCognitivo7 = idEstadoCognitivo7;
		this.idEstadoCognitivo8 = idEstadoCognitivo8;
		this.idEstadoCognitivo9 = idEstadoCognitivo9;
		this.idEstadoCognitivo10 = idEstadoCognitivo10;
		this.valoracionCognitiva = valoracionCognitiva;
		this.idEstadoAfectivo1 = idEstadoAfectivo1;
		this.idEstadoAfectivo2 = idEstadoAfectivo2;
		this.idEstadoAfectivo3 = idEstadoAfectivo3;
		this.idEstadoAfectivo4 = idEstadoAfectivo4;
		this.conManifestacionesDepresivas = conManifestacionesDepresivas;
		this.valoracionSocioFamiliar1 = valoracionSocioFamiliar1;
		this.valoracionSocioFamiliar2 = valoracionSocioFamiliar2;
		this.valoracionSocioFamiliar3 = valoracionSocioFamiliar3;
		this.valoracionSocioFamiliar4 = valoracionSocioFamiliar4;
		this.valoracionSocioFamiliar5 = valoracionSocioFamiliar5;
		this.valoracionSocioFamiliar = valoracionSocioFamiliar;
		this.idCategoriaAdutoMayor = idCategoriaAdutoMayor;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unidadReplicacion", column = @Column(name = "UnidadReplicacion", nullable = false, length = 4) ),
			@AttributeOverride(name = "idEpisodioAtencion", column = @Column(name = "IdEpisodioAtencion", nullable = false) ),
			@AttributeOverride(name = "idPaciente", column = @Column(name = "IdPaciente", nullable = false) ),
			@AttributeOverride(name = "episodioClinico", column = @Column(name = "EpisodioClinico", nullable = false) ) })
	public SsHcAnamnesisApId getId() {
		return this.id;
	}

	public void setId(SsHcAnamnesisApId id) {
		this.id = id;
	}

	@Column(name = "IdTipoEmbarazo")
	public Short getIdTipoEmbarazo() {
		return this.idTipoEmbarazo;
	}

	public void setIdTipoEmbarazo(Short idTipoEmbarazo) {
		this.idTipoEmbarazo = idTipoEmbarazo;
	}

	@Column(name = "PatologiaGestacion", length = 200)
	public String getPatologiaGestacion() {
		return this.patologiaGestacion;
	}

	public void setPatologiaGestacion(String patologiaGestacion) {
		this.patologiaGestacion = patologiaGestacion;
	}

	@Column(name = "IdControlPrenatal")
	public Short getIdControlPrenatal() {
		return this.idControlPrenatal;
	}

	public void setIdControlPrenatal(Short idControlPrenatal) {
		this.idControlPrenatal = idControlPrenatal;
	}

	@Column(name = "CPnumeroControles")
	public Short getCpnumeroControles() {
		return this.cpnumeroControles;
	}

	public void setCpnumeroControles(Short cpnumeroControles) {
		this.cpnumeroControles = cpnumeroControles;
	}

	@Column(name = "CPnumeroEmbarazos")
	public Short getCpnumeroEmbarazos() {
		return this.cpnumeroEmbarazos;
	}

	public void setCpnumeroEmbarazos(Short cpnumeroEmbarazos) {
		this.cpnumeroEmbarazos = cpnumeroEmbarazos;
	}

	@Column(name = "LugarControl", length = 200)
	public String getLugarControl() {
		return this.lugarControl;
	}

	public void setLugarControl(String lugarControl) {
		this.lugarControl = lugarControl;
	}

	@Column(name = "IdTipoParto")
	public Short getIdTipoParto() {
		return this.idTipoParto;
	}

	public void setIdTipoParto(Short idTipoParto) {
		this.idTipoParto = idTipoParto;
	}

	@Column(name = "ComplicacionesParto")
	public String getComplicacionesParto() {
		return this.complicacionesParto;
	}

	public void setComplicacionesParto(String complicacionesParto) {
		this.complicacionesParto = complicacionesParto;
	}

	@Column(name = "IdLugarParto")
	public Short getIdLugarParto() {
		return this.idLugarParto;
	}

	public void setIdLugarParto(Short idLugarParto) {
		this.idLugarParto = idLugarParto;
	}

	@Column(name = "IdPartoAtendidoPor")
	public Short getIdPartoAtendidoPor() {
		return this.idPartoAtendidoPor;
	}

	public void setIdPartoAtendidoPor(Short idPartoAtendidoPor) {
		this.idPartoAtendidoPor = idPartoAtendidoPor;
	}

	@Column(name = "AntecentesPatologicos")
	public String getAntecentesPatologicos() {
		return this.antecentesPatologicos;
	}

	public void setAntecentesPatologicos(String antecentesPatologicos) {
		this.antecentesPatologicos = antecentesPatologicos;
	}

	@Column(name = "SemanasGestacionNacer")
	public Short getSemanasGestacionNacer() {
		return this.semanasGestacionNacer;
	}

	public void setSemanasGestacionNacer(Short semanasGestacionNacer) {
		this.semanasGestacionNacer = semanasGestacionNacer;
	}

	@Column(name = "PesoAlNacerGR")
	public Integer getPesoAlNacerGr() {
		return this.pesoAlNacerGr;
	}

	public void setPesoAlNacerGr(Integer pesoAlNacerGr) {
		this.pesoAlNacerGr = pesoAlNacerGr;
	}

	@Column(name = "TallaAlNacerCM", scale = 4)
	public BigDecimal getTallaAlNacerCm() {
		return this.tallaAlNacerCm;
	}

	public void setTallaAlNacerCm(BigDecimal tallaAlNacerCm) {
		this.tallaAlNacerCm = tallaAlNacerCm;
	}

	@Column(name = "PerimetroCefalicoCM", scale = 4)
	public BigDecimal getPerimetroCefalicoCm() {
		return this.perimetroCefalicoCm;
	}

	public void setPerimetroCefalicoCm(BigDecimal perimetroCefalicoCm) {
		this.perimetroCefalicoCm = perimetroCefalicoCm;
	}

	@Column(name = "PatologiasPernatales")
	public String getPatologiasPernatales() {
		return this.patologiasPernatales;
	}

	public void setPatologiasPernatales(String patologiasPernatales) {
		this.patologiasPernatales = patologiasPernatales;
	}

	@Column(name = "DiasHospitalizacion")
	public Short getDiasHospitalizacion() {
		return this.diasHospitalizacion;
	}

	public void setDiasHospitalizacion(Short diasHospitalizacion) {
		this.diasHospitalizacion = diasHospitalizacion;
	}

	@Column(name = "IdTipoLecheHasta6meses")
	public Short getIdTipoLecheHasta6meses() {
		return this.idTipoLecheHasta6meses;
	}

	public void setIdTipoLecheHasta6meses(Short idTipoLecheHasta6meses) {
		this.idTipoLecheHasta6meses = idTipoLecheHasta6meses;
	}

	@Column(name = "AntecLactancia", length = 200)
	public String getAntecLactancia() {
		return this.antecLactancia;
	}

	public void setAntecLactancia(String antecLactancia) {
		this.antecLactancia = antecLactancia;
	}

	@Column(name = "EdadInicioAblactanciaMeses")
	public Short getEdadInicioAblactanciaMeses() {
		return this.edadInicioAblactanciaMeses;
	}

	public void setEdadInicioAblactanciaMeses(Short edadInicioAblactanciaMeses) {
		this.edadInicioAblactanciaMeses = edadInicioAblactanciaMeses;
	}

	@Column(name = "DesarrolloSicomotriz", length = 200)
	public String getDesarrolloSicomotriz() {
		return this.desarrolloSicomotriz;
	}

	public void setDesarrolloSicomotriz(String desarrolloSicomotriz) {
		this.desarrolloSicomotriz = desarrolloSicomotriz;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaUltimaRegla", length = 23)
	public Date getFechaUltimaRegla() {
		return this.fechaUltimaRegla;
	}

	public void setFechaUltimaRegla(Date fechaUltimaRegla) {
		this.fechaUltimaRegla = fechaUltimaRegla;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaUltimoPeriodo", length = 23)
	public Date getFechaUltimoPeriodo() {
		return this.fechaUltimoPeriodo;
	}

	public void setFechaUltimoPeriodo(Date fechaUltimoPeriodo) {
		this.fechaUltimoPeriodo = fechaUltimoPeriodo;
	}

	@Column(name = "MetodosAnticonceptivos", length = 200)
	public String getMetodosAnticonceptivos() {
		return this.metodosAnticonceptivos;
	}

	public void setMetodosAnticonceptivos(String metodosAnticonceptivos) {
		this.metodosAnticonceptivos = metodosAnticonceptivos;
	}

	@Column(name = "Menarquia", length = 200)
	public String getMenarquia() {
		return this.menarquia;
	}

	public void setMenarquia(String menarquia) {
		this.menarquia = menarquia;
	}

	@Column(name = "Menopausia", length = 200)
	public String getMenopausia() {
		return this.menopausia;
	}

	public void setMenopausia(String menopausia) {
		this.menopausia = menopausia;
	}

	@Column(name = "CaracteristicasMenstruaciones", length = 200)
	public String getCaracteristicasMenstruaciones() {
		return this.caracteristicasMenstruaciones;
	}

	public void setCaracteristicasMenstruaciones(String caracteristicasMenstruaciones) {
		this.caracteristicasMenstruaciones = caracteristicasMenstruaciones;
	}

	@Column(name = "InformacionEmbarazos", length = 200)
	public String getInformacionEmbarazos() {
		return this.informacionEmbarazos;
	}

	public void setInformacionEmbarazos(String informacionEmbarazos) {
		this.informacionEmbarazos = informacionEmbarazos;
	}

	@Column(name = "Transfusiones", length = 200)
	public String getTransfusiones() {
		return this.transfusiones;
	}

	public void setTransfusiones(String transfusiones) {
		this.transfusiones = transfusiones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeinmunizFechaAproximada", length = 23)
	public Date getDeinmunizFechaAproximada() {
		return this.deinmunizFechaAproximada;
	}

	public void setDeinmunizFechaAproximada(Date deinmunizFechaAproximada) {
		this.deinmunizFechaAproximada = deinmunizFechaAproximada;
	}

	@Column(name = "DeinmunizEdadAproximada")
	public Integer getDeinmunizEdadAproximada() {
		return this.deinmunizEdadAproximada;
	}

	public void setDeinmunizEdadAproximada(Integer deinmunizEdadAproximada) {
		this.deinmunizEdadAproximada = deinmunizEdadAproximada;
	}

	@Column(name = "Alcohol", length = 200)
	public String getAlcohol() {
		return this.alcohol;
	}

	public void setAlcohol(String alcohol) {
		this.alcohol = alcohol;
	}

	@Column(name = "Tabaco", length = 200)
	public String getTabaco() {
		return this.tabaco;
	}

	public void setTabaco(String tabaco) {
		this.tabaco = tabaco;
	}

	@Column(name = "Drogas", length = 200)
	public String getDrogas() {
		return this.drogas;
	}

	public void setDrogas(String drogas) {
		this.drogas = drogas;
	}

	@Column(name = "ActividadFisica", length = 200)
	public String getActividadFisica() {
		return this.actividadFisica;
	}

	public void setActividadFisica(String actividadFisica) {
		this.actividadFisica = actividadFisica;
	}

	@Column(name = "ConsumoVerduras", length = 200)
	public String getConsumoVerduras() {
		return this.consumoVerduras;
	}

	public void setConsumoVerduras(String consumoVerduras) {
		this.consumoVerduras = consumoVerduras;
	}

	@Column(name = "ConsumoFrutas", length = 200)
	public String getConsumoFrutas() {
		return this.consumoFrutas;
	}

	public void setConsumoFrutas(String consumoFrutas) {
		this.consumoFrutas = consumoFrutas;
	}

	@Column(name = "Medicamentos", length = 200)
	public String getMedicamentos() {
		return this.medicamentos;
	}

	public void setMedicamentos(String medicamentos) {
		this.medicamentos = medicamentos;
	}

	@Column(name = "Alimentos", length = 200)
	public String getAlimentos() {
		return this.alimentos;
	}

	public void setAlimentos(String alimentos) {
		this.alimentos = alimentos;
	}

	@Column(name = "SustanciasEnElAmbiente", length = 200)
	public String getSustanciasEnElAmbiente() {
		return this.sustanciasEnElAmbiente;
	}

	public void setSustanciasEnElAmbiente(String sustanciasEnElAmbiente) {
		this.sustanciasEnElAmbiente = sustanciasEnElAmbiente;
	}

	@Column(name = "SustanciasContactoConPiel", length = 200)
	public String getSustanciasContactoConPiel() {
		return this.sustanciasContactoConPiel;
	}

	public void setSustanciasContactoConPiel(String sustanciasContactoConPiel) {
		this.sustanciasContactoConPiel = sustanciasContactoConPiel;
	}

	@Column(name = "ContactoPersonaEnferma", length = 200)
	public String getContactoPersonaEnferma() {
		return this.contactoPersonaEnferma;
	}

	public void setContactoPersonaEnferma(String contactoPersonaEnferma) {
		this.contactoPersonaEnferma = contactoPersonaEnferma;
	}

	@Column(name = "CrianzaAnimalesDomesticos", length = 200)
	public String getCrianzaAnimalesDomesticos() {
		return this.crianzaAnimalesDomesticos;
	}

	public void setCrianzaAnimalesDomesticos(String crianzaAnimalesDomesticos) {
		this.crianzaAnimalesDomesticos = crianzaAnimalesDomesticos;
	}

	@Column(name = "AguaPotable", length = 200)
	public String getAguaPotable() {
		return this.aguaPotable;
	}

	public void setAguaPotable(String aguaPotable) {
		this.aguaPotable = aguaPotable;
	}

	@Column(name = "DisposicionExcretas", length = 200)
	public String getDisposicionExcretas() {
		return this.disposicionExcretas;
	}

	public void setDisposicionExcretas(String disposicionExcretas) {
		this.disposicionExcretas = disposicionExcretas;
	}

	@Column(name = "ReaccionAdversaMedicamentos", length = 200)
	public String getReaccionAdversaMedicamentos() {
		return this.reaccionAdversaMedicamentos;
	}

	public void setReaccionAdversaMedicamentos(String reaccionAdversaMedicamentos) {
		this.reaccionAdversaMedicamentos = reaccionAdversaMedicamentos;
	}

	@Column(name = "SaludBucal", length = 200)
	public String getSaludBucal() {
		return this.saludBucal;
	}

	public void setSaludBucal(String saludBucal) {
		this.saludBucal = saludBucal;
	}

	@Column(name = "VigilanciaDeCrecimiento", length = 200)
	public String getVigilanciaDeCrecimiento() {
		return this.vigilanciaDeCrecimiento;
	}

	public void setVigilanciaDeCrecimiento(String vigilanciaDeCrecimiento) {
		this.vigilanciaDeCrecimiento = vigilanciaDeCrecimiento;
	}

	@Column(name = "VigilanciaDelDesarrollo", length = 200)
	public String getVigilanciaDelDesarrollo() {
		return this.vigilanciaDelDesarrollo;
	}

	public void setVigilanciaDelDesarrollo(String vigilanciaDelDesarrollo) {
		this.vigilanciaDelDesarrollo = vigilanciaDelDesarrollo;
	}

	@Column(name = "IdValoracionFuncional1")
	public Short getIdValoracionFuncional1() {
		return this.idValoracionFuncional1;
	}

	public void setIdValoracionFuncional1(Short idValoracionFuncional1) {
		this.idValoracionFuncional1 = idValoracionFuncional1;
	}

	@Column(name = "IdValoracionFuncional2")
	public Short getIdValoracionFuncional2() {
		return this.idValoracionFuncional2;
	}

	public void setIdValoracionFuncional2(Short idValoracionFuncional2) {
		this.idValoracionFuncional2 = idValoracionFuncional2;
	}

	@Column(name = "IdValoracionFuncional3")
	public Short getIdValoracionFuncional3() {
		return this.idValoracionFuncional3;
	}

	public void setIdValoracionFuncional3(Short idValoracionFuncional3) {
		this.idValoracionFuncional3 = idValoracionFuncional3;
	}

	@Column(name = "IdValoracionFuncional4")
	public Short getIdValoracionFuncional4() {
		return this.idValoracionFuncional4;
	}

	public void setIdValoracionFuncional4(Short idValoracionFuncional4) {
		this.idValoracionFuncional4 = idValoracionFuncional4;
	}

	@Column(name = "IdValoracionFuncional5")
	public Short getIdValoracionFuncional5() {
		return this.idValoracionFuncional5;
	}

	public void setIdValoracionFuncional5(Short idValoracionFuncional5) {
		this.idValoracionFuncional5 = idValoracionFuncional5;
	}

	@Column(name = "IdValoracionFuncional6")
	public Short getIdValoracionFuncional6() {
		return this.idValoracionFuncional6;
	}

	public void setIdValoracionFuncional6(Short idValoracionFuncional6) {
		this.idValoracionFuncional6 = idValoracionFuncional6;
	}

	@Column(name = "DiagnosticoFuncional")
	public Short getDiagnosticoFuncional() {
		return this.diagnosticoFuncional;
	}

	public void setDiagnosticoFuncional(Short diagnosticoFuncional) {
		this.diagnosticoFuncional = diagnosticoFuncional;
	}

	@Column(name = "IdEstadoCognitivo1")
	public Short getIdEstadoCognitivo1() {
		return this.idEstadoCognitivo1;
	}

	public void setIdEstadoCognitivo1(Short idEstadoCognitivo1) {
		this.idEstadoCognitivo1 = idEstadoCognitivo1;
	}

	@Column(name = "IdEstadoCognitivo2")
	public Short getIdEstadoCognitivo2() {
		return this.idEstadoCognitivo2;
	}

	public void setIdEstadoCognitivo2(Short idEstadoCognitivo2) {
		this.idEstadoCognitivo2 = idEstadoCognitivo2;
	}

	@Column(name = "IdEstadoCognitivo3")
	public Short getIdEstadoCognitivo3() {
		return this.idEstadoCognitivo3;
	}

	public void setIdEstadoCognitivo3(Short idEstadoCognitivo3) {
		this.idEstadoCognitivo3 = idEstadoCognitivo3;
	}

	@Column(name = "IdEstadoCognitivo4")
	public Short getIdEstadoCognitivo4() {
		return this.idEstadoCognitivo4;
	}

	public void setIdEstadoCognitivo4(Short idEstadoCognitivo4) {
		this.idEstadoCognitivo4 = idEstadoCognitivo4;
	}

	@Column(name = "IdEstadoCognitivo5")
	public Short getIdEstadoCognitivo5() {
		return this.idEstadoCognitivo5;
	}

	public void setIdEstadoCognitivo5(Short idEstadoCognitivo5) {
		this.idEstadoCognitivo5 = idEstadoCognitivo5;
	}

	@Column(name = "IdEstadoCognitivo6")
	public Short getIdEstadoCognitivo6() {
		return this.idEstadoCognitivo6;
	}

	public void setIdEstadoCognitivo6(Short idEstadoCognitivo6) {
		this.idEstadoCognitivo6 = idEstadoCognitivo6;
	}

	@Column(name = "IdEstadoCognitivo7")
	public Short getIdEstadoCognitivo7() {
		return this.idEstadoCognitivo7;
	}

	public void setIdEstadoCognitivo7(Short idEstadoCognitivo7) {
		this.idEstadoCognitivo7 = idEstadoCognitivo7;
	}

	@Column(name = "IdEstadoCognitivo8")
	public Short getIdEstadoCognitivo8() {
		return this.idEstadoCognitivo8;
	}

	public void setIdEstadoCognitivo8(Short idEstadoCognitivo8) {
		this.idEstadoCognitivo8 = idEstadoCognitivo8;
	}

	@Column(name = "IdEstadoCognitivo9")
	public Short getIdEstadoCognitivo9() {
		return this.idEstadoCognitivo9;
	}

	public void setIdEstadoCognitivo9(Short idEstadoCognitivo9) {
		this.idEstadoCognitivo9 = idEstadoCognitivo9;
	}

	@Column(name = "IdEstadoCognitivo10")
	public Short getIdEstadoCognitivo10() {
		return this.idEstadoCognitivo10;
	}

	public void setIdEstadoCognitivo10(Short idEstadoCognitivo10) {
		this.idEstadoCognitivo10 = idEstadoCognitivo10;
	}

	@Column(name = "ValoracionCognitiva")
	public Short getValoracionCognitiva() {
		return this.valoracionCognitiva;
	}

	public void setValoracionCognitiva(Short valoracionCognitiva) {
		this.valoracionCognitiva = valoracionCognitiva;
	}

	@Column(name = "IdEstadoAfectivo1")
	public Short getIdEstadoAfectivo1() {
		return this.idEstadoAfectivo1;
	}

	public void setIdEstadoAfectivo1(Short idEstadoAfectivo1) {
		this.idEstadoAfectivo1 = idEstadoAfectivo1;
	}

	@Column(name = "IdEstadoAfectivo2")
	public Short getIdEstadoAfectivo2() {
		return this.idEstadoAfectivo2;
	}

	public void setIdEstadoAfectivo2(Short idEstadoAfectivo2) {
		this.idEstadoAfectivo2 = idEstadoAfectivo2;
	}

	@Column(name = "IdEstadoAfectivo3")
	public Short getIdEstadoAfectivo3() {
		return this.idEstadoAfectivo3;
	}

	public void setIdEstadoAfectivo3(Short idEstadoAfectivo3) {
		this.idEstadoAfectivo3 = idEstadoAfectivo3;
	}

	@Column(name = "IdEstadoAfectivo4")
	public Short getIdEstadoAfectivo4() {
		return this.idEstadoAfectivo4;
	}

	public void setIdEstadoAfectivo4(Short idEstadoAfectivo4) {
		this.idEstadoAfectivo4 = idEstadoAfectivo4;
	}

	@Column(name = "ConManifestacionesDepresivas")
	public Short getConManifestacionesDepresivas() {
		return this.conManifestacionesDepresivas;
	}

	public void setConManifestacionesDepresivas(Short conManifestacionesDepresivas) {
		this.conManifestacionesDepresivas = conManifestacionesDepresivas;
	}

	@Column(name = "ValoracionSocioFamiliar1")
	public Short getValoracionSocioFamiliar1() {
		return this.valoracionSocioFamiliar1;
	}

	public void setValoracionSocioFamiliar1(Short valoracionSocioFamiliar1) {
		this.valoracionSocioFamiliar1 = valoracionSocioFamiliar1;
	}

	@Column(name = "ValoracionSocioFamiliar2")
	public Short getValoracionSocioFamiliar2() {
		return this.valoracionSocioFamiliar2;
	}

	public void setValoracionSocioFamiliar2(Short valoracionSocioFamiliar2) {
		this.valoracionSocioFamiliar2 = valoracionSocioFamiliar2;
	}

	@Column(name = "ValoracionSocioFamiliar3")
	public Short getValoracionSocioFamiliar3() {
		return this.valoracionSocioFamiliar3;
	}

	public void setValoracionSocioFamiliar3(Short valoracionSocioFamiliar3) {
		this.valoracionSocioFamiliar3 = valoracionSocioFamiliar3;
	}

	@Column(name = "ValoracionSocioFamiliar4")
	public Short getValoracionSocioFamiliar4() {
		return this.valoracionSocioFamiliar4;
	}

	public void setValoracionSocioFamiliar4(Short valoracionSocioFamiliar4) {
		this.valoracionSocioFamiliar4 = valoracionSocioFamiliar4;
	}

	@Column(name = "ValoracionSocioFamiliar5")
	public Short getValoracionSocioFamiliar5() {
		return this.valoracionSocioFamiliar5;
	}

	public void setValoracionSocioFamiliar5(Short valoracionSocioFamiliar5) {
		this.valoracionSocioFamiliar5 = valoracionSocioFamiliar5;
	}

	@Column(name = "ValoracionSocioFamiliar")
	public Short getValoracionSocioFamiliar() {
		return this.valoracionSocioFamiliar;
	}

	public void setValoracionSocioFamiliar(Short valoracionSocioFamiliar) {
		this.valoracionSocioFamiliar = valoracionSocioFamiliar;
	}

	@Column(name = "IdCategoriaAdutoMayor")
	public Short getIdCategoriaAdutoMayor() {
		return this.idCategoriaAdutoMayor;
	}

	public void setIdCategoriaAdutoMayor(Short idCategoriaAdutoMayor) {
		this.idCategoriaAdutoMayor = idCategoriaAdutoMayor;
	}

	@Column(name = "Estado")
	public Short getEstado() {
		return this.estado;
	}

	public void setEstado(Short estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 50)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
