package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 10, 2015 11:33:54 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SsHcAuditRoyal generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_AuditRoyal")
public class SsHcAuditRoyal extends Entidad implements java.io.Serializable {

	private long auditId;
	private Date version;
	private String hostName;
	private String aplicacion;
	private String modulo;
	private String usuario;
	private Character type;
	private Serializable tableName;
	private Long tableIdValue;
	private String primaryKeyData;
	private String oldData;
	private String newData;
	private Date updateDate;
	private Serializable vistaData;
	private String accion;

	public SsHcAuditRoyal() {
	}

	public SsHcAuditRoyal(long auditId) {
		this.auditId = auditId;
	}

	public SsHcAuditRoyal(long auditId, String hostName, String aplicacion, String modulo, String usuario,
			Character type, Serializable tableName, Long tableIdValue, String primaryKeyData, String oldData,
			String newData, Date updateDate, Serializable vistaData, String accion) {
		this.auditId = auditId;
		this.hostName = hostName;
		this.aplicacion = aplicacion;
		this.modulo = modulo;
		this.usuario = usuario;
		this.type = type;
		this.tableName = tableName;
		this.tableIdValue = tableIdValue;
		this.primaryKeyData = primaryKeyData;
		this.oldData = oldData;
		this.newData = newData;
		this.updateDate = updateDate;
		this.vistaData = vistaData;
		this.accion = accion;
	}

	@Id

	@Column(name = "AuditID", unique = true, nullable = false)
	public long getAuditId() {
		return this.auditId;
	}

	public void setAuditId(long auditId) {
		this.auditId = auditId;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Version", length = 23)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "HostName", length = 300)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "Aplicacion", length = 30)
	public String getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	@Column(name = "Modulo", length = 30)
	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	@Column(name = "Usuario", length = 128)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Type", length = 1)
	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	@Column(name = "TableName")
	public Serializable getTableName() {
		return this.tableName;
	}

	public void setTableName(Serializable tableName) {
		this.tableName = tableName;
	}

	@Column(name = "TableIdValue")
	public Long getTableIdValue() {
		return this.tableIdValue;
	}

	public void setTableIdValue(Long tableIdValue) {
		this.tableIdValue = tableIdValue;
	}

	@Column(name = "PrimaryKeyData", length = 1000)
	public String getPrimaryKeyData() {
		return this.primaryKeyData;
	}

	public void setPrimaryKeyData(String primaryKeyData) {
		this.primaryKeyData = primaryKeyData;
	}

	@Column(name = "OldData")
	public String getOldData() {
		return this.oldData;
	}

	public void setOldData(String oldData) {
		this.oldData = oldData;
	}

	@Column(name = "NewData")
	public String getNewData() {
		return this.newData;
	}

	public void setNewData(String newData) {
		this.newData = newData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdateDate", length = 23)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "VistaData")
	public Serializable getVistaData() {
		return this.vistaData;
	}

	public void setVistaData(Serializable vistaData) {
		this.vistaData = vistaData;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
