package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 28, 2015 2:18:16 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SsHcEpisodioAtencion generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_EpisodioAtencion")
public class SsHcEpisodioAtencion extends Entidad implements java.io.Serializable {

	private SsHcEpisodioAtencionId id;
	private String version;
	private Long episodioAtencion;
	private Integer idOrdenAtencion;
	private Integer lineaOrdenAtencion;
	private String codigoOa;
	private Integer tipoAtencion;
	private String unidadReplicacionEc;
	private Integer tipoOrdenAtencion;
	private String tipoTrabajador;
	private String tipoEpisodio;
	private String idEpisodioAtencionCodigo;
	private Integer idEstablecimientoSalud;
	private Integer idUnidadServicio;
	private Integer idPersonalSalud;
	private Date fechaRegistro;
	private Date fechaAtencion;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private Integer idEspecialidad;
	private Character proximaAtencionFlag;
	private Integer idEspecialidadProxima;
	private Integer idEstablecimientoSaludProxima;
	private Integer idTipoInterConsulta;
	private Integer idTipoReferencia;
	private String observacionProxima;
	private String descansoMedico;
	private Integer diasDescansoMedico;
	private Date fechaInicioDescansoMedico;
	private Date fechaFinDescansoMedico;
	private Date fechaOrden;
	private Integer idProcedimiento;
	private String observacionOrden;
	private Integer idTipoOrden;
	private Integer flagFirma;
	private Date fechaFirma;
	private Integer idMedicoFirma;
	private String observacionFirma;
	private Serializable keyPrivada;
	private Serializable keyPublica;
	private String accion;

	public SsHcEpisodioAtencion() {
	}

	public SsHcEpisodioAtencion(SsHcEpisodioAtencionId id, String unidadReplicacionEc) {
		this.id = id;
		this.unidadReplicacionEc = unidadReplicacionEc;
	}

	public SsHcEpisodioAtencion(SsHcEpisodioAtencionId id, Long episodioAtencion, Integer idOrdenAtencion,
			Integer lineaOrdenAtencion, String codigoOa, Integer tipoAtencion, String unidadReplicacionEc,
			Integer tipoOrdenAtencion, String tipoTrabajador, String tipoEpisodio, String idEpisodioAtencionCodigo,
			Integer idEstablecimientoSalud, Integer idUnidadServicio, Integer idPersonalSalud, Date fechaRegistro,
			Date fechaAtencion, Integer estado, String usuarioCreacion, Date fechaCreacion, String usuarioModificacion,
			Date fechaModificacion, Integer idEspecialidad, Character proximaAtencionFlag,
			Integer idEspecialidadProxima, Integer idEstablecimientoSaludProxima, Integer idTipoInterConsulta,
			Integer idTipoReferencia, String observacionProxima, String descansoMedico, Integer diasDescansoMedico,
			Date fechaInicioDescansoMedico, Date fechaFinDescansoMedico, Date fechaOrden, Integer idProcedimiento,
			String observacionOrden, Integer idTipoOrden, Integer flagFirma, Date fechaFirma, Integer idMedicoFirma,
			String observacionFirma, Serializable keyPrivada, Serializable keyPublica, String accion) {
		this.id = id;
		this.episodioAtencion = episodioAtencion;
		this.idOrdenAtencion = idOrdenAtencion;
		this.lineaOrdenAtencion = lineaOrdenAtencion;
		this.codigoOa = codigoOa;
		this.tipoAtencion = tipoAtencion;
		this.unidadReplicacionEc = unidadReplicacionEc;
		this.tipoOrdenAtencion = tipoOrdenAtencion;
		this.tipoTrabajador = tipoTrabajador;
		this.tipoEpisodio = tipoEpisodio;
		this.idEpisodioAtencionCodigo = idEpisodioAtencionCodigo;
		this.idEstablecimientoSalud = idEstablecimientoSalud;
		this.idUnidadServicio = idUnidadServicio;
		this.idPersonalSalud = idPersonalSalud;
		this.fechaRegistro = fechaRegistro;
		this.fechaAtencion = fechaAtencion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.idEspecialidad = idEspecialidad;
		this.proximaAtencionFlag = proximaAtencionFlag;
		this.idEspecialidadProxima = idEspecialidadProxima;
		this.idEstablecimientoSaludProxima = idEstablecimientoSaludProxima;
		this.idTipoInterConsulta = idTipoInterConsulta;
		this.idTipoReferencia = idTipoReferencia;
		this.observacionProxima = observacionProxima;
		this.descansoMedico = descansoMedico;
		this.diasDescansoMedico = diasDescansoMedico;
		this.fechaInicioDescansoMedico = fechaInicioDescansoMedico;
		this.fechaFinDescansoMedico = fechaFinDescansoMedico;
		this.fechaOrden = fechaOrden;
		this.idProcedimiento = idProcedimiento;
		this.observacionOrden = observacionOrden;
		this.idTipoOrden = idTipoOrden;
		this.flagFirma = flagFirma;
		this.fechaFirma = fechaFirma;
		this.idMedicoFirma = idMedicoFirma;
		this.observacionFirma = observacionFirma;
		this.keyPrivada = keyPrivada;
		this.keyPublica = keyPublica;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unidadReplicacion", column = @Column(name = "UnidadReplicacion", nullable = false, length = 4) ),
			@AttributeOverride(name = "idPaciente", column = @Column(name = "IdPaciente", nullable = false) ),
			@AttributeOverride(name = "episodioClinico", column = @Column(name = "EpisodioClinico", nullable = false) ),
			@AttributeOverride(name = "idEpisodioAtencion", column = @Column(name = "IdEpisodioAtencion", nullable = false) ) })
	public SsHcEpisodioAtencionId getId() {
		return this.id;
	}

	public void setId(SsHcEpisodioAtencionId id) {
		this.id = id;
	}

	
	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "EpisodioAtencion")
	public Long getEpisodioAtencion() {
		return this.episodioAtencion;
	}

	public void setEpisodioAtencion(Long episodioAtencion) {
		this.episodioAtencion = episodioAtencion;
	}

	@Column(name = "IdOrdenAtencion")
	public Integer getIdOrdenAtencion() {
		return this.idOrdenAtencion;
	}

	public void setIdOrdenAtencion(Integer idOrdenAtencion) {
		this.idOrdenAtencion = idOrdenAtencion;
	}

	@Column(name = "LineaOrdenAtencion")
	public Integer getLineaOrdenAtencion() {
		return this.lineaOrdenAtencion;
	}

	public void setLineaOrdenAtencion(Integer lineaOrdenAtencion) {
		this.lineaOrdenAtencion = lineaOrdenAtencion;
	}

	@Column(name = "CodigoOA", length = 15)
	public String getCodigoOa() {
		return this.codigoOa;
	}

	public void setCodigoOa(String codigoOa) {
		this.codigoOa = codigoOa;
	}

	@Column(name = "TipoAtencion")
	public Integer getTipoAtencion() {
		return this.tipoAtencion;
	}

	public void setTipoAtencion(Integer tipoAtencion) {
		this.tipoAtencion = tipoAtencion;
	}

	@Column(name = "UnidadReplicacionEC", nullable = false, length = 4)
	public String getUnidadReplicacionEc() {
		return this.unidadReplicacionEc;
	}

	public void setUnidadReplicacionEc(String unidadReplicacionEc) {
		this.unidadReplicacionEc = unidadReplicacionEc;
	}

	@Column(name = "TipoOrdenAtencion")
	public Integer getTipoOrdenAtencion() {
		return this.tipoOrdenAtencion;
	}

	public void setTipoOrdenAtencion(Integer tipoOrdenAtencion) {
		this.tipoOrdenAtencion = tipoOrdenAtencion;
	}

	@Column(name = "TipoTrabajador", length = 20)
	public String getTipoTrabajador() {
		return this.tipoTrabajador;
	}

	public void setTipoTrabajador(String tipoTrabajador) {
		this.tipoTrabajador = tipoTrabajador;
	}

	@Column(name = "TipoEpisodio", length = 20)
	public String getTipoEpisodio() {
		return this.tipoEpisodio;
	}

	public void setTipoEpisodio(String tipoEpisodio) {
		this.tipoEpisodio = tipoEpisodio;
	}

	@Column(name = "IdEpisodioAtencionCodigo", length = 100)
	public String getIdEpisodioAtencionCodigo() {
		return this.idEpisodioAtencionCodigo;
	}

	public void setIdEpisodioAtencionCodigo(String idEpisodioAtencionCodigo) {
		this.idEpisodioAtencionCodigo = idEpisodioAtencionCodigo;
	}

	@Column(name = "IdEstablecimientoSalud")
	public Integer getIdEstablecimientoSalud() {
		return this.idEstablecimientoSalud;
	}

	public void setIdEstablecimientoSalud(Integer idEstablecimientoSalud) {
		this.idEstablecimientoSalud = idEstablecimientoSalud;
	}

	@Column(name = "IdUnidadServicio")
	public Integer getIdUnidadServicio() {
		return this.idUnidadServicio;
	}

	public void setIdUnidadServicio(Integer idUnidadServicio) {
		this.idUnidadServicio = idUnidadServicio;
	}

	@Column(name = "IdPersonalSalud")
	public Integer getIdPersonalSalud() {
		return this.idPersonalSalud;
	}

	public void setIdPersonalSalud(Integer idPersonalSalud) {
		this.idPersonalSalud = idPersonalSalud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaRegistro", length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaAtencion", length = 23)
	public Date getFechaAtencion() {
		return this.fechaAtencion;
	}

	public void setFechaAtencion(Date fechaAtencion) {
		this.fechaAtencion = fechaAtencion;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "IdEspecialidad")
	public Integer getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(Integer idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	@Column(name = "ProximaAtencionFlag", length = 1)
	public Character getProximaAtencionFlag() {
		return this.proximaAtencionFlag;
	}

	public void setProximaAtencionFlag(Character proximaAtencionFlag) {
		this.proximaAtencionFlag = proximaAtencionFlag;
	}

	@Column(name = "IdEspecialidadProxima")
	public Integer getIdEspecialidadProxima() {
		return this.idEspecialidadProxima;
	}

	public void setIdEspecialidadProxima(Integer idEspecialidadProxima) {
		this.idEspecialidadProxima = idEspecialidadProxima;
	}

	@Column(name = "IdEstablecimientoSaludProxima")
	public Integer getIdEstablecimientoSaludProxima() {
		return this.idEstablecimientoSaludProxima;
	}

	public void setIdEstablecimientoSaludProxima(Integer idEstablecimientoSaludProxima) {
		this.idEstablecimientoSaludProxima = idEstablecimientoSaludProxima;
	}

	@Column(name = "IdTipoInterConsulta")
	public Integer getIdTipoInterConsulta() {
		return this.idTipoInterConsulta;
	}

	public void setIdTipoInterConsulta(Integer idTipoInterConsulta) {
		this.idTipoInterConsulta = idTipoInterConsulta;
	}

	@Column(name = "IdTipoReferencia")
	public Integer getIdTipoReferencia() {
		return this.idTipoReferencia;
	}

	public void setIdTipoReferencia(Integer idTipoReferencia) {
		this.idTipoReferencia = idTipoReferencia;
	}

	@Column(name = "ObservacionProxima")
	public String getObservacionProxima() {
		return this.observacionProxima;
	}

	public void setObservacionProxima(String observacionProxima) {
		this.observacionProxima = observacionProxima;
	}

	@Column(name = "DescansoMedico", length = 200)
	public String getDescansoMedico() {
		return this.descansoMedico;
	}

	public void setDescansoMedico(String descansoMedico) {
		this.descansoMedico = descansoMedico;
	}

	@Column(name = "DiasDescansoMedico")
	public Integer getDiasDescansoMedico() {
		return this.diasDescansoMedico;
	}

	public void setDiasDescansoMedico(Integer diasDescansoMedico) {
		this.diasDescansoMedico = diasDescansoMedico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaInicioDescansoMedico", length = 23)
	public Date getFechaInicioDescansoMedico() {
		return this.fechaInicioDescansoMedico;
	}

	public void setFechaInicioDescansoMedico(Date fechaInicioDescansoMedico) {
		this.fechaInicioDescansoMedico = fechaInicioDescansoMedico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaFinDescansoMedico", length = 23)
	public Date getFechaFinDescansoMedico() {
		return this.fechaFinDescansoMedico;
	}

	public void setFechaFinDescansoMedico(Date fechaFinDescansoMedico) {
		this.fechaFinDescansoMedico = fechaFinDescansoMedico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaOrden", length = 23)
	public Date getFechaOrden() {
		return this.fechaOrden;
	}

	public void setFechaOrden(Date fechaOrden) {
		this.fechaOrden = fechaOrden;
	}

	@Column(name = "IdProcedimiento")
	public Integer getIdProcedimiento() {
		return this.idProcedimiento;
	}

	public void setIdProcedimiento(Integer idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}

	@Column(name = "ObservacionOrden")
	public String getObservacionOrden() {
		return this.observacionOrden;
	}

	public void setObservacionOrden(String observacionOrden) {
		this.observacionOrden = observacionOrden;
	}

	@Column(name = "IdTipoOrden")
	public Integer getIdTipoOrden() {
		return this.idTipoOrden;
	}

	public void setIdTipoOrden(Integer idTipoOrden) {
		this.idTipoOrden = idTipoOrden;
	}

	@Column(name = "FlagFirma")
	public Integer getFlagFirma() {
		return this.flagFirma;
	}

	public void setFlagFirma(Integer flagFirma) {
		this.flagFirma = flagFirma;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaFirma", length = 23)
	public Date getFechaFirma() {
		return this.fechaFirma;
	}

	public void setFechaFirma(Date fechaFirma) {
		this.fechaFirma = fechaFirma;
	}

	@Column(name = "idMedicoFirma")
	public Integer getIdMedicoFirma() {
		return this.idMedicoFirma;
	}

	public void setIdMedicoFirma(Integer idMedicoFirma) {
		this.idMedicoFirma = idMedicoFirma;
	}

	@Column(name = "ObservacionFirma", length = 300)
	public String getObservacionFirma() {
		return this.observacionFirma;
	}

	public void setObservacionFirma(String observacionFirma) {
		this.observacionFirma = observacionFirma;
	}

	@Column(name = "KeyPrivada")
	public Serializable getKeyPrivada() {
		return this.keyPrivada;
	}

	public void setKeyPrivada(Serializable keyPrivada) {
		this.keyPrivada = keyPrivada;
	}

	@Column(name = "KeyPublica")
	public Serializable getKeyPublica() {
		return this.keyPublica;
	}

	public void setKeyPublica(Serializable keyPublica) {
		this.keyPublica = keyPublica;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
