package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 5, 2015 11:10:50 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SsHcAnamnesisAfEnfermedad generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_Anamnesis_AF_Enfermedad")
public class SsHcAnamnesisAfEnfermedad extends Entidad implements java.io.Serializable {

	private SsHcAnamnesisAfEnfermedadId id;
	private String version;
	private String observaciones;
	private String accion;

	public SsHcAnamnesisAfEnfermedad() {
	}

	public SsHcAnamnesisAfEnfermedad(SsHcAnamnesisAfEnfermedadId id) {
		this.id = id;
	}

	public SsHcAnamnesisAfEnfermedad(SsHcAnamnesisAfEnfermedadId id, String observaciones, String accion) {
		this.id = id;
		this.observaciones = observaciones;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unidadReplicacion", column = @Column(name = "UnidadReplicacion", nullable = false, length = 4) ),
			@AttributeOverride(name = "idEpisodioAtencion", column = @Column(name = "IdEpisodioAtencion", nullable = false) ),
			@AttributeOverride(name = "idPaciente", column = @Column(name = "IdPaciente", nullable = false) ),
			@AttributeOverride(name = "episodioClinico", column = @Column(name = "EpisodioClinico", nullable = false) ),
			@AttributeOverride(name = "secuencia", column = @Column(name = "Secuencia", nullable = false) ),
			@AttributeOverride(name = "idDiagnostico", column = @Column(name = "IdDiagnostico", nullable = false) ) })
	public SsHcAnamnesisAfEnfermedadId getId() {
		return this.id;
	}

	public void setId(SsHcAnamnesisAfEnfermedadId id) {
		this.id = id;
	}

	
	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "Observaciones", length = 200)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
