package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 7, 2015 3:46:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SsHcFavorito generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_Favorito")
public class SsHcFavorito extends Entidad implements java.io.Serializable {

	private int idFavorito;
	private String version;
	private SgAgente sgAgente;
	private String descripcion;
	private String descripcionExtranjera;
	private Integer tipoFavorito;
	private Integer idFavoritoTabla;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;

	public SsHcFavorito() {
	}

	public SsHcFavorito(int idFavorito) {
		this.idFavorito = idFavorito;
	}

	public SsHcFavorito(int idFavorito, SgAgente sgAgente, String descripcion, String descripcionExtranjera,
			Integer tipoFavorito, Integer idFavoritoTabla, Integer estado, String usuarioCreacion, Date fechaCreacion,
			String usuarioModificacion, Date fechaModificacion, String accion) {
		this.idFavorito = idFavorito;
		this.sgAgente = sgAgente;
		this.descripcion = descripcion;
		this.descripcionExtranjera = descripcionExtranjera;
		this.tipoFavorito = tipoFavorito;
		this.idFavoritoTabla = idFavoritoTabla;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
	}

	@Id

	@Column(name = "IdFavorito", unique = true, nullable = false)
	public int getIdFavorito() {
		return this.idFavorito;
	}

	public void setIdFavorito(int idFavorito) {
		this.idFavorito = idFavorito;
	}

	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdAgente")
	public SgAgente getSgAgente() {
		return this.sgAgente;
	}

	public void setSgAgente(SgAgente sgAgente) {
		this.sgAgente = sgAgente;
	}

	@Column(name = "Descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DescripcionExtranjera", length = 100)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "TipoFavorito")
	public Integer getTipoFavorito() {
		return this.tipoFavorito;
	}

	public void setTipoFavorito(Integer tipoFavorito) {
		this.tipoFavorito = tipoFavorito;
	}

	@Column(name = "IdFavoritoTabla")
	public Integer getIdFavoritoTabla() {
		return this.idFavoritoTabla;
	}

	public void setIdFavoritoTabla(Integer idFavoritoTabla) {
		this.idFavoritoTabla = idFavoritoTabla;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
