package pe.royalsystems.springerp.model.domain;

//default package
//Generated Sep 10, 2015 3:57:00 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
* SsHcCuidadoPreventivo generated by hbm2java
*/
@Entity
@Table(name = "SS_HC_CuidadoPreventivo")
public class SsHcCuidadoPreventivo extends Entidad implements java.io.Serializable {

	private int idCuidadoPreventivo;
	private String version;
	private Integer idCuidadoPreventivoPadre;
	private String codigoCuidadoPreventivo;
	private String codigoCuidadoPreventivoPadre;
	private Integer idTipoCuidadoPreventivo;
	private Integer idTipoPeriodicidad;
	private String descripcion;
	private String descripcionExtranjera;
	private Integer nivel;
	private Character ultimoNivelFlag;
	private String cadenaRecursiva;
	private Integer orden;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String nombreTabla;
	private String accion;

	public SsHcCuidadoPreventivo() {
	}

	public SsHcCuidadoPreventivo(int idCuidadoPreventivo) {
		this.idCuidadoPreventivo = idCuidadoPreventivo;
	}

	public SsHcCuidadoPreventivo(int idCuidadoPreventivo, Integer idCuidadoPreventivoPadre,
			String codigoCuidadoPreventivo, String codigoCuidadoPreventivoPadre, Integer idTipoCuidadoPreventivo,
			Integer idTipoPeriodicidad, String descripcion, String descripcionExtranjera, Integer nivel,
			Character ultimoNivelFlag, String cadenaRecursiva, Integer orden, Integer estado, String usuarioCreacion,
			Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, String nombreTabla, String accion) {
		this.idCuidadoPreventivo = idCuidadoPreventivo;
		this.idCuidadoPreventivoPadre = idCuidadoPreventivoPadre;
		this.codigoCuidadoPreventivo = codigoCuidadoPreventivo;
		this.codigoCuidadoPreventivoPadre = codigoCuidadoPreventivoPadre;
		this.idTipoCuidadoPreventivo = idTipoCuidadoPreventivo;
		this.idTipoPeriodicidad = idTipoPeriodicidad;
		this.descripcion = descripcion;
		this.descripcionExtranjera = descripcionExtranjera;
		this.nivel = nivel;
		this.ultimoNivelFlag = ultimoNivelFlag;
		this.cadenaRecursiva = cadenaRecursiva;
		this.orden = orden;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.nombreTabla = nombreTabla;
		this.accion = accion;
	}

	@Id

	@Column(name = "IdCuidadoPreventivo", unique = true, nullable = false)
	public int getIdCuidadoPreventivo() {
		return this.idCuidadoPreventivo;
	}

	public void setIdCuidadoPreventivo(int idCuidadoPreventivo) {
		this.idCuidadoPreventivo = idCuidadoPreventivo;
	}


	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "IdCuidadoPreventivoPadre")
	public Integer getIdCuidadoPreventivoPadre() {
		return this.idCuidadoPreventivoPadre;
	}

	public void setIdCuidadoPreventivoPadre(Integer idCuidadoPreventivoPadre) {
		this.idCuidadoPreventivoPadre = idCuidadoPreventivoPadre;
	}

	@Column(name = "CodigoCuidadoPreventivo", length = 20)
	public String getCodigoCuidadoPreventivo() {
		return this.codigoCuidadoPreventivo;
	}

	public void setCodigoCuidadoPreventivo(String codigoCuidadoPreventivo) {
		this.codigoCuidadoPreventivo = codigoCuidadoPreventivo;
	}

	@Column(name = "CodigoCuidadoPreventivoPadre", length = 20)
	public String getCodigoCuidadoPreventivoPadre() {
		return this.codigoCuidadoPreventivoPadre;
	}

	public void setCodigoCuidadoPreventivoPadre(String codigoCuidadoPreventivoPadre) {
		this.codigoCuidadoPreventivoPadre = codigoCuidadoPreventivoPadre;
	}

	@Column(name = "IdTipoCuidadoPreventivo")
	public Integer getIdTipoCuidadoPreventivo() {
		return this.idTipoCuidadoPreventivo;
	}

	public void setIdTipoCuidadoPreventivo(Integer idTipoCuidadoPreventivo) {
		this.idTipoCuidadoPreventivo = idTipoCuidadoPreventivo;
	}

	@Column(name = "IdTipoPeriodicidad")
	public Integer getIdTipoPeriodicidad() {
		return this.idTipoPeriodicidad;
	}

	public void setIdTipoPeriodicidad(Integer idTipoPeriodicidad) {
		this.idTipoPeriodicidad = idTipoPeriodicidad;
	}

	@Column(name = "Descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DescripcionExtranjera", length = 200)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "Nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "UltimoNivelFlag", length = 1)
	public Character getUltimoNivelFlag() {
		return this.ultimoNivelFlag;
	}

	public void setUltimoNivelFlag(Character ultimoNivelFlag) {
		this.ultimoNivelFlag = ultimoNivelFlag;
	}

	@Column(name = "CadenaRecursiva", length = 150)
	public String getCadenaRecursiva() {
		return this.cadenaRecursiva;
	}

	public void setCadenaRecursiva(String cadenaRecursiva) {
		this.cadenaRecursiva = cadenaRecursiva;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "NombreTabla", length = 25)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
