package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 6, 2015 3:48:44 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SsHcExamenFisicoTriajeId generated by hbm2java
 */
@Embeddable
public class SsHcExamenFisicoTriajeId implements java.io.Serializable {

	private String unidadReplicacion;
	private Long idEpisodioAtencion;
	private Integer idPaciente;
	private Integer episodioClinico;

	public SsHcExamenFisicoTriajeId() {
	}

	public SsHcExamenFisicoTriajeId(String unidadReplicacion, Long idEpisodioAtencion, Integer idPaciente,
			Integer episodioClinico) {
		this.unidadReplicacion = unidadReplicacion;
		this.idEpisodioAtencion = idEpisodioAtencion;
		this.idPaciente = idPaciente;
		this.episodioClinico = episodioClinico;
	}

	@Column(name = "UnidadReplicacion", nullable = false, length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "IdEpisodioAtencion", nullable = false)
	public Long getIdEpisodioAtencion() {
		return this.idEpisodioAtencion;
	}

	public void setIdEpisodioAtencion(Long idEpisodioAtencion) {
		this.idEpisodioAtencion = idEpisodioAtencion;
	}

	@Column(name = "IdPaciente", nullable = false)
	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "EpisodioClinico", nullable = false)
	public Integer getEpisodioClinico() {
		return this.episodioClinico;
	}

	public void setEpisodioClinico(Integer episodioClinico) {
		this.episodioClinico = episodioClinico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SsHcExamenFisicoTriajeId))
			return false;
		SsHcExamenFisicoTriajeId castOther = (SsHcExamenFisicoTriajeId) other;

		return ((this.getUnidadReplicacion() == castOther.getUnidadReplicacion())
				|| (this.getUnidadReplicacion() != null && castOther.getUnidadReplicacion() != null
						&& this.getUnidadReplicacion().equals(castOther.getUnidadReplicacion())))
				&& (this.getIdEpisodioAtencion() == castOther.getIdEpisodioAtencion())
				&& (this.getIdPaciente() == castOther.getIdPaciente())
				&& (this.getEpisodioClinico() == castOther.getEpisodioClinico());
	}



}
