package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 6, 2015 3:48:44 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SsHcExamenFisicoTriaje generated by hbm2java
 */
@Entity
@Table(name = "SS_HC_ExamenFisico_Triaje")
public class SsHcExamenFisicoTriaje extends Entidad  {

	private SsHcExamenFisicoTriajeId id;
	private String version;
	private Integer presionMinima;
	private Integer presionMaxima;
	private Integer frecuenciaRespiratoria;
	private Integer frecuenciaCardiaca;
	private BigDecimal temperatura;
	private BigDecimal peso;
	private BigDecimal talla;
	private BigDecimal indiceMasaCorporal;
	private Integer idEstadoGeneral;
	private Integer idNutricion;
	private Integer idHidratacion;
	private Integer idColaboracion;
	private String observacionesAdicionales;
	private Integer estado;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String accion;

	public SsHcExamenFisicoTriaje() {
		id = new SsHcExamenFisicoTriajeId();
	}

	public SsHcExamenFisicoTriaje(SsHcExamenFisicoTriajeId id) {
		this.id = id;
	}

	public SsHcExamenFisicoTriaje(SsHcExamenFisicoTriajeId id, Integer presionMinima, Integer presionMaxima,
			Integer frecuenciaRespiratoria, Integer frecuenciaCardiaca, BigDecimal temperatura, BigDecimal peso,
			BigDecimal talla, BigDecimal indiceMasaCorporal, Integer idEstadoGeneral, Integer idNutricion,
			Integer idHidratacion, Integer idColaboracion, String observacionesAdicionales, Integer estado,
			String usuarioCreacion, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion,
			String accion) {
		this.id = id;
		this.presionMinima = presionMinima;
		this.presionMaxima = presionMaxima;
		this.frecuenciaRespiratoria = frecuenciaRespiratoria;
		this.frecuenciaCardiaca = frecuenciaCardiaca;
		this.temperatura = temperatura;
		this.peso = peso;
		this.talla = talla;
		this.indiceMasaCorporal = indiceMasaCorporal;
		this.idEstadoGeneral = idEstadoGeneral;
		this.idNutricion = idNutricion;
		this.idHidratacion = idHidratacion;
		this.idColaboracion = idColaboracion;
		this.observacionesAdicionales = observacionesAdicionales;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "unidadReplicacion", column = @Column(name = "UnidadReplicacion", nullable = false, length = 4) ),
			@AttributeOverride(name = "idEpisodioAtencion", column = @Column(name = "IdEpisodioAtencion", nullable = false) ),
			@AttributeOverride(name = "idPaciente", column = @Column(name = "IdPaciente", nullable = false) ),
			@AttributeOverride(name = "episodioClinico", column = @Column(name = "EpisodioClinico", nullable = false) ) })
	public SsHcExamenFisicoTriajeId getId() {
		return this.id;
	}

	public void setId(SsHcExamenFisicoTriajeId id) {
		this.id = id;
	}

	
	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "PresionMinima")
	public Integer getPresionMinima() {
		return this.presionMinima;
	}

	public void setPresionMinima(Integer presionMinima) {
		this.presionMinima = presionMinima;
	}

	@Column(name = "PresionMaxima")
	public Integer getPresionMaxima() {
		return this.presionMaxima;
	}

	public void setPresionMaxima(Integer presionMaxima) {
		this.presionMaxima = presionMaxima;
	}

	@Column(name = "FrecuenciaRespiratoria")
	public Integer getFrecuenciaRespiratoria() {
		return this.frecuenciaRespiratoria;
	}

	public void setFrecuenciaRespiratoria(Integer frecuenciaRespiratoria) {
		this.frecuenciaRespiratoria = frecuenciaRespiratoria;
	}

	@Column(name = "FrecuenciaCardiaca")
	public Integer getFrecuenciaCardiaca() {
		return this.frecuenciaCardiaca;
	}

	public void setFrecuenciaCardiaca(Integer frecuenciaCardiaca) {
		this.frecuenciaCardiaca = frecuenciaCardiaca;
	}

	@Column(name = "Temperatura", precision = 20, scale = 6)
	public BigDecimal getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(BigDecimal temperatura) {
		this.temperatura = temperatura;
	}

	@Column(name = "Peso", precision = 20, scale = 6)
	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	@Column(name = "Talla", precision = 20, scale = 6)
	public BigDecimal getTalla() {
		return this.talla;
	}

	public void setTalla(BigDecimal talla) {
		this.talla = talla;
	}

	@Column(name = "IndiceMasaCorporal", precision = 20, scale = 6)
	public BigDecimal getIndiceMasaCorporal() {
		return this.indiceMasaCorporal;
	}

	public void setIndiceMasaCorporal(BigDecimal indiceMasaCorporal) {
		this.indiceMasaCorporal = indiceMasaCorporal;
	}

	@Column(name = "IdEstadoGeneral")
	public Integer getIdEstadoGeneral() {
		return this.idEstadoGeneral;
	}

	public void setIdEstadoGeneral(Integer idEstadoGeneral) {
		this.idEstadoGeneral = idEstadoGeneral;
	}

	@Column(name = "IdNutricion")
	public Integer getIdNutricion() {
		return this.idNutricion;
	}

	public void setIdNutricion(Integer idNutricion) {
		this.idNutricion = idNutricion;
	}

	@Column(name = "IdHidratacion")
	public Integer getIdHidratacion() {
		return this.idHidratacion;
	}

	public void setIdHidratacion(Integer idHidratacion) {
		this.idHidratacion = idHidratacion;
	}

	@Column(name = "IdColaboracion")
	public Integer getIdColaboracion() {
		return this.idColaboracion;
	}

	public void setIdColaboracion(Integer idColaboracion) {
		this.idColaboracion = idColaboracion;
	}

	@Column(name = "ObservacionesAdicionales", length = 500)
	public String getObservacionesAdicionales() {
		return this.observacionesAdicionales;
	}

	public void setObservacionesAdicionales(String observacionesAdicionales) {
		this.observacionesAdicionales = observacionesAdicionales;
	}

	@Column(name = "Estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
