package pe.royalsystems.springerp.model.domain;
// default package
// Generated Oct 5, 2015 11:10:50 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SsHcAnamnesisAfEnfermedadId generated by hbm2java
 */
@Embeddable
public class SsHcAnamnesisAfEnfermedadId implements java.io.Serializable {

	private String unidadReplicacion;
	private long idEpisodioAtencion;
	private int idPaciente;
	private int episodioClinico;
	private int secuencia;
	private int idDiagnostico;

	public SsHcAnamnesisAfEnfermedadId() {
	}

	public SsHcAnamnesisAfEnfermedadId(String unidadReplicacion, long idEpisodioAtencion, int idPaciente,
			int episodioClinico, int secuencia, int idDiagnostico) {
		this.unidadReplicacion = unidadReplicacion;
		this.idEpisodioAtencion = idEpisodioAtencion;
		this.idPaciente = idPaciente;
		this.episodioClinico = episodioClinico;
		this.secuencia = secuencia;
		this.idDiagnostico = idDiagnostico;
	}

	@Column(name = "UnidadReplicacion", nullable = false, length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "IdEpisodioAtencion", nullable = false)
	public long getIdEpisodioAtencion() {
		return this.idEpisodioAtencion;
	}

	public void setIdEpisodioAtencion(long idEpisodioAtencion) {
		this.idEpisodioAtencion = idEpisodioAtencion;
	}

	@Column(name = "IdPaciente", nullable = false)
	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "EpisodioClinico", nullable = false)
	public int getEpisodioClinico() {
		return this.episodioClinico;
	}

	public void setEpisodioClinico(int episodioClinico) {
		this.episodioClinico = episodioClinico;
	}

	@Column(name = "Secuencia", nullable = false)
	public int getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}

	@Column(name = "IdDiagnostico", nullable = false)
	public int getIdDiagnostico() {
		return this.idDiagnostico;
	}

	public void setIdDiagnostico(int idDiagnostico) {
		this.idDiagnostico = idDiagnostico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SsHcAnamnesisAfEnfermedadId))
			return false;
		SsHcAnamnesisAfEnfermedadId castOther = (SsHcAnamnesisAfEnfermedadId) other;

		return ((this.getUnidadReplicacion() == castOther.getUnidadReplicacion())
				|| (this.getUnidadReplicacion() != null && castOther.getUnidadReplicacion() != null
						&& this.getUnidadReplicacion().equals(castOther.getUnidadReplicacion())))
				&& (this.getIdEpisodioAtencion() == castOther.getIdEpisodioAtencion())
				&& (this.getIdPaciente() == castOther.getIdPaciente())
				&& (this.getEpisodioClinico() == castOther.getEpisodioClinico())
				&& (this.getSecuencia() == castOther.getSecuencia())
				&& (this.getIdDiagnostico() == castOther.getIdDiagnostico());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUnidadReplicacion() == null ? 0 : this.getUnidadReplicacion().hashCode());
		result = 37 * result + (int) this.getIdEpisodioAtencion();
		result = 37 * result + this.getIdPaciente();
		result = 37 * result + this.getEpisodioClinico();
		result = 37 * result + this.getSecuencia();
		result = 37 * result + this.getIdDiagnostico();
		return result;
	}

}
