package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 10, 2015 12:39:11 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SySeguridadAutorizaciones generated by hbm2java
 */
@Entity
@Table(name = "SY_SeguridadAutorizaciones")
public class SySeguridadAutorizaciones extends Entidad implements java.io.Serializable {

	private SySeguridadAutorizacionesId id;
	private Character masterBrowseFlag;
	private Character masterUpdateFlag;
	private Character masterApproveFlag;
	private Character estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private Integer indAplicaSalud;
	private String accion;

	public SySeguridadAutorizaciones() {
	}

	public SySeguridadAutorizaciones(SySeguridadAutorizacionesId id) {
		this.id = id;
	}

	public SySeguridadAutorizaciones(SySeguridadAutorizacionesId id, Character masterBrowseFlag,
			Character masterUpdateFlag, Character masterApproveFlag, Character estado, String ultimoUsuario,
			Date ultimaFechaModif, Integer indAplicaSalud, String accion) {
		this.id = id;
		this.masterBrowseFlag = masterBrowseFlag;
		this.masterUpdateFlag = masterUpdateFlag;
		this.masterApproveFlag = masterApproveFlag;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.indAplicaSalud = indAplicaSalud;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "aplicacionCodigo", column = @Column(name = "AplicacionCodigo", nullable = false, length = 2) ),
			@AttributeOverride(name = "grupo", column = @Column(name = "Grupo", nullable = false, length = 20) ),
			@AttributeOverride(name = "concepto", column = @Column(name = "Concepto", nullable = false, length = 20) ),
			@AttributeOverride(name = "usuario", column = @Column(name = "Usuario", nullable = false, length = 20) ) })
	public SySeguridadAutorizacionesId getId() {
		return this.id;
	}

	public void setId(SySeguridadAutorizacionesId id) {
		this.id = id;
	}

	@Column(name = "MasterBrowseFlag", length = 1)
	public Character getMasterBrowseFlag() {
		return this.masterBrowseFlag;
	}

	public void setMasterBrowseFlag(Character masterBrowseFlag) {
		this.masterBrowseFlag = masterBrowseFlag;
	}

	@Column(name = "MasterUpdateFlag", length = 1)
	public Character getMasterUpdateFlag() {
		return this.masterUpdateFlag;
	}

	public void setMasterUpdateFlag(Character masterUpdateFlag) {
		this.masterUpdateFlag = masterUpdateFlag;
	}

	@Column(name = "MasterApproveFlag", length = 1)
	public Character getMasterApproveFlag() {
		return this.masterApproveFlag;
	}

	public void setMasterApproveFlag(Character masterApproveFlag) {
		this.masterApproveFlag = masterApproveFlag;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "IndAplicaSalud")
	public Integer getIndAplicaSalud() {
		return this.indAplicaSalud;
	}

	public void setIndAplicaSalud(Integer indAplicaSalud) {
		this.indAplicaSalud = indAplicaSalud;
	}

	@Column(name = "Accion", length = 30)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
