package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 10, 2015 12:39:11 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SySeguridadAutorizacionesId generated by hbm2java
 */
@Embeddable
public class SySeguridadAutorizacionesId implements java.io.Serializable {

	private String aplicacionCodigo;
	private String grupo;
	private String concepto;
	private String usuario;

	public SySeguridadAutorizacionesId() {
	}

	public SySeguridadAutorizacionesId(String aplicacionCodigo, String grupo, String concepto, String usuario) {
		this.aplicacionCodigo = aplicacionCodigo;
		this.grupo = grupo;
		this.concepto = concepto;
		this.usuario = usuario;
	}

	@Column(name = "AplicacionCodigo", nullable = false, length = 2)
	public String getAplicacionCodigo() {
		return this.aplicacionCodigo;
	}

	public void setAplicacionCodigo(String aplicacionCodigo) {
		this.aplicacionCodigo = aplicacionCodigo;
	}

	@Column(name = "Grupo", nullable = false, length = 20)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "Concepto", nullable = false, length = 20)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "Usuario", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SySeguridadAutorizacionesId))
			return false;
		SySeguridadAutorizacionesId castOther = (SySeguridadAutorizacionesId) other;

		return ((this.getAplicacionCodigo() == castOther.getAplicacionCodigo())
				|| (this.getAplicacionCodigo() != null && castOther.getAplicacionCodigo() != null
						&& this.getAplicacionCodigo().equals(castOther.getAplicacionCodigo())))
				&& ((this.getGrupo() == castOther.getGrupo()) || (this.getGrupo() != null
						&& castOther.getGrupo() != null && this.getGrupo().equals(castOther.getGrupo())))
				&& ((this.getConcepto() == castOther.getConcepto()) || (this.getConcepto() != null
						&& castOther.getConcepto() != null && this.getConcepto().equals(castOther.getConcepto())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
						&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAplicacionCodigo() == null ? 0 : this.getAplicacionCodigo().hashCode());
		result = 37 * result + (getGrupo() == null ? 0 : this.getGrupo().hashCode());
		result = 37 * result + (getConcepto() == null ? 0 : this.getConcepto().hashCode());
		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		return result;
	}

}
