package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 21, 2015 5:33:35 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name = "TipoPago")
public class TipoPago extends Entidad implements java.io.Serializable {

	private String tipoPago;
	private String descripcion;
	private Character restringidoFlag;
	private Character cartaFlag;
	private Character generarNumeracionFlag;
	private Character entregableFlag;
	private Character voucherSumarizadoFlag;
	private Character disponibleFeederFlag;
	private Character ingresoSimplificadoFlag;
	private Character estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private String descripcionIngles;
	private String codigoSiaf;
	private String codigoFiscal;
	private Character tipoPagoRtps;

	public TipoPago() {
	}

	public TipoPago(String tipoPago) {
		this.tipoPago = tipoPago;
	}

	public TipoPago(String tipoPago, String descripcion, Character restringidoFlag, Character cartaFlag,
			Character generarNumeracionFlag, Character entregableFlag, Character voucherSumarizadoFlag,
			Character disponibleFeederFlag, Character ingresoSimplificadoFlag, Character estado, String ultimoUsuario,
			Date ultimaFechaModif, String descripcionIngles, String codigoSiaf, String codigoFiscal,
			Character tipoPagoRtps) {
		this.tipoPago = tipoPago;
		this.descripcion = descripcion;
		this.restringidoFlag = restringidoFlag;
		this.cartaFlag = cartaFlag;
		this.generarNumeracionFlag = generarNumeracionFlag;
		this.entregableFlag = entregableFlag;
		this.voucherSumarizadoFlag = voucherSumarizadoFlag;
		this.disponibleFeederFlag = disponibleFeederFlag;
		this.ingresoSimplificadoFlag = ingresoSimplificadoFlag;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.descripcionIngles = descripcionIngles;
		this.codigoSiaf = codigoSiaf;
		this.codigoFiscal = codigoFiscal;
		this.tipoPagoRtps = tipoPagoRtps;
	}

	@Id

	@Column(name = "TipoPago", unique = true, nullable = false, length = 2)
	public String getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(String tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Column(name = "Descripcion", length = 40)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "RestringidoFlag", length = 1)
	public Character getRestringidoFlag() {
		return this.restringidoFlag;
	}

	public void setRestringidoFlag(Character restringidoFlag) {
		this.restringidoFlag = restringidoFlag;
	}

	@Column(name = "CartaFlag", length = 1)
	public Character getCartaFlag() {
		return this.cartaFlag;
	}

	public void setCartaFlag(Character cartaFlag) {
		this.cartaFlag = cartaFlag;
	}

	@Column(name = "GenerarNumeracionFlag", length = 1)
	public Character getGenerarNumeracionFlag() {
		return this.generarNumeracionFlag;
	}

	public void setGenerarNumeracionFlag(Character generarNumeracionFlag) {
		this.generarNumeracionFlag = generarNumeracionFlag;
	}

	@Column(name = "EntregableFlag", length = 1)
	public Character getEntregableFlag() {
		return this.entregableFlag;
	}

	public void setEntregableFlag(Character entregableFlag) {
		this.entregableFlag = entregableFlag;
	}

	@Column(name = "VoucherSumarizadoFlag", length = 1)
	public Character getVoucherSumarizadoFlag() {
		return this.voucherSumarizadoFlag;
	}

	public void setVoucherSumarizadoFlag(Character voucherSumarizadoFlag) {
		this.voucherSumarizadoFlag = voucherSumarizadoFlag;
	}

	@Column(name = "DisponibleFeederFlag", length = 1)
	public Character getDisponibleFeederFlag() {
		return this.disponibleFeederFlag;
	}

	public void setDisponibleFeederFlag(Character disponibleFeederFlag) {
		this.disponibleFeederFlag = disponibleFeederFlag;
	}

	@Column(name = "IngresoSimplificadoFlag", length = 1)
	public Character getIngresoSimplificadoFlag() {
		return this.ingresoSimplificadoFlag;
	}

	public void setIngresoSimplificadoFlag(Character ingresoSimplificadoFlag) {
		this.ingresoSimplificadoFlag = ingresoSimplificadoFlag;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 20)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "DescripcionIngles", length = 40)
	public String getDescripcionIngles() {
		return this.descripcionIngles;
	}

	public void setDescripcionIngles(String descripcionIngles) {
		this.descripcionIngles = descripcionIngles;
	}

	@Column(name = "CodigoSIAF", length = 3)
	public String getCodigoSiaf() {
		return this.codigoSiaf;
	}

	public void setCodigoSiaf(String codigoSiaf) {
		this.codigoSiaf = codigoSiaf;
	}

	@Column(name = "CodigoFiscal", length = 3)
	public String getCodigoFiscal() {
		return this.codigoFiscal;
	}

	public void setCodigoFiscal(String codigoFiscal) {
		this.codigoFiscal = codigoFiscal;
	}

	@Column(name = "TipoPagoRTPS", length = 1)
	public Character getTipoPagoRtps() {
		return this.tipoPagoRtps;
	}

	public void setTipoPagoRtps(Character tipoPagoRtps) {
		this.tipoPagoRtps = tipoPagoRtps;
	}

}
