package pe.royalsystems.springerp.model.domain;

//default package
//Generated Sep 10, 2015 3:49:37 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* UnidadesMast generated by hbm2java
*/
@Entity
@Table(name = "UnidadesMast")
public class UnidadesMast extends Entidad implements java.io.Serializable {

	private String unidadCodigo;
	private String descripcionCorta;
	private String descripcionExtranjera;
	private Character unidadTipo;
	private Integer numeroDecimales;
	private Character estado;
	private Date ultimaFechaModif;
	private String ultimoUsuario;
	private int idUnidadMedida;
	private Integer indicadorMedidaBase;
	private BigDecimal factorConversion;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private Integer indAfectocalculocantidad;
	private String codigoFiscal;
	private String accion;

	public UnidadesMast() {
	}

	public UnidadesMast(String unidadCodigo, String descripcionCorta, int idUnidadMedida) {
		this.unidadCodigo = unidadCodigo;
		this.descripcionCorta = descripcionCorta;
		this.idUnidadMedida = idUnidadMedida;
	}

	public UnidadesMast(String unidadCodigo, String descripcionCorta, String descripcionExtranjera,
			Character unidadTipo, Integer numeroDecimales, Character estado, Date ultimaFechaModif,
			String ultimoUsuario, int idUnidadMedida, Integer indicadorMedidaBase, BigDecimal factorConversion,
			String usuarioCreacion, Date fechaCreacion, Integer indAfectocalculocantidad, String codigoFiscal,
			String accion) {
		this.unidadCodigo = unidadCodigo;
		this.descripcionCorta = descripcionCorta;
		this.descripcionExtranjera = descripcionExtranjera;
		this.unidadTipo = unidadTipo;
		this.numeroDecimales = numeroDecimales;
		this.estado = estado;
		this.ultimaFechaModif = ultimaFechaModif;
		this.ultimoUsuario = ultimoUsuario;
		this.idUnidadMedida = idUnidadMedida;
		this.indicadorMedidaBase = indicadorMedidaBase;
		this.factorConversion = factorConversion;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.indAfectocalculocantidad = indAfectocalculocantidad;
		this.codigoFiscal = codigoFiscal;
		this.accion = accion;
	}

	@Id

	@Column(name = "UnidadCodigo", unique = true, nullable = false, length = 3)
	public String getUnidadCodigo() {
		return this.unidadCodigo;
	}

	public void setUnidadCodigo(String unidadCodigo) {
		this.unidadCodigo = unidadCodigo;
	}

	@Column(name = "DescripcionCorta", nullable = false, length = 20)
	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	@Column(name = "DescripcionExtranjera", length = 40)
	public String getDescripcionExtranjera() {
		return this.descripcionExtranjera;
	}

	public void setDescripcionExtranjera(String descripcionExtranjera) {
		this.descripcionExtranjera = descripcionExtranjera;
	}

	@Column(name = "UnidadTipo", length = 1)
	public Character getUnidadTipo() {
		return this.unidadTipo;
	}

	public void setUnidadTipo(Character unidadTipo) {
		this.unidadTipo = unidadTipo;
	}

	@Column(name = "NumeroDecimales")
	public Integer getNumeroDecimales() {
		return this.numeroDecimales;
	}

	public void setNumeroDecimales(Integer numeroDecimales) {
		this.numeroDecimales = numeroDecimales;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "IdUnidadMedida", nullable = false)
	public int getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(int idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	@Column(name = "IndicadorMedidaBase")
	public Integer getIndicadorMedidaBase() {
		return this.indicadorMedidaBase;
	}

	public void setIndicadorMedidaBase(Integer indicadorMedidaBase) {
		this.indicadorMedidaBase = indicadorMedidaBase;
	}

	@Column(name = "FactorConversion", precision = 16, scale = 6)
	public BigDecimal getFactorConversion() {
		return this.factorConversion;
	}

	public void setFactorConversion(BigDecimal factorConversion) {
		this.factorConversion = factorConversion;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "indAfectocalculocantidad")
	public Integer getIndAfectocalculocantidad() {
		return this.indAfectocalculocantidad;
	}

	public void setIndAfectocalculocantidad(Integer indAfectocalculocantidad) {
		this.indAfectocalculocantidad = indAfectocalculocantidad;
	}

	@Column(name = "CodigoFiscal", length = 2)
	public String getCodigoFiscal() {
		return this.codigoFiscal;
	}

	public void setCodigoFiscal(String codigoFiscal) {
		this.codigoFiscal = codigoFiscal;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
