package pe.royalsystems.springerp.model.domain;
// Generated Aug 11, 2015 5:13:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Subselect;

/**
 * VwAtencionpacienteGeneral generated by hbm2java
 */
@Entity
@Table(name = "VW_ATENCIONPACIENTE_GENERAL")
public class VwAtencionpacienteGeneral extends Entidad implements java.io.Serializable {


	private String tipoListado;
	private String citaTipo;
	private Date citaFecha;
	private Date citaHora;
	private String origen;
	private String nombreEspecialidad;
	private String tipoPacienteNombre;
	private String codigoOa;
	private Date fechaInicio;
	private String cama;
	private String tipoOrdenAtencionNombre;
	private String codigoHc;
	private String codigoHcanterior;
	private String pacienteNombre;
	private String medicoNombre;
	private int idOrdenAtencion;
	private int lineaOrdenAtencion;
	private int idHospitalizacion;
	private int lineaHospitalizacion;
	private Integer idConsultaExterna;
	private Integer idProcedimiento;
	private Integer modalidad;
	private Integer indicadorSeguro;
	private Integer idCita;
	private Integer idPaciente;
	private Integer tipoPaciente;
	private Integer tipoAtencion;
	private Integer idEspecialidad;
	private Integer idEmpresaAseguradora;
	private Integer tipoOrdenAtencion;
	private String componente;
	private String componenteNombre;
	private String compania;
	private String sucursal;
	private Integer idMedico;
	private int indicadorCirugia;
	private int indicadorExamenPrincipal;
	private String personaAnt;
	private Character sexo;
	private Date fechaNacimiento;
	private Character estadoCivil;
	private String nivelInstruccion;
	private String direccion;
	private Character tipoDocumento;
	private String documento;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombres;
	private String lugarNacimiento;
	private String codigoPostal;
	private String provincia;
	private String departamento;
	private String telefono;
	private String correoElectronico;
	private String esPaciente;
	private String esEmpresa;
	private String pais;
	private Character estadoPersona;
	private Date fechaCierreEpiClinico;
	private Integer estadoEpiClinico;
	private String unidadReplicacion;
	private String unidadReplicacionEc;
	private Long idEpisodioAtencion;
	private Integer episodioClinico;
	private Integer idEstablecimientoSalud;
	private Integer idUnidadServicio;
	private Integer idPersonalSalud;
	private Integer episodioAtencion;
	private Date fechaRegistro;
	private Date fechaAtencion;
	private Integer estadoEpiAtencion;
	private String usuarioCreacion;
	private String usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String accion;
	private String version;
	private Date fechaFin;
	private Date fechaOrden;
	private Integer comentarios;
	private Integer observaciones;
	private Integer diagnostico;
	private int contador;
	private int numeroFila;
	private int estado;

	public VwAtencionpacienteGeneral() {
	}

	public VwAtencionpacienteGeneral(String tipoListado, String origen, int idOrdenAtencion, int lineaOrdenAtencion,
			int idHospitalizacion, int lineaHospitalizacion, int indicadorCirugia, int indicadorExamenPrincipal,
			int contador, int numeroFila) {
		this.tipoListado = tipoListado;
		this.origen = origen;
		this.idOrdenAtencion = idOrdenAtencion;
		this.lineaOrdenAtencion = lineaOrdenAtencion;
		this.idHospitalizacion = idHospitalizacion;
		this.lineaHospitalizacion = lineaHospitalizacion;
		this.indicadorCirugia = indicadorCirugia;
		this.indicadorExamenPrincipal = indicadorExamenPrincipal;
		this.contador = contador;
		this.numeroFila = numeroFila;
	}

	public VwAtencionpacienteGeneral(String tipoListado, String citaTipo, Date citaFecha, Date citaHora,
			String origen, String nombreEspecialidad, String tipoPacienteNombre, String codigoOa, Date fechaInicio,
			String cama, String tipoOrdenAtencionNombre, String codigoHc, String codigoHcanterior,
			String pacienteNombre, String medicoNombre, int idOrdenAtencion, int lineaOrdenAtencion,
			int idHospitalizacion, int lineaHospitalizacion, Integer idConsultaExterna, Integer idProcedimiento,
			Integer modalidad, Integer indicadorSeguro, Integer idCita, Integer idPaciente, Integer tipoPaciente,
			Integer tipoAtencion, Integer idEspecialidad, Integer idEmpresaAseguradora, Integer tipoOrdenAtencion,
			String componente, String componenteNombre, String compania, String sucursal, Integer idMedico,
			int indicadorCirugia, int indicadorExamenPrincipal, String personaAnt, Character sexo, Date fechaNacimiento,
			Character estadoCivil, String nivelInstruccion, String direccion, Character tipoDocumento, String documento,
			String apellidoPaterno, String apellidoMaterno, String nombres, String lugarNacimiento, String codigoPostal,
			String provincia, String departamento, String telefono, String correoElectronico, String esPaciente,
			String esEmpresa, String pais, Character estadoPersona, Date fechaCierreEpiClinico,
			Integer estadoEpiClinico, String unidadReplicacion, String unidadReplicacionEc, Long idEpisodioAtencion,
			Integer episodioClinico, Integer idEstablecimientoSalud, Integer idUnidadServicio, Integer idPersonalSalud,
			Integer episodioAtencion, Date fechaRegistro, Date fechaAtencion, Integer estadoEpiAtencion,
			String usuarioCreacion, String usuarioModificacion, Date fechaCreacion, Date fechaModificacion,
			String accion, String version, Date fechaFin, Date fechaOrden, Integer comentarios, Integer observaciones,
			Integer diagnostico, int contador, int numeroFila,int estado) {
		this.tipoListado = tipoListado;
		this.citaTipo = citaTipo;
		this.citaFecha = citaFecha;
		this.citaHora = citaHora;
		this.origen = origen;
		this.nombreEspecialidad = nombreEspecialidad;
		this.tipoPacienteNombre = tipoPacienteNombre;
		this.codigoOa = codigoOa;
		this.fechaInicio = fechaInicio;
		this.cama = cama;
		this.tipoOrdenAtencionNombre = tipoOrdenAtencionNombre;
		this.codigoHc = codigoHc;
		this.codigoHcanterior = codigoHcanterior;
		this.pacienteNombre = pacienteNombre;
		this.medicoNombre = medicoNombre;
		this.idOrdenAtencion = idOrdenAtencion;
		this.lineaOrdenAtencion = lineaOrdenAtencion;
		this.idHospitalizacion = idHospitalizacion;
		this.lineaHospitalizacion = lineaHospitalizacion;
		this.idConsultaExterna = idConsultaExterna;
		this.idProcedimiento = idProcedimiento;
		this.modalidad = modalidad;
		this.indicadorSeguro = indicadorSeguro;
		this.idCita = idCita;
		this.idPaciente = idPaciente;
		this.tipoPaciente = tipoPaciente;
		this.tipoAtencion = tipoAtencion;
		this.idEspecialidad = idEspecialidad;
		this.idEmpresaAseguradora = idEmpresaAseguradora;
		this.tipoOrdenAtencion = tipoOrdenAtencion;
		this.componente = componente;
		this.componenteNombre = componenteNombre;
		this.compania = compania;
		this.sucursal = sucursal;
		this.idMedico = idMedico;
		this.indicadorCirugia = indicadorCirugia;
		this.indicadorExamenPrincipal = indicadorExamenPrincipal;
		this.personaAnt = personaAnt;
		this.sexo = sexo;
		this.fechaNacimiento = fechaNacimiento;
		this.estadoCivil = estadoCivil;
		this.nivelInstruccion = nivelInstruccion;
		this.direccion = direccion;
		this.tipoDocumento = tipoDocumento;
		this.documento = documento;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombres = nombres;
		this.lugarNacimiento = lugarNacimiento;
		this.codigoPostal = codigoPostal;
		this.provincia = provincia;
		this.departamento = departamento;
		this.telefono = telefono;
		this.correoElectronico = correoElectronico;
		this.esPaciente = esPaciente;
		this.esEmpresa = esEmpresa;
		this.pais = pais;
		this.estadoPersona = estadoPersona;
		this.fechaCierreEpiClinico = fechaCierreEpiClinico;
		this.estadoEpiClinico = estadoEpiClinico;
		this.unidadReplicacion = unidadReplicacion;
		this.unidadReplicacionEc = unidadReplicacionEc;
		this.idEpisodioAtencion = idEpisodioAtencion;
		this.episodioClinico = episodioClinico;
		this.idEstablecimientoSalud = idEstablecimientoSalud;
		this.idUnidadServicio = idUnidadServicio;
		this.idPersonalSalud = idPersonalSalud;
		this.episodioAtencion = episodioAtencion;
		this.fechaRegistro = fechaRegistro;
		this.fechaAtencion = fechaAtencion;
		this.estadoEpiAtencion = estadoEpiAtencion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.accion = accion;
		this.version = version;
		this.fechaFin = fechaFin;
		this.fechaOrden = fechaOrden;
		this.comentarios = comentarios;
		this.observaciones = observaciones;
		this.diagnostico = diagnostico;
		this.contador = contador;
		this.numeroFila = numeroFila;
		this.estado = estado;
	}

	@Column(name = "tipoListado", nullable = false, length = 21)
	public String getTipoListado() {
		return this.tipoListado;
	}

	public void setTipoListado(String tipoListado) {
		this.tipoListado = tipoListado;
	}

	@Column(name = "CitaTipo", length = 9)
	public String getCitaTipo() {
		return this.citaTipo;
	}

	public void setCitaTipo(String citaTipo) {
		this.citaTipo = citaTipo;
	}

	@Column(name = "CitaFecha", length = 23)
	public Date getCitaFecha() {
		return this.citaFecha;
	}

	public void setCitaFecha(Date citaFecha) {
		this.citaFecha = citaFecha;
	}

	@Column(name = "CitaHora", length = 23)
	public Date getCitaHora() {
		return this.citaHora;
	}

	public void setCitaHora(Date citaHora) {
		this.citaHora = citaHora;
	}

	@Column(name = "Origen", nullable = false, length = 13)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "NombreEspecialidad", length = 80)
	public String getNombreEspecialidad() {
		return this.nombreEspecialidad;
	}

	public void setNombreEspecialidad(String nombreEspecialidad) {
		this.nombreEspecialidad = nombreEspecialidad;
	}

	@Column(name = "TipoPacienteNombre", length = 250)
	public String getTipoPacienteNombre() {
		return this.tipoPacienteNombre;
	}

	public void setTipoPacienteNombre(String tipoPacienteNombre) {
		this.tipoPacienteNombre = tipoPacienteNombre;
	}

	@Column(name = "CodigoOA", length = 15)
	public String getCodigoOa() {
		return this.codigoOa;
	}

	public void setCodigoOa(String codigoOa) {
		this.codigoOa = codigoOa;
	}

	@Column(name = "FechaInicio", length = 23)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "Cama", length = 150)
	public String getCama() {
		return this.cama;
	}

	public void setCama(String cama) {
		this.cama = cama;
	}

	@Column(name = "TipoOrdenAtencionNombre", length = 250)
	public String getTipoOrdenAtencionNombre() {
		return this.tipoOrdenAtencionNombre;
	}

	public void setTipoOrdenAtencionNombre(String tipoOrdenAtencionNombre) {
		this.tipoOrdenAtencionNombre = tipoOrdenAtencionNombre;
	}

	@Column(name = "CodigoHC", length = 15)
	public String getCodigoHc() {
		return this.codigoHc;
	}

	public void setCodigoHc(String codigoHc) {
		this.codigoHc = codigoHc;
	}

	@Column(name = "CodigoHCAnterior", length = 15)
	public String getCodigoHcanterior() {
		return this.codigoHcanterior;
	}

	public void setCodigoHcanterior(String codigoHcanterior) {
		this.codigoHcanterior = codigoHcanterior;
	}

	@Column(name = "PacienteNombre", length = 100)
	public String getPacienteNombre() {
		return this.pacienteNombre;
	}

	public void setPacienteNombre(String pacienteNombre) {
		this.pacienteNombre = pacienteNombre;
	}

	@Column(name = "MedicoNombre", length = 100)
	public String getMedicoNombre() {
		return this.medicoNombre;
	}

	public void setMedicoNombre(String medicoNombre) {
		this.medicoNombre = medicoNombre;
	}

	@Id
	@Column(name = "IdOrdenAtencion", nullable = false)
	public int getIdOrdenAtencion() {
		return this.idOrdenAtencion;
	}

	public void setIdOrdenAtencion(int idOrdenAtencion) {
		this.idOrdenAtencion = idOrdenAtencion;
	}

	@Column(name = "LineaOrdenAtencion", nullable = false)
	public int getLineaOrdenAtencion() {
		return this.lineaOrdenAtencion;
	}

	public void setLineaOrdenAtencion(int lineaOrdenAtencion) {
		this.lineaOrdenAtencion = lineaOrdenAtencion;
	}

	@Column(name = "IdHospitalizacion", nullable = false)
	public int getIdHospitalizacion() {
		return this.idHospitalizacion;
	}

	public void setIdHospitalizacion(int idHospitalizacion) {
		this.idHospitalizacion = idHospitalizacion;
	}

	@Column(name = "LineaHospitalizacion", nullable = false)
	public int getLineaHospitalizacion() {
		return this.lineaHospitalizacion;
	}

	public void setLineaHospitalizacion(int lineaHospitalizacion) {
		this.lineaHospitalizacion = lineaHospitalizacion;
	}

	@Column(name = "IdConsultaExterna")
	public Integer getIdConsultaExterna() {
		return this.idConsultaExterna;
	}

	public void setIdConsultaExterna(Integer idConsultaExterna) {
		this.idConsultaExterna = idConsultaExterna;
	}

	@Column(name = "IdProcedimiento")
	public Integer getIdProcedimiento() {
		return this.idProcedimiento;
	}

	public void setIdProcedimiento(Integer idProcedimiento) {
		this.idProcedimiento = idProcedimiento;
	}

	@Column(name = "Modalidad")
	public Integer getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(Integer modalidad) {
		this.modalidad = modalidad;
	}

	@Column(name = "IndicadorSeguro")
	public Integer getIndicadorSeguro() {
		return this.indicadorSeguro;
	}

	public void setIndicadorSeguro(Integer indicadorSeguro) {
		this.indicadorSeguro = indicadorSeguro;
	}

	@Column(name = "IdCita")
	public Integer getIdCita() {
		return this.idCita;
	}

	public void setIdCita(Integer idCita) {
		this.idCita = idCita;
	}

	@Column(name = "IdPaciente")
	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "TipoPaciente")
	public Integer getTipoPaciente() {
		return this.tipoPaciente;
	}

	public void setTipoPaciente(Integer tipoPaciente) {
		this.tipoPaciente = tipoPaciente;
	}

	@Column(name = "TipoAtencion")
	public Integer getTipoAtencion() {
		return this.tipoAtencion;
	}

	public void setTipoAtencion(Integer tipoAtencion) {
		this.tipoAtencion = tipoAtencion;
	}

	@Column(name = "IdEspecialidad")
	public Integer getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(Integer idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	@Column(name = "IdEmpresaAseguradora")
	public Integer getIdEmpresaAseguradora() {
		return this.idEmpresaAseguradora;
	}

	public void setIdEmpresaAseguradora(Integer idEmpresaAseguradora) {
		this.idEmpresaAseguradora = idEmpresaAseguradora;
	}

	@Column(name = "TipoOrdenAtencion")
	public Integer getTipoOrdenAtencion() {
		return this.tipoOrdenAtencion;
	}

	public void setTipoOrdenAtencion(Integer tipoOrdenAtencion) {
		this.tipoOrdenAtencion = tipoOrdenAtencion;
	}

	@Column(name = "Componente", length = 25)
	public String getComponente() {
		return this.componente;
	}

	public void setComponente(String componente) {
		this.componente = componente;
	}

	@Column(name = "ComponenteNombre", length = 250)
	public String getComponenteNombre() {
		return this.componenteNombre;
	}

	public void setComponenteNombre(String componenteNombre) {
		this.componenteNombre = componenteNombre;
	}

	@Column(name = "Compania", length = 15)
	public String getCompania() {
		return this.compania;
	}

	public void setCompania(String compania) {
		this.compania = compania;
	}

	@Column(name = "Sucursal", length = 15)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "IdMedico")
	public Integer getIdMedico() {
		return this.idMedico;
	}

	public void setIdMedico(Integer idMedico) {
		this.idMedico = idMedico;
	}

	@Column(name = "IndicadorCirugia", nullable = false)
	public int getIndicadorCirugia() {
		return this.indicadorCirugia;
	}

	public void setIndicadorCirugia(int indicadorCirugia) {
		this.indicadorCirugia = indicadorCirugia;
	}

	@Column(name = "IndicadorExamenPrincipal", nullable = false)
	public int getIndicadorExamenPrincipal() {
		return this.indicadorExamenPrincipal;
	}

	public void setIndicadorExamenPrincipal(int indicadorExamenPrincipal) {
		this.indicadorExamenPrincipal = indicadorExamenPrincipal;
	}

	@Column(name = "PersonaAnt", length = 15)
	public String getPersonaAnt() {
		return this.personaAnt;
	}

	public void setPersonaAnt(String personaAnt) {
		this.personaAnt = personaAnt;
	}

	@Column(name = "sexo", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	@Column(name = "FechaNacimiento", length = 23)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "EstadoCivil", length = 1)
	public Character getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(Character estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "NivelInstruccion", length = 3)
	public String getNivelInstruccion() {
		return this.nivelInstruccion;
	}

	public void setNivelInstruccion(String nivelInstruccion) {
		this.nivelInstruccion = nivelInstruccion;
	}

	@Column(name = "Direccion", length = 190)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TipoDocumento", length = 1)
	public Character getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(Character tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "Documento", length = 20)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "ApellidoPaterno", length = 40)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "ApellidoMaterno", length = 40)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "Nombres", length = 40)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "LugarNacimiento")
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "CodigoPostal", length = 3)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "Provincia", length = 3)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "Departamento", length = 3)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "Telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "CorreoElectronico", length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "EsPaciente", length = 1)
	public String getEsPaciente() {
		return this.esPaciente;
	}

	public void setEsPaciente(String esPaciente) {
		this.esPaciente = esPaciente;
	}

	@Column(name = "EsEmpresa", length = 1)
	public String getEsEmpresa() {
		return this.esEmpresa;
	}

	public void setEsEmpresa(String esEmpresa) {
		this.esEmpresa = esEmpresa;
	}

	@Column(name = "Pais", length = 4)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "EstadoPersona", length = 1)
	public Character getEstadoPersona() {
		return this.estadoPersona;
	}

	public void setEstadoPersona(Character estadoPersona) {
		this.estadoPersona = estadoPersona;
	}

	@Column(name = "FechaCierreEpiClinico", length = 23)
	public Date getFechaCierreEpiClinico() {
		return this.fechaCierreEpiClinico;
	}

	public void setFechaCierreEpiClinico(Date fechaCierreEpiClinico) {
		this.fechaCierreEpiClinico = fechaCierreEpiClinico;
	}

	@Column(name = "EstadoEpiClinico")
	public Integer getEstadoEpiClinico() {
		return this.estadoEpiClinico;
	}

	public void setEstadoEpiClinico(Integer estadoEpiClinico) {
		this.estadoEpiClinico = estadoEpiClinico;
	}

	@Column(name = "UnidadReplicacion", length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "UnidadReplicacionEC", length = 4)
	public String getUnidadReplicacionEc() {
		return this.unidadReplicacionEc;
	}

	public void setUnidadReplicacionEc(String unidadReplicacionEc) {
		this.unidadReplicacionEc = unidadReplicacionEc;
	}

	@Column(name = "IdEpisodioAtencion")
	public Long getIdEpisodioAtencion() {
		return this.idEpisodioAtencion;
	}

	public void setIdEpisodioAtencion(Long idEpisodioAtencion) {
		this.idEpisodioAtencion = idEpisodioAtencion;
	}

	@Column(name = "EpisodioClinico")
	public Integer getEpisodioClinico() {
		return this.episodioClinico;
	}

	public void setEpisodioClinico(Integer episodioClinico) {
		this.episodioClinico = episodioClinico;
	}

	@Column(name = "IdEstablecimientoSalud")
	public Integer getIdEstablecimientoSalud() {
		return this.idEstablecimientoSalud;
	}

	public void setIdEstablecimientoSalud(Integer idEstablecimientoSalud) {
		this.idEstablecimientoSalud = idEstablecimientoSalud;
	}

	@Column(name = "IdUnidadServicio")
	public Integer getIdUnidadServicio() {
		return this.idUnidadServicio;
	}

	public void setIdUnidadServicio(Integer idUnidadServicio) {
		this.idUnidadServicio = idUnidadServicio;
	}

	@Column(name = "IdPersonalSalud")
	public Integer getIdPersonalSalud() {
		return this.idPersonalSalud;
	}

	public void setIdPersonalSalud(Integer idPersonalSalud) {
		this.idPersonalSalud = idPersonalSalud;
	}

	@Column(name = "EpisodioAtencion")
	public Integer getEpisodioAtencion() {
		return this.episodioAtencion;
	}

	public void setEpisodioAtencion(Integer episodioAtencion) {
		this.episodioAtencion = episodioAtencion;
	}

	@Column(name = "FechaRegistro", length = 23)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "FechaAtencion", length = 23)
	public Date getFechaAtencion() {
		return this.fechaAtencion;
	}

	public void setFechaAtencion(Date fechaAtencion) {
		this.fechaAtencion = fechaAtencion;
	}

	@Column(name = "EstadoEpiAtencion")
	public Integer getEstadoEpiAtencion() {
		return this.estadoEpiAtencion;
	}

	public void setEstadoEpiAtencion(Integer estadoEpiAtencion) {
		this.estadoEpiAtencion = estadoEpiAtencion;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "UsuarioModificacion", length = 25)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "FechaModificacion", length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "Version", length = 25)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "FechaFin", length = 23)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "FechaOrden", length = 23)
	public Date getFechaOrden() {
		return this.fechaOrden;
	}

	public void setFechaOrden(Date fechaOrden) {
		this.fechaOrden = fechaOrden;
	}

	@Column(name = "Comentarios")
	public Integer getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(Integer comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "Observaciones")
	public Integer getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(Integer observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "Diagnostico")
	public Integer getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(Integer diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Column(name = "Contador", nullable = false)
	public int getContador() {
		return this.contador;
	}

	public void setContador(int contador) {
		this.contador = contador;
	}

	@Column(name = "NumeroFila", nullable = false)
	public int getNumeroFila() {
		return this.numeroFila;
	}

	public void setNumeroFila(int numeroFila) {
		this.numeroFila = numeroFila;
	}

	public int getEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

}
