package pe.royalsystems.springerp.model.domain;
// default package
// Generated Sep 4, 2015 10:14:22 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwPersonapacienteId generated by hbm2java
 */
@Entity
@Table(name = "VW_PERSONAPACIENTE")
public class VwPersonapaciente extends Entidad implements java.io.Serializable {

	private Integer persona;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombreCompleto;
	private String tipoDocumento;
	private String documento;
	private String codigoBarras;
	private String esCliente;
	private String esEmpleado;
	private String esOtro;
	private String tipoPersona;
	private String esProveedor;
	private Date fechaNacimiento;
	private String ciudadNacimiento;
	private String sexo;
	private String nacionalidad;
	private String estadoCivil;
	private String nivelInstruccion;
	private String direccion;
	private String codigoPostal;
	private String provincia;
	private String departamento;
	private String telefono;
	private String documentoFiscal;
	private String documentoIdentidad;
	private String accion;
	private Integer edad;
	private String rangoEtario;
	private Integer tipoMedico;
	private Integer correcion;
	private String esPaciente;
	private String esEmpresa;
	private String pais;
	private String flagActualizacion;
	private String cuentaMonedaLocalTmp;
	private String cuentaMonedaExtranjeraTmp;
	private String correlativoSctr;
	private String seguroDiscamec;
	private String codDiscamec;
	private Date fecIniDiscamec;
	private Date fecFinDiscamec;
	private String lugarNacimiento;
	private String celular;
	private String celularEmergencia;
	private String parentescoEmergencia;
	private String direccionReferencia;
	private Date ultimaFechaModif;
	private String tipoPersonaUsuario;
	private String ultimoUsuario;
	private String estado;
	private String direccionEmergencia;
	private String telefonoEmergencia;
	private String bancoMonedaLocal;
	private String tipoCuentaLocal;
	private String cuentaMonedaLocal;
	private String bancoMonedaExtranjera;
	private String tipoCuentaExtranjera;
	private String cuentaMonedaExtranjera;
	private String correoElectronico;
	private String enfermedadGraveFlag;
	private Date ingresoFechaRegistro;
	private String ingresoAplicacionCodigo;
	private String ingresoUsuario;
	private String pymeflag;
	private String tipoPago;
	private String tipoTrabajador;
	private String religion;
	private String tipoVisa;
	private Date visaFechaInicio;
	private Date visaFechaExpiracion;
	private String codigoAfp;
	private String numeroAfp;
	private String bancoCts;
	private String tipoCuentaCts;
	private String tipoMonedaCts;
	private String numeroCuentaCts;
	private String estadoEmpleado;
	private String tipoPlanilla;
	private Date fechaIngreso;
	private Date fechaUltimaPlanilla;
	private String tipoContrato;
	private Date fechaInicioContrato;
	private Date fechaFinContrato;
	private Date fechaCese;
	private String razonCese;
	private Integer contratista;
	private String companiaSocio;
	private String centroCostos;
	private String afe;
	private String deptoOrganizacion;
	private Integer tipoHorario;
	private String gradoSalario;
	private String cargo;
	private String posicion;
	private String nivelAcceso;
	private String flagIpssvida;
	private String flagSindicato;
	private String flagAccTrabajo;
	private String flagCooperativa;
	private String flagRetencionJudicial;
	private String flagReingresos;
	private String flagComision;
	private String flagImpuestoRenta;
	private BigDecimal sueldoActualLocal;
	private BigDecimal sueldoActualDolar;
	private BigDecimal sueldoAnteriorLocal;
	private BigDecimal sueldoAnteriorDolar;
	private String monedaPago;
	private String tarjetaCredito;
	private Integer motivoCese;
	private String departamentoOrganizacional;
	private String departamentoOperacional;
	private Integer perfil;
	private String nivelSalario;
	private Date fechaLiquidacion;
	private Date fechaReingreso;
	private String unidadReplicacion;
	private Integer codigoCargo;
	private Date ultimaFechaPagoVacacion;
	private Integer gerencia;
	private Integer subGerencia;
	private Double redondeoAcuenta;
	private Integer plantillaConcepto;
	private String ruccentroAsistenciaSocial;
	private String sucursal;
	private String actividad;
	private Integer cliente;
	private Integer clienteUnidad;
	private Integer empleadoNivel;
	private Long tipoPuesto;
	private String usuario;
	private String usuarioperfil;
	private Integer personausuario;
	private String clave;
	private String expirarpasswordflag;
	private Date fechaexpiracion;
	private Date ultimologin;
	private Integer paciente;
	private Integer tipoPaciente;
	private String raza;
	private String areaLaboral;
	private String ocupacion;
	private String codigoHc;
	private String codigoHcanterior;
	private String codigoHcsecundario;
	private String tipoAlmacenamiento;
	private String tipoHistoria;
	private String tipoSituacion;
	private Integer idUbicacion;
	private String lugarProcedencia;
	private String rutaFoto;
	private Integer estadoPaciente;
	private Integer numeroFile;
	private String servicio;
	private String observacion;
	private Integer indicadorAsistencia;
	private Integer cantidadAsistencia;
	private Integer ubicacionHhcc;
	private Integer indicadorMigradoSiteds;
	private String numeroCaja;
	private Integer indicadorCodigoBarras;
	private Integer idpacienteOk;
	private String codigoAsegurado;
	private Integer numeroPoliza;
	private Integer numeroCertificado;
	private String codigoProducto;
	private String codigoPlan;
	private Integer tipoParentesco;
	private String codigoBeneficio;
	private Integer situacion;
	private Integer tomoActual;
	private Integer indicadorHistoriaFisica;
	private String descripcionHistoria;
	private String personaAnt;
	private String nombres;
	private String busqueda;

	public VwPersonapaciente() {
	}

	public VwPersonapaciente(Integer persona, String tipoDocumento, String documento) {
		this.persona = persona;
		this.tipoDocumento = tipoDocumento;
		this.documento = documento;
	}

	public VwPersonapaciente(Integer persona, String apellidoPaterno, String apellidoMaterno, String nombreCompleto,
			String tipoDocumento, String documento, String codigoBarras, String esCliente, String esEmpleado,
			String esOtro, String tipoPersona, String esProveedor, Date fechaNacimiento,
			String ciudadNacimiento, String sexo, String nacionalidad, String estadoCivil,
			String nivelInstruccion, String direccion, String codigoPostal, String provincia, String departamento,
			String telefono, String documentoFiscal, String documentoIdentidad, String accion, Integer edad,
			String rangoEtario, Integer tipoMedico, Integer correcion, String esPaciente, String esEmpresa, String pais,
			String flagActualizacion, String cuentaMonedaLocalTmp, String cuentaMonedaExtranjeraTmp,
			String correlativoSctr, String seguroDiscamec, String codDiscamec, Date fecIniDiscamec,
			Date fecFinDiscamec, String lugarNacimiento, String celular, String celularEmergencia,
			String parentescoEmergencia, String direccionReferencia, Date ultimaFechaModif, String tipoPersonaUsuario,
			String ultimoUsuario, String estado, String direccionEmergencia, String telefonoEmergencia,
			String bancoMonedaLocal, String tipoCuentaLocal, String cuentaMonedaLocal, String bancoMonedaExtranjera,
			String tipoCuentaExtranjera, String cuentaMonedaExtranjera, String correoElectronico,
			String enfermedadGraveFlag, Date ingresoFechaRegistro, String ingresoAplicacionCodigo,
			String ingresoUsuario, String pymeflag, String tipoPago, String tipoTrabajador, String religion,
			String tipoVisa, Date visaFechaInicio, Date visaFechaExpiracion, String codigoAfp, String numeroAfp,
			String bancoCts, String tipoCuentaCts, String tipoMonedaCts, String numeroCuentaCts,
			String estadoEmpleado, String tipoPlanilla, Date fechaIngreso, Date fechaUltimaPlanilla,
			String tipoContrato, Date fechaInicioContrato, Date fechaFinContrato, Date fechaCese, String razonCese,
			Integer contratista, String companiaSocio, String centroCostos, String afe, String deptoOrganizacion,
			Integer tipoHorario, String gradoSalario, String cargo, String posicion, String nivelAcceso,
			String flagIpssvida, String flagSindicato, String flagAccTrabajo, String flagCooperativa,
			String flagRetencionJudicial, String flagReingresos, String flagComision,
			String flagImpuestoRenta, BigDecimal sueldoActualLocal, BigDecimal sueldoActualDolar,
			BigDecimal sueldoAnteriorLocal, BigDecimal sueldoAnteriorDolar, String monedaPago, String tarjetaCredito,
			Integer motivoCese, String departamentoOrganizacional, String departamentoOperacional, Integer perfil,
			String nivelSalario, Date fechaLiquidacion, Date fechaReingreso, String unidadReplicacion,
			Integer codigoCargo, Date ultimaFechaPagoVacacion, Integer gerencia, Integer subGerencia,
			Double redondeoAcuenta, Integer plantillaConcepto, String ruccentroAsistenciaSocial, String sucursal,
			String actividad, Integer cliente, Integer clienteUnidad, Integer empleadoNivel, Long tipoPuesto,
			String usuario, String usuarioperfil, Integer personausuario, String clave, String expirarpasswordflag,
			Date fechaexpiracion, Date ultimologin, Integer paciente, Integer tipoPaciente, String raza,
			String areaLaboral, String ocupacion, String codigoHc, String codigoHcanterior, String codigoHcsecundario,
			String tipoAlmacenamiento, String tipoHistoria, String tipoSituacion, Integer idUbicacion,
			String lugarProcedencia, String rutaFoto, Integer estadoPaciente, Integer numeroFile, String servicio,
			String observacion, Integer indicadorAsistencia, Integer cantidadAsistencia, Integer ubicacionHhcc,
			Integer indicadorMigradoSiteds, String numeroCaja, Integer indicadorCodigoBarras, Integer idpacienteOk,
			String codigoAsegurado, Integer numeroPoliza, Integer numeroCertificado, String codigoProducto,
			String codigoPlan, Integer tipoParentesco, String codigoBeneficio, Integer situacion, Integer tomoActual,
			Integer indicadorHistoriaFisica, String descripcionHistoria, String personaAnt, String nombres,
			String busqueda) {
		this.persona = persona;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombreCompleto = nombreCompleto;
		this.tipoDocumento = tipoDocumento;
		this.documento = documento;
		this.codigoBarras = codigoBarras;
		this.esCliente = esCliente;
		this.esEmpleado = esEmpleado;
		this.esOtro = esOtro;
		this.tipoPersona = tipoPersona;
		this.esProveedor = esProveedor;
		this.fechaNacimiento = fechaNacimiento;
		this.ciudadNacimiento = ciudadNacimiento;
		this.sexo = sexo;
		this.nacionalidad = nacionalidad;
		this.estadoCivil = estadoCivil;
		this.nivelInstruccion = nivelInstruccion;
		this.direccion = direccion;
		this.codigoPostal = codigoPostal;
		this.provincia = provincia;
		this.departamento = departamento;
		this.telefono = telefono;
		this.documentoFiscal = documentoFiscal;
		this.documentoIdentidad = documentoIdentidad;
		this.accion = accion;
		this.edad = edad;
		this.rangoEtario = rangoEtario;
		this.tipoMedico = tipoMedico;
		this.correcion = correcion;
		this.esPaciente = esPaciente;
		this.esEmpresa = esEmpresa;
		this.pais = pais;
		this.flagActualizacion = flagActualizacion;
		this.cuentaMonedaLocalTmp = cuentaMonedaLocalTmp;
		this.cuentaMonedaExtranjeraTmp = cuentaMonedaExtranjeraTmp;
		this.correlativoSctr = correlativoSctr;
		this.seguroDiscamec = seguroDiscamec;
		this.codDiscamec = codDiscamec;
		this.fecIniDiscamec = fecIniDiscamec;
		this.fecFinDiscamec = fecFinDiscamec;
		this.lugarNacimiento = lugarNacimiento;
		this.celular = celular;
		this.celularEmergencia = celularEmergencia;
		this.parentescoEmergencia = parentescoEmergencia;
		this.direccionReferencia = direccionReferencia;
		this.ultimaFechaModif = ultimaFechaModif;
		this.tipoPersonaUsuario = tipoPersonaUsuario;
		this.ultimoUsuario = ultimoUsuario;
		this.estado = estado;
		this.direccionEmergencia = direccionEmergencia;
		this.telefonoEmergencia = telefonoEmergencia;
		this.bancoMonedaLocal = bancoMonedaLocal;
		this.tipoCuentaLocal = tipoCuentaLocal;
		this.cuentaMonedaLocal = cuentaMonedaLocal;
		this.bancoMonedaExtranjera = bancoMonedaExtranjera;
		this.tipoCuentaExtranjera = tipoCuentaExtranjera;
		this.cuentaMonedaExtranjera = cuentaMonedaExtranjera;
		this.correoElectronico = correoElectronico;
		this.enfermedadGraveFlag = enfermedadGraveFlag;
		this.ingresoFechaRegistro = ingresoFechaRegistro;
		this.ingresoAplicacionCodigo = ingresoAplicacionCodigo;
		this.ingresoUsuario = ingresoUsuario;
		this.pymeflag = pymeflag;
		this.tipoPago = tipoPago;
		this.tipoTrabajador = tipoTrabajador;
		this.religion = religion;
		this.tipoVisa = tipoVisa;
		this.visaFechaInicio = visaFechaInicio;
		this.visaFechaExpiracion = visaFechaExpiracion;
		this.codigoAfp = codigoAfp;
		this.numeroAfp = numeroAfp;
		this.bancoCts = bancoCts;
		this.tipoCuentaCts = tipoCuentaCts;
		this.tipoMonedaCts = tipoMonedaCts;
		this.numeroCuentaCts = numeroCuentaCts;
		this.estadoEmpleado = estadoEmpleado;
		this.tipoPlanilla = tipoPlanilla;
		this.fechaIngreso = fechaIngreso;
		this.fechaUltimaPlanilla = fechaUltimaPlanilla;
		this.tipoContrato = tipoContrato;
		this.fechaInicioContrato = fechaInicioContrato;
		this.fechaFinContrato = fechaFinContrato;
		this.fechaCese = fechaCese;
		this.razonCese = razonCese;
		this.contratista = contratista;
		this.companiaSocio = companiaSocio;
		this.centroCostos = centroCostos;
		this.afe = afe;
		this.deptoOrganizacion = deptoOrganizacion;
		this.tipoHorario = tipoHorario;
		this.gradoSalario = gradoSalario;
		this.cargo = cargo;
		this.posicion = posicion;
		this.nivelAcceso = nivelAcceso;
		this.flagIpssvida = flagIpssvida;
		this.flagSindicato = flagSindicato;
		this.flagAccTrabajo = flagAccTrabajo;
		this.flagCooperativa = flagCooperativa;
		this.flagRetencionJudicial = flagRetencionJudicial;
		this.flagReingresos = flagReingresos;
		this.flagComision = flagComision;
		this.flagImpuestoRenta = flagImpuestoRenta;
		this.sueldoActualLocal = sueldoActualLocal;
		this.sueldoActualDolar = sueldoActualDolar;
		this.sueldoAnteriorLocal = sueldoAnteriorLocal;
		this.sueldoAnteriorDolar = sueldoAnteriorDolar;
		this.monedaPago = monedaPago;
		this.tarjetaCredito = tarjetaCredito;
		this.motivoCese = motivoCese;
		this.departamentoOrganizacional = departamentoOrganizacional;
		this.departamentoOperacional = departamentoOperacional;
		this.perfil = perfil;
		this.nivelSalario = nivelSalario;
		this.fechaLiquidacion = fechaLiquidacion;
		this.fechaReingreso = fechaReingreso;
		this.unidadReplicacion = unidadReplicacion;
		this.codigoCargo = codigoCargo;
		this.ultimaFechaPagoVacacion = ultimaFechaPagoVacacion;
		this.gerencia = gerencia;
		this.subGerencia = subGerencia;
		this.redondeoAcuenta = redondeoAcuenta;
		this.plantillaConcepto = plantillaConcepto;
		this.ruccentroAsistenciaSocial = ruccentroAsistenciaSocial;
		this.sucursal = sucursal;
		this.actividad = actividad;
		this.cliente = cliente;
		this.clienteUnidad = clienteUnidad;
		this.empleadoNivel = empleadoNivel;
		this.tipoPuesto = tipoPuesto;
		this.usuario = usuario;
		this.usuarioperfil = usuarioperfil;
		this.personausuario = personausuario;
		this.clave = clave;
		this.expirarpasswordflag = expirarpasswordflag;
		this.fechaexpiracion = fechaexpiracion;
		this.ultimologin = ultimologin;
		this.paciente = paciente;
		this.tipoPaciente = tipoPaciente;
		this.raza = raza;
		this.areaLaboral = areaLaboral;
		this.ocupacion = ocupacion;
		this.codigoHc = codigoHc;
		this.codigoHcanterior = codigoHcanterior;
		this.codigoHcsecundario = codigoHcsecundario;
		this.tipoAlmacenamiento = tipoAlmacenamiento;
		this.tipoHistoria = tipoHistoria;
		this.tipoSituacion = tipoSituacion;
		this.idUbicacion = idUbicacion;
		this.lugarProcedencia = lugarProcedencia;
		this.rutaFoto = rutaFoto;
		this.estadoPaciente = estadoPaciente;
		this.numeroFile = numeroFile;
		this.servicio = servicio;
		this.observacion = observacion;
		this.indicadorAsistencia = indicadorAsistencia;
		this.cantidadAsistencia = cantidadAsistencia;
		this.ubicacionHhcc = ubicacionHhcc;
		this.indicadorMigradoSiteds = indicadorMigradoSiteds;
		this.numeroCaja = numeroCaja;
		this.indicadorCodigoBarras = indicadorCodigoBarras;
		this.idpacienteOk = idpacienteOk;
		this.codigoAsegurado = codigoAsegurado;
		this.numeroPoliza = numeroPoliza;
		this.numeroCertificado = numeroCertificado;
		this.codigoProducto = codigoProducto;
		this.codigoPlan = codigoPlan;
		this.tipoParentesco = tipoParentesco;
		this.codigoBeneficio = codigoBeneficio;
		this.situacion = situacion;
		this.tomoActual = tomoActual;
		this.indicadorHistoriaFisica = indicadorHistoriaFisica;
		this.descripcionHistoria = descripcionHistoria;
		this.personaAnt = personaAnt;
		this.nombres = nombres;
		this.busqueda = busqueda;
	}

	@Id
	@Column(name = "Persona", nullable = false)
	public Integer getPersona() {
		return this.persona;
	}

	public void setPersona(Integer persona) {
		this.persona = persona;
	}

	@Column(name = "ApellidoPaterno", length = 40)
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "ApellidoMaterno", length = 40)
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "NombreCompleto", length = 100)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@Column(name = "TipoDocumento", nullable = false, length = 1)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "Documento", nullable = false, length = 20)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "CodigoBarras", length = 18)
	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	@Column(name = "EsCliente", length = 1)
	public String getEsCliente() {
		return this.esCliente;
	}

	public void setEsCliente(String esCliente) {
		this.esCliente = esCliente;
	}

	@Column(name = "EsEmpleado", length = 1)
	public String getEsEmpleado() {
		return this.esEmpleado;
	}

	public void setEsEmpleado(String esEmpleado) {
		this.esEmpleado = esEmpleado;
	}

	@Column(name = "EsOtro", length = 1)
	public String getEsOtro() {
		return this.esOtro;
	}

	public void setEsOtro(String esOtro) {
		this.esOtro = esOtro;
	}

	@Column(name = "TipoPersona", length = 1)
	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	@Column(name = "EsProveedor", length = 1)
	public String getEsProveedor() {
		return this.esProveedor;
	}

	public void setEsProveedor(String esProveedor) {
		this.esProveedor = esProveedor;
	}

	@Column(name = "FechaNacimiento", length = 23)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "CiudadNacimiento", length = 20)
	public String getCiudadNacimiento() {
		return this.ciudadNacimiento;
	}

	public void setCiudadNacimiento(String ciudadNacimiento) {
		this.ciudadNacimiento = ciudadNacimiento;
	}

	@Column(name = "Sexo", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "Nacionalidad", length = 20)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "EstadoCivil", length = 1)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "NivelInstruccion", length = 3)
	public String getNivelInstruccion() {
		return this.nivelInstruccion;
	}

	public void setNivelInstruccion(String nivelInstruccion) {
		this.nivelInstruccion = nivelInstruccion;
	}

	@Column(name = "Direccion", length = 190)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "CodigoPostal", length = 3)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "Provincia", length = 3)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "Departamento", length = 3)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "Telefono", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "DocumentoFiscal", length = 20)
	public String getDocumentoFiscal() {
		return this.documentoFiscal;
	}

	public void setDocumentoFiscal(String documentoFiscal) {
		this.documentoFiscal = documentoFiscal;
	}

	@Column(name = "DocumentoIdentidad", length = 20)
	public String getDocumentoIdentidad() {
		return this.documentoIdentidad;
	}

	public void setDocumentoIdentidad(String documentoIdentidad) {
		this.documentoIdentidad = documentoIdentidad;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "rangoEtario", length = 10)
	public String getRangoEtario() {
		return this.rangoEtario;
	}

	public void setRangoEtario(String rangoEtario) {
		this.rangoEtario = rangoEtario;
	}

	@Column(name = "TipoMedico")
	public Integer getTipoMedico() {
		return this.tipoMedico;
	}

	public void setTipoMedico(Integer tipoMedico) {
		this.tipoMedico = tipoMedico;
	}

	@Column(name = "Correcion")
	public Integer getCorrecion() {
		return this.correcion;
	}

	public void setCorrecion(Integer correcion) {
		this.correcion = correcion;
	}

	@Column(name = "EsPaciente", length = 1)
	public String getEsPaciente() {
		return this.esPaciente;
	}

	public void setEsPaciente(String esPaciente) {
		this.esPaciente = esPaciente;
	}

	@Column(name = "EsEmpresa", length = 1)
	public String getEsEmpresa() {
		return this.esEmpresa;
	}

	public void setEsEmpresa(String esEmpresa) {
		this.esEmpresa = esEmpresa;
	}

	@Column(name = "Pais", length = 4)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "FlagActualizacion", length = 1)
	public String getFlagActualizacion() {
		return this.flagActualizacion;
	}

	public void setFlagActualizacion(String flagActualizacion) {
		this.flagActualizacion = flagActualizacion;
	}

	@Column(name = "CuentaMonedaLocal_tmp", length = 15)
	public String getCuentaMonedaLocalTmp() {
		return this.cuentaMonedaLocalTmp;
	}

	public void setCuentaMonedaLocalTmp(String cuentaMonedaLocalTmp) {
		this.cuentaMonedaLocalTmp = cuentaMonedaLocalTmp;
	}

	@Column(name = "CuentaMonedaExtranjera_tmp", length = 15)
	public String getCuentaMonedaExtranjeraTmp() {
		return this.cuentaMonedaExtranjeraTmp;
	}

	public void setCuentaMonedaExtranjeraTmp(String cuentaMonedaExtranjeraTmp) {
		this.cuentaMonedaExtranjeraTmp = cuentaMonedaExtranjeraTmp;
	}

	@Column(name = "CorrelativoSCTR", length = 3)
	public String getCorrelativoSctr() {
		return this.correlativoSctr;
	}

	public void setCorrelativoSctr(String correlativoSctr) {
		this.correlativoSctr = correlativoSctr;
	}

	@Column(name = "SeguroDiscamec", length = 1)
	public String getSeguroDiscamec() {
		return this.seguroDiscamec;
	}

	public void setSeguroDiscamec(String seguroDiscamec) {
		this.seguroDiscamec = seguroDiscamec;
	}

	@Column(name = "CodDiscamec", length = 15)
	public String getCodDiscamec() {
		return this.codDiscamec;
	}

	public void setCodDiscamec(String codDiscamec) {
		this.codDiscamec = codDiscamec;
	}

	@Column(name = "FecIniDiscamec", length = 23)
	public Date getFecIniDiscamec() {
		return this.fecIniDiscamec;
	}

	public void setFecIniDiscamec(Date fecIniDiscamec) {
		this.fecIniDiscamec = fecIniDiscamec;
	}

	@Column(name = "FecFinDiscamec", length = 23)
	public Date getFecFinDiscamec() {
		return this.fecFinDiscamec;
	}

	public void setFecFinDiscamec(Date fecFinDiscamec) {
		this.fecFinDiscamec = fecFinDiscamec;
	}

	@Column(name = "LugarNacimiento")
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "Celular", length = 15)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "CelularEmergencia", length = 15)
	public String getCelularEmergencia() {
		return this.celularEmergencia;
	}

	public void setCelularEmergencia(String celularEmergencia) {
		this.celularEmergencia = celularEmergencia;
	}

	@Column(name = "ParentescoEmergencia", length = 15)
	public String getParentescoEmergencia() {
		return this.parentescoEmergencia;
	}

	public void setParentescoEmergencia(String parentescoEmergencia) {
		this.parentescoEmergencia = parentescoEmergencia;
	}

	@Column(name = "DireccionReferencia")
	public String getDireccionReferencia() {
		return this.direccionReferencia;
	}

	public void setDireccionReferencia(String direccionReferencia) {
		this.direccionReferencia = direccionReferencia;
	}

	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "TipoPersonaUsuario", length = 3)
	public String getTipoPersonaUsuario() {
		return this.tipoPersonaUsuario;
	}

	public void setTipoPersonaUsuario(String tipoPersonaUsuario) {
		this.tipoPersonaUsuario = tipoPersonaUsuario;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "Estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "DireccionEmergencia", length = 60)
	public String getDireccionEmergencia() {
		return this.direccionEmergencia;
	}

	public void setDireccionEmergencia(String direccionEmergencia) {
		this.direccionEmergencia = direccionEmergencia;
	}

	@Column(name = "TelefonoEmergencia", length = 15)
	public String getTelefonoEmergencia() {
		return this.telefonoEmergencia;
	}

	public void setTelefonoEmergencia(String telefonoEmergencia) {
		this.telefonoEmergencia = telefonoEmergencia;
	}

	@Column(name = "BancoMonedaLocal", length = 3)
	public String getBancoMonedaLocal() {
		return this.bancoMonedaLocal;
	}

	public void setBancoMonedaLocal(String bancoMonedaLocal) {
		this.bancoMonedaLocal = bancoMonedaLocal;
	}

	@Column(name = "TipoCuentaLocal", length = 3)
	public String getTipoCuentaLocal() {
		return this.tipoCuentaLocal;
	}

	public void setTipoCuentaLocal(String tipoCuentaLocal) {
		this.tipoCuentaLocal = tipoCuentaLocal;
	}

	@Column(name = "CuentaMonedaLocal", length = 20)
	public String getCuentaMonedaLocal() {
		return this.cuentaMonedaLocal;
	}

	public void setCuentaMonedaLocal(String cuentaMonedaLocal) {
		this.cuentaMonedaLocal = cuentaMonedaLocal;
	}

	@Column(name = "BancoMonedaExtranjera", length = 3)
	public String getBancoMonedaExtranjera() {
		return this.bancoMonedaExtranjera;
	}

	public void setBancoMonedaExtranjera(String bancoMonedaExtranjera) {
		this.bancoMonedaExtranjera = bancoMonedaExtranjera;
	}

	@Column(name = "TipoCuentaExtranjera", length = 3)
	public String getTipoCuentaExtranjera() {
		return this.tipoCuentaExtranjera;
	}

	public void setTipoCuentaExtranjera(String tipoCuentaExtranjera) {
		this.tipoCuentaExtranjera = tipoCuentaExtranjera;
	}

	@Column(name = "CuentaMonedaExtranjera", length = 20)
	public String getCuentaMonedaExtranjera() {
		return this.cuentaMonedaExtranjera;
	}

	public void setCuentaMonedaExtranjera(String cuentaMonedaExtranjera) {
		this.cuentaMonedaExtranjera = cuentaMonedaExtranjera;
	}

	@Column(name = "CorreoElectronico", length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "EnfermedadGraveFlag", length = 1)
	public String getEnfermedadGraveFlag() {
		return this.enfermedadGraveFlag;
	}

	public void setEnfermedadGraveFlag(String enfermedadGraveFlag) {
		this.enfermedadGraveFlag = enfermedadGraveFlag;
	}

	@Column(name = "IngresoFechaRegistro", length = 23)
	public Date getIngresoFechaRegistro() {
		return this.ingresoFechaRegistro;
	}

	public void setIngresoFechaRegistro(Date ingresoFechaRegistro) {
		this.ingresoFechaRegistro = ingresoFechaRegistro;
	}

	@Column(name = "IngresoAplicacionCodigo", length = 2)
	public String getIngresoAplicacionCodigo() {
		return this.ingresoAplicacionCodigo;
	}

	public void setIngresoAplicacionCodigo(String ingresoAplicacionCodigo) {
		this.ingresoAplicacionCodigo = ingresoAplicacionCodigo;
	}

	@Column(name = "IngresoUsuario", length = 25)
	public String getIngresoUsuario() {
		return this.ingresoUsuario;
	}

	public void setIngresoUsuario(String ingresoUsuario) {
		this.ingresoUsuario = ingresoUsuario;
	}

	@Column(name = "PYMEFlag", length = 1)
	public String getPymeflag() {
		return this.pymeflag;
	}

	public void setPymeflag(String pymeflag) {
		this.pymeflag = pymeflag;
	}

	@Column(name = "TipoPago", length = 2)
	public String getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(String tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Column(name = "TipoTrabajador", length = 2)
	public String getTipoTrabajador() {
		return this.tipoTrabajador;
	}

	public void setTipoTrabajador(String tipoTrabajador) {
		this.tipoTrabajador = tipoTrabajador;
	}

	@Column(name = "Religion", length = 3)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "TipoVisa", length = 3)
	public String getTipoVisa() {
		return this.tipoVisa;
	}

	public void setTipoVisa(String tipoVisa) {
		this.tipoVisa = tipoVisa;
	}

	@Column(name = "VisaFechaInicio", length = 23)
	public Date getVisaFechaInicio() {
		return this.visaFechaInicio;
	}

	public void setVisaFechaInicio(Date visaFechaInicio) {
		this.visaFechaInicio = visaFechaInicio;
	}

	@Column(name = "VisaFechaExpiracion", length = 23)
	public Date getVisaFechaExpiracion() {
		return this.visaFechaExpiracion;
	}

	public void setVisaFechaExpiracion(Date visaFechaExpiracion) {
		this.visaFechaExpiracion = visaFechaExpiracion;
	}

	@Column(name = "CodigoAFP", length = 3)
	public String getCodigoAfp() {
		return this.codigoAfp;
	}

	public void setCodigoAfp(String codigoAfp) {
		this.codigoAfp = codigoAfp;
	}

	@Column(name = "NumeroAFP", length = 20)
	public String getNumeroAfp() {
		return this.numeroAfp;
	}

	public void setNumeroAfp(String numeroAfp) {
		this.numeroAfp = numeroAfp;
	}

	@Column(name = "BancoCTS", length = 3)
	public String getBancoCts() {
		return this.bancoCts;
	}

	public void setBancoCts(String bancoCts) {
		this.bancoCts = bancoCts;
	}

	@Column(name = "TipoCuentaCTS", length = 3)
	public String getTipoCuentaCts() {
		return this.tipoCuentaCts;
	}

	public void setTipoCuentaCts(String tipoCuentaCts) {
		this.tipoCuentaCts = tipoCuentaCts;
	}

	@Column(name = "TipoMonedaCTS", length = 2)
	public String getTipoMonedaCts() {
		return this.tipoMonedaCts;
	}

	public void setTipoMonedaCts(String tipoMonedaCts) {
		this.tipoMonedaCts = tipoMonedaCts;
	}

	@Column(name = "NumeroCuentaCTS", length = 20)
	public String getNumeroCuentaCts() {
		return this.numeroCuentaCts;
	}

	public void setNumeroCuentaCts(String numeroCuentaCts) {
		this.numeroCuentaCts = numeroCuentaCts;
	}

	@Column(name = "EstadoEmpleado", length = 1)
	public String getEstadoEmpleado() {
		return this.estadoEmpleado;
	}

	public void setEstadoEmpleado(String estadoEmpleado) {
		this.estadoEmpleado = estadoEmpleado;
	}

	@Column(name = "TipoPlanilla", length = 2)
	public String getTipoPlanilla() {
		return this.tipoPlanilla;
	}

	public void setTipoPlanilla(String tipoPlanilla) {
		this.tipoPlanilla = tipoPlanilla;
	}

	@Column(name = "FechaIngreso", length = 23)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "FechaUltimaPlanilla", length = 23)
	public Date getFechaUltimaPlanilla() {
		return this.fechaUltimaPlanilla;
	}

	public void setFechaUltimaPlanilla(Date fechaUltimaPlanilla) {
		this.fechaUltimaPlanilla = fechaUltimaPlanilla;
	}

	@Column(name = "TipoContrato", length = 2)
	public String getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Column(name = "FechaInicioContrato", length = 23)
	public Date getFechaInicioContrato() {
		return this.fechaInicioContrato;
	}

	public void setFechaInicioContrato(Date fechaInicioContrato) {
		this.fechaInicioContrato = fechaInicioContrato;
	}

	@Column(name = "FechaFinContrato", length = 23)
	public Date getFechaFinContrato() {
		return this.fechaFinContrato;
	}

	public void setFechaFinContrato(Date fechaFinContrato) {
		this.fechaFinContrato = fechaFinContrato;
	}

	@Column(name = "FechaCese", length = 23)
	public Date getFechaCese() {
		return this.fechaCese;
	}

	public void setFechaCese(Date fechaCese) {
		this.fechaCese = fechaCese;
	}

	@Column(name = "RazonCese", length = 30)
	public String getRazonCese() {
		return this.razonCese;
	}

	public void setRazonCese(String razonCese) {
		this.razonCese = razonCese;
	}

	@Column(name = "Contratista")
	public Integer getContratista() {
		return this.contratista;
	}

	public void setContratista(Integer contratista) {
		this.contratista = contratista;
	}

	@Column(name = "CompaniaSocio", length = 8)
	public String getCompaniaSocio() {
		return this.companiaSocio;
	}

	public void setCompaniaSocio(String companiaSocio) {
		this.companiaSocio = companiaSocio;
	}

	@Column(name = "CentroCostos", length = 10)
	public String getCentroCostos() {
		return this.centroCostos;
	}

	public void setCentroCostos(String centroCostos) {
		this.centroCostos = centroCostos;
	}

	@Column(name = "AFE", length = 15)
	public String getAfe() {
		return this.afe;
	}

	public void setAfe(String afe) {
		this.afe = afe;
	}

	@Column(name = "DeptoOrganizacion", length = 3)
	public String getDeptoOrganizacion() {
		return this.deptoOrganizacion;
	}

	public void setDeptoOrganizacion(String deptoOrganizacion) {
		this.deptoOrganizacion = deptoOrganizacion;
	}

	@Column(name = "TipoHorario")
	public Integer getTipoHorario() {
		return this.tipoHorario;
	}

	public void setTipoHorario(Integer tipoHorario) {
		this.tipoHorario = tipoHorario;
	}

	@Column(name = "GradoSalario", length = 3)
	public String getGradoSalario() {
		return this.gradoSalario;
	}

	public void setGradoSalario(String gradoSalario) {
		this.gradoSalario = gradoSalario;
	}

	@Column(name = "Cargo", length = 3)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "Posicion", length = 6)
	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	@Column(name = "NivelAcceso", length = 3)
	public String getNivelAcceso() {
		return this.nivelAcceso;
	}

	public void setNivelAcceso(String nivelAcceso) {
		this.nivelAcceso = nivelAcceso;
	}

	@Column(name = "FlagIPSSVIDA", length = 1)
	public String getFlagIpssvida() {
		return this.flagIpssvida;
	}

	public void setFlagIpssvida(String flagIpssvida) {
		this.flagIpssvida = flagIpssvida;
	}

	@Column(name = "FlagSindicato", length = 1)
	public String getFlagSindicato() {
		return this.flagSindicato;
	}

	public void setFlagSindicato(String flagSindicato) {
		this.flagSindicato = flagSindicato;
	}

	@Column(name = "FlagAccTrabajo", length = 1)
	public String getFlagAccTrabajo() {
		return this.flagAccTrabajo;
	}

	public void setFlagAccTrabajo(String flagAccTrabajo) {
		this.flagAccTrabajo = flagAccTrabajo;
	}

	@Column(name = "FlagCooperativa", length = 1)
	public String getFlagCooperativa() {
		return this.flagCooperativa;
	}

	public void setFlagCooperativa(String flagCooperativa) {
		this.flagCooperativa = flagCooperativa;
	}

	@Column(name = "FlagRetencionJudicial", length = 1)
	public String getFlagRetencionJudicial() {
		return this.flagRetencionJudicial;
	}

	public void setFlagRetencionJudicial(String flagRetencionJudicial) {
		this.flagRetencionJudicial = flagRetencionJudicial;
	}

	@Column(name = "FlagReingresos", length = 1)
	public String getFlagReingresos() {
		return this.flagReingresos;
	}

	public void setFlagReingresos(String flagReingresos) {
		this.flagReingresos = flagReingresos;
	}

	@Column(name = "FlagComision", length = 1)
	public String getFlagComision() {
		return this.flagComision;
	}

	public void setFlagComision(String flagComision) {
		this.flagComision = flagComision;
	}

	@Column(name = "FlagImpuestoRenta", length = 1)
	public String getFlagImpuestoRenta() {
		return this.flagImpuestoRenta;
	}

	public void setFlagImpuestoRenta(String flagImpuestoRenta) {
		this.flagImpuestoRenta = flagImpuestoRenta;
	}

	@Column(name = "SueldoActualLocal", scale = 4)
	public BigDecimal getSueldoActualLocal() {
		return this.sueldoActualLocal;
	}

	public void setSueldoActualLocal(BigDecimal sueldoActualLocal) {
		this.sueldoActualLocal = sueldoActualLocal;
	}

	@Column(name = "SueldoActualDolar", scale = 4)
	public BigDecimal getSueldoActualDolar() {
		return this.sueldoActualDolar;
	}

	public void setSueldoActualDolar(BigDecimal sueldoActualDolar) {
		this.sueldoActualDolar = sueldoActualDolar;
	}

	@Column(name = "SueldoAnteriorLocal", scale = 4)
	public BigDecimal getSueldoAnteriorLocal() {
		return this.sueldoAnteriorLocal;
	}

	public void setSueldoAnteriorLocal(BigDecimal sueldoAnteriorLocal) {
		this.sueldoAnteriorLocal = sueldoAnteriorLocal;
	}

	@Column(name = "SueldoAnteriorDolar", scale = 4)
	public BigDecimal getSueldoAnteriorDolar() {
		return this.sueldoAnteriorDolar;
	}

	public void setSueldoAnteriorDolar(BigDecimal sueldoAnteriorDolar) {
		this.sueldoAnteriorDolar = sueldoAnteriorDolar;
	}

	@Column(name = "MonedaPago", length = 2)
	public String getMonedaPago() {
		return this.monedaPago;
	}

	public void setMonedaPago(String monedaPago) {
		this.monedaPago = monedaPago;
	}

	@Column(name = "TarjetaCredito", length = 20)
	public String getTarjetaCredito() {
		return this.tarjetaCredito;
	}

	public void setTarjetaCredito(String tarjetaCredito) {
		this.tarjetaCredito = tarjetaCredito;
	}

	@Column(name = "MotivoCese")
	public Integer getMotivoCese() {
		return this.motivoCese;
	}

	public void setMotivoCese(Integer motivoCese) {
		this.motivoCese = motivoCese;
	}

	@Column(name = "DepartamentoOrganizacional", length = 5)
	public String getDepartamentoOrganizacional() {
		return this.departamentoOrganizacional;
	}

	public void setDepartamentoOrganizacional(String departamentoOrganizacional) {
		this.departamentoOrganizacional = departamentoOrganizacional;
	}

	@Column(name = "DepartamentoOperacional", length = 10)
	public String getDepartamentoOperacional() {
		return this.departamentoOperacional;
	}

	public void setDepartamentoOperacional(String departamentoOperacional) {
		this.departamentoOperacional = departamentoOperacional;
	}

	@Column(name = "Perfil")
	public Integer getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Integer perfil) {
		this.perfil = perfil;
	}

	@Column(name = "NivelSalario", length = 3)
	public String getNivelSalario() {
		return this.nivelSalario;
	}

	public void setNivelSalario(String nivelSalario) {
		this.nivelSalario = nivelSalario;
	}

	@Column(name = "FechaLiquidacion", length = 23)
	public Date getFechaLiquidacion() {
		return this.fechaLiquidacion;
	}

	public void setFechaLiquidacion(Date fechaLiquidacion) {
		this.fechaLiquidacion = fechaLiquidacion;
	}

	@Column(name = "FechaReingreso", length = 23)
	public Date getFechaReingreso() {
		return this.fechaReingreso;
	}

	public void setFechaReingreso(Date fechaReingreso) {
		this.fechaReingreso = fechaReingreso;
	}

	@Column(name = "UnidadReplicacion", length = 10)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "CodigoCargo")
	public Integer getCodigoCargo() {
		return this.codigoCargo;
	}

	public void setCodigoCargo(Integer codigoCargo) {
		this.codigoCargo = codigoCargo;
	}

	@Column(name = "UltimaFechaPagoVacacion", length = 23)
	public Date getUltimaFechaPagoVacacion() {
		return this.ultimaFechaPagoVacacion;
	}

	public void setUltimaFechaPagoVacacion(Date ultimaFechaPagoVacacion) {
		this.ultimaFechaPagoVacacion = ultimaFechaPagoVacacion;
	}

	@Column(name = "Gerencia")
	public Integer getGerencia() {
		return this.gerencia;
	}

	public void setGerencia(Integer gerencia) {
		this.gerencia = gerencia;
	}

	@Column(name = "SubGerencia")
	public Integer getSubGerencia() {
		return this.subGerencia;
	}

	public void setSubGerencia(Integer subGerencia) {
		this.subGerencia = subGerencia;
	}

	@Column(name = "RedondeoACuenta", precision = 53, scale = 0)
	public Double getRedondeoAcuenta() {
		return this.redondeoAcuenta;
	}

	public void setRedondeoAcuenta(Double redondeoAcuenta) {
		this.redondeoAcuenta = redondeoAcuenta;
	}

	@Column(name = "PlantillaConcepto")
	public Integer getPlantillaConcepto() {
		return this.plantillaConcepto;
	}

	public void setPlantillaConcepto(Integer plantillaConcepto) {
		this.plantillaConcepto = plantillaConcepto;
	}

	@Column(name = "RUCCentroAsistenciaSocial", length = 20)
	public String getRuccentroAsistenciaSocial() {
		return this.ruccentroAsistenciaSocial;
	}

	public void setRuccentroAsistenciaSocial(String ruccentroAsistenciaSocial) {
		this.ruccentroAsistenciaSocial = ruccentroAsistenciaSocial;
	}

	@Column(name = "Sucursal", length = 4)
	public String getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "Actividad", length = 8)
	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

	@Column(name = "Cliente")
	public Integer getCliente() {
		return this.cliente;
	}

	public void setCliente(Integer cliente) {
		this.cliente = cliente;
	}

	@Column(name = "ClienteUnidad")
	public Integer getClienteUnidad() {
		return this.clienteUnidad;
	}

	public void setClienteUnidad(Integer clienteUnidad) {
		this.clienteUnidad = clienteUnidad;
	}

	@Column(name = "EmpleadoNivel")
	public Integer getEmpleadoNivel() {
		return this.empleadoNivel;
	}

	public void setEmpleadoNivel(Integer empleadoNivel) {
		this.empleadoNivel = empleadoNivel;
	}

	@Column(name = "TipoPuesto", precision = 10, scale = 0)
	public Long getTipoPuesto() {
		return this.tipoPuesto;
	}

	public void setTipoPuesto(Long tipoPuesto) {
		this.tipoPuesto = tipoPuesto;
	}

	@Column(name = "USUARIO", length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "USUARIOPERFIL", length = 2)
	public String getUsuarioperfil() {
		return this.usuarioperfil;
	}

	public void setUsuarioperfil(String usuarioperfil) {
		this.usuarioperfil = usuarioperfil;
	}

	@Column(name = "PERSONAUSUARIO")
	public Integer getPersonausuario() {
		return this.personausuario;
	}

	public void setPersonausuario(Integer personausuario) {
		this.personausuario = personausuario;
	}

	@Column(name = "CLAVE", length = 100)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "EXPIRARPASSWORDFLAG", length = 1)
	public String getExpirarpasswordflag() {
		return this.expirarpasswordflag;
	}

	public void setExpirarpasswordflag(String expirarpasswordflag) {
		this.expirarpasswordflag = expirarpasswordflag;
	}

	@Column(name = "FECHAEXPIRACION", length = 23)
	public Date getFechaexpiracion() {
		return this.fechaexpiracion;
	}

	public void setFechaexpiracion(Date fechaexpiracion) {
		this.fechaexpiracion = fechaexpiracion;
	}

	@Column(name = "ULTIMOLOGIN", length = 23)
	public Date getUltimologin() {
		return this.ultimologin;
	}

	public void setUltimologin(Date ultimologin) {
		this.ultimologin = ultimologin;
	}

	@Column(name = "Paciente")
	public Integer getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Integer paciente) {
		this.paciente = paciente;
	}

	@Column(name = "TipoPaciente")
	public Integer getTipoPaciente() {
		return this.tipoPaciente;
	}

	public void setTipoPaciente(Integer tipoPaciente) {
		this.tipoPaciente = tipoPaciente;
	}

	@Column(name = "Raza", length = 30)
	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	@Column(name = "AreaLaboral", length = 30)
	public String getAreaLaboral() {
		return this.areaLaboral;
	}

	public void setAreaLaboral(String areaLaboral) {
		this.areaLaboral = areaLaboral;
	}

	@Column(name = "Ocupacion", length = 80)
	public String getOcupacion() {
		return this.ocupacion;
	}

	public void setOcupacion(String ocupacion) {
		this.ocupacion = ocupacion;
	}

	@Column(name = "CodigoHC", length = 15)
	public String getCodigoHc() {
		return this.codigoHc;
	}

	public void setCodigoHc(String codigoHc) {
		this.codigoHc = codigoHc;
	}

	@Column(name = "CodigoHCAnterior", length = 15)
	public String getCodigoHcanterior() {
		return this.codigoHcanterior;
	}

	public void setCodigoHcanterior(String codigoHcanterior) {
		this.codigoHcanterior = codigoHcanterior;
	}

	@Column(name = "CodigoHCSecundario", length = 15)
	public String getCodigoHcsecundario() {
		return this.codigoHcsecundario;
	}

	public void setCodigoHcsecundario(String codigoHcsecundario) {
		this.codigoHcsecundario = codigoHcsecundario;
	}

	@Column(name = "TipoAlmacenamiento", length = 2)
	public String getTipoAlmacenamiento() {
		return this.tipoAlmacenamiento;
	}

	public void setTipoAlmacenamiento(String tipoAlmacenamiento) {
		this.tipoAlmacenamiento = tipoAlmacenamiento;
	}

	@Column(name = "TipoHistoria", length = 1)
	public String getTipoHistoria() {
		return this.tipoHistoria;
	}

	public void setTipoHistoria(String tipoHistoria) {
		this.tipoHistoria = tipoHistoria;
	}

	@Column(name = "TipoSituacion", length = 1)
	public String getTipoSituacion() {
		return this.tipoSituacion;
	}

	public void setTipoSituacion(String tipoSituacion) {
		this.tipoSituacion = tipoSituacion;
	}

	@Column(name = "IdUbicacion")
	public Integer getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(Integer idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	@Column(name = "LugarProcedencia", length = 30)
	public String getLugarProcedencia() {
		return this.lugarProcedencia;
	}

	public void setLugarProcedencia(String lugarProcedencia) {
		this.lugarProcedencia = lugarProcedencia;
	}

	@Column(name = "RutaFoto", length = 150)
	public String getRutaFoto() {
		return this.rutaFoto;
	}

	public void setRutaFoto(String rutaFoto) {
		this.rutaFoto = rutaFoto;
	}

	@Column(name = "EstadoPaciente")
	public Integer getEstadoPaciente() {
		return this.estadoPaciente;
	}

	public void setEstadoPaciente(Integer estadoPaciente) {
		this.estadoPaciente = estadoPaciente;
	}

	@Column(name = "NumeroFile")
	public Integer getNumeroFile() {
		return this.numeroFile;
	}

	public void setNumeroFile(Integer numeroFile) {
		this.numeroFile = numeroFile;
	}

	@Column(name = "Servicio", length = 25)
	public String getServicio() {
		return this.servicio;
	}

	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	@Column(name = "Observacion", length = 250)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "IndicadorAsistencia")
	public Integer getIndicadorAsistencia() {
		return this.indicadorAsistencia;
	}

	public void setIndicadorAsistencia(Integer indicadorAsistencia) {
		this.indicadorAsistencia = indicadorAsistencia;
	}

	@Column(name = "CantidadAsistencia")
	public Integer getCantidadAsistencia() {
		return this.cantidadAsistencia;
	}

	public void setCantidadAsistencia(Integer cantidadAsistencia) {
		this.cantidadAsistencia = cantidadAsistencia;
	}

	@Column(name = "UbicacionHHCC")
	public Integer getUbicacionHhcc() {
		return this.ubicacionHhcc;
	}

	public void setUbicacionHhcc(Integer ubicacionHhcc) {
		this.ubicacionHhcc = ubicacionHhcc;
	}

	@Column(name = "IndicadorMigradoSiteds")
	public Integer getIndicadorMigradoSiteds() {
		return this.indicadorMigradoSiteds;
	}

	public void setIndicadorMigradoSiteds(Integer indicadorMigradoSiteds) {
		this.indicadorMigradoSiteds = indicadorMigradoSiteds;
	}

	@Column(name = "NumeroCaja", length = 25)
	public String getNumeroCaja() {
		return this.numeroCaja;
	}

	public void setNumeroCaja(String numeroCaja) {
		this.numeroCaja = numeroCaja;
	}

	@Column(name = "IndicadorCodigoBarras")
	public Integer getIndicadorCodigoBarras() {
		return this.indicadorCodigoBarras;
	}

	public void setIndicadorCodigoBarras(Integer indicadorCodigoBarras) {
		this.indicadorCodigoBarras = indicadorCodigoBarras;
	}

	@Column(name = "IDPACIENTE_OK")
	public Integer getIdpacienteOk() {
		return this.idpacienteOk;
	}

	public void setIdpacienteOk(Integer idpacienteOk) {
		this.idpacienteOk = idpacienteOk;
	}

	@Column(name = "CodigoAsegurado", length = 30)
	public String getCodigoAsegurado() {
		return this.codigoAsegurado;
	}

	public void setCodigoAsegurado(String codigoAsegurado) {
		this.codigoAsegurado = codigoAsegurado;
	}

	@Column(name = "NumeroPoliza")
	public Integer getNumeroPoliza() {
		return this.numeroPoliza;
	}

	public void setNumeroPoliza(Integer numeroPoliza) {
		this.numeroPoliza = numeroPoliza;
	}

	@Column(name = "NumeroCertificado")
	public Integer getNumeroCertificado() {
		return this.numeroCertificado;
	}

	public void setNumeroCertificado(Integer numeroCertificado) {
		this.numeroCertificado = numeroCertificado;
	}

	@Column(name = "CodigoProducto", length = 25)
	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "CodigoPlan", length = 25)
	public String getCodigoPlan() {
		return this.codigoPlan;
	}

	public void setCodigoPlan(String codigoPlan) {
		this.codigoPlan = codigoPlan;
	}

	@Column(name = "TipoParentesco")
	public Integer getTipoParentesco() {
		return this.tipoParentesco;
	}

	public void setTipoParentesco(Integer tipoParentesco) {
		this.tipoParentesco = tipoParentesco;
	}

	@Column(name = "CodigoBeneficio", length = 25)
	public String getCodigoBeneficio() {
		return this.codigoBeneficio;
	}

	public void setCodigoBeneficio(String codigoBeneficio) {
		this.codigoBeneficio = codigoBeneficio;
	}

	@Column(name = "Situacion")
	public Integer getSituacion() {
		return this.situacion;
	}

	public void setSituacion(Integer situacion) {
		this.situacion = situacion;
	}

	@Column(name = "TomoActual")
	public Integer getTomoActual() {
		return this.tomoActual;
	}

	public void setTomoActual(Integer tomoActual) {
		this.tomoActual = tomoActual;
	}

	@Column(name = "IndicadorHistoriaFisica")
	public Integer getIndicadorHistoriaFisica() {
		return this.indicadorHistoriaFisica;
	}

	public void setIndicadorHistoriaFisica(Integer indicadorHistoriaFisica) {
		this.indicadorHistoriaFisica = indicadorHistoriaFisica;
	}

	@Column(name = "DescripcionHistoria", length = 500)
	public String getDescripcionHistoria() {
		return this.descripcionHistoria;
	}

	public void setDescripcionHistoria(String descripcionHistoria) {
		this.descripcionHistoria = descripcionHistoria;
	}

	@Column(name = "PersonaAnt", length = 15)
	public String getPersonaAnt() {
		return this.personaAnt;
	}

	public void setPersonaAnt(String personaAnt) {
		this.personaAnt = personaAnt;
	}

	@Column(name = "Nombres", length = 40)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "Busqueda", length = 100)
	public String getBusqueda() {
		return this.busqueda;
	}

	public void setBusqueda(String busqueda) {
		this.busqueda = busqueda;
	}

}
