package pe.royalsystems.springerp.model.domain;

//default package
//Generated Sep 10, 2015 3:30:07 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
* VwServicioPrestacion generated by hbm2java
*/
@Entity
@Table(name = "VW_ServicioPrestacion")
public class VwServicioPrestacion extends Entidad implements java.io.Serializable {

	private VwServicioPrestacionId id;

	public VwServicioPrestacion() {
	}

	public VwServicioPrestacion(VwServicioPrestacionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "componente", column = @Column(name = "Componente", nullable = false, length = 25) ),
			@AttributeOverride(name = "valorMedida", column = @Column(name = "ValorMedida", precision = 20, scale = 6) ),
			@AttributeOverride(name = "cantidadAsistentes", column = @Column(name = "CantidadAsistentes", precision = 20, scale = 6) ),
			@AttributeOverride(name = "instrumentistas", column = @Column(name = "Instrumentistas") ),
			@AttributeOverride(name = "diasHospitalizacion", column = @Column(name = "DiasHospitalizacion", precision = 9) ),
			@AttributeOverride(name = "codigoSegus", column = @Column(name = "CodigoSegus", length = 15) ),
			@AttributeOverride(name = "codigoNuevo", column = @Column(name = "CodigoNuevo", length = 15) ),
			@AttributeOverride(name = "estado", column = @Column(name = "Estado") ),
			@AttributeOverride(name = "nombre", column = @Column(name = "Nombre", length = 250) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "Descripcion", length = 300) ),
			@AttributeOverride(name = "compania", column = @Column(name = "Compania", length = 15) ),
			@AttributeOverride(name = "centroCosto", column = @Column(name = "CentroCosto", length = 15) ),
			@AttributeOverride(name = "clasificadorMovimiento", column = @Column(name = "ClasificadorMovimiento", length = 15) ),
			@AttributeOverride(name = "conceptoGasto", column = @Column(name = "ConceptoGasto", length = 15) ),
			@AttributeOverride(name = "indicadorImpuesto", column = @Column(name = "IndicadorImpuesto") ),
			@AttributeOverride(name = "idClasificacion", column = @Column(name = "IdClasificacion", nullable = false) ),
			@AttributeOverride(name = "codClasificacion", column = @Column(name = "CodClasificacion", length = 15) ),
			@AttributeOverride(name = "nomClasificacion", column = @Column(name = "NomClasificacion", length = 250) ),
			@AttributeOverride(name = "orden", column = @Column(name = "Orden") ),
			@AttributeOverride(name = "tipoPrestacion", column = @Column(name = "TipoPrestacion") ),
			@AttributeOverride(name = "indicadorCita", column = @Column(name = "IndicadorCita", nullable = false) ),
			@AttributeOverride(name = "indicadorHc", column = @Column(name = "IndicadorHC", nullable = false) ),
			@AttributeOverride(name = "cadenaRecursividad", column = @Column(name = "CadenaRecursividad", length = 150) ),
			@AttributeOverride(name = "indicadorPrestacionPrincipal", column = @Column(name = "IndicadorPrestacionPrincipal") ),
			@AttributeOverride(name = "indicadorRequierePersonal", column = @Column(name = "IndicadorRequierePersonal") ),
			@AttributeOverride(name = "idServicio", column = @Column(name = "IdServicio") ),
			@AttributeOverride(name = "idGrupoAtencion", column = @Column(name = "IdGrupoAtencion") ),
			@AttributeOverride(name = "codigo", column = @Column(name = "Codigo", length = 15) ),
			@AttributeOverride(name = "tipoOrdenAtencion", column = @Column(name = "TipoOrdenAtencion") ),
			@AttributeOverride(name = "accion", column = @Column(name = "ACCION", nullable = false, length = 25) ) })
	public VwServicioPrestacionId getId() {
		return this.id;
	}

	public void setId(VwServicioPrestacionId id) {
		this.id = id;
	}

}

