package pe.royalsystems.springerp.model.domain;

//default package
//Generated Sep 10, 2015 3:48:09 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
* VwSsGeEspecialidadmedicoId generated by hbm2java
*/
@Embeddable
public class VwSsGeEspecialidadmedicoId implements java.io.Serializable {

	private int persona;
	private String origen;
	private String nombres;
	private String nombrecompleto;
	private String busqueda;
	private Character tipodocumentoidentidad;
	private String documentoidentidad;
	private Character escliente;
	private Character esproveedor;
	private Character esempleado;
	private Character esotro;
	private Character tipopersona;
	private Date fechanacimiento;
	private String ciudadnacimiento;
	private String documentofiscal;
	private String documento;
	private String personaant;
	private String correoelectronico;
	private String clasepersonacodigo;
	private Character estado;
	private String ultimousuario;
	private Date ultimafechamodif;
	private String tipopersonausuario;
	private String cmp;
	private String foto;
	private String numeroregistroespecialidad;
	private Integer tipogeneracioncita;
	private BigDecimal tiempopromedioatencion;
	private Integer idespecialidad;
	private String nombre;
	private String accion;
	private Character sexo;
	private String direccion;
	private String telefono;
	private int programado;
	private int servicio;
	private String tipohorario;
	private int idhorario;
	private String codigousuario;

	public VwSsGeEspecialidadmedicoId() {
	}

	public VwSsGeEspecialidadmedicoId(int persona, String origen, String documento, int programado, int servicio,
			String tipohorario, int idhorario) {
		this.persona = persona;
		this.origen = origen;
		this.documento = documento;
		this.programado = programado;
		this.servicio = servicio;
		this.tipohorario = tipohorario;
		this.idhorario = idhorario;
	}

	public VwSsGeEspecialidadmedicoId(int persona, String origen, String nombres, String nombrecompleto,
			String busqueda, Character tipodocumentoidentidad, String documentoidentidad, Character escliente,
			Character esproveedor, Character esempleado, Character esotro, Character tipopersona, Date fechanacimiento,
			String ciudadnacimiento, String documentofiscal, String documento, String personaant,
			String correoelectronico, String clasepersonacodigo, Character estado, String ultimousuario,
			Date ultimafechamodif, String tipopersonausuario, String cmp, String foto,
			String numeroregistroespecialidad, Integer tipogeneracioncita, BigDecimal tiempopromedioatencion,
			Integer idespecialidad, String nombre, String accion, Character sexo, String direccion, String telefono,
			int programado, int servicio, String tipohorario, int idhorario, String codigousuario) {
		this.persona = persona;
		this.origen = origen;
		this.nombres = nombres;
		this.nombrecompleto = nombrecompleto;
		this.busqueda = busqueda;
		this.tipodocumentoidentidad = tipodocumentoidentidad;
		this.documentoidentidad = documentoidentidad;
		this.escliente = escliente;
		this.esproveedor = esproveedor;
		this.esempleado = esempleado;
		this.esotro = esotro;
		this.tipopersona = tipopersona;
		this.fechanacimiento = fechanacimiento;
		this.ciudadnacimiento = ciudadnacimiento;
		this.documentofiscal = documentofiscal;
		this.documento = documento;
		this.personaant = personaant;
		this.correoelectronico = correoelectronico;
		this.clasepersonacodigo = clasepersonacodigo;
		this.estado = estado;
		this.ultimousuario = ultimousuario;
		this.ultimafechamodif = ultimafechamodif;
		this.tipopersonausuario = tipopersonausuario;
		this.cmp = cmp;
		this.foto = foto;
		this.numeroregistroespecialidad = numeroregistroespecialidad;
		this.tipogeneracioncita = tipogeneracioncita;
		this.tiempopromedioatencion = tiempopromedioatencion;
		this.idespecialidad = idespecialidad;
		this.nombre = nombre;
		this.accion = accion;
		this.sexo = sexo;
		this.direccion = direccion;
		this.telefono = telefono;
		this.programado = programado;
		this.servicio = servicio;
		this.tipohorario = tipohorario;
		this.idhorario = idhorario;
		this.codigousuario = codigousuario;
	}

	@Column(name = "PERSONA", nullable = false)
	public int getPersona() {
		return this.persona;
	}

	public void setPersona(int persona) {
		this.persona = persona;
	}

	@Column(name = "ORIGEN", nullable = false, length = 4)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "NOMBRES", length = 40)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "NOMBRECOMPLETO", length = 100)
	public String getNombrecompleto() {
		return this.nombrecompleto;
	}

	public void setNombrecompleto(String nombrecompleto) {
		this.nombrecompleto = nombrecompleto;
	}

	@Column(name = "BUSQUEDA", length = 100)
	public String getBusqueda() {
		return this.busqueda;
	}

	public void setBusqueda(String busqueda) {
		this.busqueda = busqueda;
	}

	@Column(name = "TIPODOCUMENTOIDENTIDAD", length = 1)
	public Character getTipodocumentoidentidad() {
		return this.tipodocumentoidentidad;
	}

	public void setTipodocumentoidentidad(Character tipodocumentoidentidad) {
		this.tipodocumentoidentidad = tipodocumentoidentidad;
	}

	@Column(name = "DOCUMENTOIDENTIDAD", length = 20)
	public String getDocumentoidentidad() {
		return this.documentoidentidad;
	}

	public void setDocumentoidentidad(String documentoidentidad) {
		this.documentoidentidad = documentoidentidad;
	}

	@Column(name = "ESCLIENTE", length = 1)
	public Character getEscliente() {
		return this.escliente;
	}

	public void setEscliente(Character escliente) {
		this.escliente = escliente;
	}

	@Column(name = "ESPROVEEDOR", length = 1)
	public Character getEsproveedor() {
		return this.esproveedor;
	}

	public void setEsproveedor(Character esproveedor) {
		this.esproveedor = esproveedor;
	}

	@Column(name = "ESEMPLEADO", length = 1)
	public Character getEsempleado() {
		return this.esempleado;
	}

	public void setEsempleado(Character esempleado) {
		this.esempleado = esempleado;
	}

	@Column(name = "ESOTRO", length = 1)
	public Character getEsotro() {
		return this.esotro;
	}

	public void setEsotro(Character esotro) {
		this.esotro = esotro;
	}

	@Column(name = "TIPOPERSONA", length = 1)
	public Character getTipopersona() {
		return this.tipopersona;
	}

	public void setTipopersona(Character tipopersona) {
		this.tipopersona = tipopersona;
	}

	@Column(name = "FECHANACIMIENTO", length = 23)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "CIUDADNACIMIENTO", length = 20)
	public String getCiudadnacimiento() {
		return this.ciudadnacimiento;
	}

	public void setCiudadnacimiento(String ciudadnacimiento) {
		this.ciudadnacimiento = ciudadnacimiento;
	}

	@Column(name = "DOCUMENTOFISCAL", length = 20)
	public String getDocumentofiscal() {
		return this.documentofiscal;
	}

	public void setDocumentofiscal(String documentofiscal) {
		this.documentofiscal = documentofiscal;
	}

	@Column(name = "DOCUMENTO", nullable = false, length = 20)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "PERSONAANT", length = 15)
	public String getPersonaant() {
		return this.personaant;
	}

	public void setPersonaant(String personaant) {
		this.personaant = personaant;
	}

	@Column(name = "CORREOELECTRONICO", length = 50)
	public String getCorreoelectronico() {
		return this.correoelectronico;
	}

	public void setCorreoelectronico(String correoelectronico) {
		this.correoelectronico = correoelectronico;
	}

	@Column(name = "CLASEPERSONACODIGO", length = 3)
	public String getClasepersonacodigo() {
		return this.clasepersonacodigo;
	}

	public void setClasepersonacodigo(String clasepersonacodigo) {
		this.clasepersonacodigo = clasepersonacodigo;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "ULTIMOUSUARIO", length = 25)
	public String getUltimousuario() {
		return this.ultimousuario;
	}

	public void setUltimousuario(String ultimousuario) {
		this.ultimousuario = ultimousuario;
	}

	@Column(name = "ULTIMAFECHAMODIF", length = 23)
	public Date getUltimafechamodif() {
		return this.ultimafechamodif;
	}

	public void setUltimafechamodif(Date ultimafechamodif) {
		this.ultimafechamodif = ultimafechamodif;
	}

	@Column(name = "TIPOPERSONAUSUARIO", length = 3)
	public String getTipopersonausuario() {
		return this.tipopersonausuario;
	}

	public void setTipopersonausuario(String tipopersonausuario) {
		this.tipopersonausuario = tipopersonausuario;
	}

	@Column(name = "CMP", length = 25)
	public String getCmp() {
		return this.cmp;
	}

	public void setCmp(String cmp) {
		this.cmp = cmp;
	}

	@Column(name = "FOTO", length = 150)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Column(name = "NUMEROREGISTROESPECIALIDAD", length = 25)
	public String getNumeroregistroespecialidad() {
		return this.numeroregistroespecialidad;
	}

	public void setNumeroregistroespecialidad(String numeroregistroespecialidad) {
		this.numeroregistroespecialidad = numeroregistroespecialidad;
	}

	@Column(name = "TIPOGENERACIONCITA")
	public Integer getTipogeneracioncita() {
		return this.tipogeneracioncita;
	}

	public void setTipogeneracioncita(Integer tipogeneracioncita) {
		this.tipogeneracioncita = tipogeneracioncita;
	}

	@Column(name = "TIEMPOPROMEDIOATENCION", precision = 9)
	public BigDecimal getTiempopromedioatencion() {
		return this.tiempopromedioatencion;
	}

	public void setTiempopromedioatencion(BigDecimal tiempopromedioatencion) {
		this.tiempopromedioatencion = tiempopromedioatencion;
	}

	@Column(name = "IDESPECIALIDAD")
	public Integer getIdespecialidad() {
		return this.idespecialidad;
	}

	public void setIdespecialidad(Integer idespecialidad) {
		this.idespecialidad = idespecialidad;
	}

	@Column(name = "NOMBRE", length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ACCION", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@Column(name = "SEXO", length = 1)
	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	@Column(name = "DIRECCION", length = 190)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "TELEFONO", length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "PROGRAMADO", nullable = false)
	public int getProgramado() {
		return this.programado;
	}

	public void setProgramado(int programado) {
		this.programado = programado;
	}

	@Column(name = "SERVICIO", nullable = false)
	public int getServicio() {
		return this.servicio;
	}

	public void setServicio(int servicio) {
		this.servicio = servicio;
	}

	@Column(name = "TIPOHORARIO", nullable = false, length = 3)
	public String getTipohorario() {
		return this.tipohorario;
	}

	public void setTipohorario(String tipohorario) {
		this.tipohorario = tipohorario;
	}

	@Column(name = "IDHORARIO", nullable = false)
	public int getIdhorario() {
		return this.idhorario;
	}

	public void setIdhorario(int idhorario) {
		this.idhorario = idhorario;
	}

	@Column(name = "CODIGOUSUARIO", length = 25)
	public String getCodigousuario() {
		return this.codigousuario;
	}

	public void setCodigousuario(String codigousuario) {
		this.codigousuario = codigousuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwSsGeEspecialidadmedicoId))
			return false;
		VwSsGeEspecialidadmedicoId castOther = (VwSsGeEspecialidadmedicoId) other;

		return (this.getPersona() == castOther.getPersona())
				&& ((this.getOrigen() == castOther.getOrigen()) || (this.getOrigen() != null
						&& castOther.getOrigen() != null && this.getOrigen().equals(castOther.getOrigen())))
				&& ((this.getNombres() == castOther.getNombres()) || (this.getNombres() != null
						&& castOther.getNombres() != null && this.getNombres().equals(castOther.getNombres())))
				&& ((this.getNombrecompleto() == castOther.getNombrecompleto())
						|| (this.getNombrecompleto() != null && castOther.getNombrecompleto() != null
								&& this.getNombrecompleto().equals(castOther.getNombrecompleto())))
				&& ((this.getBusqueda() == castOther.getBusqueda()) || (this.getBusqueda() != null
						&& castOther.getBusqueda() != null && this.getBusqueda().equals(castOther.getBusqueda())))
				&& ((this.getTipodocumentoidentidad() == castOther.getTipodocumentoidentidad())
						|| (this.getTipodocumentoidentidad() != null && castOther.getTipodocumentoidentidad() != null
								&& this.getTipodocumentoidentidad().equals(castOther.getTipodocumentoidentidad())))
				&& ((this.getDocumentoidentidad() == castOther.getDocumentoidentidad())
						|| (this.getDocumentoidentidad() != null && castOther.getDocumentoidentidad() != null
								&& this.getDocumentoidentidad().equals(castOther.getDocumentoidentidad())))
				&& ((this.getEscliente() == castOther.getEscliente()) || (this.getEscliente() != null
						&& castOther.getEscliente() != null && this.getEscliente().equals(castOther.getEscliente())))
				&& ((this.getEsproveedor() == castOther.getEsproveedor())
						|| (this.getEsproveedor() != null && castOther.getEsproveedor() != null
								&& this.getEsproveedor().equals(castOther.getEsproveedor())))
				&& ((this.getEsempleado() == castOther.getEsempleado()) || (this.getEsempleado() != null
						&& castOther.getEsempleado() != null && this.getEsempleado().equals(castOther.getEsempleado())))
				&& ((this.getEsotro() == castOther.getEsotro()) || (this.getEsotro() != null
						&& castOther.getEsotro() != null && this.getEsotro().equals(castOther.getEsotro())))
				&& ((this.getTipopersona() == castOther.getTipopersona())
						|| (this.getTipopersona() != null && castOther.getTipopersona() != null
								&& this.getTipopersona().equals(castOther.getTipopersona())))
				&& ((this.getFechanacimiento() == castOther.getFechanacimiento())
						|| (this.getFechanacimiento() != null && castOther.getFechanacimiento() != null
								&& this.getFechanacimiento().equals(castOther.getFechanacimiento())))
				&& ((this.getCiudadnacimiento() == castOther.getCiudadnacimiento())
						|| (this.getCiudadnacimiento() != null && castOther.getCiudadnacimiento() != null
								&& this.getCiudadnacimiento().equals(castOther.getCiudadnacimiento())))
				&& ((this.getDocumentofiscal() == castOther.getDocumentofiscal())
						|| (this.getDocumentofiscal() != null && castOther.getDocumentofiscal() != null
								&& this.getDocumentofiscal().equals(castOther.getDocumentofiscal())))
				&& ((this.getDocumento() == castOther.getDocumento()) || (this.getDocumento() != null
						&& castOther.getDocumento() != null && this.getDocumento().equals(castOther.getDocumento())))
				&& ((this.getPersonaant() == castOther.getPersonaant()) || (this.getPersonaant() != null
						&& castOther.getPersonaant() != null && this.getPersonaant().equals(castOther.getPersonaant())))
				&& ((this.getCorreoelectronico() == castOther.getCorreoelectronico())
						|| (this.getCorreoelectronico() != null && castOther.getCorreoelectronico() != null
								&& this.getCorreoelectronico().equals(castOther.getCorreoelectronico())))
				&& ((this.getClasepersonacodigo() == castOther.getClasepersonacodigo())
						|| (this.getClasepersonacodigo() != null && castOther.getClasepersonacodigo() != null
								&& this.getClasepersonacodigo().equals(castOther.getClasepersonacodigo())))
				&& ((this.getEstado() == castOther.getEstado()) || (this.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado().equals(castOther.getEstado())))
				&& ((this.getUltimousuario() == castOther.getUltimousuario())
						|| (this.getUltimousuario() != null && castOther.getUltimousuario() != null
								&& this.getUltimousuario().equals(castOther.getUltimousuario())))
				&& ((this.getUltimafechamodif() == castOther.getUltimafechamodif())
						|| (this.getUltimafechamodif() != null && castOther.getUltimafechamodif() != null
								&& this.getUltimafechamodif().equals(castOther.getUltimafechamodif())))
				&& ((this.getTipopersonausuario() == castOther.getTipopersonausuario())
						|| (this.getTipopersonausuario() != null && castOther.getTipopersonausuario() != null
								&& this.getTipopersonausuario().equals(castOther.getTipopersonausuario())))
				&& ((this.getCmp() == castOther.getCmp()) || (this.getCmp() != null && castOther.getCmp() != null
						&& this.getCmp().equals(castOther.getCmp())))
				&& ((this.getFoto() == castOther.getFoto()) || (this.getFoto() != null && castOther.getFoto() != null
						&& this.getFoto().equals(castOther.getFoto())))
				&& ((this.getNumeroregistroespecialidad() == castOther.getNumeroregistroespecialidad())
						|| (this.getNumeroregistroespecialidad() != null
								&& castOther.getNumeroregistroespecialidad() != null
								&& this.getNumeroregistroespecialidad()
										.equals(castOther.getNumeroregistroespecialidad())))
				&& ((this.getTipogeneracioncita() == castOther.getTipogeneracioncita())
						|| (this.getTipogeneracioncita() != null && castOther.getTipogeneracioncita() != null
								&& this.getTipogeneracioncita().equals(castOther.getTipogeneracioncita())))
				&& ((this.getTiempopromedioatencion() == castOther.getTiempopromedioatencion())
						|| (this.getTiempopromedioatencion() != null && castOther.getTiempopromedioatencion() != null
								&& this.getTiempopromedioatencion().equals(castOther.getTiempopromedioatencion())))
				&& ((this.getIdespecialidad() == castOther.getIdespecialidad())
						|| (this.getIdespecialidad() != null && castOther.getIdespecialidad() != null
								&& this.getIdespecialidad().equals(castOther.getIdespecialidad())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getAccion() == castOther.getAccion()) || (this.getAccion() != null
						&& castOther.getAccion() != null && this.getAccion().equals(castOther.getAccion())))
				&& ((this.getSexo() == castOther.getSexo()) || (this.getSexo() != null && castOther.getSexo() != null
						&& this.getSexo().equals(castOther.getSexo())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this.getDireccion() != null
						&& castOther.getDireccion() != null && this.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this.getTelefono() != null
						&& castOther.getTelefono() != null && this.getTelefono().equals(castOther.getTelefono())))
				&& (this.getProgramado() == castOther.getProgramado())
				&& (this.getServicio() == castOther.getServicio())
				&& ((this.getTipohorario() == castOther.getTipohorario())
						|| (this.getTipohorario() != null && castOther.getTipohorario() != null
								&& this.getTipohorario().equals(castOther.getTipohorario())))
				&& (this.getIdhorario() == castOther.getIdhorario())
				&& ((this.getCodigousuario() == castOther.getCodigousuario())
						|| (this.getCodigousuario() != null && castOther.getCodigousuario() != null
								&& this.getCodigousuario().equals(castOther.getCodigousuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersona();
		result = 37 * result + (getOrigen() == null ? 0 : this.getOrigen().hashCode());
		result = 37 * result + (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37 * result + (getNombrecompleto() == null ? 0 : this.getNombrecompleto().hashCode());
		result = 37 * result + (getBusqueda() == null ? 0 : this.getBusqueda().hashCode());
		result = 37 * result + (getTipodocumentoidentidad() == null ? 0 : this.getTipodocumentoidentidad().hashCode());
		result = 37 * result + (getDocumentoidentidad() == null ? 0 : this.getDocumentoidentidad().hashCode());
		result = 37 * result + (getEscliente() == null ? 0 : this.getEscliente().hashCode());
		result = 37 * result + (getEsproveedor() == null ? 0 : this.getEsproveedor().hashCode());
		result = 37 * result + (getEsempleado() == null ? 0 : this.getEsempleado().hashCode());
		result = 37 * result + (getEsotro() == null ? 0 : this.getEsotro().hashCode());
		result = 37 * result + (getTipopersona() == null ? 0 : this.getTipopersona().hashCode());
		result = 37 * result + (getFechanacimiento() == null ? 0 : this.getFechanacimiento().hashCode());
		result = 37 * result + (getCiudadnacimiento() == null ? 0 : this.getCiudadnacimiento().hashCode());
		result = 37 * result + (getDocumentofiscal() == null ? 0 : this.getDocumentofiscal().hashCode());
		result = 37 * result + (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37 * result + (getPersonaant() == null ? 0 : this.getPersonaant().hashCode());
		result = 37 * result + (getCorreoelectronico() == null ? 0 : this.getCorreoelectronico().hashCode());
		result = 37 * result + (getClasepersonacodigo() == null ? 0 : this.getClasepersonacodigo().hashCode());
		result = 37 * result + (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result + (getUltimousuario() == null ? 0 : this.getUltimousuario().hashCode());
		result = 37 * result + (getUltimafechamodif() == null ? 0 : this.getUltimafechamodif().hashCode());
		result = 37 * result + (getTipopersonausuario() == null ? 0 : this.getTipopersonausuario().hashCode());
		result = 37 * result + (getCmp() == null ? 0 : this.getCmp().hashCode());
		result = 37 * result + (getFoto() == null ? 0 : this.getFoto().hashCode());
		result = 37 * result
				+ (getNumeroregistroespecialidad() == null ? 0 : this.getNumeroregistroespecialidad().hashCode());
		result = 37 * result + (getTipogeneracioncita() == null ? 0 : this.getTipogeneracioncita().hashCode());
		result = 37 * result + (getTiempopromedioatencion() == null ? 0 : this.getTiempopromedioatencion().hashCode());
		result = 37 * result + (getIdespecialidad() == null ? 0 : this.getIdespecialidad().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getAccion() == null ? 0 : this.getAccion().hashCode());
		result = 37 * result + (getSexo() == null ? 0 : this.getSexo().hashCode());
		result = 37 * result + (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37 * result + (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result + this.getProgramado();
		result = 37 * result + this.getServicio();
		result = 37 * result + (getTipohorario() == null ? 0 : this.getTipohorario().hashCode());
		result = 37 * result + this.getIdhorario();
		result = 37 * result + (getCodigousuario() == null ? 0 : this.getCodigousuario().hashCode());
		return result;
	}

}
