package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 16, 2015 3:06:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhClaseSubFamilia generated by hbm2java
 */
@Entity
@Table(name = "WH_ClaseSubFamilia")
public class WhClaseSubFamilia extends Entidad implements java.io.Serializable {

	private WhClaseSubFamiliaId id;
	private WhClaseFamilia whClaseFamilia;
	private String descripcionLocal;
	private String descripcionIngles;
	private String descripcionCompleta;
	private Character itemTipo;
	private String transaccionOperacion;
	private Character estado;
	private Date ultimaFechaModif;
	private String ultimoUsuario;
	private String accion;

	public WhClaseSubFamilia() {
	}

	public WhClaseSubFamilia(WhClaseSubFamiliaId id, WhClaseFamilia whClaseFamilia) {
		this.id = id;
		this.whClaseFamilia = whClaseFamilia;
	}

	public WhClaseSubFamilia(WhClaseSubFamiliaId id, WhClaseFamilia whClaseFamilia, String descripcionLocal,
			String descripcionIngles, String descripcionCompleta, Character itemTipo, String transaccionOperacion,
			Character estado, Date ultimaFechaModif, String ultimoUsuario, String accion) {
		this.id = id;
		this.whClaseFamilia = whClaseFamilia;
		this.descripcionLocal = descripcionLocal;
		this.descripcionIngles = descripcionIngles;
		this.descripcionCompleta = descripcionCompleta;
		this.itemTipo = itemTipo;
		this.transaccionOperacion = transaccionOperacion;
		this.estado = estado;
		this.ultimaFechaModif = ultimaFechaModif;
		this.ultimoUsuario = ultimoUsuario;
		this.accion = accion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "linea", column = @Column(name = "Linea", nullable = false, length = 6) ),
			@AttributeOverride(name = "familia", column = @Column(name = "Familia", nullable = false, length = 6) ),
			@AttributeOverride(name = "subFamilia", column = @Column(name = "SubFamilia", nullable = false, length = 6) ) })
	public WhClaseSubFamiliaId getId() {
		return this.id;
	}

	public void setId(WhClaseSubFamiliaId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumns({
			@JoinColumn(name = "Linea", referencedColumnName = "Linea", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "Familia", referencedColumnName = "Familia", nullable = false, insertable = false, updatable = false) })
	public WhClaseFamilia getWhClaseFamilia() {
		return this.whClaseFamilia;
	}

	public void setWhClaseFamilia(WhClaseFamilia whClaseFamilia) {
		this.whClaseFamilia = whClaseFamilia;
	}

	@Column(name = "DescripcionLocal", length = 150)
	public String getDescripcionLocal() {
		return this.descripcionLocal;
	}

	public void setDescripcionLocal(String descripcionLocal) {
		this.descripcionLocal = descripcionLocal;
	}

	@Column(name = "DescripcionIngles", length = 150)
	public String getDescripcionIngles() {
		return this.descripcionIngles;
	}

	public void setDescripcionIngles(String descripcionIngles) {
		this.descripcionIngles = descripcionIngles;
	}

	@Column(name = "DescripcionCompleta", length = 250)
	public String getDescripcionCompleta() {
		return this.descripcionCompleta;
	}

	public void setDescripcionCompleta(String descripcionCompleta) {
		this.descripcionCompleta = descripcionCompleta;
	}

	@Column(name = "ItemTipo", length = 1)
	public Character getItemTipo() {
		return this.itemTipo;
	}

	public void setItemTipo(Character itemTipo) {
		this.itemTipo = itemTipo;
	}

	@Column(name = "TransaccionOperacion", length = 3)
	public String getTransaccionOperacion() {
		return this.transaccionOperacion;
	}

	public void setTransaccionOperacion(String transaccionOperacion) {
		this.transaccionOperacion = transaccionOperacion;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
