package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 16, 2015 3:06:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WhClaseFamiliaId generated by hbm2java
 */
@Embeddable
public class WhClaseFamiliaId implements java.io.Serializable {

	private String linea;
	private String familia;

	public WhClaseFamiliaId() {
	}

	public WhClaseFamiliaId(String linea, String familia) {
		this.linea = linea;
		this.familia = familia;
	}

	@Column(name = "Linea", nullable = false, length = 6)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "Familia", nullable = false, length = 6)
	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WhClaseFamiliaId))
			return false;
		WhClaseFamiliaId castOther = (WhClaseFamiliaId) other;

		return ((this.getLinea() == castOther.getLinea()) || (this.getLinea() != null && castOther.getLinea() != null
				&& this.getLinea().equals(castOther.getLinea())))
				&& ((this.getFamilia() == castOther.getFamilia()) || (this.getFamilia() != null
						&& castOther.getFamilia() != null && this.getFamilia().equals(castOther.getFamilia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLinea() == null ? 0 : this.getLinea().hashCode());
		result = 37 * result + (getFamilia() == null ? 0 : this.getFamilia().hashCode());
		return result;
	}

}
