package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 16, 2015 3:06:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WhClaseSubFamiliaId generated by hbm2java
 */
@Embeddable
public class WhClaseSubFamiliaId implements java.io.Serializable {

	private String linea;
	private String familia;
	private String subFamilia;

	public WhClaseSubFamiliaId() {
	}

	public WhClaseSubFamiliaId(String linea, String familia, String subFamilia) {
		this.linea = linea;
		this.familia = familia;
		this.subFamilia = subFamilia;
	}

	@Column(name = "Linea", nullable = false, length = 6)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "Familia", nullable = false, length = 6)
	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	@Column(name = "SubFamilia", nullable = false, length = 6)
	public String getSubFamilia() {
		return this.subFamilia;
	}

	public void setSubFamilia(String subFamilia) {
		this.subFamilia = subFamilia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WhClaseSubFamiliaId))
			return false;
		WhClaseSubFamiliaId castOther = (WhClaseSubFamiliaId) other;

		return ((this.getLinea() == castOther.getLinea()) || (this.getLinea() != null && castOther.getLinea() != null
				&& this.getLinea().equals(castOther.getLinea())))
				&& ((this.getFamilia() == castOther.getFamilia()) || (this.getFamilia() != null
						&& castOther.getFamilia() != null && this.getFamilia().equals(castOther.getFamilia())))
				&& ((this.getSubFamilia() == castOther.getSubFamilia())
						|| (this.getSubFamilia() != null && castOther.getSubFamilia() != null
								&& this.getSubFamilia().equals(castOther.getSubFamilia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLinea() == null ? 0 : this.getLinea().hashCode());
		result = 37 * result + (getFamilia() == null ? 0 : this.getFamilia().hashCode());
		result = 37 * result + (getSubFamilia() == null ? 0 : this.getSubFamilia().hashCode());
		return result;
	}

}
