package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 16, 2015 3:06:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhClaseFamilia generated by hbm2java
 */
@Entity
@Table(name = "WH_ClaseFamilia")
public class WhClaseFamilia extends Entidad implements java.io.Serializable {

	private WhClaseFamiliaId id;
	private WhClaseLinea whClaseLinea;
	private String descripcionLocal;
	private String descripcionIngles;
	private String descripcionCompleta;
	private String cuentaInventario;
	private String cuentaGasto;
	private String elementoGasto;
	private String partidaPresupuestal;
	private String flujodeCaja;
	private String lineaFamilia;
	private Character loteValidacionFlag;
	private Character medicinaGrupoAflag;
	private Character medicinaGrupoHflag;
	private Character medicinaGrupoEflag;
	private Character medicinaGrupoRflag;
	private String cuentaVentas;
	private String cuentaTransito;
	private String cuentaCostoVentas;
	private String caracteristica01;
	private String caracteristica02;
	private String caracteristica03;
	private String caracteristica04;
	private String caracteristica05;
	private Character estado;
	private String ultimoUsuario;
	private Date ultimaFechaModif;
	private String referenciaFiscal01;
	private String referenciaFiscal02;
	private String referenciaFiscal03;
	private String contactoEmail;
	private String contactoFax;
	private String contactoNombre;
	private String contactoTelefono;
	private String cuentaVentaComercial;
	private String cuentaCompras;
	private String centroCosto;
	private String cuentaServicioTecnico;
	private String accion;
	private Set<WhClaseSubFamilia> whClaseSubFamilias = new HashSet<WhClaseSubFamilia>(0);
	private Set<WhClaseSubFamilia> whClaseSubFamilias_1 = new HashSet<WhClaseSubFamilia>(0);

	public WhClaseFamilia() {
	}

	public WhClaseFamilia(WhClaseFamiliaId id, WhClaseLinea whClaseLinea) {
		this.id = id;
		this.whClaseLinea = whClaseLinea;
	}

	public WhClaseFamilia(WhClaseFamiliaId id, WhClaseLinea whClaseLinea, String descripcionLocal,
			String descripcionIngles, String descripcionCompleta, String cuentaInventario, String cuentaGasto,
			String elementoGasto, String partidaPresupuestal, String flujodeCaja, String lineaFamilia,
			Character loteValidacionFlag, Character medicinaGrupoAflag, Character medicinaGrupoHflag,
			Character medicinaGrupoEflag, Character medicinaGrupoRflag, String cuentaVentas, String cuentaTransito,
			String cuentaCostoVentas, String caracteristica01, String caracteristica02, String caracteristica03,
			String caracteristica04, String caracteristica05, Character estado, String ultimoUsuario,
			Date ultimaFechaModif, String referenciaFiscal01, String referenciaFiscal02, String referenciaFiscal03,
			String contactoEmail, String contactoFax, String contactoNombre, String contactoTelefono,
			String cuentaVentaComercial, String cuentaCompras, String centroCosto, String cuentaServicioTecnico,
			String accion, Set<WhClaseSubFamilia> whClaseSubFamilias, Set<WhClaseSubFamilia> whClaseSubFamilias_1) {
		this.id = id;
		this.whClaseLinea = whClaseLinea;
		this.descripcionLocal = descripcionLocal;
		this.descripcionIngles = descripcionIngles;
		this.descripcionCompleta = descripcionCompleta;
		this.cuentaInventario = cuentaInventario;
		this.cuentaGasto = cuentaGasto;
		this.elementoGasto = elementoGasto;
		this.partidaPresupuestal = partidaPresupuestal;
		this.flujodeCaja = flujodeCaja;
		this.lineaFamilia = lineaFamilia;
		this.loteValidacionFlag = loteValidacionFlag;
		this.medicinaGrupoAflag = medicinaGrupoAflag;
		this.medicinaGrupoHflag = medicinaGrupoHflag;
		this.medicinaGrupoEflag = medicinaGrupoEflag;
		this.medicinaGrupoRflag = medicinaGrupoRflag;
		this.cuentaVentas = cuentaVentas;
		this.cuentaTransito = cuentaTransito;
		this.cuentaCostoVentas = cuentaCostoVentas;
		this.caracteristica01 = caracteristica01;
		this.caracteristica02 = caracteristica02;
		this.caracteristica03 = caracteristica03;
		this.caracteristica04 = caracteristica04;
		this.caracteristica05 = caracteristica05;
		this.estado = estado;
		this.ultimoUsuario = ultimoUsuario;
		this.ultimaFechaModif = ultimaFechaModif;
		this.referenciaFiscal01 = referenciaFiscal01;
		this.referenciaFiscal02 = referenciaFiscal02;
		this.referenciaFiscal03 = referenciaFiscal03;
		this.contactoEmail = contactoEmail;
		this.contactoFax = contactoFax;
		this.contactoNombre = contactoNombre;
		this.contactoTelefono = contactoTelefono;
		this.cuentaVentaComercial = cuentaVentaComercial;
		this.cuentaCompras = cuentaCompras;
		this.centroCosto = centroCosto;
		this.cuentaServicioTecnico = cuentaServicioTecnico;
		this.accion = accion;
		this.whClaseSubFamilias = whClaseSubFamilias;
		this.whClaseSubFamilias_1 = whClaseSubFamilias_1;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "linea", column = @Column(name = "Linea", nullable = false, length = 6) ),
			@AttributeOverride(name = "familia", column = @Column(name = "Familia", nullable = false, length = 6) ) })
	public WhClaseFamiliaId getId() {
		return this.id;
	}

	public void setId(WhClaseFamiliaId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "Linea", nullable = false, insertable = false, updatable = false)
	public WhClaseLinea getWhClaseLinea() {
		return this.whClaseLinea;
	}

	public void setWhClaseLinea(WhClaseLinea whClaseLinea) {
		this.whClaseLinea = whClaseLinea;
	}

	@Column(name = "DescripcionLocal", length = 150)
	public String getDescripcionLocal() {
		return this.descripcionLocal;
	}

	public void setDescripcionLocal(String descripcionLocal) {
		this.descripcionLocal = descripcionLocal;
	}

	@Column(name = "DescripcionIngles", length = 150)
	public String getDescripcionIngles() {
		return this.descripcionIngles;
	}

	public void setDescripcionIngles(String descripcionIngles) {
		this.descripcionIngles = descripcionIngles;
	}

	@Column(name = "DescripcionCompleta", length = 150)
	public String getDescripcionCompleta() {
		return this.descripcionCompleta;
	}

	public void setDescripcionCompleta(String descripcionCompleta) {
		this.descripcionCompleta = descripcionCompleta;
	}

	@Column(name = "CuentaInventario", length = 20)
	public String getCuentaInventario() {
		return this.cuentaInventario;
	}

	public void setCuentaInventario(String cuentaInventario) {
		this.cuentaInventario = cuentaInventario;
	}

	@Column(name = "CuentaGasto", length = 20)
	public String getCuentaGasto() {
		return this.cuentaGasto;
	}

	public void setCuentaGasto(String cuentaGasto) {
		this.cuentaGasto = cuentaGasto;
	}

	@Column(name = "ElementoGasto", length = 6)
	public String getElementoGasto() {
		return this.elementoGasto;
	}

	public void setElementoGasto(String elementoGasto) {
		this.elementoGasto = elementoGasto;
	}

	@Column(name = "PartidaPresupuestal", length = 4)
	public String getPartidaPresupuestal() {
		return this.partidaPresupuestal;
	}

	public void setPartidaPresupuestal(String partidaPresupuestal) {
		this.partidaPresupuestal = partidaPresupuestal;
	}

	@Column(name = "FlujodeCaja", length = 4)
	public String getFlujodeCaja() {
		return this.flujodeCaja;
	}

	public void setFlujodeCaja(String flujodeCaja) {
		this.flujodeCaja = flujodeCaja;
	}

	@Column(name = "LineaFamilia", length = 12)
	public String getLineaFamilia() {
		return this.lineaFamilia;
	}

	public void setLineaFamilia(String lineaFamilia) {
		this.lineaFamilia = lineaFamilia;
	}

	@Column(name = "LoteValidacionFlag", length = 1)
	public Character getLoteValidacionFlag() {
		return this.loteValidacionFlag;
	}

	public void setLoteValidacionFlag(Character loteValidacionFlag) {
		this.loteValidacionFlag = loteValidacionFlag;
	}

	@Column(name = "MedicinaGrupoAFlag", length = 1)
	public Character getMedicinaGrupoAflag() {
		return this.medicinaGrupoAflag;
	}

	public void setMedicinaGrupoAflag(Character medicinaGrupoAflag) {
		this.medicinaGrupoAflag = medicinaGrupoAflag;
	}

	@Column(name = "MedicinaGrupoHFlag", length = 1)
	public Character getMedicinaGrupoHflag() {
		return this.medicinaGrupoHflag;
	}

	public void setMedicinaGrupoHflag(Character medicinaGrupoHflag) {
		this.medicinaGrupoHflag = medicinaGrupoHflag;
	}

	@Column(name = "MedicinaGrupoEFlag", length = 1)
	public Character getMedicinaGrupoEflag() {
		return this.medicinaGrupoEflag;
	}

	public void setMedicinaGrupoEflag(Character medicinaGrupoEflag) {
		this.medicinaGrupoEflag = medicinaGrupoEflag;
	}

	@Column(name = "MedicinaGrupoRFlag", length = 1)
	public Character getMedicinaGrupoRflag() {
		return this.medicinaGrupoRflag;
	}

	public void setMedicinaGrupoRflag(Character medicinaGrupoRflag) {
		this.medicinaGrupoRflag = medicinaGrupoRflag;
	}

	@Column(name = "CuentaVentas", length = 20)
	public String getCuentaVentas() {
		return this.cuentaVentas;
	}

	public void setCuentaVentas(String cuentaVentas) {
		this.cuentaVentas = cuentaVentas;
	}

	@Column(name = "CuentaTransito", length = 20)
	public String getCuentaTransito() {
		return this.cuentaTransito;
	}

	public void setCuentaTransito(String cuentaTransito) {
		this.cuentaTransito = cuentaTransito;
	}

	@Column(name = "CuentaCostoVentas", length = 20)
	public String getCuentaCostoVentas() {
		return this.cuentaCostoVentas;
	}

	public void setCuentaCostoVentas(String cuentaCostoVentas) {
		this.cuentaCostoVentas = cuentaCostoVentas;
	}

	@Column(name = "Caracteristica01", length = 3)
	public String getCaracteristica01() {
		return this.caracteristica01;
	}

	public void setCaracteristica01(String caracteristica01) {
		this.caracteristica01 = caracteristica01;
	}

	@Column(name = "Caracteristica02", length = 3)
	public String getCaracteristica02() {
		return this.caracteristica02;
	}

	public void setCaracteristica02(String caracteristica02) {
		this.caracteristica02 = caracteristica02;
	}

	@Column(name = "Caracteristica03", length = 3)
	public String getCaracteristica03() {
		return this.caracteristica03;
	}

	public void setCaracteristica03(String caracteristica03) {
		this.caracteristica03 = caracteristica03;
	}

	@Column(name = "Caracteristica04", length = 3)
	public String getCaracteristica04() {
		return this.caracteristica04;
	}

	public void setCaracteristica04(String caracteristica04) {
		this.caracteristica04 = caracteristica04;
	}

	@Column(name = "Caracteristica05", length = 3)
	public String getCaracteristica05() {
		return this.caracteristica05;
	}

	public void setCaracteristica05(String caracteristica05) {
		this.caracteristica05 = caracteristica05;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "ReferenciaFiscal01", length = 10)
	public String getReferenciaFiscal01() {
		return this.referenciaFiscal01;
	}

	public void setReferenciaFiscal01(String referenciaFiscal01) {
		this.referenciaFiscal01 = referenciaFiscal01;
	}

	@Column(name = "ReferenciaFiscal02", length = 20)
	public String getReferenciaFiscal02() {
		return this.referenciaFiscal02;
	}

	public void setReferenciaFiscal02(String referenciaFiscal02) {
		this.referenciaFiscal02 = referenciaFiscal02;
	}

	@Column(name = "ReferenciaFiscal03", length = 10)
	public String getReferenciaFiscal03() {
		return this.referenciaFiscal03;
	}

	public void setReferenciaFiscal03(String referenciaFiscal03) {
		this.referenciaFiscal03 = referenciaFiscal03;
	}

	@Column(name = "ContactoEMail", length = 50)
	public String getContactoEmail() {
		return this.contactoEmail;
	}

	public void setContactoEmail(String contactoEmail) {
		this.contactoEmail = contactoEmail;
	}

	@Column(name = "ContactoFax", length = 10)
	public String getContactoFax() {
		return this.contactoFax;
	}

	public void setContactoFax(String contactoFax) {
		this.contactoFax = contactoFax;
	}

	@Column(name = "ContactoNombre", length = 50)
	public String getContactoNombre() {
		return this.contactoNombre;
	}

	public void setContactoNombre(String contactoNombre) {
		this.contactoNombre = contactoNombre;
	}

	@Column(name = "ContactoTelefono", length = 10)
	public String getContactoTelefono() {
		return this.contactoTelefono;
	}

	public void setContactoTelefono(String contactoTelefono) {
		this.contactoTelefono = contactoTelefono;
	}

	@Column(name = "CuentaVentaComercial", length = 25)
	public String getCuentaVentaComercial() {
		return this.cuentaVentaComercial;
	}

	public void setCuentaVentaComercial(String cuentaVentaComercial) {
		this.cuentaVentaComercial = cuentaVentaComercial;
	}

	@Column(name = "CuentaCompras", length = 20)
	public String getCuentaCompras() {
		return this.cuentaCompras;
	}

	public void setCuentaCompras(String cuentaCompras) {
		this.cuentaCompras = cuentaCompras;
	}

	@Column(name = "CentroCosto", length = 15)
	public String getCentroCosto() {
		return this.centroCosto;
	}

	public void setCentroCosto(String centroCosto) {
		this.centroCosto = centroCosto;
	}

	@Column(name = "CuentaServicioTecnico", length = 20)
	public String getCuentaServicioTecnico() {
		return this.cuentaServicioTecnico;
	}

	public void setCuentaServicioTecnico(String cuentaServicioTecnico) {
		this.cuentaServicioTecnico = cuentaServicioTecnico;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "whClaseFamilia")
	public Set<WhClaseSubFamilia> getWhClaseSubFamilias() {
		return this.whClaseSubFamilias;
	}

	public void setWhClaseSubFamilias(Set<WhClaseSubFamilia> whClaseSubFamilias) {
		this.whClaseSubFamilias = whClaseSubFamilias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "whClaseFamilia")
	public Set<WhClaseSubFamilia> getWhClaseSubFamilias_1() {
		return this.whClaseSubFamilias_1;
	}

	public void setWhClaseSubFamilias_1(Set<WhClaseSubFamilia> whClaseSubFamilias_1) {
		this.whClaseSubFamilias_1 = whClaseSubFamilias_1;
	}

}
