package pe.royalsystems.springerp.model.domain;

// default package
// Generated Sep 16, 2015 3:06:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhClaseLinea generated by hbm2java
 */
@Entity
@Table(name = "WH_ClaseLinea")
public class WhClaseLinea extends Entidad implements java.io.Serializable {

	private String linea;
	private String descripcionLocal;
	private String descripcionIngles;
	private String grupoLinea;
	private String manejoColorSerieFlag;
	private Character estado;
	private Date ultimaFechaModif;
	private String ultimoUsuario;
	private String accion;
	private Set<WhClaseFamilia> whClaseFamilias = new HashSet<WhClaseFamilia>(0);
	private Set<WhClaseFamilia> whClaseFamilias_1 = new HashSet<WhClaseFamilia>(0);

	public WhClaseLinea() {
	}

	public WhClaseLinea(String linea) {
		this.linea = linea;
	}

	public WhClaseLinea(String linea, String descripcionLocal, String descripcionIngles, String grupoLinea,
			String manejoColorSerieFlag, Character estado, Date ultimaFechaModif, String ultimoUsuario, String accion,
			Set<WhClaseFamilia> whClaseFamilias, Set<WhClaseFamilia> whClaseFamilias_1) {
		this.linea = linea;
		this.descripcionLocal = descripcionLocal;
		this.descripcionIngles = descripcionIngles;
		this.grupoLinea = grupoLinea;
		this.manejoColorSerieFlag = manejoColorSerieFlag;
		this.estado = estado;
		this.ultimaFechaModif = ultimaFechaModif;
		this.ultimoUsuario = ultimoUsuario;
		this.accion = accion;
		this.whClaseFamilias = whClaseFamilias;
		this.whClaseFamilias_1 = whClaseFamilias_1;
	}

	@Id

	@Column(name = "Linea", unique = true, nullable = false, length = 6)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "DescripcionLocal", length = 30)
	public String getDescripcionLocal() {
		return this.descripcionLocal;
	}

	public void setDescripcionLocal(String descripcionLocal) {
		this.descripcionLocal = descripcionLocal;
	}

	@Column(name = "DescripcionIngles", length = 30)
	public String getDescripcionIngles() {
		return this.descripcionIngles;
	}

	public void setDescripcionIngles(String descripcionIngles) {
		this.descripcionIngles = descripcionIngles;
	}

	@Column(name = "GrupoLinea", length = 2)
	public String getGrupoLinea() {
		return this.grupoLinea;
	}

	public void setGrupoLinea(String grupoLinea) {
		this.grupoLinea = grupoLinea;
	}

	@Column(name = "ManejoColorSerieFlag", length = 18)
	public String getManejoColorSerieFlag() {
		return this.manejoColorSerieFlag;
	}

	public void setManejoColorSerieFlag(String manejoColorSerieFlag) {
		this.manejoColorSerieFlag = manejoColorSerieFlag;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "whClaseLinea")
	public Set<WhClaseFamilia> getWhClaseFamilias() {
		return this.whClaseFamilias;
	}

	public void setWhClaseFamilias(Set<WhClaseFamilia> whClaseFamilias) {
		this.whClaseFamilias = whClaseFamilias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "whClaseLinea")
	public Set<WhClaseFamilia> getWhClaseFamilias_1() {
		return this.whClaseFamilias_1;
	}

	public void setWhClaseFamilias_1(Set<WhClaseFamilia> whClaseFamilias_1) {
		this.whClaseFamilias_1 = whClaseFamilias_1;
	}

}
