package pe.royalsystems.springerp.model.domain;
// Generated Aug 27, 2015 10:25:40 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhItemMast generated by hbm2java
 */
@Entity
@Table(name = "WH_ItemMast")
public class WhItemMast extends Entidad implements java.io.Serializable {

	private String item;
	private String itemTipo;
	private String linea;
	private String familia;
	private String subFamilia;
	private String subFamiliaInferior;
	private String descripcionLocal;
	private String descripcionIngles;
	private String descripcionCompleta;
	private String numeroDeParte;
	private String codigoInterno;
	private String unidadCodigo;
	private String unidadCompra;
	private String unidadEmbalaje;
	private String color;
	private String modelo;
	private String marcaCodigo;
	private String itemProcedencia;
	private String clasificacionComercial;
	private String partidaArancelaria;
	private String codigoBarras;
	private String codigoBarrasFabricante;
	private String codigoBarras2;
	private String monedaCodigo;
	private BigDecimal precioCosto;
	private BigDecimal precioUnitarioLocal;
	private BigDecimal precioUnitarioDolares;
	private Character itemPrecioFlag;
	private String itemPrecioCodigo;
	private Character disponibleVentaFlag;
	private Character manejoxLoteFlag;
	private Character manejoxSerieFlag;
	private Character manejoxKitFlag;
	private Character manejoxKitSplitFlag;
	private Character manejoxUnidadFlag;
	private Character afectoImpuestoVentasFlag;
	private Character afectoImpuesto2flag;
	private Character requisicionamientoAutomaticoFl;
	private Character controlCalidadFlag;
	private Character disponibleTransferenciaFlag;
	private Character disponibleConsumoFlag;
	private Character formularioFlag;
	private Integer formularioNroJuegos;
	private Character isoaplicableFlag;
	private String isonormaInterna;
	private Character cantidadDobleFlag;
	private BigDecimal cantidadDobleFactor;
	private String unidadCodigoDoble;
	private String unidadReplicacion;
	private String imageFile;
	private String mapaFile;
	private String cuentaInventario;
	private String cuentaGasto;
	private String cuentaInversion;
	private String cuentaServicioTecnico;
	private String cuentaSalidaTerceros;
	private String cuentaVentas;
	private String cuentaTransito;
	private String elementoGasto;
	private String elementoInversion;
	private String partidaPresupuestal;
	private String flujodeCaja;
	private Integer lotedeCompra;
	private BigDecimal lotedeDespacho;
	private BigDecimal lotedeCompraM3;
	private BigDecimal lotedeCompraKg;
	private BigDecimal periodicidadCompraMeses;
	private String especificacionTecnica;
	private String dimensiones;
	private BigDecimal factorEquivalenciaComercial;
	private String abccodigo;
	private BigDecimal inventarioTolerancia;
	private BigDecimal stockMinimo;
	private BigDecimal stockMaximo;
	private Integer lotedeVenta;
	private String descripcionAdicional;
	private String codigoPrecio;
	private String caracteristicaValor01;
	private String caracteristicaValor02;
	private String caracteristicaValor03;
	private String caracteristicaValor04;
	private String caracteristicaValor05;
	private String referenciaFiscal02;
	private String referenciaFiscalIngreso02;
	private String detraccionCodigo;
	private Character estado;
	private Character periodicidadCompra;
	private Date ultimaFechaModif;
	private String ultimoUsuario;
	private String centrocosto;
	private String conceptoGasto;
	private String clasificadorMovimiento;
	private String flujodeCajaIngreso;
	private String mapaCodigo;
	private String paisfabricacion;
	private String abccodigoIn;
	private String lectura;
	private Integer idGrupoComponente;
	private Integer idRegimenVenta;
	private Integer indicadorReemplazo;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String cuentaVentaComercial;
	private String cuentaDescuentoVentaComercial;
	private Integer indicadorCuentaVenta;
	private String tipoRepuesto;
	private Integer cantidadkit;
	private Integer periodoInicioReposicion;
	private Integer periodosReposicion;
	private Integer indicadorClasificacion;
	private Integer peridoInicioReposicion;
	private Integer idClasificacion;
	private BigDecimal cantidadReposicion;
	private String grupoReposicion;
	private Integer indicadorReposicion;
	private Integer indicadorPrecioManual;
	private Integer indicadorConsumoFraccionado;
	private String nombreLaboratorio;
	private String estadoAnterior;
	private String cuentaCompras;
	private BigDecimal precioCostoAnt;
	private String ultimaOc;
	private String previaOc;
	private String tipomedicamento;
	private String codigoDigemid;
	private String ean13;
	private String medicamentoCodigo;
	private String medicamentoCodigoPadre;
	private String nombreTabla;
	private Integer tipofolder;
	private String accion;

	public WhItemMast() {
	}

	public WhItemMast(String item) {
		this.item = item;
	}

	public WhItemMast(String item, String itemTipo, String linea, String familia, String subFamilia,
			String subFamiliaInferior, String descripcionLocal, String descripcionIngles, String descripcionCompleta,
			String numeroDeParte, String codigoInterno, String unidadCodigo, String unidadCompra, String unidadEmbalaje,
			String color, String modelo, String marcaCodigo, String itemProcedencia, String clasificacionComercial,
			String partidaArancelaria, String codigoBarras, String codigoBarrasFabricante, String codigoBarras2,
			String monedaCodigo, BigDecimal precioCosto, BigDecimal precioUnitarioLocal,
			BigDecimal precioUnitarioDolares, Character itemPrecioFlag, String itemPrecioCodigo,
			Character disponibleVentaFlag, Character manejoxLoteFlag, Character manejoxSerieFlag,
			Character manejoxKitFlag, Character manejoxKitSplitFlag, Character manejoxUnidadFlag,
			Character afectoImpuestoVentasFlag, Character afectoImpuesto2flag, Character requisicionamientoAutomaticoFl,
			Character controlCalidadFlag, Character disponibleTransferenciaFlag, Character disponibleConsumoFlag,
			Character formularioFlag, Integer formularioNroJuegos, Character isoaplicableFlag, String isonormaInterna,
			Character cantidadDobleFlag, BigDecimal cantidadDobleFactor, String unidadCodigoDoble,
			String unidadReplicacion, String imageFile, String mapaFile, String cuentaInventario, String cuentaGasto,
			String cuentaInversion, String cuentaServicioTecnico, String cuentaSalidaTerceros, String cuentaVentas,
			String cuentaTransito, String elementoGasto, String elementoInversion, String partidaPresupuestal,
			String flujodeCaja, Integer lotedeCompra, BigDecimal lotedeDespacho, BigDecimal lotedeCompraM3,
			BigDecimal lotedeCompraKg, BigDecimal periodicidadCompraMeses, String especificacionTecnica,
			String dimensiones, BigDecimal factorEquivalenciaComercial, String abccodigo,
			BigDecimal inventarioTolerancia, BigDecimal stockMinimo, BigDecimal stockMaximo, Integer lotedeVenta,
			String descripcionAdicional, String codigoPrecio, String caracteristicaValor01,
			String caracteristicaValor02, String caracteristicaValor03, String caracteristicaValor04,
			String caracteristicaValor05, String referenciaFiscal02, String referenciaFiscalIngreso02,
			String detraccionCodigo, Character estado, Character periodicidadCompra, Date ultimaFechaModif,
			String ultimoUsuario, String centrocosto, String conceptoGasto, String clasificadorMovimiento,
			String flujodeCajaIngreso, String mapaCodigo, String paisfabricacion, String abccodigoIn, String lectura,
			Integer idGrupoComponente, Integer idRegimenVenta, Integer indicadorReemplazo, String usuarioCreacion,
			Date fechaCreacion, String cuentaVentaComercial, String cuentaDescuentoVentaComercial,
			Integer indicadorCuentaVenta, String tipoRepuesto, Integer cantidadkit, Integer periodoInicioReposicion,
			Integer periodosReposicion, Integer indicadorClasificacion, Integer peridoInicioReposicion,
			Integer idClasificacion, BigDecimal cantidadReposicion, String grupoReposicion, Integer indicadorReposicion,
			Integer indicadorPrecioManual, Integer indicadorConsumoFraccionado, String nombreLaboratorio,
			String estadoAnterior, String cuentaCompras, BigDecimal precioCostoAnt, String ultimaOc, String previaOc,
			String tipomedicamento, String codigoDigemid, String ean13, String medicamentoCodigo,
			String medicamentoCodigoPadre, String nombreTabla, Integer tipofolder, String accion) {
		this.item = item;
		this.itemTipo = itemTipo;
		this.linea = linea;
		this.familia = familia;
		this.subFamilia = subFamilia;
		this.subFamiliaInferior = subFamiliaInferior;
		this.descripcionLocal = descripcionLocal;
		this.descripcionIngles = descripcionIngles;
		this.descripcionCompleta = descripcionCompleta;
		this.numeroDeParte = numeroDeParte;
		this.codigoInterno = codigoInterno;
		this.unidadCodigo = unidadCodigo;
		this.unidadCompra = unidadCompra;
		this.unidadEmbalaje = unidadEmbalaje;
		this.color = color;
		this.modelo = modelo;
		this.marcaCodigo = marcaCodigo;
		this.itemProcedencia = itemProcedencia;
		this.clasificacionComercial = clasificacionComercial;
		this.partidaArancelaria = partidaArancelaria;
		this.codigoBarras = codigoBarras;
		this.codigoBarrasFabricante = codigoBarrasFabricante;
		this.codigoBarras2 = codigoBarras2;
		this.monedaCodigo = monedaCodigo;
		this.precioCosto = precioCosto;
		this.precioUnitarioLocal = precioUnitarioLocal;
		this.precioUnitarioDolares = precioUnitarioDolares;
		this.itemPrecioFlag = itemPrecioFlag;
		this.itemPrecioCodigo = itemPrecioCodigo;
		this.disponibleVentaFlag = disponibleVentaFlag;
		this.manejoxLoteFlag = manejoxLoteFlag;
		this.manejoxSerieFlag = manejoxSerieFlag;
		this.manejoxKitFlag = manejoxKitFlag;
		this.manejoxKitSplitFlag = manejoxKitSplitFlag;
		this.manejoxUnidadFlag = manejoxUnidadFlag;
		this.afectoImpuestoVentasFlag = afectoImpuestoVentasFlag;
		this.afectoImpuesto2flag = afectoImpuesto2flag;
		this.requisicionamientoAutomaticoFl = requisicionamientoAutomaticoFl;
		this.controlCalidadFlag = controlCalidadFlag;
		this.disponibleTransferenciaFlag = disponibleTransferenciaFlag;
		this.disponibleConsumoFlag = disponibleConsumoFlag;
		this.formularioFlag = formularioFlag;
		this.formularioNroJuegos = formularioNroJuegos;
		this.isoaplicableFlag = isoaplicableFlag;
		this.isonormaInterna = isonormaInterna;
		this.cantidadDobleFlag = cantidadDobleFlag;
		this.cantidadDobleFactor = cantidadDobleFactor;
		this.unidadCodigoDoble = unidadCodigoDoble;
		this.unidadReplicacion = unidadReplicacion;
		this.imageFile = imageFile;
		this.mapaFile = mapaFile;
		this.cuentaInventario = cuentaInventario;
		this.cuentaGasto = cuentaGasto;
		this.cuentaInversion = cuentaInversion;
		this.cuentaServicioTecnico = cuentaServicioTecnico;
		this.cuentaSalidaTerceros = cuentaSalidaTerceros;
		this.cuentaVentas = cuentaVentas;
		this.cuentaTransito = cuentaTransito;
		this.elementoGasto = elementoGasto;
		this.elementoInversion = elementoInversion;
		this.partidaPresupuestal = partidaPresupuestal;
		this.flujodeCaja = flujodeCaja;
		this.lotedeCompra = lotedeCompra;
		this.lotedeDespacho = lotedeDespacho;
		this.lotedeCompraM3 = lotedeCompraM3;
		this.lotedeCompraKg = lotedeCompraKg;
		this.periodicidadCompraMeses = periodicidadCompraMeses;
		this.especificacionTecnica = especificacionTecnica;
		this.dimensiones = dimensiones;
		this.factorEquivalenciaComercial = factorEquivalenciaComercial;
		this.abccodigo = abccodigo;
		this.inventarioTolerancia = inventarioTolerancia;
		this.stockMinimo = stockMinimo;
		this.stockMaximo = stockMaximo;
		this.lotedeVenta = lotedeVenta;
		this.descripcionAdicional = descripcionAdicional;
		this.codigoPrecio = codigoPrecio;
		this.caracteristicaValor01 = caracteristicaValor01;
		this.caracteristicaValor02 = caracteristicaValor02;
		this.caracteristicaValor03 = caracteristicaValor03;
		this.caracteristicaValor04 = caracteristicaValor04;
		this.caracteristicaValor05 = caracteristicaValor05;
		this.referenciaFiscal02 = referenciaFiscal02;
		this.referenciaFiscalIngreso02 = referenciaFiscalIngreso02;
		this.detraccionCodigo = detraccionCodigo;
		this.estado = estado;
		this.periodicidadCompra = periodicidadCompra;
		this.ultimaFechaModif = ultimaFechaModif;
		this.ultimoUsuario = ultimoUsuario;
		this.centrocosto = centrocosto;
		this.conceptoGasto = conceptoGasto;
		this.clasificadorMovimiento = clasificadorMovimiento;
		this.flujodeCajaIngreso = flujodeCajaIngreso;
		this.mapaCodigo = mapaCodigo;
		this.paisfabricacion = paisfabricacion;
		this.abccodigoIn = abccodigoIn;
		this.lectura = lectura;
		this.idGrupoComponente = idGrupoComponente;
		this.idRegimenVenta = idRegimenVenta;
		this.indicadorReemplazo = indicadorReemplazo;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.cuentaVentaComercial = cuentaVentaComercial;
		this.cuentaDescuentoVentaComercial = cuentaDescuentoVentaComercial;
		this.indicadorCuentaVenta = indicadorCuentaVenta;
		this.tipoRepuesto = tipoRepuesto;
		this.cantidadkit = cantidadkit;
		this.periodoInicioReposicion = periodoInicioReposicion;
		this.periodosReposicion = periodosReposicion;
		this.indicadorClasificacion = indicadorClasificacion;
		this.peridoInicioReposicion = peridoInicioReposicion;
		this.idClasificacion = idClasificacion;
		this.cantidadReposicion = cantidadReposicion;
		this.grupoReposicion = grupoReposicion;
		this.indicadorReposicion = indicadorReposicion;
		this.indicadorPrecioManual = indicadorPrecioManual;
		this.indicadorConsumoFraccionado = indicadorConsumoFraccionado;
		this.nombreLaboratorio = nombreLaboratorio;
		this.estadoAnterior = estadoAnterior;
		this.cuentaCompras = cuentaCompras;
		this.precioCostoAnt = precioCostoAnt;
		this.ultimaOc = ultimaOc;
		this.previaOc = previaOc;
		this.tipomedicamento = tipomedicamento;
		this.codigoDigemid = codigoDigemid;
		this.ean13 = ean13;
		this.medicamentoCodigo = medicamentoCodigo;
		this.medicamentoCodigoPadre = medicamentoCodigoPadre;
		this.nombreTabla = nombreTabla;
		this.tipofolder = tipofolder;
		this.accion = accion;
	}

	@Id

	@Column(name = "Item", unique = true, nullable = false, length = 50)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "ItemTipo", length = 2)
	public String getItemTipo() {
		return this.itemTipo;
	}

	public void setItemTipo(String itemTipo) {
		this.itemTipo = itemTipo;
	}

	@Column(name = "Linea", length = 6)
	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	@Column(name = "Familia", length = 6)
	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	@Column(name = "SubFamilia", length = 6)
	public String getSubFamilia() {
		return this.subFamilia;
	}

	public void setSubFamilia(String subFamilia) {
		this.subFamilia = subFamilia;
	}

	@Column(name = "SubFamiliaInferior", length = 6)
	public String getSubFamiliaInferior() {
		return this.subFamiliaInferior;
	}

	public void setSubFamiliaInferior(String subFamiliaInferior) {
		this.subFamiliaInferior = subFamiliaInferior;
	}

	@Column(name = "DescripcionLocal")
	public String getDescripcionLocal() {
		return this.descripcionLocal;
	}

	public void setDescripcionLocal(String descripcionLocal) {
		this.descripcionLocal = descripcionLocal;
	}

	@Column(name = "DescripcionIngles")
	public String getDescripcionIngles() {
		return this.descripcionIngles;
	}

	public void setDescripcionIngles(String descripcionIngles) {
		this.descripcionIngles = descripcionIngles;
	}

	@Column(name = "DescripcionCompleta")
	public String getDescripcionCompleta() {
		return this.descripcionCompleta;
	}

	public void setDescripcionCompleta(String descripcionCompleta) {
		this.descripcionCompleta = descripcionCompleta;
	}

	@Column(name = "NumeroDeParte", length = 20)
	public String getNumeroDeParte() {
		return this.numeroDeParte;
	}

	public void setNumeroDeParte(String numeroDeParte) {
		this.numeroDeParte = numeroDeParte;
	}

	@Column(name = "CodigoInterno", length = 20)
	public String getCodigoInterno() {
		return this.codigoInterno;
	}

	public void setCodigoInterno(String codigoInterno) {
		this.codigoInterno = codigoInterno;
	}

	@Column(name = "UnidadCodigo", length = 6)
	public String getUnidadCodigo() {
		return this.unidadCodigo;
	}

	public void setUnidadCodigo(String unidadCodigo) {
		this.unidadCodigo = unidadCodigo;
	}

	@Column(name = "UnidadCompra", length = 6)
	public String getUnidadCompra() {
		return this.unidadCompra;
	}

	public void setUnidadCompra(String unidadCompra) {
		this.unidadCompra = unidadCompra;
	}

	@Column(name = "UnidadEmbalaje", length = 6)
	public String getUnidadEmbalaje() {
		return this.unidadEmbalaje;
	}

	public void setUnidadEmbalaje(String unidadEmbalaje) {
		this.unidadEmbalaje = unidadEmbalaje;
	}

	@Column(name = "Color", length = 3)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "Modelo", length = 20)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "MarcaCodigo", length = 4)
	public String getMarcaCodigo() {
		return this.marcaCodigo;
	}

	public void setMarcaCodigo(String marcaCodigo) {
		this.marcaCodigo = marcaCodigo;
	}

	@Column(name = "ItemProcedencia", length = 10)
	public String getItemProcedencia() {
		return this.itemProcedencia;
	}

	public void setItemProcedencia(String itemProcedencia) {
		this.itemProcedencia = itemProcedencia;
	}

	@Column(name = "ClasificacionComercial", length = 6)
	public String getClasificacionComercial() {
		return this.clasificacionComercial;
	}

	public void setClasificacionComercial(String clasificacionComercial) {
		this.clasificacionComercial = clasificacionComercial;
	}

	@Column(name = "PartidaArancelaria", length = 10)
	public String getPartidaArancelaria() {
		return this.partidaArancelaria;
	}

	public void setPartidaArancelaria(String partidaArancelaria) {
		this.partidaArancelaria = partidaArancelaria;
	}

	@Column(name = "CodigoBarras", length = 25)
	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	@Column(name = "CodigoBarrasFabricante", length = 13)
	public String getCodigoBarrasFabricante() {
		return this.codigoBarrasFabricante;
	}

	public void setCodigoBarrasFabricante(String codigoBarrasFabricante) {
		this.codigoBarrasFabricante = codigoBarrasFabricante;
	}

	@Column(name = "CodigoBarras2", length = 30)
	public String getCodigoBarras2() {
		return this.codigoBarras2;
	}

	public void setCodigoBarras2(String codigoBarras2) {
		this.codigoBarras2 = codigoBarras2;
	}

	@Column(name = "MonedaCodigo", length = 2)
	public String getMonedaCodigo() {
		return this.monedaCodigo;
	}

	public void setMonedaCodigo(String monedaCodigo) {
		this.monedaCodigo = monedaCodigo;
	}

	@Column(name = "PrecioCosto", precision = 16, scale = 6)
	public BigDecimal getPrecioCosto() {
		return this.precioCosto;
	}

	public void setPrecioCosto(BigDecimal precioCosto) {
		this.precioCosto = precioCosto;
	}

	@Column(name = "PrecioUnitarioLocal", precision = 16, scale = 6)
	public BigDecimal getPrecioUnitarioLocal() {
		return this.precioUnitarioLocal;
	}

	public void setPrecioUnitarioLocal(BigDecimal precioUnitarioLocal) {
		this.precioUnitarioLocal = precioUnitarioLocal;
	}

	@Column(name = "PrecioUnitarioDolares", precision = 16, scale = 6)
	public BigDecimal getPrecioUnitarioDolares() {
		return this.precioUnitarioDolares;
	}

	public void setPrecioUnitarioDolares(BigDecimal precioUnitarioDolares) {
		this.precioUnitarioDolares = precioUnitarioDolares;
	}

	@Column(name = "ItemPrecioFlag", length = 1)
	public Character getItemPrecioFlag() {
		return this.itemPrecioFlag;
	}

	public void setItemPrecioFlag(Character itemPrecioFlag) {
		this.itemPrecioFlag = itemPrecioFlag;
	}

	@Column(name = "ItemPrecioCodigo", length = 20)
	public String getItemPrecioCodigo() {
		return this.itemPrecioCodigo;
	}

	public void setItemPrecioCodigo(String itemPrecioCodigo) {
		this.itemPrecioCodigo = itemPrecioCodigo;
	}

	@Column(name = "DisponibleVentaFlag", length = 1)
	public Character getDisponibleVentaFlag() {
		return this.disponibleVentaFlag;
	}

	public void setDisponibleVentaFlag(Character disponibleVentaFlag) {
		this.disponibleVentaFlag = disponibleVentaFlag;
	}

	@Column(name = "ManejoxLoteFlag", length = 1)
	public Character getManejoxLoteFlag() {
		return this.manejoxLoteFlag;
	}

	public void setManejoxLoteFlag(Character manejoxLoteFlag) {
		this.manejoxLoteFlag = manejoxLoteFlag;
	}

	@Column(name = "ManejoxSerieFlag", length = 1)
	public Character getManejoxSerieFlag() {
		return this.manejoxSerieFlag;
	}

	public void setManejoxSerieFlag(Character manejoxSerieFlag) {
		this.manejoxSerieFlag = manejoxSerieFlag;
	}

	@Column(name = "ManejoxKitFlag", length = 1)
	public Character getManejoxKitFlag() {
		return this.manejoxKitFlag;
	}

	public void setManejoxKitFlag(Character manejoxKitFlag) {
		this.manejoxKitFlag = manejoxKitFlag;
	}

	@Column(name = "ManejoxKitSplitFlag", length = 1)
	public Character getManejoxKitSplitFlag() {
		return this.manejoxKitSplitFlag;
	}

	public void setManejoxKitSplitFlag(Character manejoxKitSplitFlag) {
		this.manejoxKitSplitFlag = manejoxKitSplitFlag;
	}

	@Column(name = "ManejoxUnidadFlag", length = 1)
	public Character getManejoxUnidadFlag() {
		return this.manejoxUnidadFlag;
	}

	public void setManejoxUnidadFlag(Character manejoxUnidadFlag) {
		this.manejoxUnidadFlag = manejoxUnidadFlag;
	}

	@Column(name = "AfectoImpuestoVentasFlag", length = 1)
	public Character getAfectoImpuestoVentasFlag() {
		return this.afectoImpuestoVentasFlag;
	}

	public void setAfectoImpuestoVentasFlag(Character afectoImpuestoVentasFlag) {
		this.afectoImpuestoVentasFlag = afectoImpuestoVentasFlag;
	}

	@Column(name = "AfectoImpuesto2Flag", length = 1)
	public Character getAfectoImpuesto2flag() {
		return this.afectoImpuesto2flag;
	}

	public void setAfectoImpuesto2flag(Character afectoImpuesto2flag) {
		this.afectoImpuesto2flag = afectoImpuesto2flag;
	}

	@Column(name = "RequisicionamientoAutomaticoFl", length = 1)
	public Character getRequisicionamientoAutomaticoFl() {
		return this.requisicionamientoAutomaticoFl;
	}

	public void setRequisicionamientoAutomaticoFl(Character requisicionamientoAutomaticoFl) {
		this.requisicionamientoAutomaticoFl = requisicionamientoAutomaticoFl;
	}

	@Column(name = "ControlCalidadFlag", length = 1)
	public Character getControlCalidadFlag() {
		return this.controlCalidadFlag;
	}

	public void setControlCalidadFlag(Character controlCalidadFlag) {
		this.controlCalidadFlag = controlCalidadFlag;
	}

	@Column(name = "DisponibleTransferenciaFlag", length = 1)
	public Character getDisponibleTransferenciaFlag() {
		return this.disponibleTransferenciaFlag;
	}

	public void setDisponibleTransferenciaFlag(Character disponibleTransferenciaFlag) {
		this.disponibleTransferenciaFlag = disponibleTransferenciaFlag;
	}

	@Column(name = "DisponibleConsumoFlag", length = 1)
	public Character getDisponibleConsumoFlag() {
		return this.disponibleConsumoFlag;
	}

	public void setDisponibleConsumoFlag(Character disponibleConsumoFlag) {
		this.disponibleConsumoFlag = disponibleConsumoFlag;
	}

	@Column(name = "FormularioFlag", length = 1)
	public Character getFormularioFlag() {
		return this.formularioFlag;
	}

	public void setFormularioFlag(Character formularioFlag) {
		this.formularioFlag = formularioFlag;
	}

	@Column(name = "FormularioNroJuegos")
	public Integer getFormularioNroJuegos() {
		return this.formularioNroJuegos;
	}

	public void setFormularioNroJuegos(Integer formularioNroJuegos) {
		this.formularioNroJuegos = formularioNroJuegos;
	}

	@Column(name = "ISOAplicableFlag", length = 1)
	public Character getIsoaplicableFlag() {
		return this.isoaplicableFlag;
	}

	public void setIsoaplicableFlag(Character isoaplicableFlag) {
		this.isoaplicableFlag = isoaplicableFlag;
	}

	@Column(name = "ISONormaInterna", length = 15)
	public String getIsonormaInterna() {
		return this.isonormaInterna;
	}

	public void setIsonormaInterna(String isonormaInterna) {
		this.isonormaInterna = isonormaInterna;
	}

	@Column(name = "CantidadDobleFlag", length = 1)
	public Character getCantidadDobleFlag() {
		return this.cantidadDobleFlag;
	}

	public void setCantidadDobleFlag(Character cantidadDobleFlag) {
		this.cantidadDobleFlag = cantidadDobleFlag;
	}

	@Column(name = "CantidadDobleFactor", precision = 16, scale = 10)
	public BigDecimal getCantidadDobleFactor() {
		return this.cantidadDobleFactor;
	}

	public void setCantidadDobleFactor(BigDecimal cantidadDobleFactor) {
		this.cantidadDobleFactor = cantidadDobleFactor;
	}

	@Column(name = "UnidadCodigoDoble", length = 6)
	public String getUnidadCodigoDoble() {
		return this.unidadCodigoDoble;
	}

	public void setUnidadCodigoDoble(String unidadCodigoDoble) {
		this.unidadCodigoDoble = unidadCodigoDoble;
	}

	@Column(name = "UnidadReplicacion", length = 4)
	public String getUnidadReplicacion() {
		return this.unidadReplicacion;
	}

	public void setUnidadReplicacion(String unidadReplicacion) {
		this.unidadReplicacion = unidadReplicacion;
	}

	@Column(name = "ImageFile", length = 80)
	public String getImageFile() {
		return this.imageFile;
	}

	public void setImageFile(String imageFile) {
		this.imageFile = imageFile;
	}

	@Column(name = "MapaFile", length = 80)
	public String getMapaFile() {
		return this.mapaFile;
	}

	public void setMapaFile(String mapaFile) {
		this.mapaFile = mapaFile;
	}

	@Column(name = "CuentaInventario", length = 20)
	public String getCuentaInventario() {
		return this.cuentaInventario;
	}

	public void setCuentaInventario(String cuentaInventario) {
		this.cuentaInventario = cuentaInventario;
	}

	@Column(name = "CuentaGasto", length = 20)
	public String getCuentaGasto() {
		return this.cuentaGasto;
	}

	public void setCuentaGasto(String cuentaGasto) {
		this.cuentaGasto = cuentaGasto;
	}

	@Column(name = "CuentaInversion", length = 20)
	public String getCuentaInversion() {
		return this.cuentaInversion;
	}

	public void setCuentaInversion(String cuentaInversion) {
		this.cuentaInversion = cuentaInversion;
	}

	@Column(name = "CuentaServicioTecnico", length = 20)
	public String getCuentaServicioTecnico() {
		return this.cuentaServicioTecnico;
	}

	public void setCuentaServicioTecnico(String cuentaServicioTecnico) {
		this.cuentaServicioTecnico = cuentaServicioTecnico;
	}

	@Column(name = "CuentaSalidaTerceros", length = 20)
	public String getCuentaSalidaTerceros() {
		return this.cuentaSalidaTerceros;
	}

	public void setCuentaSalidaTerceros(String cuentaSalidaTerceros) {
		this.cuentaSalidaTerceros = cuentaSalidaTerceros;
	}

	@Column(name = "CuentaVentas", length = 20)
	public String getCuentaVentas() {
		return this.cuentaVentas;
	}

	public void setCuentaVentas(String cuentaVentas) {
		this.cuentaVentas = cuentaVentas;
	}

	@Column(name = "CuentaTransito", length = 20)
	public String getCuentaTransito() {
		return this.cuentaTransito;
	}

	public void setCuentaTransito(String cuentaTransito) {
		this.cuentaTransito = cuentaTransito;
	}

	@Column(name = "ElementoGasto", length = 10)
	public String getElementoGasto() {
		return this.elementoGasto;
	}

	public void setElementoGasto(String elementoGasto) {
		this.elementoGasto = elementoGasto;
	}

	@Column(name = "ElementoInversion", length = 10)
	public String getElementoInversion() {
		return this.elementoInversion;
	}

	public void setElementoInversion(String elementoInversion) {
		this.elementoInversion = elementoInversion;
	}

	@Column(name = "PartidaPresupuestal", length = 4)
	public String getPartidaPresupuestal() {
		return this.partidaPresupuestal;
	}

	public void setPartidaPresupuestal(String partidaPresupuestal) {
		this.partidaPresupuestal = partidaPresupuestal;
	}

	@Column(name = "FlujodeCaja", length = 4)
	public String getFlujodeCaja() {
		return this.flujodeCaja;
	}

	public void setFlujodeCaja(String flujodeCaja) {
		this.flujodeCaja = flujodeCaja;
	}

	@Column(name = "LotedeCompra")
	public Integer getLotedeCompra() {
		return this.lotedeCompra;
	}

	public void setLotedeCompra(Integer lotedeCompra) {
		this.lotedeCompra = lotedeCompra;
	}

	@Column(name = "LotedeDespacho", precision = 16, scale = 6)
	public BigDecimal getLotedeDespacho() {
		return this.lotedeDespacho;
	}

	public void setLotedeDespacho(BigDecimal lotedeDespacho) {
		this.lotedeDespacho = lotedeDespacho;
	}

	@Column(name = "LotedeCompraM3", precision = 16, scale = 6)
	public BigDecimal getLotedeCompraM3() {
		return this.lotedeCompraM3;
	}

	public void setLotedeCompraM3(BigDecimal lotedeCompraM3) {
		this.lotedeCompraM3 = lotedeCompraM3;
	}

	@Column(name = "LotedeCompraKG", precision = 16, scale = 6)
	public BigDecimal getLotedeCompraKg() {
		return this.lotedeCompraKg;
	}

	public void setLotedeCompraKg(BigDecimal lotedeCompraKg) {
		this.lotedeCompraKg = lotedeCompraKg;
	}

	@Column(name = "PeriodicidadCompraMeses", scale = 4)
	public BigDecimal getPeriodicidadCompraMeses() {
		return this.periodicidadCompraMeses;
	}

	public void setPeriodicidadCompraMeses(BigDecimal periodicidadCompraMeses) {
		this.periodicidadCompraMeses = periodicidadCompraMeses;
	}

	@Column(name = "EspecificacionTecnica")
	public String getEspecificacionTecnica() {
		return this.especificacionTecnica;
	}

	public void setEspecificacionTecnica(String especificacionTecnica) {
		this.especificacionTecnica = especificacionTecnica;
	}

	@Column(name = "Dimensiones", length = 30)
	public String getDimensiones() {
		return this.dimensiones;
	}

	public void setDimensiones(String dimensiones) {
		this.dimensiones = dimensiones;
	}

	@Column(name = "FactorEquivalenciaComercial", precision = 10, scale = 4)
	public BigDecimal getFactorEquivalenciaComercial() {
		return this.factorEquivalenciaComercial;
	}

	public void setFactorEquivalenciaComercial(BigDecimal factorEquivalenciaComercial) {
		this.factorEquivalenciaComercial = factorEquivalenciaComercial;
	}

	@Column(name = "ABCCodigo", length = 2)
	public String getAbccodigo() {
		return this.abccodigo;
	}

	public void setAbccodigo(String abccodigo) {
		this.abccodigo = abccodigo;
	}

	@Column(name = "InventarioTolerancia", precision = 10, scale = 7)
	public BigDecimal getInventarioTolerancia() {
		return this.inventarioTolerancia;
	}

	public void setInventarioTolerancia(BigDecimal inventarioTolerancia) {
		this.inventarioTolerancia = inventarioTolerancia;
	}

	@Column(name = "StockMinimo", scale = 4)
	public BigDecimal getStockMinimo() {
		return this.stockMinimo;
	}

	public void setStockMinimo(BigDecimal stockMinimo) {
		this.stockMinimo = stockMinimo;
	}

	@Column(name = "StockMaximo", scale = 4)
	public BigDecimal getStockMaximo() {
		return this.stockMaximo;
	}

	public void setStockMaximo(BigDecimal stockMaximo) {
		this.stockMaximo = stockMaximo;
	}

	@Column(name = "LotedeVenta")
	public Integer getLotedeVenta() {
		return this.lotedeVenta;
	}

	public void setLotedeVenta(Integer lotedeVenta) {
		this.lotedeVenta = lotedeVenta;
	}

	@Column(name = "DescripcionAdicional")
	public String getDescripcionAdicional() {
		return this.descripcionAdicional;
	}

	public void setDescripcionAdicional(String descripcionAdicional) {
		this.descripcionAdicional = descripcionAdicional;
	}

	@Column(name = "CodigoPrecio", length = 3)
	public String getCodigoPrecio() {
		return this.codigoPrecio;
	}

	public void setCodigoPrecio(String codigoPrecio) {
		this.codigoPrecio = codigoPrecio;
	}

	@Column(name = "CaracteristicaValor01", length = 10)
	public String getCaracteristicaValor01() {
		return this.caracteristicaValor01;
	}

	public void setCaracteristicaValor01(String caracteristicaValor01) {
		this.caracteristicaValor01 = caracteristicaValor01;
	}

	@Column(name = "CaracteristicaValor02", length = 10)
	public String getCaracteristicaValor02() {
		return this.caracteristicaValor02;
	}

	public void setCaracteristicaValor02(String caracteristicaValor02) {
		this.caracteristicaValor02 = caracteristicaValor02;
	}

	@Column(name = "CaracteristicaValor03", length = 10)
	public String getCaracteristicaValor03() {
		return this.caracteristicaValor03;
	}

	public void setCaracteristicaValor03(String caracteristicaValor03) {
		this.caracteristicaValor03 = caracteristicaValor03;
	}

	@Column(name = "CaracteristicaValor04", length = 10)
	public String getCaracteristicaValor04() {
		return this.caracteristicaValor04;
	}

	public void setCaracteristicaValor04(String caracteristicaValor04) {
		this.caracteristicaValor04 = caracteristicaValor04;
	}

	@Column(name = "CaracteristicaValor05", length = 10)
	public String getCaracteristicaValor05() {
		return this.caracteristicaValor05;
	}

	public void setCaracteristicaValor05(String caracteristicaValor05) {
		this.caracteristicaValor05 = caracteristicaValor05;
	}

	@Column(name = "ReferenciaFiscal02", length = 20)
	public String getReferenciaFiscal02() {
		return this.referenciaFiscal02;
	}

	public void setReferenciaFiscal02(String referenciaFiscal02) {
		this.referenciaFiscal02 = referenciaFiscal02;
	}

	@Column(name = "ReferenciaFiscalIngreso02", length = 20)
	public String getReferenciaFiscalIngreso02() {
		return this.referenciaFiscalIngreso02;
	}

	public void setReferenciaFiscalIngreso02(String referenciaFiscalIngreso02) {
		this.referenciaFiscalIngreso02 = referenciaFiscalIngreso02;
	}

	@Column(name = "DetraccionCodigo", length = 4)
	public String getDetraccionCodigo() {
		return this.detraccionCodigo;
	}

	public void setDetraccionCodigo(String detraccionCodigo) {
		this.detraccionCodigo = detraccionCodigo;
	}

	@Column(name = "Estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "PeriodicidadCompra", length = 1)
	public Character getPeriodicidadCompra() {
		return this.periodicidadCompra;
	}

	public void setPeriodicidadCompra(Character periodicidadCompra) {
		this.periodicidadCompra = periodicidadCompra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UltimaFechaModif", length = 23)
	public Date getUltimaFechaModif() {
		return this.ultimaFechaModif;
	}

	public void setUltimaFechaModif(Date ultimaFechaModif) {
		this.ultimaFechaModif = ultimaFechaModif;
	}

	@Column(name = "UltimoUsuario", length = 25)
	public String getUltimoUsuario() {
		return this.ultimoUsuario;
	}

	public void setUltimoUsuario(String ultimoUsuario) {
		this.ultimoUsuario = ultimoUsuario;
	}

	@Column(name = "Centrocosto", length = 15)
	public String getCentrocosto() {
		return this.centrocosto;
	}

	public void setCentrocosto(String centrocosto) {
		this.centrocosto = centrocosto;
	}

	@Column(name = "ConceptoGasto", length = 15)
	public String getConceptoGasto() {
		return this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}

	@Column(name = "ClasificadorMovimiento", length = 15)
	public String getClasificadorMovimiento() {
		return this.clasificadorMovimiento;
	}

	public void setClasificadorMovimiento(String clasificadorMovimiento) {
		this.clasificadorMovimiento = clasificadorMovimiento;
	}

	@Column(name = "FlujodeCajaIngreso", length = 4)
	public String getFlujodeCajaIngreso() {
		return this.flujodeCajaIngreso;
	}

	public void setFlujodeCajaIngreso(String flujodeCajaIngreso) {
		this.flujodeCajaIngreso = flujodeCajaIngreso;
	}

	@Column(name = "MapaCodigo", length = 10)
	public String getMapaCodigo() {
		return this.mapaCodigo;
	}

	public void setMapaCodigo(String mapaCodigo) {
		this.mapaCodigo = mapaCodigo;
	}

	@Column(name = "paisfabricacion", length = 4)
	public String getPaisfabricacion() {
		return this.paisfabricacion;
	}

	public void setPaisfabricacion(String paisfabricacion) {
		this.paisfabricacion = paisfabricacion;
	}

	@Column(name = "ABCCodigoIN", length = 3)
	public String getAbccodigoIn() {
		return this.abccodigoIn;
	}

	public void setAbccodigoIn(String abccodigoIn) {
		this.abccodigoIn = abccodigoIn;
	}

	@Column(name = "Lectura", length = 1)
	public String getLectura() {
		return this.lectura;
	}

	public void setLectura(String lectura) {
		this.lectura = lectura;
	}

	@Column(name = "IdGrupoComponente")
	public Integer getIdGrupoComponente() {
		return this.idGrupoComponente;
	}

	public void setIdGrupoComponente(Integer idGrupoComponente) {
		this.idGrupoComponente = idGrupoComponente;
	}

	@Column(name = "IdRegimenVenta")
	public Integer getIdRegimenVenta() {
		return this.idRegimenVenta;
	}

	public void setIdRegimenVenta(Integer idRegimenVenta) {
		this.idRegimenVenta = idRegimenVenta;
	}

	@Column(name = "IndicadorReemplazo")
	public Integer getIndicadorReemplazo() {
		return this.indicadorReemplazo;
	}

	public void setIndicadorReemplazo(Integer indicadorReemplazo) {
		this.indicadorReemplazo = indicadorReemplazo;
	}

	@Column(name = "UsuarioCreacion", length = 25)
	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "CuentaVentaComercial", length = 25)
	public String getCuentaVentaComercial() {
		return this.cuentaVentaComercial;
	}

	public void setCuentaVentaComercial(String cuentaVentaComercial) {
		this.cuentaVentaComercial = cuentaVentaComercial;
	}

	@Column(name = "CuentaDescuentoVentaComercial", length = 25)
	public String getCuentaDescuentoVentaComercial() {
		return this.cuentaDescuentoVentaComercial;
	}

	public void setCuentaDescuentoVentaComercial(String cuentaDescuentoVentaComercial) {
		this.cuentaDescuentoVentaComercial = cuentaDescuentoVentaComercial;
	}

	@Column(name = "IndicadorCuentaVenta")
	public Integer getIndicadorCuentaVenta() {
		return this.indicadorCuentaVenta;
	}

	public void setIndicadorCuentaVenta(Integer indicadorCuentaVenta) {
		this.indicadorCuentaVenta = indicadorCuentaVenta;
	}

	@Column(name = "TipoRepuesto", length = 2)
	public String getTipoRepuesto() {
		return this.tipoRepuesto;
	}

	public void setTipoRepuesto(String tipoRepuesto) {
		this.tipoRepuesto = tipoRepuesto;
	}

	@Column(name = "Cantidadkit")
	public Integer getCantidadkit() {
		return this.cantidadkit;
	}

	public void setCantidadkit(Integer cantidadkit) {
		this.cantidadkit = cantidadkit;
	}

	@Column(name = "PeriodoInicioReposicion")
	public Integer getPeriodoInicioReposicion() {
		return this.periodoInicioReposicion;
	}

	public void setPeriodoInicioReposicion(Integer periodoInicioReposicion) {
		this.periodoInicioReposicion = periodoInicioReposicion;
	}

	@Column(name = "PeriodosReposicion")
	public Integer getPeriodosReposicion() {
		return this.periodosReposicion;
	}

	public void setPeriodosReposicion(Integer periodosReposicion) {
		this.periodosReposicion = periodosReposicion;
	}

	@Column(name = "IndicadorClasificacion")
	public Integer getIndicadorClasificacion() {
		return this.indicadorClasificacion;
	}

	public void setIndicadorClasificacion(Integer indicadorClasificacion) {
		this.indicadorClasificacion = indicadorClasificacion;
	}

	@Column(name = "PeridoInicioReposicion")
	public Integer getPeridoInicioReposicion() {
		return this.peridoInicioReposicion;
	}

	public void setPeridoInicioReposicion(Integer peridoInicioReposicion) {
		this.peridoInicioReposicion = peridoInicioReposicion;
	}

	@Column(name = "IdClasificacion")
	public Integer getIdClasificacion() {
		return this.idClasificacion;
	}

	public void setIdClasificacion(Integer idClasificacion) {
		this.idClasificacion = idClasificacion;
	}

	@Column(name = "cantidadReposicion", precision = 16, scale = 6)
	public BigDecimal getCantidadReposicion() {
		return this.cantidadReposicion;
	}

	public void setCantidadReposicion(BigDecimal cantidadReposicion) {
		this.cantidadReposicion = cantidadReposicion;
	}

	@Column(name = "grupoReposicion", length = 6)
	public String getGrupoReposicion() {
		return this.grupoReposicion;
	}

	public void setGrupoReposicion(String grupoReposicion) {
		this.grupoReposicion = grupoReposicion;
	}

	@Column(name = "IndicadorReposicion")
	public Integer getIndicadorReposicion() {
		return this.indicadorReposicion;
	}

	public void setIndicadorReposicion(Integer indicadorReposicion) {
		this.indicadorReposicion = indicadorReposicion;
	}

	@Column(name = "IndicadorPrecioManual")
	public Integer getIndicadorPrecioManual() {
		return this.indicadorPrecioManual;
	}

	public void setIndicadorPrecioManual(Integer indicadorPrecioManual) {
		this.indicadorPrecioManual = indicadorPrecioManual;
	}

	@Column(name = "IndicadorConsumoFraccionado")
	public Integer getIndicadorConsumoFraccionado() {
		return this.indicadorConsumoFraccionado;
	}

	public void setIndicadorConsumoFraccionado(Integer indicadorConsumoFraccionado) {
		this.indicadorConsumoFraccionado = indicadorConsumoFraccionado;
	}

	@Column(name = "nombreLaboratorio")
	public String getNombreLaboratorio() {
		return this.nombreLaboratorio;
	}

	public void setNombreLaboratorio(String nombreLaboratorio) {
		this.nombreLaboratorio = nombreLaboratorio;
	}

	@Column(name = "estadoAnterior", length = 1)
	public String getEstadoAnterior() {
		return this.estadoAnterior;
	}

	public void setEstadoAnterior(String estadoAnterior) {
		this.estadoAnterior = estadoAnterior;
	}

	@Column(name = "CuentaCompras", length = 20)
	public String getCuentaCompras() {
		return this.cuentaCompras;
	}

	public void setCuentaCompras(String cuentaCompras) {
		this.cuentaCompras = cuentaCompras;
	}

	@Column(name = "PrecioCostoAnt", precision = 16, scale = 6)
	public BigDecimal getPrecioCostoAnt() {
		return this.precioCostoAnt;
	}

	public void setPrecioCostoAnt(BigDecimal precioCostoAnt) {
		this.precioCostoAnt = precioCostoAnt;
	}

	@Column(name = "UltimaOC", length = 10)
	public String getUltimaOc() {
		return this.ultimaOc;
	}

	public void setUltimaOc(String ultimaOc) {
		this.ultimaOc = ultimaOc;
	}

	@Column(name = "PreviaOC", length = 10)
	public String getPreviaOc() {
		return this.previaOc;
	}

	public void setPreviaOc(String previaOc) {
		this.previaOc = previaOc;
	}

	@Column(name = "tipomedicamento", length = 1)
	public String getTipomedicamento() {
		return this.tipomedicamento;
	}

	public void setTipomedicamento(String tipomedicamento) {
		this.tipomedicamento = tipomedicamento;
	}

	@Column(name = "CodigoDigemid", length = 50)
	public String getCodigoDigemid() {
		return this.codigoDigemid;
	}

	public void setCodigoDigemid(String codigoDigemid) {
		this.codigoDigemid = codigoDigemid;
	}

	@Column(name = "EAN13", length = 20)
	public String getEan13() {
		return this.ean13;
	}

	public void setEan13(String ean13) {
		this.ean13 = ean13;
	}

	@Column(name = "MedicamentoCodigo", length = 50)
	public String getMedicamentoCodigo() {
		return this.medicamentoCodigo;
	}

	public void setMedicamentoCodigo(String medicamentoCodigo) {
		this.medicamentoCodigo = medicamentoCodigo;
	}

	@Column(name = "MedicamentoCodigoPadre", length = 50)
	public String getMedicamentoCodigoPadre() {
		return this.medicamentoCodigoPadre;
	}

	public void setMedicamentoCodigoPadre(String medicamentoCodigoPadre) {
		this.medicamentoCodigoPadre = medicamentoCodigoPadre;
	}

	@Column(name = "NombreTabla", length = 100)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "tipofolder")
	public Integer getTipofolder() {
		return this.tipofolder;
	}

	public void setTipofolder(Integer tipofolder) {
		this.tipofolder = tipofolder;
	}

	@Column(name = "Accion", length = 25)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

}
